import uuid
from datetime import datetime
from sqlalchemy import DateTime, ForeignKey, Integer, String, Text, Boolean, Index
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column
from app.db.database import Base
class AutomationEventRecord(Base):
    __tablename__="automation_event_records"
    id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); event_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),unique=True,index=True); event_type:Mapped[str]=mapped_column(String(80),index=True); property_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey("properties.id"),index=True); source_entity_type:Mapped[str|None]=mapped_column(String(50)); source_entity_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True)); safe_payload:Mapped[str|None]=mapped_column(Text); processing_status:Mapped[str]=mapped_column(String(20),default="received",index=True); occurred_at:Mapped[datetime]=mapped_column(DateTime(timezone=True)); received_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default="now()")
class AutomationTriggerSubscription(Base):
    __tablename__="automation_trigger_subscriptions"
    id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); workflow_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("automation_workflows.id",ondelete="CASCADE")); workflow_version_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("automation_workflow_versions.id")); property_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey("properties.id"),index=True); event_type:Mapped[str]=mapped_column(String(80),index=True); enabled:Mapped[bool]=mapped_column(Boolean,default=False,server_default="false"); trigger_mode:Mapped[str]=mapped_column(String(20),default="notify_only"); cooldown_seconds:Mapped[int]=mapped_column(Integer,default=300); deduplication_window_seconds:Mapped[int]=mapped_column(Integer,default=300)
class AutomationWorkflowSchedule(Base):
    __tablename__="automation_workflow_schedules"
    id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); workflow_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("automation_workflows.id",ondelete="CASCADE")); workflow_version_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("automation_workflow_versions.id")); property_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey("properties.id"),index=True); name:Mapped[str]=mapped_column(String(120)); schedule_type:Mapped[str]=mapped_column(String(20),default="one_time"); timezone:Mapped[str]=mapped_column(String(64),default="UTC"); interval_minutes:Mapped[int|None]=mapped_column(Integer); enabled:Mapped[bool]=mapped_column(Boolean,default=False,server_default="false"); next_run_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); maximum_runs:Mapped[int|None]=mapped_column(Integer); runs_completed:Mapped[int]=mapped_column(Integer,default=0,server_default="0"); __table_args__=(Index("ix_automation_schedule_enabled","enabled"),)
class AutomationTriggerExecution(Base):
    __tablename__="automation_trigger_executions"
    id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); subscription_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("automation_trigger_subscriptions.id",ondelete="CASCADE")); event_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey("automation_event_records.id")); property_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey("properties.id")); deduplication_key:Mapped[str]=mapped_column(String(255)); status:Mapped[str]=mapped_column(String(20),default="matched"); suppression_reason:Mapped[str|None]=mapped_column(String(255)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default="now()",nullable=False)
