import uuid
from datetime import datetime
from sqlalchemy import DateTime, ForeignKey, Integer, String, Text, Boolean, Index, UniqueConstraint
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column
from app.db.database import Base
class AutomationEventRecord(Base):
    __tablename__="automation_event_records"
    id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); event_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),unique=True,index=True); event_type:Mapped[str]=mapped_column(String(80),index=True); event_version:Mapped[int]=mapped_column(Integer,default=1); property_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey("properties.id"),index=True); source_module:Mapped[str|None]=mapped_column(String(50)); source_entity_type:Mapped[str|None]=mapped_column(String(50)); source_entity_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True)); severity:Mapped[str|None]=mapped_column(String(20)); status:Mapped[str|None]=mapped_column(String(30)); correlation_key:Mapped[str|None]=mapped_column(String(160),index=True); safe_payload:Mapped[str|None]=mapped_column(Text); processing_status:Mapped[str]=mapped_column(String(20),default="received",index=True); occurred_at:Mapped[datetime]=mapped_column(DateTime(timezone=True)); received_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default="now()"); processed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); expires_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
class AutomationTriggerSubscription(Base):
    __tablename__="automation_trigger_subscriptions"
    id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); workflow_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("automation_workflows.id",ondelete="CASCADE")); workflow_version_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("automation_workflow_versions.id")); property_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey("properties.id"),index=True); event_type:Mapped[str]=mapped_column(String(80),index=True); enabled:Mapped[bool]=mapped_column(Boolean,default=False,server_default="false"); trigger_mode:Mapped[str]=mapped_column(String(20),default="notify_only"); filter_definition:Mapped[str|None]=mapped_column(Text); condition_definition:Mapped[str|None]=mapped_column(Text); input_mapping:Mapped[str|None]=mapped_column(Text); cooldown_seconds:Mapped[int]=mapped_column(Integer,default=300); deduplication_window_seconds:Mapped[int]=mapped_column(Integer,default=300); correlation_window_seconds:Mapped[int]=mapped_column(Integer,default=300); correlation_threshold:Mapped[int]=mapped_column(Integer,default=1); maximum_correlation_members:Mapped[int]=mapped_column(Integer,default=100); recovery_event_type:Mapped[str|None]=mapped_column(String(80)); maximum_runs_per_window:Mapped[int]=mapped_column(Integer,default=5); run_window_seconds:Mapped[int]=mapped_column(Integer,default=3600); delay_seconds:Mapped[int]=mapped_column(Integer,default=0); approval_mode:Mapped[str]=mapped_column(String(30),default="use_workflow_policy"); maintenance_behavior:Mapped[str]=mapped_column(String(30),default="suppress"); blackout_behavior:Mapped[str]=mapped_column(String(30),default="suppress"); blackout_start:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); blackout_end:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); created_by:Mapped[str|None]=mapped_column(String)
class AutomationWorkflowSchedule(Base):
    __tablename__="automation_workflow_schedules"
    id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); workflow_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("automation_workflows.id",ondelete="CASCADE")); workflow_version_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("automation_workflow_versions.id")); property_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey("properties.id"),index=True); name:Mapped[str]=mapped_column(String(120)); schedule_type:Mapped[str]=mapped_column(String(20),default="one_time"); timezone:Mapped[str]=mapped_column(String(64),default="UTC"); interval_minutes:Mapped[int|None]=mapped_column(Integer); day_of_week:Mapped[int|None]=mapped_column(Integer); day_of_month:Mapped[int|None]=mapped_column(Integer); preferred_time:Mapped[str|None]=mapped_column(String(5)); start_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); end_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); jitter_seconds:Mapped[int]=mapped_column(Integer,default=0); enabled:Mapped[bool]=mapped_column(Boolean,default=False,server_default="false"); next_run_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); maximum_runs:Mapped[int|None]=mapped_column(Integer); runs_completed:Mapped[int]=mapped_column(Integer,default=0,server_default="0"); approval_mode:Mapped[str]=mapped_column(String(30),default="use_workflow_policy"); maintenance_behavior:Mapped[str]=mapped_column(String(30),default="suppress"); blackout_behavior:Mapped[str]=mapped_column(String(30),default="suppress"); blackout_start:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); blackout_end:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); last_run_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); last_run_status:Mapped[str|None]=mapped_column(String(30)); __table_args__=(Index("ix_automation_schedule_enabled","enabled"),)
class AutomationTriggerExecution(Base):
    __tablename__="automation_trigger_executions"
    id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); subscription_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("automation_trigger_subscriptions.id",ondelete="CASCADE")); event_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey("automation_event_records.id")); property_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey("properties.id")); deduplication_key:Mapped[str]=mapped_column(String(255)); status:Mapped[str]=mapped_column(String(20),default="matched"); suppression_reason:Mapped[str|None]=mapped_column(String(255)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default="now()",nullable=False)

class AutomationEventOutbox(Base):
    __tablename__="automation_event_outbox"
    id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); event_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),unique=True,index=True); event_type:Mapped[str]=mapped_column(String(80),index=True); property_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey("properties.id"),index=True); payload:Mapped[str]=mapped_column(Text); status:Mapped[str]=mapped_column(String(20),default="pending",index=True); attempts:Mapped[int]=mapped_column(Integer,default=0); next_attempt_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),index=True); published_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); error_summary:Mapped[str|None]=mapped_column(String(500)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default="now()",nullable=False)

class AutomationTriggerCorrelationGroup(Base):
    __tablename__="automation_trigger_correlation_groups"
    id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); subscription_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("automation_trigger_subscriptions.id",ondelete="CASCADE"),index=True); property_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey("properties.id"),index=True); correlation_key:Mapped[str]=mapped_column(String(160)); status:Mapped[str]=mapped_column(String(20),default="collecting",index=True); first_event_at:Mapped[datetime]=mapped_column(DateTime(timezone=True)); last_event_at:Mapped[datetime]=mapped_column(DateTime(timezone=True)); event_count:Mapped[int]=mapped_column(Integer,default=0); member_event_ids:Mapped[str]=mapped_column(Text,default="[]"); threshold_reached:Mapped[bool]=mapped_column(Boolean,default=False); workflow_run_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey("automation_workflow_runs.id")); expires_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),index=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default="now()",nullable=False); __table_args__=(Index("ix_automation_correlation_key_status","subscription_id","correlation_key","status"),)

class AutomationTriggerRevision(Base):
    __tablename__="automation_trigger_revisions"
    id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); subscription_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("automation_trigger_subscriptions.id",ondelete="CASCADE"),index=True); revision_number:Mapped[int]=mapped_column(Integer); configuration_snapshot:Mapped[str]=mapped_column(Text); checksum:Mapped[str]=mapped_column(String(64)); status:Mapped[str]=mapped_column(String(20),default="draft"); created_by:Mapped[str|None]=mapped_column(String); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default="now()",nullable=False); __table_args__=(UniqueConstraint("subscription_id","revision_number",name="uq_automation_trigger_revision"),)
