import uuid
from datetime import datetime
from sqlalchemy import DateTime, ForeignKey, Integer, String, Text, Boolean, Index
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column
from app.db.database import Base
class AutomationWorkflow(Base):
    __tablename__="automation_workflows"
    id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); property_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey("properties.id"),index=True); name:Mapped[str]=mapped_column(String(160)); code:Mapped[str]=mapped_column(String(60)); workflow_category:Mapped[str]=mapped_column(String(40),default="custom"); status:Mapped[str]=mapped_column(String(20),default="draft",index=True); enabled:Mapped[bool]=mapped_column(Boolean,default=False,server_default="false"); requires_approval:Mapped[bool]=mapped_column(Boolean,default=True,server_default="true"); current_version_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True)); created_by:Mapped[str]=mapped_column(String); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default="now()",nullable=False); __table_args__=(Index("uq_automation_workflow_scope_code","property_id","code",unique=True),)
class AutomationWorkflowVersion(Base):
    __tablename__="automation_workflow_versions"
    id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); workflow_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("automation_workflows.id",ondelete="CASCADE"),index=True); version_number:Mapped[int]=mapped_column(Integer); status:Mapped[str]=mapped_column(String(20),default="draft"); trigger_definition:Mapped[str|None]=mapped_column(Text); workflow_graph:Mapped[str|None]=mapped_column(Text); checksum:Mapped[str|None]=mapped_column(String(64)); created_by:Mapped[str]=mapped_column(String); approved_by:Mapped[str|None]=mapped_column(String); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default="now()",nullable=False); __table_args__=(Index("uq_workflow_version_number","workflow_id","version_number",unique=True),)
class AutomationAction(Base):
    __tablename__="automation_actions"
    action_key:Mapped[str]=mapped_column(String(80),primary_key=True); name:Mapped[str]=mapped_column(String(120)); description:Mapped[str]=mapped_column(Text); risk_level:Mapped[str]=mapped_column(String(20),default="low"); property_scoped:Mapped[bool]=mapped_column(Boolean,default=True,server_default="true"); enabled:Mapped[bool]=mapped_column(Boolean,default=True,server_default="true"); approval_required:Mapped[bool]=mapped_column(Boolean,default=False,server_default="false")
class AutomationDryRun(Base):
    __tablename__="automation_dry_runs"
    id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); workflow_version_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("automation_workflow_versions.id")); property_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey("properties.id")); status:Mapped[str]=mapped_column(String(20),default="passed_with_warnings"); eligible_for_execution:Mapped[bool]=mapped_column(Boolean,default=False); warnings_count:Mapped[int]=mapped_column(Integer,default=1); execution_path:Mapped[str|None]=mapped_column(Text); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default="now()",nullable=False)
class AutomationWorkflowRun(Base):
    __tablename__="automation_workflow_runs"
    id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); property_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey("properties.id"),index=True); workflow_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("automation_workflows.id")); workflow_version_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("automation_workflow_versions.id")); status:Mapped[str]=mapped_column(String(25),default="pending",index=True); trigger_type:Mapped[str]=mapped_column(String(20),default="manual"); triggered_by:Mapped[str]=mapped_column(String); idempotency_key:Mapped[str|None]=mapped_column(String(120),index=True); error_summary:Mapped[str|None]=mapped_column(Text); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default="now()",nullable=False)
class AutomationWorkflowStep(Base):
    __tablename__="automation_workflow_steps"
    id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); workflow_version_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("automation_workflow_versions.id",ondelete="CASCADE"),index=True); step_key:Mapped[str]=mapped_column(String(80)); name:Mapped[str]=mapped_column(String(160)); step_type:Mapped[str]=mapped_column(String(30)); action_key:Mapped[str|None]=mapped_column(String(80),ForeignKey("automation_actions.action_key")); sequence_order:Mapped[int]=mapped_column(Integer,default=0); timeout_seconds:Mapped[int]=mapped_column(Integer,default=60); retry_policy:Mapped[str|None]=mapped_column(Text); condition_definition:Mapped[str|None]=mapped_column(Text); approval_required:Mapped[bool]=mapped_column(Boolean,default=False,server_default="false"); compensation_action_key:Mapped[str|None]=mapped_column(String(80)); continue_on_failure:Mapped[bool]=mapped_column(Boolean,default=False,server_default="false"); enabled:Mapped[bool]=mapped_column(Boolean,default=True,server_default="true"); __table_args__=(Index("uq_automation_step_key","workflow_version_id","step_key",unique=True),)
class AutomationStepDependency(Base):
    __tablename__="automation_step_dependencies"
    id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); workflow_version_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("automation_workflow_versions.id",ondelete="CASCADE"),index=True); upstream_step_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("automation_workflow_steps.id",ondelete="CASCADE")); downstream_step_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("automation_workflow_steps.id",ondelete="CASCADE")); dependency_type:Mapped[str]=mapped_column(String(30),default="success")
class AutomationStepRun(Base):
    __tablename__="automation_step_runs"
    id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); workflow_run_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("automation_workflow_runs.id",ondelete="CASCADE"),index=True); step_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("automation_workflow_steps.id")); status:Mapped[str]=mapped_column(String(25),default="pending",index=True); attempt_count:Mapped[int]=mapped_column(Integer,default=0); output_summary:Mapped[str|None]=mapped_column(Text); error_category:Mapped[str|None]=mapped_column(String(40)); started_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); completed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
class AutomationApprovalRequest(Base):
    __tablename__="automation_approval_requests"
    id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); workflow_run_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("automation_workflow_runs.id",ondelete="CASCADE"),index=True); step_run_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey("automation_step_runs.id",ondelete="CASCADE")); status:Mapped[str]=mapped_column(String(20),default="pending",index=True); requested_by:Mapped[str]=mapped_column(String); reviewed_by:Mapped[str|None]=mapped_column(String); decision_reason:Mapped[str|None]=mapped_column(Text); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default="now()",nullable=False)
