import uuid
from datetime import date,datetime
from decimal import Decimal
from sqlalchemy import Boolean,Date,DateTime,ForeignKey,Index,Integer,Numeric,String,Text,UniqueConstraint
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped,mapped_column
from sqlalchemy.sql import func
from app.db.database import Base

def uid():return mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4)
def now():return mapped_column(DateTime(timezone=True),server_default=func.now(),nullable=False)
class KPIDefinition(Base):
    __tablename__="bi_kpi_definitions";id:Mapped[uuid.UUID]=uid();key:Mapped[str]=mapped_column(String(100),unique=True,index=True);name:Mapped[str]=mapped_column(String(180));description:Mapped[str|None]=mapped_column(Text);category:Mapped[str]=mapped_column(String(60),index=True);unit:Mapped[str|None]=mapped_column(String(30));operation:Mapped[str]=mapped_column(String(30));source_keys:Mapped[str]=mapped_column(Text,default="[]");higher_is_better:Mapped[bool]=mapped_column(Boolean,default=True);enabled:Mapped[bool]=mapped_column(Boolean,default=True);created_by:Mapped[str]=mapped_column(String,ForeignKey("users.id"));created_at:Mapped[datetime]=now();updated_at:Mapped[datetime]=now()
class KPI(Base):
    __tablename__="bi_kpis";id:Mapped[uuid.UUID]=uid();definition_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("bi_kpi_definitions.id"),index=True);scope_type:Mapped[str]=mapped_column(String(30),default="corporate");scope_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),index=True);display_name:Mapped[str|None]=mapped_column(String(180));enabled:Mapped[bool]=mapped_column(Boolean,default=True);sort_order:Mapped[int]=mapped_column(Integer,default=0);__table_args__=(UniqueConstraint("definition_id","scope_type","scope_id",name="uq_bi_kpi_scope"),)
class KPIValue(Base):
    __tablename__="bi_kpi_values";id:Mapped[uuid.UUID]=uid();kpi_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("bi_kpis.id",ondelete="CASCADE"),index=True);value:Mapped[Decimal]=mapped_column(Numeric(20,4));period_start:Mapped[datetime]=mapped_column(DateTime(timezone=True));period_end:Mapped[datetime]=mapped_column(DateTime(timezone=True));frequency:Mapped[str]=mapped_column(String(20));status:Mapped[str]=mapped_column(String(20));inputs:Mapped[str]=mapped_column(Text,default="{}");calculation_version:Mapped[str]=mapped_column(String(20),default="1.0");calculated_at:Mapped[datetime]=now();__table_args__=(UniqueConstraint("kpi_id","period_start","period_end",name="uq_bi_kpi_value_period"),)
class KPITarget(Base):
    __tablename__="bi_kpi_targets";id:Mapped[uuid.UUID]=uid();kpi_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("bi_kpis.id",ondelete="CASCADE"),index=True);target_value:Mapped[Decimal]=mapped_column(Numeric(20,4));effective_from:Mapped[date]=mapped_column(Date);effective_to:Mapped[date|None]=mapped_column(Date);approved_by:Mapped[str]=mapped_column(String,ForeignKey("users.id"));created_at:Mapped[datetime]=now()
class KPIThreshold(Base):
    __tablename__="bi_kpi_thresholds";id:Mapped[uuid.UUID]=uid();kpi_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("bi_kpis.id",ondelete="CASCADE"),index=True);warning_value:Mapped[Decimal|None]=mapped_column(Numeric(20,4));critical_value:Mapped[Decimal|None]=mapped_column(Numeric(20,4));comparison:Mapped[str]=mapped_column(String(20),default="minimum");created_at:Mapped[datetime]=now()
class KPISnapshot(Base):
    __tablename__="bi_kpi_snapshots";id:Mapped[uuid.UUID]=uid();scope_type:Mapped[str]=mapped_column(String(30));scope_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),index=True);period_start:Mapped[datetime]=mapped_column(DateTime(timezone=True));period_end:Mapped[datetime]=mapped_column(DateTime(timezone=True));frequency:Mapped[str]=mapped_column(String(20));values:Mapped[str]=mapped_column(Text);checksum:Mapped[str]=mapped_column(String(64));created_at:Mapped[datetime]=now();__table_args__=(UniqueConstraint("scope_type","scope_id","period_start","period_end","frequency",name="uq_bi_kpi_snapshot"),)
class ExecutiveDashboard(Base):
    __tablename__="bi_dashboards";id:Mapped[uuid.UUID]=uid();key:Mapped[str]=mapped_column(String(80),unique=True);name:Mapped[str]=mapped_column(String(180));audience:Mapped[str]=mapped_column(String(60),index=True);description:Mapped[str|None]=mapped_column(Text);enabled:Mapped[bool]=mapped_column(Boolean,default=True);created_by:Mapped[str]=mapped_column(String,ForeignKey("users.id"));created_at:Mapped[datetime]=now()
class DashboardWidget(Base):
    __tablename__="bi_dashboard_widgets";id:Mapped[uuid.UUID]=uid();dashboard_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("bi_dashboards.id",ondelete="CASCADE"),index=True);widget_type:Mapped[str]=mapped_column(String(30));title:Mapped[str]=mapped_column(String(180));data_source:Mapped[str]=mapped_column(String(100));configuration:Mapped[str]=mapped_column(Text,default="{}");position:Mapped[int]=mapped_column(Integer);width:Mapped[int]=mapped_column(Integer,default=1);__table_args__=(UniqueConstraint("dashboard_id","position",name="uq_bi_dashboard_widget_position"),)
class DashboardCache(Base):
    __tablename__="bi_dashboard_cache";id:Mapped[uuid.UUID]=uid();dashboard_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("bi_dashboards.id",ondelete="CASCADE"),index=True);scope_type:Mapped[str]=mapped_column(String(30));scope_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True));payload:Mapped[str]=mapped_column(Text);generated_at:Mapped[datetime]=now();expires_at:Mapped[datetime]=mapped_column(DateTime(timezone=True));__table_args__=(UniqueConstraint("dashboard_id","scope_type","scope_id",name="uq_bi_dashboard_cache_scope"),)
class ReportTemplate(Base):
    __tablename__="bi_report_templates";id:Mapped[uuid.UUID]=uid();name:Mapped[str]=mapped_column(String(180));description:Mapped[str|None]=mapped_column(Text);category:Mapped[str]=mapped_column(String(60));branding:Mapped[str]=mapped_column(Text,default="{}");parameters:Mapped[str]=mapped_column(Text,default="{}");version:Mapped[int]=mapped_column(Integer,default=1);enabled:Mapped[bool]=mapped_column(Boolean,default=True);created_by:Mapped[str]=mapped_column(String,ForeignKey("users.id"));created_at:Mapped[datetime]=now();updated_at:Mapped[datetime]=now()
class Report(Base):
    __tablename__="bi_reports";id:Mapped[uuid.UUID]=uid();template_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey("bi_report_templates.id"));name:Mapped[str]=mapped_column(String(180));scope_type:Mapped[str]=mapped_column(String(30));scope_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True));parameters:Mapped[str]=mapped_column(Text,default="{}");status:Mapped[str]=mapped_column(String(20),default="draft");created_by:Mapped[str]=mapped_column(String,ForeignKey("users.id"));created_at:Mapped[datetime]=now();updated_at:Mapped[datetime]=now()
class ReportSection(Base):
    __tablename__="bi_report_sections";id:Mapped[uuid.UUID]=uid();report_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("bi_reports.id",ondelete="CASCADE"),index=True);section_type:Mapped[str]=mapped_column(String(30));title:Mapped[str]=mapped_column(String(180));data_source:Mapped[str]=mapped_column(String(100));configuration:Mapped[str]=mapped_column(Text,default="{}");position:Mapped[int]=mapped_column(Integer);__table_args__=(UniqueConstraint("report_id","position",name="uq_bi_report_section_position"),)
class ReportExecution(Base):
    __tablename__="bi_report_executions";id:Mapped[uuid.UUID]=uid();report_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("bi_reports.id"),index=True);status:Mapped[str]=mapped_column(String(20),default="pending",index=True);format:Mapped[str]=mapped_column(String(10));parameters:Mapped[str]=mapped_column(Text,default="{}");row_count:Mapped[int]=mapped_column(Integer,default=0);output_reference:Mapped[str|None]=mapped_column(String(500));error:Mapped[str|None]=mapped_column(Text);trigger_type:Mapped[str]=mapped_column(String(20),default="manual");requested_by:Mapped[str|None]=mapped_column(String,ForeignKey("users.id"));started_at:Mapped[datetime]=now();completed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
class ScheduledReport(Base):
    __tablename__="bi_scheduled_reports";id:Mapped[uuid.UUID]=uid();report_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("bi_reports.id"),index=True);frequency:Mapped[str]=mapped_column(String(20));timezone:Mapped[str]=mapped_column(String(60),default="UTC");next_run_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),index=True);format:Mapped[str]=mapped_column(String(10),default="pdf");enabled:Mapped[bool]=mapped_column(Boolean,default=False);last_run_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));created_by:Mapped[str]=mapped_column(String,ForeignKey("users.id"));created_at:Mapped[datetime]=now()
class ReportRecipient(Base):
    __tablename__="bi_report_recipients";id:Mapped[uuid.UUID]=uid();scheduled_report_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("bi_scheduled_reports.id",ondelete="CASCADE"),index=True);recipient_type:Mapped[str]=mapped_column(String(20));recipient_value:Mapped[str]=mapped_column(String(255));enabled:Mapped[bool]=mapped_column(Boolean,default=True);__table_args__=(UniqueConstraint("scheduled_report_id","recipient_type","recipient_value",name="uq_bi_report_recipient"),)
