import uuid
from datetime import datetime
from sqlalchemy import DateTime, ForeignKey, Integer, String, Text, Index
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column
from app.db.database import Base
class ConfigurationComparison(Base):
    __tablename__="configuration_comparisons"
    id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); property_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("properties.id"),index=True); device_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("devices.id"),index=True); source_version_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("device_configuration_versions.id")); target_version_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("device_configuration_versions.id")); comparison_type:Mapped[str]=mapped_column(String(30),default="previous_version"); status:Mapped[str]=mapped_column(String(20),default="completed"); added_lines:Mapped[int]=mapped_column(Integer,default=0); removed_lines:Mapped[int]=mapped_column(Integer,default=0); change_count:Mapped[int]=mapped_column(Integer,default=0); sensitive_changes_count:Mapped[int]=mapped_column(Integer,default=0); risk_level:Mapped[str]=mapped_column(String(20),default="unknown"); summary:Mapped[str|None]=mapped_column(Text); generated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default="now()",nullable=False)
class ConfigurationComparisonChange(Base):
    __tablename__="configuration_comparison_changes"
    id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); comparison_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("configuration_comparisons.id",ondelete="CASCADE"),index=True); change_type:Mapped[str]=mapped_column(String(20)); classification:Mapped[str]=mapped_column(String(30),default="unknown"); risk_level:Mapped[str]=mapped_column(String(20),default="unknown"); section:Mapped[str|None]=mapped_column(String(120)); before_value_redacted:Mapped[str|None]=mapped_column(Text); after_value_redacted:Mapped[str|None]=mapped_column(Text)
class ConfigurationDriftRecord(Base):
    __tablename__="configuration_drift_records"
    id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); property_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("properties.id"),index=True); device_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("devices.id"),index=True); baseline_version_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey("device_configuration_versions.id")); current_version_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("device_configuration_versions.id")); comparison_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey("configuration_comparisons.id")); drift_status:Mapped[str]=mapped_column(String(20),default="new"); severity:Mapped[str]=mapped_column(String(20),default="unknown"); occurrence_count:Mapped[int]=mapped_column(Integer,default=1); first_detected_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default="now()",nullable=False); last_detected_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default="now()",nullable=False); resolution_reason:Mapped[str|None]=mapped_column(Text); __table_args__=(Index("ix_drift_status_severity","drift_status","severity"),)
