import uuid
from datetime import datetime
from sqlalchemy import DateTime, ForeignKey, Integer, String, Text, Float, Index
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column
from app.db.database import Base
class ConfigurationComplianceStandard(Base):
    __tablename__="configuration_compliance_standards"
    id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); property_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey("properties.id"),index=True); name:Mapped[str]=mapped_column(String(120),nullable=False); code:Mapped[str]=mapped_column(String(50),nullable=False); version:Mapped[str]=mapped_column(String(30),nullable=False); standard_type:Mapped[str]=mapped_column(String(30),default="internal"); scope_type:Mapped[str]=mapped_column(String(30),default="property"); enabled:Mapped[bool]=mapped_column(default=False,server_default="false"); description:Mapped[str|None]=mapped_column(Text); __table_args__=(Index("uq_compliance_standard_code_version","code","version",unique=True),)
class ConfigurationCompliancePolicy(Base):
    __tablename__="configuration_compliance_policies"
    id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); standard_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("configuration_compliance_standards.id"),nullable=False,index=True); property_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey("properties.id"),index=True); name:Mapped[str]=mapped_column(String(120),nullable=False); code:Mapped[str]=mapped_column(String(50),nullable=False); severity_default:Mapped[str]=mapped_column(String(20),default="medium"); evaluation_mode:Mapped[str]=mapped_column(String(30),default="manual_only"); enabled:Mapped[bool]=mapped_column(default=False,server_default="false"); __table_args__=(Index("uq_compliance_policy_code","property_id","code",unique=True),)
class ConfigurationComplianceRule(Base):
    __tablename__="configuration_compliance_rules"
    id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); policy_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("configuration_compliance_policies.id",ondelete="CASCADE"),nullable=False,index=True); name:Mapped[str]=mapped_column(String(120),nullable=False); code:Mapped[str]=mapped_column(String(50),nullable=False); rule_type:Mapped[str]=mapped_column(String(40),default="required_setting"); target_path:Mapped[str|None]=mapped_column(String(255)); operator:Mapped[str]=mapped_column(String(40),default="exists"); expected_value:Mapped[str|None]=mapped_column(String(255)); severity:Mapped[str]=mapped_column(String(20),default="medium"); enabled:Mapped[bool]=mapped_column(default=True,server_default="true"); priority:Mapped[int]=mapped_column(Integer,default=0); __table_args__=(Index("uq_compliance_rule_policy_code","policy_id","code",unique=True),)
class ConfigurationComplianceRun(Base):
    __tablename__="configuration_compliance_runs"
    id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); property_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey("properties.id"),index=True); run_type:Mapped[str]=mapped_column(String(20),default="manual"); status:Mapped[str]=mapped_column(String(20),default="pending"); trigger_type:Mapped[str]=mapped_column(String(20),default="manual"); rules_evaluated:Mapped[int]=mapped_column(Integer,default=0); rules_passed:Mapped[int]=mapped_column(Integer,default=0); rules_failed:Mapped[int]=mapped_column(Integer,default=0); error_summary:Mapped[str|None]=mapped_column(Text); started_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default="now()",nullable=False)
class ConfigurationComplianceResult(Base):
    __tablename__="configuration_compliance_results"
    id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); property_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("properties.id"),index=True); run_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("configuration_compliance_runs.id")); device_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("devices.id"),index=True); version_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("device_configuration_versions.id")); policy_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("configuration_compliance_policies.id")); status:Mapped[str]=mapped_column(String(30),default="unknown"); compliance_score:Mapped[float|None]=mapped_column(Float); rules_total:Mapped[int]=mapped_column(Integer,default=0); rules_passed:Mapped[int]=mapped_column(Integer,default=0); rules_failed:Mapped[int]=mapped_column(Integer,default=0); data_quality:Mapped[str]=mapped_column(String(20),default="unknown"); evaluated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default="now()",nullable=False)
class ConfigurationComplianceViolation(Base):
    __tablename__="configuration_compliance_violations"
    id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); property_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("properties.id"),index=True); device_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("devices.id"),index=True); policy_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("configuration_compliance_policies.id")); rule_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("configuration_compliance_rules.id")); violation_key:Mapped[str]=mapped_column(String(255),unique=True); severity:Mapped[str]=mapped_column(String(20)); status:Mapped[str]=mapped_column(String(20),default="open"); title:Mapped[str]=mapped_column(String(160)); evidence:Mapped[str|None]=mapped_column(Text); occurrence_count:Mapped[int]=mapped_column(Integer,default=1); first_detected_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default="now()",nullable=False); last_detected_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default="now()",nullable=False)
class ConfigurationComplianceException(Base):
    __tablename__="configuration_compliance_exceptions"
    id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); property_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("properties.id"),index=True); policy_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("configuration_compliance_policies.id")); rule_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("configuration_compliance_rules.id")); reason:Mapped[str]=mapped_column(Text); requested_by:Mapped[str]=mapped_column(String); approved_by:Mapped[str|None]=mapped_column(String); status:Mapped[str]=mapped_column(String(20),default="requested"); expires_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default="now()",nullable=False)
