import uuid
from datetime import datetime
from sqlalchemy import DateTime, ForeignKey, Integer, String, Text, Boolean, Index
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column
from app.db.database import Base
class ConfigurationChangeRequest(Base):
    __tablename__="configuration_change_requests"
    id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); property_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("properties.id"),index=True); title:Mapped[str]=mapped_column(String(160)); description:Mapped[str|None]=mapped_column(Text); change_type:Mapped[str]=mapped_column(String(30),default="restore_configuration"); status:Mapped[str]=mapped_column(String(20),default="draft",index=True); risk_level:Mapped[str]=mapped_column(String(20),default="unknown"); business_reason:Mapped[str]=mapped_column(Text); requested_by:Mapped[str]=mapped_column(String); approved_by:Mapped[str|None]=mapped_column(String); scheduled_start:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); scheduled_end:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); emergency_change:Mapped[bool]=mapped_column(Boolean,default=False,server_default="false"); rollback_required:Mapped[bool]=mapped_column(Boolean,default=True,server_default="true"); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default="now()",nullable=False)
class ConfigurationChangeWindow(Base):
    __tablename__="configuration_change_windows"
    id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); property_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("properties.id"),index=True); name:Mapped[str]=mapped_column(String(120)); window_type:Mapped[str]=mapped_column(String(20),default="standard"); start_at:Mapped[datetime]=mapped_column(DateTime(timezone=True)); end_at:Mapped[datetime]=mapped_column(DateTime(timezone=True)); timezone:Mapped[str]=mapped_column(String(64),default="UTC"); enabled:Mapped[bool]=mapped_column(Boolean,default=True,server_default="true")
class ConfigurationRestorePlan(Base):
    __tablename__="configuration_restore_plans"
    id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); change_request_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("configuration_change_requests.id",ondelete="CASCADE")); source_version_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("device_configuration_versions.id")); status:Mapped[str]=mapped_column(String(20),default="draft"); pre_change_backup_required:Mapped[bool]=mapped_column(Boolean,default=True,server_default="true"); dry_run_required:Mapped[bool]=mapped_column(Boolean,default=True,server_default="true"); restore_method:Mapped[str]=mapped_column(String(30),default="unsupported"); risk_summary:Mapped[str|None]=mapped_column(Text); checksum:Mapped[str|None]=mapped_column(String(64)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default="now()",nullable=False)
class ConfigurationRestoreDryRun(Base):
    __tablename__="configuration_restore_dry_runs"
    id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); restore_plan_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("configuration_restore_plans.id",ondelete="CASCADE")); status:Mapped[str]=mapped_column(String(20),default="failed"); checks_total:Mapped[int]=mapped_column(Integer,default=1); checks_passed:Mapped[int]=mapped_column(Integer,default=0); checks_failed:Mapped[int]=mapped_column(Integer,default=1); eligible_for_execution:Mapped[bool]=mapped_column(Boolean,default=False); safe_results:Mapped[str|None]=mapped_column(Text); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default="now()",nullable=False)
