import uuid
from datetime import datetime
from sqlalchemy import Boolean, DateTime, ForeignKey, Integer, String, LargeBinary, Index, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column
from app.db.database import Base
class ConfigurationDeviceProfile(Base):
    __tablename__="configuration_device_profiles"
    id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); property_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey("properties.id",ondelete="CASCADE"),index=True); name:Mapped[str]=mapped_column(String(120),nullable=False); code:Mapped[str]=mapped_column(String(50),unique=True,nullable=False); vendor:Mapped[str|None]=mapped_column(String(80)); platform:Mapped[str|None]=mapped_column(String(80)); connection_method:Mapped[str]=mapped_column(String(30),default="manual",server_default="manual"); backup_strategy:Mapped[str]=mapped_column(String(30),default="manual_upload",server_default="manual_upload"); export_format:Mapped[str|None]=mapped_column(String(20)); supports_restore:Mapped[bool]=mapped_column(Boolean,default=False,server_default="false"); enabled:Mapped[bool]=mapped_column(Boolean,default=True,server_default="true"); description:Mapped[str|None]=mapped_column(String(255))
class ConfigurationBackupPolicy(Base):
    __tablename__="configuration_backup_policies"
    id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); property_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey("properties.id",ondelete="CASCADE"),index=True); name:Mapped[str]=mapped_column(String(120),nullable=False); enabled:Mapped[bool]=mapped_column(Boolean,default=True,server_default="true"); backup_frequency:Mapped[str]=mapped_column(String(20),default="manual",server_default="manual"); retention_count:Mapped[int]=mapped_column(Integer,default=10,server_default="10"); retention_days:Mapped[int]=mapped_column(Integer,default=365,server_default="365"); encrypt_content:Mapped[bool]=mapped_column(Boolean,default=True,server_default="true"); maximum_backup_size_bytes:Mapped[int]=mapped_column(Integer,default=10485760,server_default="10485760")
class ConfigurationBackupRun(Base):
    __tablename__="configuration_backup_runs"
    id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); property_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("properties.id"),index=True); device_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("devices.id"),index=True); status:Mapped[str]=mapped_column(String(20),nullable=False); trigger_type:Mapped[str]=mapped_column(String(30),default="manual_upload"); configuration_scope:Mapped[str]=mapped_column(String(30),default="full"); bytes_received:Mapped[int|None]=mapped_column(Integer); checksum:Mapped[str|None]=mapped_column(String(128)); error_summary:Mapped[str|None]=mapped_column(String(255)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default="now()",nullable=False)
class DeviceConfigurationVersion(Base):
    __tablename__="device_configuration_versions"
    id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); property_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("properties.id"),index=True); device_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("devices.id"),index=True); backup_run_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("configuration_backup_runs.id"),nullable=False); version_number:Mapped[int]=mapped_column(Integer,nullable=False); configuration_scope:Mapped[str]=mapped_column(String(30),default="full"); format:Mapped[str]=mapped_column(String(20),default="txt"); encrypted_content:Mapped[bytes]=mapped_column(LargeBinary,nullable=False); original_filename:Mapped[str|None]=mapped_column(String(255)); content_size_bytes:Mapped[int]=mapped_column(Integer,nullable=False); checksum:Mapped[str]=mapped_column(String(64),nullable=False,index=True); checksum_algorithm:Mapped[str]=mapped_column(String(20),default="sha256",server_default="sha256"); is_baseline:Mapped[bool]=mapped_column(Boolean,default=False,server_default="false"); is_protected:Mapped[bool]=mapped_column(Boolean,default=False,server_default="false"); source_type:Mapped[str]=mapped_column(String(30),default="manual_upload"); captured_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default="now()",nullable=False); __table_args__=(Index("uq_config_version_scope","device_id","configuration_scope","version_number",unique=True),)
