import uuid
from datetime import datetime

from sqlalchemy import Boolean, CheckConstraint, DateTime, Float, ForeignKey, Index, Integer, String, Text, UniqueConstraint
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.sql import func

from app.db.database import Base

def uid():return mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4)
def now():return mapped_column(DateTime(timezone=True),server_default=func.now(),nullable=False)

class DiscoveryPolicy(Base):
    __tablename__="enterprise_discovery_policies";id:Mapped[uuid.UUID]=uid();name:Mapped[str]=mapped_column(String(180));property_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey("properties.id"),index=True);authorized_ranges:Mapped[str]=mapped_column(Text);excluded_ranges:Mapped[str]=mapped_column(Text,default="[]");enabled_stages:Mapped[str]=mapped_column(Text,default="[]");allowed_ports:Mapped[str]=mapped_column(Text,default="[]");max_hosts:Mapped[int]=mapped_column(Integer,default=1024);concurrency:Mapped[int]=mapped_column(Integer,default=20);timeout_seconds:Mapped[int]=mapped_column(Integer,default=2);rate_limit_per_second:Mapped[int]=mapped_column(Integer,default=20);allow_credentialed:Mapped[bool]=mapped_column(Boolean,default=False);enabled:Mapped[bool]=mapped_column(Boolean,default=True);created_by:Mapped[str]=mapped_column(String,ForeignKey("users.id"));created_at:Mapped[datetime]=now();updated_at:Mapped[datetime]=now()
class DiscoveryCredential(Base):
    __tablename__="enterprise_discovery_credentials";id:Mapped[uuid.UUID]=uid();policy_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("enterprise_discovery_policies.id",ondelete="CASCADE"),index=True);name:Mapped[str]=mapped_column(String(180));credential_type:Mapped[str]=mapped_column(String(30));username:Mapped[str|None]=mapped_column(String(180));secret_ciphertext:Mapped[str]=mapped_column(Text);scope_cidr:Mapped[str|None]=mapped_column(String(64));least_privilege_notes:Mapped[str]=mapped_column(Text);enabled:Mapped[bool]=mapped_column(Boolean,default=False);last_used_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));created_by:Mapped[str]=mapped_column(String,ForeignKey("users.id"));created_at:Mapped[datetime]=now();__table_args__=(UniqueConstraint("policy_id","name",name="uq_discovery_credential_policy_name"),)
class DiscoveryJob(Base):
    __tablename__="enterprise_discovery_jobs";id:Mapped[uuid.UUID]=uid();policy_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("enterprise_discovery_policies.id"),index=True);property_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey("properties.id"),index=True);job_type:Mapped[str]=mapped_column(String(30));trigger_type:Mapped[str]=mapped_column(String(30));network_range:Mapped[str]=mapped_column(String(64));status:Mapped[str]=mapped_column(String(30),default="pending",index=True);current_stage:Mapped[str|None]=mapped_column(String(60));hosts_total:Mapped[int]=mapped_column(Integer,default=0);hosts_completed:Mapped[int]=mapped_column(Integer,default=0);tasks_failed:Mapped[int]=mapped_column(Integer,default=0);requested_by:Mapped[str|None]=mapped_column(String,ForeignKey("users.id"));started_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));completed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));created_at:Mapped[datetime]=now();__table_args__=(Index("ix_enterprise_discovery_job_property_status","property_id","status"),)
class DiscoveryStage(Base):
    __tablename__="enterprise_discovery_stages";id:Mapped[uuid.UUID]=uid();job_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("enterprise_discovery_jobs.id",ondelete="CASCADE"),index=True);stage_key:Mapped[str]=mapped_column(String(60));sequence:Mapped[int]=mapped_column(Integer);status:Mapped[str]=mapped_column(String(30),default="pending");attempts:Mapped[int]=mapped_column(Integer,default=0);started_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));completed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));error:Mapped[str|None]=mapped_column(Text);__table_args__=(UniqueConstraint("job_id","stage_key",name="uq_discovery_job_stage"),UniqueConstraint("job_id","sequence",name="uq_discovery_job_stage_sequence"))
class DiscoveryTask(Base):
    __tablename__="enterprise_discovery_tasks";id:Mapped[uuid.UUID]=uid();job_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("enterprise_discovery_jobs.id",ondelete="CASCADE"),index=True);stage_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("enterprise_discovery_stages.id",ondelete="CASCADE"),index=True);target:Mapped[str]=mapped_column(String(255));status:Mapped[str]=mapped_column(String(30),default="pending",index=True);attempts:Mapped[int]=mapped_column(Integer,default=0);max_attempts:Mapped[int]=mapped_column(Integer,default=3);next_retry_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));started_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));completed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));error_code:Mapped[str|None]=mapped_column(String(80));error:Mapped[str|None]=mapped_column(Text);__table_args__=(UniqueConstraint("stage_id","target",name="uq_discovery_stage_target"),)
class DiscoveryResult(Base):
    __tablename__="enterprise_discovery_results";id:Mapped[uuid.UUID]=uid();job_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("enterprise_discovery_jobs.id",ondelete="CASCADE"),index=True);discovered_device_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey("discovered_devices.id"),index=True);property_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey("properties.id"),index=True);ip_address:Mapped[str]=mapped_column(String(45),index=True);primary_hostname:Mapped[str|None]=mapped_column(String(255));fqdn:Mapped[str|None]=mapped_column(String(255));dns_status:Mapped[str]=mapped_column(String(40),default="not_attempted",server_default="not_attempted");friendly_name:Mapped[str|None]=mapped_column(String(255));department:Mapped[str|None]=mapped_column(String(120));device_number:Mapped[str|None]=mapped_column(String(40));description:Mapped[str|None]=mapped_column(Text);description_source:Mapped[str|None]=mapped_column(String(40));location:Mapped[str|None]=mapped_column(String(160));mac_address:Mapped[str|None]=mapped_column(String(17),index=True);vendor:Mapped[str|None]=mapped_column(String(160));device_type:Mapped[str]=mapped_column(String(80),default="Unknown Device");classification:Mapped[str]=mapped_column(String(120),default="Unknown Device");operating_system:Mapped[str|None]=mapped_column(String(180));review_status:Mapped[str]=mapped_column(String(40),default="needs_review",index=True);confidence_score:Mapped[int]=mapped_column(Integer,default=0);confidence_explanation:Mapped[str]=mapped_column(Text,default="[]");configuration_snapshot:Mapped[str]=mapped_column(Text,default="{}");configuration_checksum:Mapped[str|None]=mapped_column(String(64));ci_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey("configuration_items.id"),index=True);first_seen_at:Mapped[datetime]=now();last_seen_at:Mapped[datetime]=now();last_changed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));__table_args__=(CheckConstraint("confidence_score BETWEEN 0 AND 100",name="ck_enterprise_discovery_confidence"),UniqueConstraint("job_id","ip_address",name="uq_discovery_result_job_ip"))
class DiscoveryEvidence(Base):
    __tablename__="enterprise_discovery_evidence";id:Mapped[uuid.UUID]=uid();result_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("enterprise_discovery_results.id",ondelete="CASCADE"),index=True);task_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True),ForeignKey("enterprise_discovery_tasks.id",ondelete="SET NULL"));evidence_type:Mapped[str]=mapped_column(String(60),index=True);source:Mapped[str]=mapped_column(String(60));value:Mapped[str]=mapped_column(Text);normalized_value:Mapped[str|None]=mapped_column(String(500),index=True);weight:Mapped[int]=mapped_column(Integer,default=0);verified:Mapped[bool]=mapped_column(Boolean,default=False);observed_at:Mapped[datetime]=now();expires_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));__table_args__=(UniqueConstraint("result_id","evidence_type","source","normalized_value",name="uq_discovery_evidence_identity"),)
class DiscoveryFingerprint(Base):
    __tablename__="enterprise_discovery_fingerprints";id:Mapped[uuid.UUID]=uid();result_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("enterprise_discovery_results.id",ondelete="CASCADE"),unique=True,index=True);fingerprint_version:Mapped[str]=mapped_column(String(20),default="1.0");device_family:Mapped[str]=mapped_column(String(80));classification:Mapped[str]=mapped_column(String(120));operating_system:Mapped[str|None]=mapped_column(String(180));service_fingerprints:Mapped[str]=mapped_column(Text,default="[]");hostname_candidates:Mapped[str]=mapped_column(Text,default="[]");hardware:Mapped[str]=mapped_column(Text,default="{}");software:Mapped[str]=mapped_column(Text,default="{}");network:Mapped[str]=mapped_column(Text,default="{}");certificate_summary:Mapped[str]=mapped_column(Text,default="{}");confidence_score:Mapped[int]=mapped_column(Integer);rules_matched:Mapped[str]=mapped_column(Text,default="[]");editable_override:Mapped[str|None]=mapped_column(String(120));updated_at:Mapped[datetime]=now()
class DiscoveryOUI(Base):
    __tablename__="discovery_oui_vendors";id:Mapped[uuid.UUID]=uid();prefix:Mapped[str]=mapped_column(String(6),unique=True,index=True);vendor:Mapped[str]=mapped_column(String(180),index=True);source:Mapped[str]=mapped_column(String(60),default="bundled");version:Mapped[str]=mapped_column(String(40),default="2026.1");updated_at:Mapped[datetime]=now()
class DiscoveryDHCPLease(Base):
    __tablename__="enterprise_discovery_dhcp_leases";id:Mapped[uuid.UUID]=uid();ip_address:Mapped[str]=mapped_column(String(45),index=True);mac_address:Mapped[str]=mapped_column(String(17),index=True);hostname:Mapped[str|None]=mapped_column(String(255),index=True);source:Mapped[str]=mapped_column(String(120));lease_server:Mapped[str|None]=mapped_column(String(255));starts_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));expires_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),index=True);is_reservation:Mapped[bool]=mapped_column(Boolean,default=False,server_default="false");reservation_name:Mapped[str|None]=mapped_column(String(255));description:Mapped[str|None]=mapped_column(Text);last_imported_at:Mapped[datetime]=now();created_by:Mapped[str|None]=mapped_column(String,ForeignKey("users.id",ondelete="SET NULL"));__table_args__=(UniqueConstraint("source","ip_address","mac_address",name="uq_discovery_dhcp_lease_identity"),)
class DiscoveryChangeSuggestion(Base):
    __tablename__="discovery_change_suggestions";id:Mapped[uuid.UUID]=uid();result_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("enterprise_discovery_results.id",ondelete="CASCADE"),index=True);ci_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),ForeignKey("configuration_items.id"),index=True);change_type:Mapped[str]=mapped_column(String(40));previous_value:Mapped[str|None]=mapped_column(Text);current_value:Mapped[str]=mapped_column(Text);status:Mapped[str]=mapped_column(String(30),default="proposed",index=True);created_at:Mapped[datetime]=now();__table_args__=(UniqueConstraint("result_id","ci_id","change_type","current_value",name="uq_discovery_change_suggestion"),)
