import { useEffect, useMemo, useState, type DragEvent } from "react";
import { Feedback } from "../Feedback";
import { Icon } from "../Icon";
import Modal from "../Modal";
import { StatusBadge } from "../StatusBadge";
import { useRequest } from "../../hooks/useRequest";
import { endpoints } from "../../lib/api";
import type { Device, DiscoveredDevice, HierarchyCatalog, ImportColumnDetection, ImportedDevice, ImportLocationSuggestion, ImportMatchCandidate, ImportPreview, ImportSession, ImportValidationStatus, LocationReviewInput, MergePlan } from "../../lib/types";

const canonicalFields = ["asset_tag","hostname","ip_address","mac_address","department_name","building_name","floor_name","room_name","network_zone","vendor","brand","model","serial_number","inventory_status","notes"];
const requiredFields = new Set(["asset_tag", "hostname"]);
const display = (value: unknown) => value == null || value === "" ? "—" : String(value);
const message = (error: unknown) => error instanceof Error ? error.message : "The import request could not be completed.";

export function UploadStep({admin,onUploaded}:{admin:boolean;onUploaded:(session:ImportSession,preview:ImportPreview)=>void}) {
  const [file,setFile]=useState<File|null>(null); const [drag,setDrag]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [controller,setController]=useState<AbortController|null>(null);
  const choose=(candidate:File|undefined)=>{setError("");if(!candidate)return;const extension=candidate.name.split(".").pop()?.toLowerCase();if(!["csv","xlsx"].includes(extension??"")){setFile(null);setError("Choose a CSV or XLSX file.");return}setFile(candidate)};
  const drop=(event:DragEvent)=>{event.preventDefault();setDrag(false);choose(event.dataTransfer.files[0])};
  const upload=async()=>{if(!file||!admin)return;const next=new AbortController();setController(next);setBusy(true);setError("");try{const result=await endpoints.uploadImport(file,next.signal);onUploaded(result.session,result.preview)}catch(error){if(next.signal.aborted)setError("Upload cancelled before staging completed.");else setError(message(error))}finally{setBusy(false);setController(null)}};
  return <section className="wizard-card"><div className="wizard-card-head"><span className="step-number">1</span><div><h2>Upload device inventory</h2><p>CSV and XLSX are parsed into staging only. Nothing is added directly to Devices.</p></div></div>
    {!admin&&<div className="inline-notice warning" role="alert">Only administrators can upload inventory files. Your access is read-only.</div>}
    <div className={`import-dropzone ${drag?"dragging":""}`} onDragOver={event=>{event.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={drop}>
      <Icon name="import" size={34}/><strong>Drop CSV or XLSX here</strong><span>or</span><label className="secondary-action">Browse file<input type="file" accept=".csv,.xlsx,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={event=>choose(event.target.files?.[0])} disabled={!admin||busy}/></label><small>Backend-enforced size and content checks apply. The configured default limit is 10 MiB.</small>
    </div>
    {file&&<div className="selected-file"><Icon name="server"/><div><strong>{file.name}</strong><span>{(file.size/1024).toFixed(1)} KiB · {file.type||"content type unavailable"}</span></div><button className="icon-button" aria-label="Clear selected file" onClick={()=>setFile(null)} disabled={busy}><Icon name="close"/></button></div>}
    <div className="import-guidance"><div><strong>Required</strong><span>Asset tag, hostname</span></div><div><strong>Recommended</strong><span>MAC, serial, IP, department and location</span></div><div><strong>Security</strong><span>Macros and formulas are never executed</span></div></div>
    {error&&<div className="inline-notice error" role="alert">{error}</div>}{busy&&<div className="processing-state" role="status"><span className="spinner"/><div><strong>Uploading and inspecting file</strong><span>Extension, content, workbook and row limits are being checked.</span></div><span className="progress-track indeterminate"><i/></span></div>}
    <footer className="wizard-actions">{busy&&<button className="secondary-action" onClick={()=>controller?.abort()}>Cancel upload</button>}<button className="primary-action" disabled={!file||!admin||busy} onClick={()=>void upload()}>{busy?"Uploading…":"Upload securely"}</button></footer>
  </section>;
}

export function WorksheetStep({columns,worksheet,onSelect,onContinue}:{columns:ImportColumnDetection;worksheet:string;onSelect:(value:string)=>void;onContinue:()=>void}) {
  const names=columns.worksheet_names??[]; return <section className="wizard-card"><div className="wizard-card-head"><span className="step-number">2</span><div><h2>Select worksheet</h2><p>{names.length?"Choose the worksheet whose headers should be mapped.":"CSV contains one logical table, so worksheet selection is not required."}</p></div></div>
    {!names.length?<div className="empty-inline"><Icon name="check"/><strong>CSV detected</strong><span>This step can be skipped safely.</span></div>:<div className="worksheet-grid">{names.map(name=><button key={name} className={worksheet===name?"active":""} onClick={()=>onSelect(name)}><Icon name="server"/><strong>{name}</strong><span>{name===columns.selected_worksheet?"Detected default":"Available worksheet"}</span></button>)}</div>}
    <footer className="wizard-actions"><button className="primary-action" disabled={!!names.length&&!worksheet} onClick={onContinue}>Continue to mapping</button></footer>
  </section>;
}

export function MappingStep({sessionId,columns,worksheet,admin,onSaved}:{sessionId:string;columns:ImportColumnDetection;worksheet:string;admin:boolean;onSaved:(value:ImportColumnDetection)=>void}) {
  const headers=columns.headers??columns.preview?.detected_headers??Object.keys(columns.mapping??columns.suggested_mapping??{}); const suggested=columns.suggested_mapping??{};
  const [mapping,setMapping]=useState<Record<string,string|null>>(()=>({...suggested,...(columns.mapping??{})})); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  const targets=Object.values(mapping).filter(Boolean) as string[]; const duplicates=new Set(targets.filter((value,index)=>targets.indexOf(value)!==index)); const mappedRequired=new Set(targets.filter(value=>requiredFields.has(value))); const missing=[...requiredFields].filter(value=>!mappedRequired.has(value));
  const save=async()=>{setBusy(true);setError("");try{const result=await endpoints.saveImportMapping(sessionId,mapping,worksheet||null);onSaved(result)}catch(error){setError(message(error))}finally{setBusy(false)}};
  const samples=(header:string)=>columns.preview?.rows.slice(0,3).map(row=>display(row.raw_data[header])).filter(value=>value!=="—").join(" · ")||"No sample value";
  return <section className="wizard-card"><div className="wizard-card-head"><span className="step-number">3</span><div><h2>Map source columns</h2><p>Backend validation remains authoritative. Duplicate targets and missing required fields block validation.</p></div></div>
    {(missing.length>0||duplicates.size>0)&&<div className="inline-notice error" role="alert">{missing.length>0&&<>Required mappings missing: {missing.join(", ")}. </>}{duplicates.size>0&&<>Duplicate targets: {[...duplicates].join(", ")}.</>}</div>}
    <div className="mapping-list" role="table" aria-label="Column mappings"><div className="mapping-row heading" role="row"><strong>Source column</strong><strong>HIOP field</strong><strong>Samples and status</strong></div>{headers.map(header=>{const target=mapping[header]??null;return <div className={`mapping-row ${target&&duplicates.has(target)?"conflict":""}`} key={header} role="row"><div><strong>{header}</strong><small>{suggested[header]?"Suggested mapping":"Unknown source column"}</small></div><label><span className="sr-only">Map {header}</span><select value={target??""} onChange={event=>setMapping(current=>({...current,[header]:event.target.value||null}))} disabled={!admin||busy}><option value="">Ignore column</option>{canonicalFields.map(field=><option key={field} value={field}>{field.replaceAll("_"," ")}{requiredFields.has(field)?" *":""}</option>)}</select></label><div><span>{samples(header)}</span>{target&&<small className={duplicates.has(target)?"text-danger":"text-success"}>{duplicates.has(target)?"Target already used":requiredFields.has(target)?"Required field":"Optional field"}</small>}</div></div>})}</div>
    {columns.preview?.rows.length?<PreviewTable preview={columns.preview}/>:<div className="empty-inline"><Icon name="search"/><span>No resumable preview is available after processing; saved mapping remains authoritative.</span></div>}
    {error&&<div className="inline-notice error" role="alert">{error}</div>}<footer className="wizard-actions"><button className="secondary-action" disabled={!admin||busy} onClick={()=>setMapping({...suggested})}>Reset suggestions</button><button className="primary-action" disabled={!admin||busy||missing.length>0||duplicates.size>0} onClick={()=>void save()}>{busy?"Saving…":"Save mapping"}</button></footer>
  </section>;
}

function PreviewTable({preview}:{preview:ImportPreview}) { const fields=[...new Set(preview.rows.flatMap(row=>Object.keys(row.raw_data)))].slice(0,8); return <div className="mapping-preview"><header><h3>Limited mapping preview</h3><span>{preview.rows.length} safe preview rows</span></header><div className="table-wrap"><table className="data-table"><thead><tr><th>Row</th>{fields.map(field=><th key={field}>{field}</th>)}<th>Findings</th></tr></thead><tbody>{preview.rows.map(row=><tr key={row.source_row_number}><td>{row.source_row_number}</td>{fields.map(field=><td key={field}>{display(row.raw_data[field])}</td>)}<td>{row.errors.length} errors · {row.warnings.length} warnings</td></tr>)}</tbody></table></div></div> }

export function ValidationStep({session,admin,onValidated}:{session:ImportSession;admin:boolean;onValidated:(session:ImportSession)=>void}) {
  const [status,setStatus]=useState<ImportValidationStatus|"">(""); const [search,setSearch]=useState(""); const [page,setPage]=useState(1); const [detail,setDetail]=useState<ImportedDevice|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  const rows=useRequest(()=>endpoints.importRows(session.id,{validation_status:status||undefined,search:search||undefined,page,page_size:25}),[session.id,status,search,page]);
  const validate=async()=>{setBusy(true);setError("");try{const result=await endpoints.validateImport(session.id);onValidated(result);await rows.reload()}catch(error){setError(message(error))}finally{setBusy(false)}};
  const exportErrors=async()=>{setBusy(true);try{const result=await endpoints.exportImportErrors(session.id);const url=URL.createObjectURL(result.blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=result.filename;anchor.click();URL.revokeObjectURL(url)}catch(error){setError(message(error))}finally{setBusy(false)}};
  const counts=session.validation_summary??{}; return <section className="wizard-card"><div className="wizard-card-head"><span className="step-number">4</span><div><h2>Validate staged rows</h2><p>Errors are retained for correction in the source file; staged rows are read-only.</p></div></div>
    <div className="mini-kpis">{[["Total",session.total_rows],["Valid",counts.valid??0],["Warning",counts.warning??0],["Invalid",counts.invalid??session.failed_rows],["Duplicate",counts.duplicate??session.duplicate_rows],["Skipped",session.skipped_rows]].map(([label,value])=><div key={String(label)}><span>{label}</span><strong>{value}</strong></div>)}</div>
    {session.status==="uploaded"&&<div className="empty-inline"><Icon name="clock"/><div><strong>Validation has not run</strong><span>Save mapping first, then ask the backend to parse and stage every row.</span></div>{admin&&<button className="primary-action" disabled={busy} onClick={()=>void validate()}>{busy?"Validating…":"Validate rows"}</button>}</div>}
    <div className="toolbar import-toolbar"><label className="search-field"><Icon name="search"/><input aria-label="Search validation rows" value={search} onChange={event=>{setSearch(event.target.value);setPage(1)}} placeholder="Asset, host, IP, MAC or serial"/></label><select aria-label="Validation status" value={status} onChange={event=>{setStatus(event.target.value as ImportValidationStatus|"");setPage(1)}}><option value="">All statuses</option>{["valid","warning","invalid","duplicate"].map(value=><option key={value}>{value}</option>)}</select><button className="secondary-action" disabled={busy} onClick={()=>void exportErrors()}>Download validation errors</button></div>
    {error&&<div className="inline-notice error" role="alert">{error}</div>}{rows.loading||rows.error?<Feedback loading={rows.loading} error={rows.error} onRetry={rows.reload}/>:!rows.data?.items.length?<Feedback emptyTitle="No staged rows" empty={session.status==="uploaded"?"Run validation to create staging records.":"No rows match the active filters."}/>:<div className="table-wrap"><table className="data-table"><thead><tr><th>Row</th><th>Asset tag</th><th>Hostname</th><th>IP</th><th>MAC</th><th>Department / location</th><th>Status</th><th>Findings</th><th>Action</th></tr></thead><tbody>{rows.data.items.map(row=><tr key={row.id}><td>{row.source_row_number}</td><td>{display(row.asset_tag)}</td><td>{display(row.hostname)}</td><td>{display(row.ip_address)}</td><td>{display(row.mac_address)}</td><td>{display(row.department_name)} · {display(row.room_name)}</td><td><StatusBadge status={row.validation_status}/></td><td>{row.errors.length} errors · {row.warnings.length} warnings</td><td><button className="table-link" onClick={()=>setDetail(row)}>Review</button></td></tr>)}</tbody></table></div>}
    {rows.data&&rows.data.pages>1&&<Pagination current={page} pages={rows.data.pages} onChange={setPage}/>} {detail&&<RowDetail row={detail} onClose={()=>setDetail(null)}/>}
  </section>;
}

function RowDetail({row,onClose}:{row:ImportedDevice;onClose:()=>void}) { return <Modal title={`Source row ${row.source_row_number}`} onClose={onClose}><div className="modal-body import-detail"><div className="inline-notice warning">Read-only staging record. Correct the source file and restart when changes are required.</div><KeyValues title="Original row" values={row.raw_data}/><KeyValues title="Normalized row" values={row.normalized_data}/><IssueList title="Errors" items={row.errors}/><IssueList title="Warnings" items={row.warnings}/></div></Modal> }
function KeyValues({title,values}:{title:string;values:Record<string,unknown>}) { return <section><h3>{title}</h3><dl className="key-values">{Object.entries(values).map(([key,value])=><div key={key}><dt>{key.replaceAll("_"," ")}</dt><dd>{display(value)}</dd></div>)}</dl></section> }
function IssueList({title,items}:{title:string;items:Array<{field?:string;code:string;message:string;related_row_number?:number}>}) { return <section><h3>{title}</h3>{items.length?<ul className="issue-list">{items.map((item,index)=><li key={`${item.code}-${index}`}><strong>{item.field??"row"}: {item.code}</strong><span>{item.message}{item.related_row_number?` (row ${item.related_row_number})`:""}</span></li>)}</ul>:<p>No {title.toLowerCase()}.</p>}</section> }

export function MatchReviewStep({session,admin,conflictsOnly=false,onChanged}:{session:ImportSession;admin:boolean;conflictsOnly?:boolean;onChanged:()=>Promise<void>}) {
  const matches=useRequest(()=>endpoints.importMatches(session.id,{has_conflicts:conflictsOnly?"true":undefined,page_size:100}),[session.id,conflictsOnly]); const rows=useRequest(()=>endpoints.importRows(session.id,{page_size:100}),[session.id]); const [selected,setSelected]=useState<ImportMatchCandidate|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [checked,setChecked]=useState<Set<string>>(new Set());
  const topByRow=useMemo(()=>{const map=new Map<string,ImportMatchCandidate>();for(const candidate of matches.data?.items??[]){if(!map.has(candidate.imported_device_id))map.set(candidate.imported_device_id,candidate)}return map},[matches.data]);
  const queue=(rows.data?.items??[]).filter(row=>row.validation_status!=="invalid").map(row=>({row,candidate:topByRow.get(row.id)})).filter(item=>!conflictsOnly||!!item.candidate?.conflicting_fields.length);
  const refresh=async()=>{await Promise.all([matches.reload(),rows.reload(),onChanged()])};
  const run=async(recompute=false)=>{setBusy(true);setError("");try{if(recompute)await endpoints.recomputeImportMatches(session.id);else await endpoints.runImportMatching(session.id);await refresh()}catch(error){setError(message(error))}finally{setBusy(false)}};
  const resolve=async(action:"accept"|"reject"|"create"|"skip",row:ImportedDevice,candidate?:ImportMatchCandidate)=>{if(!admin)return;if(action==="accept"&&candidate?.conflicting_fields.length&&!window.confirm("This candidate contains identifier conflicts. Accept the reviewed staging link anyway?"))return;setBusy(true);setError("");try{if(action==="accept"&&candidate)await endpoints.acceptImportMatch(session.id,row.id,candidate.id);if(action==="reject"&&candidate)await endpoints.rejectImportMatch(session.id,row.id,candidate.id);if(action==="create")await endpoints.markImportCreateNew(session.id,row.id);if(action==="skip")await endpoints.markImportSkip(session.id,row.id);setSelected(null);await refresh()}catch(error){setError(message(error))}finally{setBusy(false)}};
  const bulk=async(action:"accept"|"reject"|"create"|"skip")=>{const items=queue.filter(item=>checked.has(item.row.id));const safe=action!=="accept"?items:items.filter(item=>item.candidate?.match_level==="exact"&&!item.candidate.conflicting_fields.length&&item.candidate.match_status==="pending");if(!safe.length){setError(action==="accept"?"Bulk accept requires pending exact matches with no conflicts.":"Select at least one eligible row.");return}if(!window.confirm(`${action} ${safe.length} selected records? Each result will remain auditable.`))return;setBusy(true);const failures:string[]=[];for(const item of safe){try{await resolveOne(action,item.row,item.candidate)}catch(error){failures.push(`${item.row.hostname??item.row.asset_tag??item.row.id}: ${message(error)}`)}}setChecked(new Set());setError(failures.length?`${failures.length} records failed: ${failures.slice(0,3).join("; ")}`:"");setBusy(false);await refresh()};
  const resolveOne=async(action:string,row:ImportedDevice,candidate?:ImportMatchCandidate)=>{if(action==="accept"&&candidate)return endpoints.acceptImportMatch(session.id,row.id,candidate.id);if(action==="reject"&&candidate)return endpoints.rejectImportMatch(session.id,row.id,candidate.id);if(action==="create")return endpoints.markImportCreateNew(session.id,row.id);return endpoints.markImportSkip(session.id,row.id)};
  const summary=session.match_summary??{}; return <section className="wizard-card"><div className="wizard-card-head"><span className="step-number">{conflictsOnly?7:5}</span><div><h2>{conflictsOnly?"Resolve conflicts":"Review matches and duplicates"}</h2><p>Compare explainable candidates. No action here mutates official inventory.</p></div></div>
    <div className="mini-kpis">{[["Exact",summary.exact??0],["Strong",summary.strong??0],["Probable",summary.probable??0],["Weak",summary.weak??0],["Conflicts",summary.conflicts??0],["Unmatched",summary.unmatched??0],["Resolved",summary.resolved??0],["Create-new",summary.suggested_new_devices??0]].map(([label,value])=><div key={String(label)}><span>{label}</span><strong>{value}</strong></div>)}</div>
    <div className="wizard-toolbar"><div>{admin&&<><button className="primary-action" disabled={busy} onClick={()=>void run(session.matching_state==="completed")}>{busy?"Working…":session.matching_state==="completed"?"Recompute candidates":"Run matching"}</button><button className="secondary-action" disabled={busy} onClick={()=>void bulk("accept")}>Accept safe exact</button><button className="secondary-action" disabled={busy} onClick={()=>void bulk("reject")}>Reject selected</button><button className="secondary-action" disabled={busy} onClick={()=>void bulk("create")}>Mark create-new</button><button className="secondary-action" disabled={busy} onClick={()=>void bulk("skip")}>Skip selected</button></>}</div><span>{checked.size} selected</span></div>
    {error&&<div className="inline-notice error" role="alert">{error}</div>}{matches.loading||rows.loading||matches.error||rows.error?<Feedback loading={matches.loading||rows.loading} error={matches.error||rows.error} onRetry={()=>void refresh()}/>:!queue.length?<Feedback emptyTitle={conflictsOnly?"No conflicts":"No match candidates"} empty={session.matching_state==="idle"?"Run matching to generate candidates.":conflictsOnly?"No conflicting candidate is waiting in this page.":"No validated rows are available."}/>:<div className="review-queue">{queue.map(({row,candidate})=><article key={row.id} className={`review-card ${candidate?.conflicting_fields.length?"has-conflict":""}`}><label className="select-row"><input type="checkbox" checked={checked.has(row.id)} onChange={event=>setChecked(current=>{const next=new Set(current);if(event.target.checked)next.add(row.id);else next.delete(row.id);return next})}/><span className="sr-only">Select {row.hostname??row.asset_tag}</span></label><div className="review-identity"><strong>{row.hostname??"Unnamed device"}</strong><span>{row.asset_tag??"No asset tag"} · {row.ip_address??"No IP"} · {row.mac_address??"No MAC"}</span><small>{row.resolution_action?`Resolved: ${row.resolution_action}`:"Pending review"}</small></div>{candidate?<><div className="match-score"><strong>{candidate.match_score}</strong><span>{candidate.match_level}</span></div><div className="match-summary"><strong>{candidate.candidate_type.replaceAll("_"," ")}</strong><span>{candidate.matching_fields.length} matching fields · {candidate.conflicting_fields.length} conflicts</span><small>Recommendation: {candidate.recommended_action}</small></div><StatusBadge status={candidate.match_status}/></>:<div className="match-summary"><strong>No candidate</strong><span>Backend found no score above the weak threshold.</span></div>}<div className="row-actions import-actions">{candidate&&<button onClick={()=>setSelected(candidate)}>Compare</button>}{admin&&!row.resolution_action&&candidate?.match_status==="pending"&&<><button onClick={()=>void resolve("accept",row,candidate)}>Accept</button><button onClick={()=>void resolve("reject",row,candidate)}>Reject</button></>}{admin&&!row.resolution_action&&<><button onClick={()=>void resolve("create",row)}>Create-new</button><button onClick={()=>void resolve("skip",row)}>Skip</button></>}</div></article>)}</div>}
    {selected&&<CandidateDialog sessionId={session.id} candidate={selected} onClose={()=>setSelected(null)} onAccept={()=>{const row=rows.data?.items.find(item=>item.id===selected.imported_device_id);if(row)void resolve("accept",row,selected)}}/>}
  </section>;
}

function CandidateDialog({sessionId,candidate,onClose,onAccept}:{sessionId:string;candidate:ImportMatchCandidate;onClose:()=>void;onAccept:()=>void}) {
  const [source,setSource]=useState<ImportedDevice|null>(null); const [target,setTarget]=useState<Record<string,unknown>|null>(null); const [plan,setPlan]=useState<MergePlan|null>(null); const [error,setError]=useState("");
  useEffect(()=>{let active=true;const load=async()=>{try{const imported=await endpoints.importRow(sessionId,candidate.imported_device_id);let value:ImportedDevice|Device|DiscoveredDevice;if(candidate.candidate_device_id)value=await endpoints.device(candidate.candidate_device_id);else if(candidate.candidate_discovery_id)value=await endpoints.discoveryDetail(candidate.candidate_discovery_id);else value=await endpoints.importRow(sessionId,candidate.candidate_imported_device_id!);if(active){setSource(imported);setTarget(value as unknown as Record<string,unknown>)}}catch(error){if(active)setError(message(error))}};void load();return()=>{active=false}},[sessionId,candidate]);
  const merge=async()=>{try{setPlan(await endpoints.importMergePlan(sessionId,candidate.imported_device_id,candidate.id))}catch(error){setError(message(error))}};
  const fields=["asset_tag","hostname","ip_address","mac_address","serial_number","vendor","brand","model","department_name","room_name","network_zone"];
  return <Modal title="Candidate comparison" onClose={onClose}><div className="modal-body candidate-dialog">{error&&<div className="inline-notice error">{error}</div>}{!source||!target?<Feedback loading/>:<><div className="comparison-head"><div><span>Imported row</span><strong>{source.hostname??source.asset_tag}</strong></div><div className="match-score"><strong>{candidate.match_score}</strong><span>{candidate.match_level}</span></div><div><span>{candidate.candidate_type.replaceAll("_"," ")}</span><strong>{display(target.hostname??target.asset_tag??target.ip_address)}</strong></div></div><div className="comparison-grid">{fields.map(field=>{const left=source[field as keyof ImportedDevice];const right=target[field];const same=left!=null&&right!=null&&String(left).toLowerCase()===String(right).toLowerCase();const conflict=candidate.conflicting_fields.some(item=>item.field===field);return <div key={field} className={conflict?"conflict":same?"matching":"missing"}><strong>{field.replaceAll("_"," ")}</strong><span>{display(left)}</span><i>{conflict?"Conflict":same?"Exact":"Different or missing"}</i><span>{display(right)}</span></div>})}</div><section><h3>Explainable evidence</h3><ul className="evidence-list">{candidate.evidence.map((item,index)=><li key={index}><strong>{item.field.replaceAll("_"," ")}</strong><span>{item.kind??item.source} {item.weight!=null?`+${item.weight}`:""}{item.similarity!=null?` · ${item.similarity}% similar`:""}</span></li>)}</ul></section>{candidate.conflicting_fields.length>0&&<IssueList title="Conflicting identifiers" items={candidate.conflicting_fields.map(item=>({field:item.field,code:"conflict",message:`Imported ${display(item.imported)} differs from candidate ${display(item.candidate)}.`}))}/>}<footer className="wizard-actions"><button className="secondary-action" onClick={()=>void merge()}>Open merge plan</button>{candidate.match_status==="pending"&&<button className="primary-action" onClick={onAccept}>Accept reviewed link</button>}</footer></>}{plan&&<MergePlanView plan={plan} onClose={()=>setPlan(null)}/>}</div></Modal>;
}
function MergePlanView({plan,onClose}:{plan:MergePlan;onClose:()=>void}) { return <div className="nested-plan" role="region" aria-label="Merge plan preview"><header><h3>Non-destructive merge plan</h3><button className="icon-button" onClick={onClose}><Icon name="close"/></button></header><div className="inline-notice warning">Preview only. Epic 2D cannot execute an inventory merge.</div><IssueList title="Conflicts requiring explicit future decisions" items={plan.conflicts.map(item=>({field:item.field,code:"conflict",message:`Imported ${display(item.imported)}; inventory ${display(item.inventory)}`}))}/><KeyValues title="Fields that could enrich missing inventory values" values={Object.fromEntries(plan.fields_to_enrich.map(item=>[item.field,item.value]))}/><KeyValues title="Inventory fields preserved" values={Object.fromEntries(plan.fields_preserved.map(item=>[item.field,item.value]))}/><p>Audit required: {plan.audit_required?"Yes":"No"}. Destructive: {plan.destructive?"Yes":"No"}.</p></div> }

export function LocationStep({session,admin,onChanged}:{session:ImportSession;admin:boolean;onChanged:()=>Promise<void>}) {
  const locations=useRequest(()=>endpoints.importLocationSuggestions(session.id),[session.id]); const hierarchy=useRequest(endpoints.hierarchy,[]); const rows=useRequest(()=>endpoints.importRows(session.id,{page_size:100}),[session.id]); const [editing,setEditing]=useState<ImportLocationSuggestion|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  const rowMap=useMemo(()=>new Map((rows.data?.items??[]).map(row=>[row.id,row])),[rows.data]); const names=hierarchy.data?hierarchyNames(hierarchy.data):new Map<string,string>();
  const review=async(suggestion:ImportLocationSuggestion,action:"accept"|"reject"|"override",overrides:Partial<LocationReviewInput>={})=>{setBusy(true);setError("");try{await endpoints.reviewImportLocation(session.id,suggestion.imported_device_id,{action,...overrides});setEditing(null);await Promise.all([locations.reload(),onChanged()])}catch(error){setError(message(error))}finally{setBusy(false)}};
  return <section className="wizard-card"><div className="wizard-card-head"><span className="step-number">6</span><div><h2>Review location suggestions</h2><p>Every suggestion shows its source and confidence. Overrides use existing active hierarchy only.</p></div></div>{error&&<div className="inline-notice error">{error}</div>}
    {locations.loading||hierarchy.loading||rows.loading||locations.error||hierarchy.error||rows.error?<Feedback loading={locations.loading||hierarchy.loading||rows.loading} error={locations.error||hierarchy.error||rows.error} onRetry={()=>void Promise.all([locations.reload(),hierarchy.reload(),rows.reload()])}/>:!locations.data?.length?<Feedback emptyTitle="No location suggestions" empty="Matching did not produce hierarchy or network evidence for this session."/>:<div className="location-grid">{locations.data.map(item=>{const row=rowMap.get(item.imported_device_id);return <article key={item.id} className="location-card"><header><div><strong>{row?.hostname??row?.asset_tag??`Row ${row?.source_row_number??""}`}</strong><span>Imported: {row?.department_name??"No department"} · {row?.room_name??"No room"}</span></div><span className="confidence-pill">{item.confidence_score}%</span></header><dl><div><dt>Department</dt><dd>{item.department_id?names.get(item.department_id)??"Unavailable":"—"}</dd></div><div><dt>Building</dt><dd>{item.building_id?names.get(item.building_id)??"Unavailable":"—"}</dd></div><div><dt>Floor</dt><dd>{item.floor_id?names.get(item.floor_id)??"Unavailable":"—"}</dd></div><div><dt>Room</dt><dd>{item.room_id?names.get(item.room_id)??"Unavailable":"—"}</dd></div><div><dt>Network zone</dt><dd>{item.network_zone_id?names.get(item.network_zone_id)??"Unavailable":"—"}</dd></div></dl><ul className="evidence-list">{item.evidence.map((evidence,index)=><li key={index}><strong>{evidence.field.replaceAll("_"," ")}</strong><span>{(evidence.source??evidence.kind??"evidence").replaceAll("_"," ")}{evidence.rule?` · ${evidence.rule}`:""}</span></li>)}</ul>{item.conflicts.length>0&&<span className="text-danger">{item.conflicts.length} ambiguous or conflicting fields</span>}<footer><StatusBadge status={item.status}/>{admin&&item.status==="pending"&&<div><button disabled={busy} onClick={()=>void review(item,"accept")}>Accept</button><button disabled={busy} onClick={()=>void review(item,"reject")}>Reject</button><button disabled={busy} onClick={()=>setEditing(item)}>Override</button></div>}</footer></article>})}</div>}
    {editing&&hierarchy.data&&<LocationOverride suggestion={editing} catalog={hierarchy.data} busy={busy} onClose={()=>setEditing(null)} onSubmit={values=>void review(editing,"override",values)}/>}
  </section>;
}

function hierarchyNames(catalog:HierarchyCatalog) { return new Map(Object.values(catalog).flat().map(item=>[item.id,item.name])); }
function LocationOverride({suggestion,catalog,busy,onClose,onSubmit}:{suggestion:ImportLocationSuggestion;catalog:HierarchyCatalog;busy:boolean;onClose:()=>void;onSubmit:(value:Partial<LocationReviewInput>)=>void}) { const [value,setValue]=useState({department_id:suggestion.department_id??"",building_id:suggestion.building_id??"",floor_id:suggestion.floor_id??"",room_id:suggestion.room_id??"",network_zone_id:suggestion.network_zone_id??""}); const field=(label:string,key:keyof typeof value,items:HierarchyCatalog[keyof HierarchyCatalog])=><label>{label}<select value={value[key]} onChange={event=>setValue(current=>({...current,[key]:event.target.value}))}><option value="">No selection</option>{items.filter(item=>item.is_active).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>; return <Modal title="Override location suggestion" onClose={onClose}><div className="modal-body location-override"><p>Select existing hierarchy records. This does not create new locations.</p>{field("Department","department_id",catalog.departments)}{field("Building","building_id",catalog.buildings)}{field("Floor","floor_id",catalog.floors)}{field("Room","room_id",catalog.rooms)}{field("Network zone","network_zone_id",catalog.network_zones)}<footer className="wizard-actions"><button className="secondary-action" onClick={onClose}>Cancel</button><button className="primary-action" disabled={busy||!Object.values(value).some(Boolean)} onClick={()=>onSubmit(Object.fromEntries(Object.entries(value).map(([key,item])=>[key,item||null])))}>Save override</button></footer></div></Modal> }

export function SummaryStep({session}:{session:ImportSession}) { const summary=session.match_summary??{}; const unresolved=Math.max(0,(summary.total_valid_rows??0)-(summary.resolved??0)); const blockers=session.failed_rows+(summary.conflicts??0); return <section className="wizard-card"><div className="wizard-card-head"><span className="step-number">8</span><div><h2>Review import summary</h2><p>This summary prepares the session for Epic 2E; it does not execute inventory changes.</p></div></div><div className="summary-grid">{[["Total rows",session.total_rows],["Valid/warning",session.successful_rows],["Invalid",session.failed_rows],["Exact matches",summary.exact??0],["Strong matches",summary.strong??0],["Probable matches",summary.probable??0],["Weak matches",summary.weak??0],["Conflicts",summary.conflicts??0],["Resolved",summary.resolved??0],["Create-new",summary.suggested_new_devices??0],["Skipped",session.skipped_rows],["Suggested locations",summary.suggested_locations??0]].map(([label,value])=><div key={String(label)}><span>{label}</span><strong>{value}</strong></div>)}</div><section className={`readiness-card ${blockers||unresolved?"blocked":"ready"}`}><Icon name={blockers||unresolved?"warning":"check"} size={30}/><div><h3>{blockers||unresolved?"Review is not complete":"Ready for final-import preparation"}</h3><p>{blockers} blocking findings and {unresolved} unresolved valid rows remain. Epic 2E will own final transactional inventory changes.</p></div></section></section> }

export function ReadyStep({session}:{session:ImportSession}) { const summary=session.match_summary??{}; const unresolved=Math.max(0,(summary.total_valid_rows??0)-(summary.resolved??0)); const blocking=session.failed_rows+(summary.conflicts??0)+unresolved; return <section className="wizard-card"><div className="wizard-card-head"><span className="step-number">9</span><div><h2>Ready for Final Import</h2><p>Final inventory creation and merging are intentionally unavailable until Epic 2E.</p></div></div><div className={`final-checklist ${blocking?"blocked":"ready"}`}><h3>{blocking?`${blocking} blockers remain`:"Review checklist complete"}</h3><ul><li><Icon name={session.status==="completed"||session.status==="partial"?"check":"clock"}/>File parsed and staged</li><li><Icon name={session.matching_state==="completed"?"check":"clock"}/>Matching completed</li><li><Icon name={unresolved===0?"check":"warning"}/>All valid rows resolved or deferred</li><li><Icon name={(summary.conflicts??0)===0?"check":"warning"}/>No unresolved conflicts</li><li><Icon name="lock"/>No inventory mutation performed</li></ul><p>Prepared links: {session.matched_rows}. Suggested new devices: {summary.suggested_new_devices??0}. Excluded or invalid: {session.failed_rows+session.skipped_rows}.</p></div><div className="inline-notice warning">There is no final-import endpoint in Epic 2D. This screen cannot create, merge, or overwrite official inventory.</div></section> }

function Pagination({current,pages,onChange}:{current:number;pages:number;onChange:(page:number)=>void}) { return <nav className="pagination" aria-label="Import rows pages"><button disabled={current<=1} onClick={()=>onChange(current-1)}>Previous</button><span>Page {current} of {pages}</span><button disabled={current>=pages} onClick={()=>onChange(current+1)}>Next</button></nav> }
