"""create network scans table

Revision ID: 18a12dcf5369
Revises: b08524d4ba01
Create Date: 2026-07-10 20:28:25.432993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18a12dcf5369'
down_revision: Union[str, Sequence[str], None] = 'b08524d4ba01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_scans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('response_time', sa.Integer(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('network_scans')
    # ### end Alembic commands ###
