"""add configuration compliance foundation"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="a7b8c9d0e1f2"; down_revision="f6a7b8c9d0e1"; branch_labels=None; depends_on=None
def upgrade():
 u=postgresql.UUID(as_uuid=True)
 op.create_table("configuration_compliance_standards",sa.Column("id",u,primary_key=True),sa.Column("property_id",u,sa.ForeignKey("properties.id")),sa.Column("name",sa.String(120),nullable=False),sa.Column("code",sa.String(50),nullable=False),sa.Column("version",sa.String(30),nullable=False),sa.Column("standard_type",sa.String(30)),sa.Column("scope_type",sa.String(30)),sa.Column("enabled",sa.Boolean(),server_default=sa.text("false")),sa.Column("description",sa.Text()));op.create_index("uq_compliance_standard_code_version","configuration_compliance_standards",["code","version"],unique=True)
 op.create_table("configuration_compliance_policies",sa.Column("id",u,primary_key=True),sa.Column("standard_id",u,sa.ForeignKey("configuration_compliance_standards.id")),sa.Column("property_id",u,sa.ForeignKey("properties.id")),sa.Column("name",sa.String(120)),sa.Column("code",sa.String(50)),sa.Column("severity_default",sa.String(20)),sa.Column("evaluation_mode",sa.String(30)),sa.Column("enabled",sa.Boolean(),server_default=sa.text("false")));op.create_index("uq_compliance_policy_code","configuration_compliance_policies",["property_id","code"],unique=True)
 op.create_table("configuration_compliance_rules",sa.Column("id",u,primary_key=True),sa.Column("policy_id",u,sa.ForeignKey("configuration_compliance_policies.id",ondelete="CASCADE")),sa.Column("name",sa.String(120)),sa.Column("code",sa.String(50)),sa.Column("rule_type",sa.String(40)),sa.Column("target_path",sa.String(255)),sa.Column("operator",sa.String(40)),sa.Column("expected_value",sa.String(255)),sa.Column("severity",sa.String(20)),sa.Column("enabled",sa.Boolean(),server_default=sa.text("true")),sa.Column("priority",sa.Integer(),server_default="0"));op.create_index("uq_compliance_rule_policy_code","configuration_compliance_rules",["policy_id","code"],unique=True)
 for table,cols in [("configuration_compliance_runs",[("property_id",u),("run_type",sa.String(20)),("status",sa.String(20)),("trigger_type",sa.String(20)),("rules_evaluated",sa.Integer()),("rules_passed",sa.Integer()),("rules_failed",sa.Integer()),("error_summary",sa.Text())]),("configuration_compliance_results",[("property_id",u),("run_id",u),("device_id",u),("version_id",u),("policy_id",u),("status",sa.String(30)),("compliance_score",sa.Float()),("rules_total",sa.Integer()),("rules_passed",sa.Integer()),("rules_failed",sa.Integer()),("data_quality",sa.String(20))]),("configuration_compliance_violations",[("property_id",u),("device_id",u),("policy_id",u),("rule_id",u),("violation_key",sa.String(255)),("severity",sa.String(20)),("status",sa.String(20)),("title",sa.String(160)),("evidence",sa.Text()),("occurrence_count",sa.Integer())]),("configuration_compliance_exceptions",[("property_id",u),("policy_id",u),("rule_id",u),("reason",sa.Text()),("requested_by",sa.String()),("approved_by",sa.String()),("status",sa.String(20)),("expires_at",sa.DateTime(timezone=True))])]:
  op.create_table(table,sa.Column("id",u,primary_key=True),*[sa.Column(n,t) for n,t in cols],sa.Column("started_at" if "run" in table else "created_at",sa.DateTime(timezone=True),server_default=sa.func.now()))
def downgrade():
 for t in ["configuration_compliance_exceptions","configuration_compliance_violations","configuration_compliance_results","configuration_compliance_runs"]: op.drop_table(t)
 op.drop_index("uq_compliance_rule_policy_code",table_name="configuration_compliance_rules");op.drop_table("configuration_compliance_rules");op.drop_index("uq_compliance_policy_code",table_name="configuration_compliance_policies");op.drop_table("configuration_compliance_policies");op.drop_index("uq_compliance_standard_code_version",table_name="configuration_compliance_standards");op.drop_table("configuration_compliance_standards")
