"""add reviewed restore workflow foundation"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="b8c9d0e1f2a3"; down_revision="a7b8c9d0e1f2"; branch_labels=None; depends_on=None
def upgrade():
 u=postgresql.UUID(as_uuid=True)
 op.create_table("configuration_change_requests",sa.Column("id",u,primary_key=True),sa.Column("property_id",u,sa.ForeignKey("properties.id")),sa.Column("title",sa.String(160)),sa.Column("description",sa.Text()),sa.Column("change_type",sa.String(30)),sa.Column("status",sa.String(20)),sa.Column("risk_level",sa.String(20)),sa.Column("business_reason",sa.Text()),sa.Column("requested_by",sa.String()),sa.Column("approved_by",sa.String()),sa.Column("scheduled_start",sa.DateTime(timezone=True)),sa.Column("scheduled_end",sa.DateTime(timezone=True)),sa.Column("emergency_change",sa.Boolean(),server_default=sa.text("false")),sa.Column("rollback_required",sa.Boolean(),server_default=sa.text("true")),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now()))
 op.create_index("ix_change_request_status","configuration_change_requests",["status"])
 op.create_table("configuration_change_windows",sa.Column("id",u,primary_key=True),sa.Column("property_id",u,sa.ForeignKey("properties.id")),sa.Column("name",sa.String(120)),sa.Column("window_type",sa.String(20)),sa.Column("start_at",sa.DateTime(timezone=True)),sa.Column("end_at",sa.DateTime(timezone=True)),sa.Column("timezone",sa.String(64)),sa.Column("enabled",sa.Boolean(),server_default=sa.text("true")))
 op.create_table("configuration_restore_plans",sa.Column("id",u,primary_key=True),sa.Column("change_request_id",u,sa.ForeignKey("configuration_change_requests.id",ondelete="CASCADE")),sa.Column("source_version_id",u,sa.ForeignKey("device_configuration_versions.id")),sa.Column("status",sa.String(20)),sa.Column("pre_change_backup_required",sa.Boolean(),server_default=sa.text("true")),sa.Column("dry_run_required",sa.Boolean(),server_default=sa.text("true")),sa.Column("restore_method",sa.String(30)),sa.Column("risk_summary",sa.Text()),sa.Column("checksum",sa.String(64)),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now()))
 op.create_table("configuration_restore_dry_runs",sa.Column("id",u,primary_key=True),sa.Column("restore_plan_id",u,sa.ForeignKey("configuration_restore_plans.id",ondelete="CASCADE")),sa.Column("status",sa.String(20)),sa.Column("checks_total",sa.Integer(),server_default="1"),sa.Column("checks_passed",sa.Integer(),server_default="0"),sa.Column("checks_failed",sa.Integer(),server_default="1"),sa.Column("eligible_for_execution",sa.Boolean(),server_default=sa.text("false")),sa.Column("safe_results",sa.Text()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now()))
def downgrade():
 op.drop_table("configuration_restore_dry_runs");op.drop_table("configuration_restore_plans");op.drop_table("configuration_change_windows");op.drop_index("ix_change_request_status",table_name="configuration_change_requests");op.drop_table("configuration_change_requests")
