"""add hospitality asset classification and services"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="c3d4e5f6a7b8"; down_revision="b2c3d4e5f6a7"; branch_labels=None; depends_on=None
def upgrade():
    op.create_table("hospitality_asset_categories",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("name",sa.String(120),nullable=False),sa.Column("code",sa.String(40),unique=True,nullable=False),sa.Column("description",sa.String(255)),sa.Column("icon_key",sa.String(40)),sa.Column("color_token",sa.String(40)),sa.Column("criticality_default",sa.String(20),server_default="medium",nullable=False),sa.Column("enabled",sa.Boolean(),server_default=sa.text("true"),nullable=False),sa.Column("sort_order",sa.Integer(),server_default="0",nullable=False))
    op.create_table("hospitality_asset_types",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("category_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("hospitality_asset_categories.id"),nullable=False),sa.Column("name",sa.String(120),nullable=False),sa.Column("code",sa.String(50),unique=True,nullable=False),sa.Column("default_device_type",sa.String(60)),sa.Column("default_criticality",sa.String(20),server_default="medium",nullable=False),sa.Column("enabled",sa.Boolean(),server_default=sa.text("true"),nullable=False))
    op.create_table("hospitality_technology_services",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("property_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("properties.id",ondelete="CASCADE"),nullable=False),sa.Column("name",sa.String(160),nullable=False),sa.Column("code",sa.String(50),nullable=False),sa.Column("service_category",sa.String(60),nullable=False),sa.Column("criticality",sa.String(20),server_default="medium",nullable=False),sa.Column("status",sa.String(20),server_default="unknown",nullable=False),sa.Column("description",sa.String(255)))
    op.create_index("uq_hospitality_service_property_code","hospitality_technology_services",["property_id","code"],unique=True)
    op.create_table("device_technology_services",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("device_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("devices.id",ondelete="CASCADE"),nullable=False),sa.Column("technology_service_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("hospitality_technology_services.id",ondelete="CASCADE"),nullable=False),sa.Column("relationship_type",sa.String(30),server_default="supports",nullable=False),sa.Column("is_primary",sa.Boolean(),server_default=sa.text("false"),nullable=False),sa.Column("confidence_score",sa.Float()))
def downgrade():
    op.drop_table("device_technology_services");op.drop_index("uq_hospitality_service_property_code",table_name="hospitality_technology_services");op.drop_table("hospitality_technology_services");op.drop_table("hospitality_asset_types");op.drop_table("hospitality_asset_categories")
