"""add approval-safe automation foundation"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="c9d0e1f2a3b4"; down_revision="b8c9d0e1f2a3"; branch_labels=None; depends_on=None
def upgrade():
 u=postgresql.UUID(as_uuid=True)
 op.create_table("automation_workflows",sa.Column("id",u,primary_key=True),sa.Column("property_id",u,sa.ForeignKey("properties.id")),sa.Column("name",sa.String(160)),sa.Column("code",sa.String(60)),sa.Column("workflow_category",sa.String(40)),sa.Column("status",sa.String(20)),sa.Column("enabled",sa.Boolean(),server_default=sa.text("false")),sa.Column("requires_approval",sa.Boolean(),server_default=sa.text("true")),sa.Column("current_version_id",u),sa.Column("created_by",sa.String()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now()));op.create_index("uq_automation_workflow_scope_code","automation_workflows",["property_id","code"],unique=True)
 op.create_table("automation_workflow_versions",sa.Column("id",u,primary_key=True),sa.Column("workflow_id",u,sa.ForeignKey("automation_workflows.id",ondelete="CASCADE")),sa.Column("version_number",sa.Integer()),sa.Column("status",sa.String(20)),sa.Column("trigger_definition",sa.Text()),sa.Column("workflow_graph",sa.Text()),sa.Column("checksum",sa.String(64)),sa.Column("created_by",sa.String()),sa.Column("approved_by",sa.String()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now()));op.create_index("uq_workflow_version_number","automation_workflow_versions",["workflow_id","version_number"],unique=True)
 op.create_table("automation_actions",sa.Column("action_key",sa.String(80),primary_key=True),sa.Column("name",sa.String(120)),sa.Column("description",sa.Text()),sa.Column("risk_level",sa.String(20)),sa.Column("property_scoped",sa.Boolean(),server_default=sa.text("true")),sa.Column("enabled",sa.Boolean(),server_default=sa.text("true")),sa.Column("approval_required",sa.Boolean(),server_default=sa.text("false")))
 op.create_table("automation_dry_runs",sa.Column("id",u,primary_key=True),sa.Column("workflow_version_id",u,sa.ForeignKey("automation_workflow_versions.id")),sa.Column("property_id",u,sa.ForeignKey("properties.id")),sa.Column("status",sa.String(20)),sa.Column("eligible_for_execution",sa.Boolean(),server_default=sa.text("false")),sa.Column("warnings_count",sa.Integer(),server_default="1"),sa.Column("execution_path",sa.Text()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now()))
 op.create_table("automation_workflow_runs",sa.Column("id",u,primary_key=True),sa.Column("property_id",u,sa.ForeignKey("properties.id")),sa.Column("workflow_id",u,sa.ForeignKey("automation_workflows.id")),sa.Column("workflow_version_id",u,sa.ForeignKey("automation_workflow_versions.id")),sa.Column("status",sa.String(25)),sa.Column("trigger_type",sa.String(20)),sa.Column("triggered_by",sa.String()),sa.Column("idempotency_key",sa.String(120)),sa.Column("error_summary",sa.Text()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now()));op.create_index("ix_automation_run_status","automation_workflow_runs",["status"])
def downgrade():
 op.drop_index("ix_automation_run_status",table_name="automation_workflow_runs");op.drop_table("automation_workflow_runs");op.drop_table("automation_dry_runs");op.drop_table("automation_actions");op.drop_index("uq_workflow_version_number",table_name="automation_workflow_versions");op.drop_table("automation_workflow_versions");op.drop_index("uq_automation_workflow_scope_code",table_name="automation_workflows");op.drop_table("automation_workflows")
