"""add topology foundation

Revision ID: d0c2bcea6dda
Revises: f5e4d3c2b1a0
Create Date: 2026-07-26 01:36:40.455605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0c2bcea6dda'
down_revision: Union[str, Sequence[str], None] = 'f5e4d3c2b1a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topologies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('topology_type', sa.String(length=30), server_default='physical', nullable=False),
    sa.Column('scope_type', sa.String(length=30), server_default='global', nullable=False),
    sa.Column('building_id', sa.UUID(), nullable=True),
    sa.Column('floor_id', sa.UUID(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('network_zone_id', sa.UUID(), nullable=True),
    sa.Column('root_node_id', sa.UUID(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('layout_mode', sa.String(length=30), server_default='manual', nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['network_zone_id'], ['network_zones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'scope_type', name='uq_topology_name_scope')
    )
    op.create_table('network_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topology_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('cidr', sa.String(length=64), nullable=False),
    sa.Column('vlan_id', sa.Integer(), nullable=True),
    sa.Column('vlan_name', sa.String(length=120), nullable=True),
    sa.Column('segment_type', sa.String(length=30), server_default='unknown', nullable=False),
    sa.Column('network_zone_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('source_type', sa.String(length=30), server_default='manual', nullable=False),
    sa.Column('confidence_score', sa.Integer(), server_default='100', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['network_zone_id'], ['network_zones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topology_id'], ['topologies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topology_id', 'cidr', 'vlan_id', name='uq_topology_segment_cidr_vlan')
    )
    op.create_index(op.f('ix_network_segments_cidr'), 'network_segments', ['cidr'], unique=False)
    op.create_index(op.f('ix_network_segments_topology_id'), 'network_segments', ['topology_id'], unique=False)
    op.create_index(op.f('ix_network_segments_vlan_id'), 'network_segments', ['vlan_id'], unique=False)
    op.create_table('topology_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topology_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('group_type', sa.String(length=30), nullable=False),
    sa.Column('parent_group_id', sa.UUID(), nullable=True),
    sa.Column('collapsed_by_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_group_id'], ['topology_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topology_id'], ['topologies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topology_groups_topology_id'), 'topology_groups', ['topology_id'], unique=False)
    op.create_table('topology_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topology_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('snapshot_type', sa.String(length=30), server_default='manual', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('node_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('link_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('segment_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topology_id'], ['topologies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topology_snapshots_created_at'), 'topology_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_topology_snapshots_topology_id'), 'topology_snapshots', ['topology_id'], unique=False)
    op.create_table('topology_snapshot_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('source_topology_link_id', sa.UUID(), nullable=True),
    sa.Column('source_node_reference', sa.UUID(), nullable=False),
    sa.Column('target_node_reference', sa.UUID(), nullable=False),
    sa.Column('link_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('speed_bps', sa.BigInteger(), nullable=True),
    sa.Column('vlan_id', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['topology_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topology_snapshot_links_snapshot_id'), 'topology_snapshot_links', ['snapshot_id'], unique=False)
    op.create_table('topology_snapshot_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('source_topology_node_id', sa.UUID(), nullable=True),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('node_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('layer', sa.String(length=30), nullable=False),
    sa.Column('management_ip', sa.String(length=45), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['topology_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topology_snapshot_nodes_snapshot_id'), 'topology_snapshot_nodes', ['snapshot_id'], unique=False)
    op.create_table('topology_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topology_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('discovered_device_id', sa.UUID(), nullable=True),
    sa.Column('snmp_target_id', sa.UUID(), nullable=True),
    sa.Column('node_type', sa.String(length=40), server_default='unknown', nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='unknown', nullable=False),
    sa.Column('role', sa.String(length=30), server_default='unknown', nullable=False),
    sa.Column('layer', sa.String(length=30), server_default='unknown', nullable=False),
    sa.Column('parent_node_id', sa.UUID(), nullable=True),
    sa.Column('network_zone_id', sa.UUID(), nullable=True),
    sa.Column('building_id', sa.UUID(), nullable=True),
    sa.Column('floor_id', sa.UUID(), nullable=True),
    sa.Column('room_id', sa.UUID(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('management_ip', sa.String(length=45), nullable=True),
    sa.Column('vendor', sa.String(length=120), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('source_type', sa.String(length=30), server_default='manual', nullable=False),
    sa.Column('confidence_score', sa.Integer(), server_default='100', nullable=False),
    sa.Column('is_manual', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_hidden', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence_score BETWEEN 0 AND 100', name='ck_topology_node_confidence'),
    sa.CheckConstraint('parent_node_id IS NULL OR parent_node_id <> id', name='ck_topology_node_parent_self'),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['discovered_device_id'], ['discovered_devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['network_zone_id'], ['network_zones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_node_id'], ['topology_nodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['snmp_target_id'], ['snmp_targets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topology_id'], ['topologies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topology_id', 'device_id', name='uq_topology_node_device')
    )
    op.create_index('ix_topology_nodes_location', 'topology_nodes', ['building_id', 'floor_id', 'room_id'], unique=False)
    op.create_index('ix_topology_nodes_topology_type_status', 'topology_nodes', ['topology_id', 'node_type', 'status'], unique=False)
    op.create_table('topology_dependencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topology_id', sa.UUID(), nullable=False),
    sa.Column('upstream_node_id', sa.UUID(), nullable=False),
    sa.Column('downstream_node_id', sa.UUID(), nullable=False),
    sa.Column('dependency_type', sa.String(length=30), nullable=False),
    sa.Column('criticality', sa.String(length=20), server_default='medium', nullable=False),
    sa.Column('source_type', sa.String(length=30), server_default='manual', nullable=False),
    sa.Column('confidence_score', sa.Integer(), server_default='100', nullable=False),
    sa.Column('is_manual', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('upstream_node_id <> downstream_node_id', name='ck_topology_dependency_not_self'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['downstream_node_id'], ['topology_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topology_id'], ['topologies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['upstream_node_id'], ['topology_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topology_id', 'upstream_node_id', 'downstream_node_id', 'dependency_type', name='uq_topology_dependency')
    )
    op.create_index(op.f('ix_topology_dependencies_topology_id'), 'topology_dependencies', ['topology_id'], unique=False)
    op.create_index('ix_topology_dependency_nodes', 'topology_dependencies', ['upstream_node_id', 'downstream_node_id'], unique=False)
    op.create_table('topology_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topology_id', sa.UUID(), nullable=False),
    sa.Column('source_node_id', sa.UUID(), nullable=False),
    sa.Column('target_node_id', sa.UUID(), nullable=False),
    sa.Column('source_interface_id', sa.UUID(), nullable=True),
    sa.Column('target_interface_id', sa.UUID(), nullable=True),
    sa.Column('link_type', sa.String(length=30), server_default='physical', nullable=False),
    sa.Column('direction', sa.String(length=30), server_default='bidirectional', nullable=False),
    sa.Column('status', sa.String(length=30), server_default='active', nullable=False),
    sa.Column('speed_bps', sa.BigInteger(), nullable=True),
    sa.Column('duplex', sa.String(length=20), nullable=True),
    sa.Column('vlan_id', sa.Integer(), nullable=True),
    sa.Column('lag_identifier', sa.String(length=80), nullable=True),
    sa.Column('source_type', sa.String(length=30), server_default='manual', nullable=False),
    sa.Column('confidence_score', sa.Integer(), server_default='100', nullable=False),
    sa.Column('discovery_method', sa.String(length=30), server_default='manual', nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('missing_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_manual', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_suppressed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence_score BETWEEN 0 AND 100', name='ck_topology_link_confidence'),
    sa.CheckConstraint('source_node_id <> target_node_id', name='ck_topology_link_not_self'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_interface_id'], ['snmp_interfaces.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_node_id'], ['topology_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_interface_id'], ['snmp_interfaces.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_node_id'], ['topology_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topology_id'], ['topologies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_topology_links_endpoints', 'topology_links', ['source_node_id', 'target_node_id'], unique=False)
    op.create_index('ix_topology_links_interfaces', 'topology_links', ['source_interface_id', 'target_interface_id'], unique=False)
    op.create_index('ix_topology_links_topology_status', 'topology_links', ['topology_id', 'status'], unique=False)
    op.create_table('topology_node_positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topology_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('x_position', sa.Float(), nullable=False),
    sa.Column('y_position', sa.Float(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('locked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('layout_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['topology_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topology_id'], ['topologies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topology_id', 'node_id', name='uq_topology_node_position')
    )
    op.create_index(op.f('ix_topology_node_positions_node_id'), 'topology_node_positions', ['node_id'], unique=False)
    op.create_table('topology_node_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topology_node_id', sa.UUID(), nullable=False),
    sa.Column('network_segment_id', sa.UUID(), nullable=False),
    sa.Column('interface_id', sa.UUID(), nullable=True),
    sa.Column('membership_type', sa.String(length=30), nullable=False),
    sa.Column('source_type', sa.String(length=30), server_default='manual', nullable=False),
    sa.Column('confidence_score', sa.Integer(), server_default='100', nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interface_id'], ['snmp_interfaces.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['network_segment_id'], ['network_segments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topology_node_id'], ['topology_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topology_node_id', 'network_segment_id', 'interface_id', name='uq_topology_node_segment')
    )
    op.create_index(op.f('ix_topology_node_segments_network_segment_id'), 'topology_node_segments', ['network_segment_id'], unique=False)
    op.create_index(op.f('ix_topology_node_segments_topology_node_id'), 'topology_node_segments', ['topology_node_id'], unique=False)
    op.create_table('topology_changes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topology_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=True),
    sa.Column('change_type', sa.String(length=40), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=True),
    sa.Column('link_id', sa.UUID(), nullable=True),
    sa.Column('segment_id', sa.UUID(), nullable=True),
    sa.Column('previous_values', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('current_values', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('source_type', sa.String(length=30), server_default='manual', nullable=False),
    sa.Column('confidence_score', sa.Integer(), server_default='100', nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_status', sa.String(length=20), server_default='pending', nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['topology_links.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['node_id'], ['topology_nodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['segment_id'], ['network_segments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['topology_snapshots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topology_id'], ['topologies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_topology_changes_topology_type_time', 'topology_changes', ['topology_id', 'change_type', 'detected_at'], unique=False)
    op.create_table('topology_link_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topology_link_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('evidence_type', sa.String(length=40), nullable=False),
    sa.Column('evidence_value', sa.String(length=500), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topology_link_id'], ['topology_links.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topology_link_evidence_topology_link_id'), 'topology_link_evidence', ['topology_link_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topology_link_evidence_topology_link_id'), table_name='topology_link_evidence')
    op.drop_table('topology_link_evidence')
    op.drop_index('ix_topology_changes_topology_type_time', table_name='topology_changes')
    op.drop_table('topology_changes')
    op.drop_index(op.f('ix_topology_node_segments_topology_node_id'), table_name='topology_node_segments')
    op.drop_index(op.f('ix_topology_node_segments_network_segment_id'), table_name='topology_node_segments')
    op.drop_table('topology_node_segments')
    op.drop_index(op.f('ix_topology_node_positions_node_id'), table_name='topology_node_positions')
    op.drop_table('topology_node_positions')
    op.drop_index('ix_topology_links_topology_status', table_name='topology_links')
    op.drop_index('ix_topology_links_interfaces', table_name='topology_links')
    op.drop_index('ix_topology_links_endpoints', table_name='topology_links')
    op.drop_table('topology_links')
    op.drop_index('ix_topology_dependency_nodes', table_name='topology_dependencies')
    op.drop_index(op.f('ix_topology_dependencies_topology_id'), table_name='topology_dependencies')
    op.drop_table('topology_dependencies')
    op.drop_index('ix_topology_nodes_topology_type_status', table_name='topology_nodes')
    op.drop_index('ix_topology_nodes_location', table_name='topology_nodes')
    op.drop_table('topology_nodes')
    op.drop_index(op.f('ix_topology_snapshot_nodes_snapshot_id'), table_name='topology_snapshot_nodes')
    op.drop_table('topology_snapshot_nodes')
    op.drop_index(op.f('ix_topology_snapshot_links_snapshot_id'), table_name='topology_snapshot_links')
    op.drop_table('topology_snapshot_links')
    op.drop_index(op.f('ix_topology_snapshots_topology_id'), table_name='topology_snapshots')
    op.drop_index(op.f('ix_topology_snapshots_created_at'), table_name='topology_snapshots')
    op.drop_table('topology_snapshots')
    op.drop_index(op.f('ix_topology_groups_topology_id'), table_name='topology_groups')
    op.drop_table('topology_groups')
    op.drop_index(op.f('ix_network_segments_vlan_id'), table_name='network_segments')
    op.drop_index(op.f('ix_network_segments_topology_id'), table_name='network_segments')
    op.drop_index(op.f('ix_network_segments_cidr'), table_name='network_segments')
    op.drop_table('network_segments')
    op.drop_table('topologies')
    # ### end Alembic commands ###
