"""add internal automation triggers and schedules"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="d0e1f2a3b4c5"; down_revision="c9d0e1f2a3b4"; branch_labels=None; depends_on=None
def upgrade():
 u=postgresql.UUID(as_uuid=True)
 op.create_table("automation_event_records",sa.Column("id",u,primary_key=True),sa.Column("event_id",u,unique=True),sa.Column("event_type",sa.String(80)),sa.Column("property_id",u,sa.ForeignKey("properties.id")),sa.Column("source_entity_type",sa.String(50)),sa.Column("source_entity_id",u),sa.Column("safe_payload",sa.Text()),sa.Column("processing_status",sa.String(20),server_default="received"),sa.Column("occurred_at",sa.DateTime(timezone=True)),sa.Column("received_at",sa.DateTime(timezone=True),server_default=sa.func.now()))
 op.create_table("automation_trigger_subscriptions",sa.Column("id",u,primary_key=True),sa.Column("workflow_id",u,sa.ForeignKey("automation_workflows.id",ondelete="CASCADE")),sa.Column("workflow_version_id",u,sa.ForeignKey("automation_workflow_versions.id")),sa.Column("property_id",u,sa.ForeignKey("properties.id")),sa.Column("event_type",sa.String(80)),sa.Column("enabled",sa.Boolean(),server_default=sa.text("false")),sa.Column("trigger_mode",sa.String(20),server_default="notify_only"),sa.Column("cooldown_seconds",sa.Integer(),server_default="300"),sa.Column("deduplication_window_seconds",sa.Integer(),server_default="300"))
 op.create_table("automation_workflow_schedules",sa.Column("id",u,primary_key=True),sa.Column("workflow_id",u,sa.ForeignKey("automation_workflows.id",ondelete="CASCADE")),sa.Column("workflow_version_id",u,sa.ForeignKey("automation_workflow_versions.id")),sa.Column("property_id",u,sa.ForeignKey("properties.id")),sa.Column("name",sa.String(120)),sa.Column("schedule_type",sa.String(20),server_default="one_time"),sa.Column("timezone",sa.String(64),server_default="UTC"),sa.Column("interval_minutes",sa.Integer()),sa.Column("enabled",sa.Boolean(),server_default=sa.text("false")),sa.Column("next_run_at",sa.DateTime(timezone=True)),sa.Column("maximum_runs",sa.Integer()),sa.Column("runs_completed",sa.Integer(),server_default="0"));op.create_index("ix_automation_schedule_enabled","automation_workflow_schedules",["enabled"])
 op.create_table("automation_trigger_executions",sa.Column("id",u,primary_key=True),sa.Column("subscription_id",u,sa.ForeignKey("automation_trigger_subscriptions.id",ondelete="CASCADE")),sa.Column("event_id",u,sa.ForeignKey("automation_event_records.id")),sa.Column("property_id",u,sa.ForeignKey("properties.id")),sa.Column("deduplication_key",sa.String(255)),sa.Column("status",sa.String(20)),sa.Column("suppression_reason",sa.String(255)),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now()))
def downgrade():
 op.drop_table("automation_trigger_executions");op.drop_index("ix_automation_schedule_enabled",table_name="automation_workflow_schedules");op.drop_table("automation_workflow_schedules");op.drop_table("automation_trigger_subscriptions");op.drop_table("automation_event_records")
