"""add secure configuration management foundation"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="d4e5f6a7b8c9"; down_revision="c3d4e5f6a7b8"; branch_labels=None; depends_on=None
def upgrade():
    u=postgresql.UUID(as_uuid=True)
    op.create_table("configuration_device_profiles",sa.Column("id",u,primary_key=True),sa.Column("property_id",u,sa.ForeignKey("properties.id",ondelete="CASCADE")),sa.Column("name",sa.String(120),nullable=False),sa.Column("code",sa.String(50),unique=True,nullable=False),sa.Column("vendor",sa.String(80)),sa.Column("platform",sa.String(80)),sa.Column("connection_method",sa.String(30),server_default="manual",nullable=False),sa.Column("backup_strategy",sa.String(30),server_default="manual_upload",nullable=False),sa.Column("export_format",sa.String(20)),sa.Column("supports_restore",sa.Boolean(),server_default=sa.text("false"),nullable=False),sa.Column("enabled",sa.Boolean(),server_default=sa.text("true"),nullable=False),sa.Column("description",sa.String(255)))
    op.create_table("configuration_backup_policies",sa.Column("id",u,primary_key=True),sa.Column("property_id",u,sa.ForeignKey("properties.id",ondelete="CASCADE")),sa.Column("name",sa.String(120),nullable=False),sa.Column("enabled",sa.Boolean(),server_default=sa.text("true"),nullable=False),sa.Column("backup_frequency",sa.String(20),server_default="manual",nullable=False),sa.Column("retention_count",sa.Integer(),server_default="10",nullable=False),sa.Column("retention_days",sa.Integer(),server_default="365",nullable=False),sa.Column("encrypt_content",sa.Boolean(),server_default=sa.text("true"),nullable=False),sa.Column("maximum_backup_size_bytes",sa.Integer(),server_default="10485760",nullable=False))
    op.create_table("configuration_backup_runs",sa.Column("id",u,primary_key=True),sa.Column("property_id",u,sa.ForeignKey("properties.id")),sa.Column("device_id",u,sa.ForeignKey("devices.id")),sa.Column("status",sa.String(20),nullable=False),sa.Column("trigger_type",sa.String(30),server_default="manual_upload"),sa.Column("configuration_scope",sa.String(30),server_default="full"),sa.Column("bytes_received",sa.Integer()),sa.Column("checksum",sa.String(128)),sa.Column("error_summary",sa.String(255)),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
    op.create_table("device_configuration_versions",sa.Column("id",u,primary_key=True),sa.Column("property_id",u,sa.ForeignKey("properties.id")),sa.Column("device_id",u,sa.ForeignKey("devices.id")),sa.Column("backup_run_id",u,sa.ForeignKey("configuration_backup_runs.id"),nullable=False),sa.Column("version_number",sa.Integer(),nullable=False),sa.Column("configuration_scope",sa.String(30),server_default="full"),sa.Column("format",sa.String(20),server_default="txt"),sa.Column("encrypted_content",sa.LargeBinary(),nullable=False),sa.Column("original_filename",sa.String(255)),sa.Column("content_size_bytes",sa.Integer(),nullable=False),sa.Column("checksum",sa.String(64),nullable=False),sa.Column("checksum_algorithm",sa.String(20),server_default="sha256"),sa.Column("is_baseline",sa.Boolean(),server_default=sa.text("false")),sa.Column("is_protected",sa.Boolean(),server_default=sa.text("false")),sa.Column("source_type",sa.String(30),server_default="manual_upload"),sa.Column("captured_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False));op.create_index("uq_config_version_scope","device_configuration_versions",["device_id","configuration_scope","version_number"],unique=True);op.create_index("ix_config_version_checksum","device_configuration_versions",["checksum"])
def downgrade():
    op.drop_index("ix_config_version_checksum",table_name="device_configuration_versions");op.drop_index("uq_config_version_scope",table_name="device_configuration_versions");op.drop_table("device_configuration_versions");op.drop_table("configuration_backup_runs");op.drop_table("configuration_backup_policies");op.drop_table("configuration_device_profiles")
