"""add explainable analytics baselines anomalies and correlations

Revision ID: e7f8a9b0c1d2
Revises: d9f7c5e3b812
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "e7f8a9b0c1d2"
down_revision = "d9f7c5e3b812"
branch_labels = None
depends_on = None


def _json(name):
    return sa.Column(name, postgresql.JSONB(), server_default=sa.text("'{}'::jsonb"), nullable=False)


def upgrade():
    for name, default in {
        "baseline_enabled": "false", "anomaly_detection_enabled": "false", "correlation_enabled": "false",
        "insight_refresh_enabled": "false", "anomaly_recovery_interval_minutes": "15", "correlation_window_minutes": "15",
        "maximum_events_per_run": "1000", "maximum_groups_per_run": "100", "anomaly_retention_days": "180",
        "correlation_retention_days": "365", "insight_retention_days": "180",
    }.items():
        typ = sa.Boolean() if name.endswith("enabled") else sa.Integer()
        op.add_column("analytics_schedule_configurations", sa.Column(name, typ, server_default=default, nullable=False))
    op.add_column("analytics_schedule_configurations", sa.Column("baseline_interval_hours", sa.Integer(), server_default="24", nullable=False))
    op.add_column("analytics_schedule_configurations", sa.Column("anomaly_interval_minutes", sa.Integer(), server_default="15", nullable=False))
    op.add_column("analytics_schedule_configurations", sa.Column("correlation_interval_minutes", sa.Integer(), server_default="15", nullable=False))
    op.add_column("analytics_schedule_configurations", sa.Column("insight_interval_minutes", sa.Integer(), server_default="30", nullable=False))

    op.create_table("analytics_baselines",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("entity_type", sa.String(30), nullable=False),
        sa.Column("entity_id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("metric_key", sa.String(120), nullable=False),
        sa.Column("baseline_type", sa.String(30), nullable=False), sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False), sa.Column("bucket_size", sa.String(20), nullable=False),
        *[sa.Column(n, sa.Integer(), nullable=False) for n in ["sample_count"]],
        *[sa.Column(n, sa.Float(), nullable=False) for n in ["mean_value", "median_value", "minimum_value", "maximum_value", "standard_deviation", "median_absolute_deviation", "percentile_05", "percentile_25", "percentile_75", "percentile_95", "expected_lower_bound", "expected_upper_bound", "confidence_score"]],
        sa.Column("seasonality_key", sa.String(40), server_default="", nullable=False), sa.Column("data_quality", sa.String(20), nullable=False),
        sa.Column("calculation_version", sa.String(20), server_default="1.0", nullable=False), sa.Column("calculated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.UniqueConstraint("entity_type", "entity_id", "metric_key", "baseline_type", "bucket_size", "seasonality_key", name="uq_analytics_baseline_scope"))
    op.create_index("ix_analytics_baseline_entity_metric", "analytics_baselines", ["entity_type", "entity_id", "metric_key"])
    op.create_index("ix_analytics_baseline_validity", "analytics_baselines", ["valid_until", "data_quality"])

    op.create_table("analytics_anomaly_rules",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("name", sa.String(120), nullable=False), sa.Column("entity_type", sa.String(30), nullable=False), sa.Column("metric_key", sa.String(120), nullable=False), sa.Column("scope_type", sa.String(30), server_default="global", nullable=False), sa.Column("scope_id", postgresql.UUID(as_uuid=True)), sa.Column("detection_method", sa.String(30), nullable=False), sa.Column("sensitivity", sa.Float(), server_default="3", nullable=False), sa.Column("minimum_samples", sa.Integer(), server_default="12", nullable=False), sa.Column("baseline_window", sa.Integer(), server_default="168", nullable=False), sa.Column("evaluation_window", sa.Integer(), server_default="3", nullable=False), sa.Column("consecutive_occurrences", sa.Integer(), server_default="2", nullable=False), sa.Column("recovery_occurrences", sa.Integer(), server_default="2", nullable=False), sa.Column("minimum_confidence", sa.Float(), server_default="60", nullable=False), sa.Column("warning_score", sa.Float(), server_default="60", nullable=False), sa.Column("critical_score", sa.Float(), server_default="85", nullable=False), sa.Column("alert_creation_enabled", sa.Boolean(), server_default="false", nullable=False), sa.Column("notification_enabled", sa.Boolean(), server_default="false", nullable=False), sa.Column("suppress_during_maintenance", sa.Boolean(), server_default="true", nullable=False), sa.Column("enabled", sa.Boolean(), server_default="false", nullable=False), sa.Column("created_by", sa.String(), sa.ForeignKey("users.id", ondelete="SET NULL")), sa.Column("updated_by", sa.String(), sa.ForeignKey("users.id", ondelete="SET NULL")), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_index("ix_analytics_anomaly_rule_metric_enabled", "analytics_anomaly_rules", ["metric_key", "enabled"])

    op.create_table("analytics_anomalies",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("entity_type", sa.String(30), nullable=False), sa.Column("entity_id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("metric_key", sa.String(120), nullable=False), sa.Column("baseline_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("analytics_baselines.id", ondelete="SET NULL")), sa.Column("rule_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("analytics_anomaly_rules.id", ondelete="SET NULL")), sa.Column("anomaly_type", sa.String(30), nullable=False), sa.Column("severity", sa.String(20), nullable=False), sa.Column("status", sa.String(20), server_default="open", nullable=False), *[sa.Column(n, sa.Float()) for n in ["observed_value", "expected_value", "expected_lower_bound", "expected_upper_bound", "deviation_value", "deviation_percent"]], sa.Column("anomaly_score", sa.Float(), nullable=False), sa.Column("confidence_score", sa.Float(), nullable=False), sa.Column("detection_method", sa.String(30), nullable=False), _json("evidence"), sa.Column("first_detected_at", sa.DateTime(timezone=True), nullable=False), sa.Column("last_detected_at", sa.DateTime(timezone=True), nullable=False), sa.Column("occurrence_count", sa.Integer(), server_default="1", nullable=False), sa.Column("recovery_count", sa.Integer(), server_default="0", nullable=False), sa.Column("flap_count", sa.Integer(), server_default="0", nullable=False), sa.Column("source_aggregate_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("analytics_aggregates.id", ondelete="SET NULL")), sa.Column("source_alert_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("alerts.id", ondelete="SET NULL")), sa.Column("acknowledged_by", sa.String(), sa.ForeignKey("users.id", ondelete="SET NULL")), sa.Column("acknowledged_at", sa.DateTime(timezone=True)), sa.Column("resolved_at", sa.DateTime(timezone=True)), sa.Column("resolution_reason", sa.String(500)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_index("ix_analytics_anomaly_status_time", "analytics_anomalies", ["status", "last_detected_at"])
    op.create_index("ix_analytics_anomaly_entity_metric", "analytics_anomalies", ["entity_type", "entity_id", "metric_key"])

    op.create_table("analytics_correlation_groups", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("title", sa.String(200), nullable=False), sa.Column("description", sa.String(1000), nullable=False), sa.Column("status", sa.String(20), server_default="open", nullable=False), sa.Column("severity", sa.String(20), nullable=False), sa.Column("correlation_type", sa.String(40), nullable=False), sa.Column("confidence_score", sa.Float(), nullable=False), sa.Column("probable_common_entity_type", sa.String(30)), sa.Column("probable_common_entity_id", postgresql.UUID(as_uuid=True)), sa.Column("topology_node_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("topology_nodes.id", ondelete="SET NULL")), sa.Column("device_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("devices.id", ondelete="SET NULL")), sa.Column("first_event_at", sa.DateTime(timezone=True), nullable=False), sa.Column("last_event_at", sa.DateTime(timezone=True), nullable=False), *[sa.Column(n, sa.Integer(), server_default="0", nullable=False) for n in ["event_count", "alert_count", "anomaly_count", "affected_device_count", "affected_location_count"]], _json("evidence"), sa.Column("reviewed_by", sa.String(), sa.ForeignKey("users.id", ondelete="SET NULL")), sa.Column("reviewed_at", sa.DateTime(timezone=True)), sa.Column("ticket_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("tickets.id", ondelete="SET NULL")), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_index("ix_analytics_correlation_status_time", "analytics_correlation_groups", ["status", "last_event_at"])
    op.create_index("ix_analytics_correlation_common_entity", "analytics_correlation_groups", ["probable_common_entity_type", "probable_common_entity_id"])
    op.create_table("analytics_correlation_members", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("correlation_group_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("analytics_correlation_groups.id", ondelete="CASCADE"), nullable=False), sa.Column("member_type", sa.String(30), nullable=False), sa.Column("alert_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("alerts.id", ondelete="SET NULL")), sa.Column("anomaly_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("analytics_anomalies.id", ondelete="SET NULL")), sa.Column("ticket_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("tickets.id", ondelete="SET NULL")), sa.Column("device_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("devices.id", ondelete="SET NULL")), sa.Column("entity_type", sa.String(30), nullable=False), sa.Column("entity_id", postgresql.UUID(as_uuid=True)), sa.Column("relationship_type", sa.String(40), nullable=False), sa.Column("confidence_contribution", sa.Float(), nullable=False), _json("evidence"), sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.UniqueConstraint("correlation_group_id", "member_type", "entity_type", "entity_id", "occurred_at", name="uq_analytics_correlation_member"))
    op.create_index("ix_analytics_correlation_member_group_time", "analytics_correlation_members", ["correlation_group_id", "occurred_at"])
    op.create_table("analytics_insights", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("insight_type", sa.String(40), nullable=False), sa.Column("entity_type", sa.String(30), nullable=False), sa.Column("entity_id", postgresql.UUID(as_uuid=True)), sa.Column("correlation_group_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("analytics_correlation_groups.id", ondelete="SET NULL")), sa.Column("title", sa.String(200), nullable=False), sa.Column("summary", sa.String(1000), nullable=False), sa.Column("severity", sa.String(20), nullable=False), sa.Column("confidence_score", sa.Float(), nullable=False), _json("evidence"), sa.Column("recommended_review_steps", postgresql.JSONB(), server_default=sa.text("'[]'::jsonb"), nullable=False), sa.Column("status", sa.String(20), server_default="open", nullable=False), sa.Column("generated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("reviewed_by", sa.String(), sa.ForeignKey("users.id", ondelete="SET NULL")), sa.Column("reviewed_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_index("ix_analytics_insight_status_time", "analytics_insights", ["status", "generated_at"])
    op.create_index("ix_analytics_insight_entity", "analytics_insights", ["entity_type", "entity_id"])


def downgrade():
    for index, table in [("ix_analytics_insight_entity", "analytics_insights"), ("ix_analytics_insight_status_time", "analytics_insights"), ("ix_analytics_correlation_member_group_time", "analytics_correlation_members"), ("ix_analytics_correlation_common_entity", "analytics_correlation_groups"), ("ix_analytics_correlation_status_time", "analytics_correlation_groups"), ("ix_analytics_anomaly_entity_metric", "analytics_anomalies"), ("ix_analytics_anomaly_status_time", "analytics_anomalies"), ("ix_analytics_anomaly_rule_metric_enabled", "analytics_anomaly_rules"), ("ix_analytics_baseline_validity", "analytics_baselines"), ("ix_analytics_baseline_entity_metric", "analytics_baselines")]: op.drop_index(index, table_name=table)
    for table in ["analytics_insights", "analytics_correlation_members", "analytics_correlation_groups", "analytics_anomalies", "analytics_anomaly_rules", "analytics_baselines"]: op.drop_table(table)
    for name in ["baseline_enabled", "baseline_interval_hours", "anomaly_detection_enabled", "anomaly_interval_minutes", "correlation_enabled", "correlation_interval_minutes", "insight_refresh_enabled", "insight_interval_minutes", "anomaly_recovery_interval_minutes", "correlation_window_minutes", "maximum_events_per_run", "maximum_groups_per_run", "anomaly_retention_days", "correlation_retention_days", "insight_retention_days"]: op.drop_column("analytics_schedule_configurations", name)
