"""add automation execution tables

Revision ID: f2a3b4c5d6e7
Revises: e1f2a3b4c5d6
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision="f2a3b4c5d6e7"; down_revision="e1f2a3b4c5d6"; branch_labels=None; depends_on=None

def upgrade():
    op.create_table("automation_workflow_steps",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("workflow_version_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("automation_workflow_versions.id",ondelete="CASCADE"),nullable=False),sa.Column("step_key",sa.String(80),nullable=False),sa.Column("name",sa.String(160),nullable=False),sa.Column("step_type",sa.String(30),nullable=False),sa.Column("action_key",sa.String(80),sa.ForeignKey("automation_actions.action_key")),sa.Column("sequence_order",sa.Integer(),server_default="0"),sa.Column("timeout_seconds",sa.Integer(),server_default="60"),sa.Column("retry_policy",sa.Text()),sa.Column("condition_definition",sa.Text()),sa.Column("approval_required",sa.Boolean(),server_default=sa.text("false")),sa.Column("compensation_action_key",sa.String(80)),sa.Column("continue_on_failure",sa.Boolean(),server_default=sa.text("false")),sa.Column("enabled",sa.Boolean(),server_default=sa.text("true")))
    op.create_index("ix_automation_steps_version","automation_workflow_steps",["workflow_version_id"]);op.create_index("uq_automation_step_key","automation_workflow_steps",["workflow_version_id","step_key"],unique=True)
    op.create_table("automation_step_dependencies",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("workflow_version_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("automation_workflow_versions.id",ondelete="CASCADE"),nullable=False),sa.Column("upstream_step_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("automation_workflow_steps.id",ondelete="CASCADE"),nullable=False),sa.Column("downstream_step_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("automation_workflow_steps.id",ondelete="CASCADE"),nullable=False),sa.Column("dependency_type",sa.String(30),server_default="success"),sa.CheckConstraint("upstream_step_id <> downstream_step_id",name="ck_automation_dependency_not_self"));op.create_index("ix_automation_dependencies_version","automation_step_dependencies",["workflow_version_id"])
    op.create_table("automation_step_runs",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("workflow_run_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("automation_workflow_runs.id",ondelete="CASCADE"),nullable=False),sa.Column("step_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("automation_workflow_steps.id"),nullable=False),sa.Column("status",sa.String(25),server_default="pending"),sa.Column("attempt_count",sa.Integer(),server_default="0"),sa.Column("output_summary",sa.Text()),sa.Column("error_category",sa.String(40)),sa.Column("started_at",sa.DateTime(timezone=True)),sa.Column("completed_at",sa.DateTime(timezone=True)));op.create_index("ix_automation_step_runs_workflow","automation_step_runs",["workflow_run_id"]);op.create_index("ix_automation_step_runs_status","automation_step_runs",["status"])
    op.create_table("automation_approval_requests",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("workflow_run_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("automation_workflow_runs.id",ondelete="CASCADE"),nullable=False),sa.Column("step_run_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("automation_step_runs.id",ondelete="CASCADE")),sa.Column("status",sa.String(20),server_default="pending"),sa.Column("requested_by",sa.String(),nullable=False),sa.Column("reviewed_by",sa.String()),sa.Column("decision_reason",sa.Text()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False));op.create_index("ix_automation_approval_run","automation_approval_requests",["workflow_run_id"]);op.create_index("ix_automation_approval_status","automation_approval_requests",["status"])

def downgrade():
    op.drop_table("automation_approval_requests");op.drop_table("automation_step_runs");op.drop_table("automation_step_dependencies");op.drop_table("automation_workflow_steps")
