"""add comparison and drift foundation"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="f6a7b8c9d0e1"; down_revision="e5f6a7b8c9d0"; branch_labels=None; depends_on=None
def upgrade():
 u=postgresql.UUID(as_uuid=True)
 op.create_table("configuration_comparisons",sa.Column("id",u,primary_key=True),sa.Column("property_id",u,sa.ForeignKey("properties.id")),sa.Column("device_id",u,sa.ForeignKey("devices.id")),sa.Column("source_version_id",u,sa.ForeignKey("device_configuration_versions.id")),sa.Column("target_version_id",u,sa.ForeignKey("device_configuration_versions.id")),sa.Column("comparison_type",sa.String(30)),sa.Column("status",sa.String(20)),sa.Column("added_lines",sa.Integer(),server_default="0"),sa.Column("removed_lines",sa.Integer(),server_default="0"),sa.Column("change_count",sa.Integer(),server_default="0"),sa.Column("sensitive_changes_count",sa.Integer(),server_default="0"),sa.Column("risk_level",sa.String(20)),sa.Column("summary",sa.Text()),sa.Column("generated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
 op.create_index("ix_comparison_property","configuration_comparisons",["property_id"]);op.create_index("ix_comparison_device","configuration_comparisons",["device_id"])
 op.create_table("configuration_comparison_changes",sa.Column("id",u,primary_key=True),sa.Column("comparison_id",u,sa.ForeignKey("configuration_comparisons.id",ondelete="CASCADE")),sa.Column("change_type",sa.String(20)),sa.Column("classification",sa.String(30)),sa.Column("risk_level",sa.String(20)),sa.Column("section",sa.String(120)),sa.Column("before_value_redacted",sa.Text()),sa.Column("after_value_redacted",sa.Text()))
 op.create_table("configuration_drift_records",sa.Column("id",u,primary_key=True),sa.Column("property_id",u,sa.ForeignKey("properties.id")),sa.Column("device_id",u,sa.ForeignKey("devices.id")),sa.Column("baseline_version_id",u,sa.ForeignKey("device_configuration_versions.id")),sa.Column("current_version_id",u,sa.ForeignKey("device_configuration_versions.id")),sa.Column("comparison_id",u,sa.ForeignKey("configuration_comparisons.id")),sa.Column("drift_status",sa.String(20),server_default="new"),sa.Column("severity",sa.String(20),server_default="unknown"),sa.Column("occurrence_count",sa.Integer(),server_default="1"),sa.Column("first_detected_at",sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column("last_detected_at",sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column("resolution_reason",sa.Text()))
 op.create_index("ix_drift_status_severity","configuration_drift_records",["drift_status","severity"])
def downgrade():
 op.drop_index("ix_drift_status_severity",table_name="configuration_drift_records");op.drop_table("configuration_drift_records");op.drop_table("configuration_comparison_changes");op.drop_index("ix_comparison_device",table_name="configuration_comparisons");op.drop_index("ix_comparison_property",table_name="configuration_comparisons");op.drop_table("configuration_comparisons")
