"""add V3E alerts and events

Revision ID: v3e9f1a3c5b7
Revises: v3c8d0e2f4a6
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="v3e9f1a3c5b7";down_revision="v3c8d0e2f4a6";branch_labels=None;depends_on=None
def upgrade():
    op.create_table("alert_rules",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("rule_type",sa.String(40),unique=True,nullable=False),sa.Column("name",sa.String(120),nullable=False),sa.Column("description",sa.String(500),nullable=False),sa.Column("enabled",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("severity",sa.String(10),nullable=False),sa.Column("threshold_value",sa.Float()),sa.Column("duration_minutes",sa.Integer(),nullable=False,server_default="5"),sa.Column("consecutive_observations",sa.Integer(),nullable=False,server_default="3"),sa.Column("notify_in_app",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("notify_email",sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column("updated_by",sa.String(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()))
    for name,kind,severity,threshold,count,description in [("Device Offline","device_offline","critical",None,3,"Consecutive failed ICMP checks"),("High Latency","high_latency","warning",100,3,"Sustained response time above threshold"),("Packet Loss","packet_loss","warning",10,5,"Failed-check percentage above threshold"),("Health Degradation","health_degradation","warning",None,2,"Device health degraded"),("Interface Down","interface_down","critical",None,2,"Monitored interface is down"),("SNMP Unavailable","snmp_unavailable","warning",None,3,"SNMP source unavailable while reachability remains known")]:op.execute(sa.text("INSERT INTO alert_rules (id,rule_type,name,description,severity,threshold_value,consecutive_observations) VALUES (gen_random_uuid(),:k,:n,:d,:s,:t,:c)").bindparams(k=kind,n=name,d=description,s=severity,t=threshold,c=count))
    for name,column in [("rule_id",sa.Column("rule_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("alert_rules.id",ondelete="SET NULL"))),("alert_type",sa.Column("alert_type",sa.String(40),nullable=False,server_default="device_status")),("title",sa.Column("title",sa.String(255),nullable=False,server_default="Device status changed")),("severity",sa.Column("severity",sa.String(10),nullable=False,server_default="warning")),("lifecycle_status",sa.Column("lifecycle_status",sa.String(20),nullable=False,server_default="open")),("source",sa.Column("source",sa.String(40),nullable=False,server_default="monitoring")),("reason",sa.Column("reason",sa.Text(),nullable=False,server_default="Monitoring condition crossed a threshold")),("evidence",sa.Column("evidence",postgresql.JSONB(),nullable=False,server_default=sa.text("'{}'::jsonb"))),("current_value",sa.Column("current_value",sa.Float())),("threshold_value",sa.Column("threshold_value",sa.Float())),("deduplication_key",sa.Column("deduplication_key",sa.String(255))),("last_updated_at",sa.Column("last_updated_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now())),("acknowledged_by",sa.Column("acknowledged_by",sa.String(),sa.ForeignKey("users.id",ondelete="SET NULL"))),("acknowledged_at",sa.Column("acknowledged_at",sa.DateTime(timezone=True))),("resolved_by",sa.Column("resolved_by",sa.String(),sa.ForeignKey("users.id",ondelete="SET NULL"))),("resolved_at",sa.Column("resolved_at",sa.DateTime(timezone=True))),("resolution_reason",sa.Column("resolution_reason",sa.String(500))),("manually_resolved",sa.Column("manually_resolved",sa.Boolean(),nullable=False,server_default=sa.false()))]:op.add_column("alerts",column)
    op.create_index("ix_alerts_deduplication_key","alerts",["deduplication_key"])
    op.create_table("monitoring_events",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("device_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("devices.id",ondelete="CASCADE"),nullable=False),sa.Column("event_type",sa.String(40),nullable=False),sa.Column("source",sa.String(40),nullable=False),sa.Column("source_type",sa.String(40),nullable=False),sa.Column("source_id",sa.String(64),nullable=False),sa.Column("value_numeric",sa.Float()),sa.Column("evidence",postgresql.JSONB(),nullable=False,server_default=sa.text("'{}'::jsonb")),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column("processed_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("source_type","source_id","event_type",name="uq_monitoring_event_source_type"));op.create_index("ix_monitoring_events_device_occurred","monitoring_events",["device_id","occurred_at"])
    op.create_table("alert_history",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("alert_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("alerts.id",ondelete="CASCADE"),nullable=False),sa.Column("action",sa.String(30),nullable=False),sa.Column("actor",sa.String(120),nullable=False),sa.Column("previous_status",sa.String(20)),sa.Column("current_status",sa.String(20),nullable=False),sa.Column("reason",sa.String(500),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()));op.create_index("ix_alert_history_alert_id","alert_history",["alert_id"])
    op.create_table("in_app_notifications",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("alert_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("alerts.id",ondelete="CASCADE"),nullable=False),sa.Column("user_id",sa.String(),sa.ForeignKey("users.id",ondelete="CASCADE")),sa.Column("channel",sa.String(20),nullable=False,server_default="in_app"),sa.Column("delivery_status",sa.String(20),nullable=False,server_default="pending"),sa.Column("read_at",sa.DateTime(timezone=True)),sa.Column("error_summary",sa.String(500)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()));op.create_index("ix_in_app_notifications_alert_id","in_app_notifications",["alert_id"]);op.create_index("ix_in_app_notifications_user_id","in_app_notifications",["user_id"])
def downgrade():
    op.drop_table("in_app_notifications");op.drop_table("alert_history");op.drop_table("monitoring_events")
    for name in ("manually_resolved","resolution_reason","resolved_at","resolved_by","acknowledged_at","acknowledged_by","last_updated_at","deduplication_key","threshold_value","current_value","evidence","reason","source","lifecycle_status","severity","title","alert_type","rule_id"):op.drop_column("alerts",name)
    op.drop_table("alert_rules")
