"""V4C procurement and acquisition management."""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="v4c7d8e9f0a1";down_revision="v4b6c7d8e9f0";branch_labels=None;depends_on=None
def upgrade():
    op.execute("CREATE SEQUENCE IF NOT EXISTS asset_procurement_number_seq START 1")
    op.create_table("asset_procurements",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("organization_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("organizations.id",ondelete="RESTRICT"),nullable=False),sa.Column("procurement_number",sa.String(24),nullable=False,unique=True),sa.Column("reference_number",sa.String(80)),sa.Column("title",sa.String(220),nullable=False),sa.Column("description",sa.Text()),sa.Column("status",sa.String(30),nullable=False,server_default="draft"),sa.Column("requested_date",sa.Date()),sa.Column("approved_date",sa.Date()),sa.Column("ordered_date",sa.Date()),sa.Column("expected_delivery_date",sa.Date()),sa.Column("received_date",sa.Date()),sa.Column("department_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("departments.id",ondelete="SET NULL")),sa.Column("requested_by",sa.String(),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("approved_by",sa.String(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("currency",sa.String(3),nullable=False,server_default="NGN"),sa.Column("notes",sa.Text()),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.CheckConstraint("status IN ('draft','requested','approved','ordered','partially_received','received','cancelled')",name="ck_asset_procurement_status"))
    op.create_index("ix_asset_procurement_org_status","asset_procurements",["organization_id","status"])
    op.create_table("procurement_line_items",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("procurement_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("asset_procurements.id",ondelete="CASCADE"),nullable=False),sa.Column("description",sa.String(500),nullable=False),sa.Column("device_type",sa.String(80),nullable=False,server_default="Other"),sa.Column("quantity_requested",sa.Integer(),nullable=False),sa.Column("quantity_received",sa.Integer(),nullable=False,server_default="0"),sa.Column("unit_cost",sa.Numeric(18,2),nullable=False,server_default="0"),sa.CheckConstraint("quantity_requested > 0",name="ck_procurement_item_quantity"),sa.CheckConstraint("quantity_received >= 0 AND quantity_received <= quantity_requested",name="ck_procurement_item_received"))
    op.create_index("ix_procurement_line_items_procurement_id","procurement_line_items",["procurement_id"])
    op.create_table("procurement_asset_links",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("procurement_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("asset_procurements.id",ondelete="CASCADE"),nullable=False),sa.Column("line_item_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("procurement_line_items.id",ondelete="SET NULL")),sa.Column("asset_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("managed_assets.id",ondelete="RESTRICT"),nullable=False),sa.Column("linked_by",sa.String(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("linked_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.UniqueConstraint("asset_id",name="uq_procurement_asset_link_asset"),sa.UniqueConstraint("procurement_id","asset_id",name="uq_procurement_asset_link"))
    op.create_table("procurement_events",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("procurement_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("asset_procurements.id",ondelete="CASCADE"),nullable=False),sa.Column("organization_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("organizations.id",ondelete="RESTRICT"),nullable=False),sa.Column("action",sa.String(40),nullable=False),sa.Column("previous_status",sa.String(30)),sa.Column("new_status",sa.String(30),nullable=False),sa.Column("actor_id",sa.String(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("actor_name",sa.String(180),nullable=False),sa.Column("notes",sa.Text()),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()))
    op.create_index("ix_procurement_events_record_created","procurement_events",["procurement_id","created_at"]);op.create_index("ix_procurement_events_organization_id","procurement_events",["organization_id"])
def downgrade():
    for table in ("procurement_events","procurement_asset_links","procurement_line_items","asset_procurements"):op.drop_table(table)
    op.execute("DROP SEQUENCE IF EXISTS asset_procurement_number_seq")
