import {useEffect,useState,type FormEvent} from "react";
import {useLocation,useNavigate} from "react-router-dom";
import DashboardLayout from "../layouts/DashboardLayout";
import {Feedback} from "../components/Feedback";
import {StatCard} from "../components/StatCard";
import {StatusBadge} from "../components/StatusBadge";
import {endpoints} from "../lib/api";
import type {AssetDashboard,AssetReport,ContractRecord,EnterpriseAsset,PurchaseOrderRecord,PurchaseRequestRecord,SoftwareLicenseRecord,VendorRecord,WarrantyRecord} from "../lib/types";
import "../styles/asset-management.css";

const tabs=[["Asset Dashboard","/assets"],["Asset Explorer","/assets/explorer"],["Asset Timeline","/assets/timeline"],["Vendor Directory","/assets/vendors"],["Vendor Details","/assets/vendor-details"],["Procurement Center","/assets/procurement"],["Purchase Orders","/assets/orders"],["Contract Manager","/assets/contracts"],["Warranty Center","/assets/warranties"],["Software Licensing","/assets/licenses"],["Inventory Manager","/assets/inventory"],["Financial Reports","/assets/financials"]] as const;
const stages=["planned","requested","approved","purchased","received","installed","assigned","operational","maintenance","loaned","transferred","retired","disposed","archived"];
const propertyId=()=>localStorage.getItem("hiop.active_property_id")||null;

export default function AssetManagementPage(){
 const location=useLocation(),navigate=useNavigate(),mode=location.pathname.split("/")[2]||"dashboard";
 const [role,setRole]=useState("");const [dashboard,setDashboard]=useState<AssetDashboard>();const [assets,setAssets]=useState<EnterpriseAsset[]>([]);const [selected,setSelected]=useState<EnterpriseAsset>();const [vendors,setVendors]=useState<VendorRecord[]>([]);const [requests,setRequests]=useState<PurchaseRequestRecord[]>([]);const [orders,setOrders]=useState<PurchaseOrderRecord[]>([]);const [contracts,setContracts]=useState<ContractRecord[]>([]);const [warranties,setWarranties]=useState<WarrantyRecord[]>([]);const [licenses,setLicenses]=useState<SoftwareLicenseRecord[]>([]);const [report,setReport]=useState<AssetReport>();const [timeline,setTimeline]=useState<Record<string,unknown>>();const [inventory,setInventory]=useState<Record<string,unknown>>();const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 const admin=["admin","superadmin"].includes(role),contributor=admin||role==="technician";
 const load=async()=>{try{const list=await endpoints.enterpriseAssets({page_size:100});setAssets(list.items);const active=selected||list.items[0];if(!selected&&active)setSelected(active);if(mode==="dashboard")setDashboard(await endpoints.assetDashboard());if(["vendors","vendor-details","contracts"].includes(mode))setVendors((await endpoints.vendors({page_size:100})).items);if(mode==="timeline"&&active)setTimeline(await endpoints.assetTimeline(active.id));if(mode==="procurement")setRequests((await endpoints.purchaseRequests()).items);if(mode==="orders")setOrders((await endpoints.purchaseOrders()).items);if(mode==="contracts")setContracts((await endpoints.contracts()).items);if(mode==="warranties")setWarranties((await endpoints.warranties()).items);if(mode==="licenses")setLicenses((await endpoints.softwareLicenses()).items);if(mode==="inventory")setInventory(await endpoints.inventory());if(mode==="financials")setReport(await endpoints.assetReport());setError("")}catch(e){setError(e instanceof Error?e.message:"Unable to load Asset Management")}};
 useEffect(()=>{void endpoints.me().then(u=>setRole(u.role))},[]);useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);// eslint-disable-next-line react-hooks/exhaustive-deps
 },[mode]);
 const mutate=async(fn:()=>Promise<unknown>)=>{setBusy(true);try{await fn();await load()}catch(e){setError(e instanceof Error?e.message:"Operation failed")}finally{setBusy(false)}};
 const choose=(id:string)=>{const row=assets.find(a=>a.id===id);setSelected(row);if(mode==="timeline"&&row)void endpoints.assetTimeline(row.id).then(setTimeline)};
 const download=async(format:"csv"|"xlsx"|"pdf")=>{const out=await endpoints.exportAssetReport(format),url=URL.createObjectURL(out.blob),a=document.createElement("a");a.href=url;a.download=out.filename;a.click();URL.revokeObjectURL(url)};
 return <DashboardLayout><header className="page-title asset-title"><div><span className="eyebrow">Enterprise lifecycle governance</span><h1>Assets, Vendors & Procurement</h1><p>Control physical and software assets, suppliers, purchasing, contracts, warranties, inventory, and total cost across hospitality properties.</p></div>{contributor&&<button className="primary-action" onClick={()=>navigate("/assets/explorer")}>Register asset</button>}</header><nav className="asset-tabs" aria-label="Asset Management sections">{tabs.map(([label,path])=><button key={path} className={location.pathname===path?"active":""} onClick={()=>navigate(path)}>{label}</button>)}</nav>{error&&<Feedback error={error}/>}
 {mode==="dashboard"&&<><section className="asset-stats"><StatCard label="Enterprise assets" value={dashboard?.assets??0} detail="Registered" icon="devices"/><StatCard label="Operational" value={dashboard?.operational??0} detail="In service" icon="network"/><StatCard label="Current value" value={`$${dashboard?.asset_value??0}`} detail="Book value" icon="audit"/><StatCard label="Warranty expiry" value={dashboard?.warranties_expiring??0} detail="Next 90 days" icon="warning"/><StatCard label="Contract expiry" value={dashboard?.contracts_expiring??0} detail="Next 90 days" icon="clock"/><StatCard label="Low stock" value={dashboard?.low_stock??0} detail="Review threshold" icon="alerts"/></section><Panel title="Recently updated assets" copy="Lifecycle and valuation changes remain fully auditable."><AssetCards rows={dashboard?.recent??[]} choose={choose}/></Panel></>}
 {mode==="explorer"&&<><Panel title="Asset Explorer" copy="Searchable enterprise registry linked to legacy devices and CMDB configuration items.">{contributor&&<AssetForm mutate={mutate}/>}<AssetCards rows={assets} choose={choose}/></Panel>{selected&&<Panel title={`${selected.asset_number} · ${selected.manufacturer||"Asset"} ${selected.model||""}`} copy={`${selected.lifecycle_stage} · current value $${selected.current_value}`}><div className="asset-detail"><Detail label="Asset tag" value={selected.asset_tag||"Not assigned"}/><Detail label="Serial" value={selected.serial_number||"Not recorded"}/><Detail label="Depreciation" value={`$${selected.depreciation_value}`}/><Detail label="Warranty end" value={selected.warranty_end||"None"}/></div>{contributor&&stages.indexOf(selected.lifecycle_stage)<stages.length-1&&<button className="primary-action" disabled={busy} onClick={()=>void mutate(()=>endpoints.transitionEnterpriseAsset(selected.id,stages[stages.indexOf(selected.lifecycle_stage)+1],"Reviewed enterprise asset lifecycle transition"))}>Advance to {stages[stages.indexOf(selected.lifecycle_stage)+1]}</button>}</Panel>}</>}
 {mode==="timeline"&&<Panel title="Asset Timeline" copy="Lifecycle, location, assignment, transfer, disposal, and cost history."><Picker rows={assets} value={selected?.id} onChange={choose}/><pre className="asset-json">{JSON.stringify(timeline||{},null,2)}</pre></Panel>}
 {mode==="vendors"&&<Panel title="Vendor Directory" copy="Approved vendor lists, service regions, contacts, certifications, and scorecards.">{contributor&&<form className="asset-inline" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void mutate(()=>endpoints.createVendor({legal_name:f.get("legal_name"),trading_name:f.get("trading_name")||null,preferred:f.get("preferred")==="on",service_regions:String(f.get("regions")||"").split(",").filter(Boolean)}))}}><input name="legal_name" placeholder="Legal vendor name" required/><input name="trading_name" placeholder="Trading name"/><input name="regions" placeholder="Service regions"/><label><input name="preferred" type="checkbox"/> Preferred</label><button>Add vendor</button></form>}<VendorCards rows={vendors} admin={admin} mutate={mutate}/></Panel>}
 {mode==="vendor-details"&&<Panel title="Vendor Details" copy="Support and escalation contacts, certifications, reviews, and performance history."><VendorCards rows={vendors} admin={admin} mutate={mutate}/><p className="asset-guard">Vendor scores are arithmetic aggregations of submitted scorecards; no purchasing recommendation is generated.</p></Panel>}
 {mode==="procurement"&&<Panel title="Procurement Center" copy="Budget-validated requests require explicit submission and administrator approval.">{contributor&&<form className="asset-inline" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void mutate(()=>endpoints.createPurchaseRequest({property_id:propertyId(),title:f.get("title"),justification:f.get("justification"),requested_amount:Number(f.get("amount")),currency:f.get("currency")}))}}><input name="title" placeholder="Request title" required/><input name="justification" placeholder="Business justification" required/><input name="amount" type="number" min="0.01" step="0.01" placeholder="Amount" required/><select name="currency"><option>USD</option><option>NGN</option><option>GBP</option><option>EUR</option></select><button>Create request</button></form>}<div className="asset-grid">{requests.map(r=><article key={r.id}><StatusBadge status={r.status}/><h3>{r.request_number} · {r.title}</h3><p>{r.justification}</p><strong>{r.currency} {r.requested_amount}</strong><div className="asset-actions">{contributor&&r.status==="draft"&&<button onClick={()=>void mutate(()=>endpoints.submitPurchaseRequest(r.id))}>Submit</button>}{admin&&r.status==="submitted"&&<><button onClick={()=>void mutate(()=>endpoints.decidePurchaseRequest(r.id,{decision:"approve",notes:"Budget and business justification reviewed"}))}>Approve</button><button onClick={()=>void mutate(()=>endpoints.decidePurchaseRequest(r.id,{decision:"reject",notes:"Request rejected after finance review"}))}>Reject</button></>}</div></article>)}</div></Panel>}
 {mode==="orders"&&<Panel title="Purchase Orders" copy="Approved requests become bounded orders with partial receiving history."><SimpleCards rows={orders} title={r=>`${r.order_number} · ${r.currency} ${r.total_amount}`} status={r=>r.status}/></Panel>}
 {mode==="contracts"&&<Panel title="Contract Manager" copy="Support, maintenance, software, hardware, cloud, milestones, renewals, and immutable versions."><SimpleCards rows={contracts} title={r=>`${r.contract_number} · ${r.title}`} status={r=>r.status} detail={r=>`${r.start_date} → ${r.end_date} · ${r.currency} ${r.value}`}/></Panel>}
 {mode==="warranties"&&<Panel title="Warranty Center" copy="Coverage, providers, claims, linked assets, and expiration review."><SimpleCards rows={warranties} title={r=>r.provider} status={r=>r.status} detail={r=>`${r.start_date} → ${r.end_date} · ${r.coverage}`}/></Panel>}
 {mode==="licenses"&&<Panel title="Software Licensing" copy="Keys remain write-only while seats, utilization, renewals, subscriptions, and compliance are visible.">{admin&&<button className="primary-action" onClick={()=>void mutate(()=>endpoints.checkLicenseCompliance())}>Run compliance check</button>}<SimpleCards rows={licenses} title={r=>`${r.license_number} · ${r.license_type}`} status={r=>r.status} detail={r=>`${r.seats_allocated} / ${r.seats_purchased} seats · renewal ${r.renewal_date||"none"}`}/></Panel>}
 {mode==="inventory"&&<Panel title="Inventory Manager" copy="Spare parts, consumables, warehouse balances, reorder thresholds, and stock movements."><pre className="asset-json">{JSON.stringify(inventory||{},null,2)}</pre></Panel>}
 {mode==="financials"&&<Panel title="Financial Reports" copy="Purchase cost, depreciation, residual value, maintenance, repair, replacement, TCO, and executive summary."><section className="asset-report"><Detail label="Purchase cost" value={`$${report?.purchase_cost??0}`}/><Detail label="Current value" value={`$${report?.current_value??0}`}/><Detail label="Depreciation" value={`$${report?.depreciation??0}`}/><Detail label="Procurement spend" value={`$${report?.procurement_spend??0}`}/><Detail label="Contracts" value={String(report?.contracts??0)}/><Detail label="Inventory units" value={String(report?.inventory_units??0)}/></section>{admin&&<button onClick={()=>void mutate(()=>endpoints.recalculateDepreciation())}>Recalculate depreciation</button>}<div className="page-actions"><button onClick={()=>void download("csv")}>CSV</button><button onClick={()=>void download("xlsx")}>Excel</button><button onClick={()=>void download("pdf")}>PDF</button></div></Panel>}
 </DashboardLayout>
}
function Panel({title,copy,children}:{title:string;copy:string;children:React.ReactNode}){return <section className="hospitality-panel asset-panel"><div className="panel-heading"><div><h2>{title}</h2><span>{copy}</span></div></div>{children}</section>}
function Detail({label,value}:{label:string;value:string}){return <div><small>{label}</small><strong>{value}</strong></div>}
function Picker({rows,value,onChange}:{rows:EnterpriseAsset[];value?:string;onChange:(id:string)=>void}){return <label className="asset-picker">Asset<select value={value||""} onChange={e=>onChange(e.target.value)}><option value="" disabled>Select asset</option>{rows.map(a=><option key={a.id} value={a.id}>{a.asset_number} · {a.asset_tag||a.model}</option>)}</select></label>}
function AssetCards({rows,choose}:{rows:EnterpriseAsset[];choose:(id:string)=>void}){return !rows.length?<Feedback empty="No enterprise assets in scope."/>:<div className="asset-grid">{rows.map(a=><article key={a.id}><div><StatusBadge status={a.lifecycle_stage}/></div><h3>{a.asset_number} · {a.asset_tag||"Untagged"}</h3><p>{a.manufacturer} {a.model}</p><small>Book value ${a.current_value} · {a.serial_number||"No serial"}</small><button onClick={()=>choose(a.id)}>Select asset</button></article>)}</div>}
function VendorCards({rows,admin,mutate}:{rows:VendorRecord[];admin:boolean;mutate:(fn:()=>Promise<unknown>)=>Promise<void>}){return !rows.length?<Feedback empty="No vendors registered."/>:<div className="asset-grid">{rows.map(v=><article key={v.id}><StatusBadge status={v.status}/><h3>{v.vendor_number} · {v.legal_name}</h3><p>Rating {v.rating} / 5 {v.preferred?"· Preferred":""}</p>{admin&&!v.approved&&<button onClick={()=>void mutate(()=>endpoints.approveVendor(v.id))}>Approve vendor</button>}</article>)}</div>}
function SimpleCards<T extends {id:string}>({rows,title,status,detail}:{rows:T[];title:(row:T)=>string;status:(row:T)=>string;detail?:(row:T)=>string}){return !rows.length?<Feedback empty="No records in scope."/>:<div className="asset-grid">{rows.map(row=><article key={row.id}><StatusBadge status={status(row)}/><h3>{title(row)}</h3>{detail&&<p>{detail(row)}</p>}</article>)}</div>}
function AssetForm({mutate}:{mutate:(fn:()=>Promise<unknown>)=>Promise<void>}){return <form className="asset-form" onSubmit={(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);void mutate(()=>endpoints.createEnterpriseAsset({property_id:propertyId(),asset_tag:f.get("asset_tag")||null,serial_number:f.get("serial_number")||null,manufacturer:f.get("manufacturer")||null,model:f.get("model")||null,description:f.get("description")||null,purchase_date:f.get("purchase_date")||null,purchase_cost:Number(f.get("purchase_cost")||0),residual_value:Number(f.get("residual_value")||0),depreciation_method:f.get("depreciation_method"),useful_life_months:Number(f.get("useful_life_months")),warranty_end:f.get("warranty_end")||null}))}}><input name="asset_tag" placeholder="Asset tag"/><input name="serial_number" placeholder="Serial number"/><input name="manufacturer" placeholder="Manufacturer"/><input name="model" placeholder="Model"/><input name="purchase_date" type="date"/><input name="purchase_cost" type="number" min="0" step="0.01" placeholder="Purchase cost"/><input name="residual_value" type="number" min="0" step="0.01" placeholder="Residual value"/><select name="depreciation_method"><option value="straight_line">Straight line</option><option value="declining_balance">Declining balance</option><option value="none">No depreciation</option></select><input name="useful_life_months" type="number" min="1" defaultValue="60"/><input name="warranty_end" type="date"/><textarea name="description" placeholder="Asset description"/><button className="primary-action">Register asset</button></form>}
