import {useState} from "react";
import {Link,useParams} from "react-router-dom";
import {Feedback} from "../components/Feedback";
import {StatusBadge} from "../components/StatusBadge";
import {useRequest} from "../hooks/useRequest";
import DashboardLayout from "../layouts/DashboardLayout";
import {endpoints} from "../lib/api";
import type {LifecycleStatus} from "../lib/types";
import {PageTitle} from "./DashboardPage";
const labels:Record<LifecycleStatus,string>={planned:"Planned",received:"Received",deployed:"Deployed",active:"Active",in_maintenance:"In maintenance",retired:"Retired"};
const next:Record<LifecycleStatus,LifecycleStatus[]>={planned:["received"],received:["deployed"],deployed:["active"],active:["in_maintenance","retired"],in_maintenance:["active","retired"],retired:["active"]};
export default function AssetDetailsPage(){
 const {id=""}=useParams();const asset=useRequest(()=>endpoints.asset(id),[id]);const incidents=useRequest(()=>endpoints.assetIncidentHistory(id),[id]);const problems=useRequest(()=>endpoints.assetProblems(id),[id]);const changes=useRequest(()=>endpoints.linkedGovernanceChanges("asset",id),[id]);const knowledge=useRequest(()=>endpoints.linkedPracticalKnowledge("asset",id),[id]);const me=useRequest(endpoints.me,[]);const vendors=useRequest(()=>endpoints.operationalVendors({status:"active"}),[]);const [target,setTarget]=useState<LifecycleStatus|null>(null),[reason,setReason]=useState(""),[notes,setNotes]=useState(""),[vendorId,setVendorId]=useState(""),[error,setError]=useState("");const row=asset.data,canManage=me.data?.role==="admin"||me.data?.role==="technician";
 const transition=async()=>{if(!target)return;setError("");try{await endpoints.transitionAsset(id,{status:target,reason:reason||undefined,notes:notes||undefined});setTarget(null);setReason("");setNotes("");await asset.reload()}catch(x){setError(x instanceof Error?x.message:"Unable to update lifecycle")}};
 const linkVendor=async()=>{if(!vendorId)return;setError("");try{await endpoints.linkVendorAsset(vendorId,id);setVendorId("");await asset.reload()}catch(x){setError(x instanceof Error?x.message:"Unable to associate vendor")}};
 return <DashboardLayout><PageTitle eyebrow="Asset lifecycle & intelligence" title={row?.name??"Asset record"} copy="Organizational identity, technical evidence, and traceable lifecycle history." action={<div className="page-actions"><Link className="secondary-action" to="/devices">Back to Manage</Link>{row&&me.data?.role==="admin"&&<Link className="primary-action" to={`/assets/${row.id}/edit`}>Edit asset</Link>}</div>}/>{asset.loading||asset.error?<Feedback loading={asset.loading} error={asset.error}/>:row&&<section className="device-details"><header><div className="overview-statuses"><span>Lifecycle</span><StatusBadge status={labels[row.status]}/><span>Health</span><StatusBadge status={row.status==="retired"?"N/A":row.health}/></div></header>{error&&<Feedback error={error}/>}<h2>Lifecycle</h2><dl><D l="Status" v={labels[row.status]}/><D l="Condition" v={row.condition}/><D l="Acquired" v={date(row.acquisition_date)}/><D l="Received" v={date(row.received_date)}/><D l="Deployed" v={date(row.deployment_date)}/><D l="Asset age" v={row.asset_age_months==null?null:age(row.asset_age_months)}/><D l="Warranty" v={row.warranty_status}/><D l="Warranty starts" v={date(row.warranty_start)}/><D l="Warranty ends" v={date(row.warranty_end)}/><D l="Expected replacement" v={date(row.expected_replacement_date)}/>{row.status==="retired"&&<><D l="Retired" v={date(row.retirement_date)}/><D l="Retirement reason" v={row.retirement_reason}/></>}<D l="Lifecycle notes" v={row.lifecycle_notes}/></dl>{canManage&&<div className="page-actions lifecycle-actions">{next[row.status].filter(x=>me.data?.role==="admin"||new Set(["active","in_maintenance"]).has(x)).map(x=><button key={x} className={x==="retired"?"danger-action":"secondary-action"} onClick={()=>setTarget(x)}>{action(row.status,x)}</button>)}</div>}{target&&<div className="inline-editor"><h3>Confirm {labels[target]}</h3>{target==="retired"&&<label>Retirement reason<select value={reason} onChange={e=>setReason(e.target.value)} required><option value="">Select reason</option><option value="replaced">Replaced</option><option value="end_of_life">End of life</option><option value="damaged">Damaged</option><option value="no_longer_required">No longer required</option><option value="other">Other</option></select></label>}<label>Notes<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label><div className="page-actions"><button onClick={()=>setTarget(null)}>Cancel</button><button className="primary-action" disabled={target==="retired"&&!reason} onClick={()=>void transition()}>Confirm change</button></div></div>}
 <h2>Lifecycle history</h2>{!row.lifecycle_history.length?<Feedback empty="No lifecycle transitions have been recorded yet."/>:<ol className="lifecycle-timeline">{row.lifecycle_history.map(event=><li key={event.id}><strong>{labels[event.new_status]}</strong><span>{new Date(event.created_at).toLocaleString()} · {event.changed_by_name}</span>{event.previous_status&&<small>{labels[event.previous_status as LifecycleStatus]} → {labels[event.new_status]}</small>}{event.reason&&<p>{event.reason}</p>}{event.notes&&<p>{event.notes}</p>}</li>)}</ol>}
 <h2>Asset</h2><dl><D l="Asset ID" v={row.asset_number}/><D l="Asset Tag" v={row.asset_tag}/><D l="CI Category" v={row.ci_category}/><D l="Source" v={row.source}/></dl><h2>Identity</h2><dl><D l="Name" v={row.name}/><D l="Device Type" v={row.device_type}/><D l="Manufacturer" v={row.vendor}/><D l="Model" v={row.model}/><D l="Serial Number" v={row.serial_number}/><D l="Hostname" v={row.hostname}/><D l="IP" v={row.ip_address}/><D l="MAC" v={row.mac_address}/></dl>
 <h2>Vendor & acquisition</h2><dl><D l="Supplier / Support Vendor" v={row.supplier?.name}/><D l="Vendor ID" v={row.supplier?.vendor_id}/><D l="Vendor Status" v={row.supplier?.status}/><D l="Support Contact" v={row.supplier?.primary_email||row.supplier?.primary_phone}/><D l="Procurement" v={row.acquisition?.procurement_number}/><D l="Warranty" v={row.warranty_status}/></dl>{row.supplier&&<Link className="linked-record" to={`/vendors/${row.supplier.id}`}>Open {row.supplier.name}</Link>}{me.data?.role==="admin"&&<div className="inline-editor"><label>Associate vendor<select value={vendorId} onChange={e=>setVendorId(e.target.value)}><option value="">Select active vendor</option>{vendors.data?.map(item=><option key={item.id} value={item.id}>{item.vendor_id} · {item.name}</option>)}</select></label><button disabled={!vendorId} onClick={()=>void linkVendor()}>Save Vendor</button></div>}
 <h2>Ownership & location</h2><dl><D l="Department" v={row.department}/><D l="Business Owner" v={row.business_owner}/><D l="Technical Owner" v={row.technical_owner}/><D l="Location" v={row.location}/><D l="Description" v={row.description}/></dl><h2>Incident history</h2>{incidents.loading||incidents.error?<Feedback loading={incidents.loading} error={incidents.error}/>:!incidents.data?.length?<Feedback empty="No incidents are linked to this asset."/>:<div className="linked-list">{incidents.data.map(item=><Link key={item.id} to={`/incidents/${item.id}`} className="linked-record"><strong>{item.incident_number}</strong> {item.title}<small>{new Date(item.created_at).toLocaleDateString()} · {item.status}</small></Link>)}</div>}<h2>Problem context</h2>{problems.loading||problems.error?<Feedback loading={problems.loading} error={problems.error}/>:!problems.data?.length?<Feedback empty="No problems are linked to this asset."/>:<div className="linked-list">{problems.data.map(item=><Link key={item.id} to={`/problems/${item.id}`} className="linked-record"><strong>{item.problem_number}</strong> {item.title}<small>{item.status}</small></Link>)}</div>}<h2>Change history</h2>{changes.loading||changes.error?<Feedback loading={changes.loading} error={changes.error}/>:!changes.data?.length?<Feedback empty="No changes are linked to this asset."/>:<div className="linked-list">{changes.data.map(item=><Link key={item.id} to={`/changes/${item.id}`} className="linked-record"><strong>{item.change_id}</strong> {item.title}<small>{item.status}</small></Link>)}</div>}<h2>Related knowledge</h2>{knowledge.loading||knowledge.error?<Feedback loading={knowledge.loading} error={knowledge.error}/>:!knowledge.data?.length?<Feedback empty="No knowledge articles are linked to this asset."/>:<div className="linked-list">{knowledge.data.map(item=><Link key={item.id} to={`/knowledge/${item.id}`} className="linked-record"><strong>{item.article_id}</strong> {item.title}<small>{item.status}</small></Link>)}</div>}<h2>Relationships</h2><dl>{Object.entries(row.relationships).map(([key,value])=><D key={key} l={key} v={String(value)}/>)}</dl></section>}</DashboardLayout>
}
function action(from:LifecycleStatus,to:LifecycleStatus){if(to==="in_maintenance")return "Place in Maintenance";if(from==="in_maintenance"&&to==="active")return "Return to Active";if(from==="retired")return "Reactivate Asset";if(to==="retired")return "Retire Asset";return `Mark ${labels[to]}`}
function date(value:string|null){return value?new Date(`${value}T00:00:00`).toLocaleDateString():null}function age(months:number){return months<12?`${months} month${months===1?"":"s"}`:`${Math.floor(months/12)} year${Math.floor(months/12)===1?"":"s"}, ${months%12} months`}function D({l,v}:{l:string;v:string|null|undefined}){return <div><dt>{l}</dt><dd>{v||"Not available"}</dd></div>}
