/* eslint-disable @typescript-eslint/no-explicit-any */
import DashboardLayout from "../layouts/DashboardLayout";
import { PageTitle } from "./DashboardPage";
import { Feedback } from "../components/Feedback";
import { endpoints } from "../lib/api";
import { useRequest } from "../hooks/useRequest";

export default function AuditPage() {
  const logs = useRequest(endpoints.auditLogs, []);
  return <DashboardLayout><PageTitle eyebrow="Governance" title="Audit trail" copy="Accountability records generated by HIOP operations."/>{logs.loading||logs.error?<Feedback loading={logs.loading} error={logs.error} onRetry={logs.reload}/>:<section className="event-list">{(logs.data??[]).map((log:any)=><article key={log.id}><span className="pulse online"/><div><strong>{log.action}</strong><p>{log.description} · {log.actor}</p></div><time>{log.created_at?new Date(log.created_at).toLocaleString():"—"}</time></article>)}{!logs.data?.length&&<Feedback empty="No audit records yet."/>}</section>}</DashboardLayout>;
}
