import {useEffect,useState,type FormEvent} from "react";
import DashboardLayout from "../layouts/DashboardLayout";
import {Feedback} from "../components/Feedback";
import {StatCard} from "../components/StatCard";
import {endpoints} from "../lib/api";
import type {AutomationApproval,AutomationRun,AutomationVersion,AutomationWorkflow} from "../lib/types";

export default function AutomationPage(){
  const [workflows,setWorkflows]=useState<AutomationWorkflow[]>([]),[runs,setRuns]=useState<AutomationRun[]>([]),[approvals,setApprovals]=useState<AutomationApproval[]>([]),[selected,setSelected]=useState<AutomationWorkflow>(),[versions,setVersions]=useState<AutomationVersion[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  const load=async()=>{try{const [w,r,a]=await Promise.all([endpoints.automationWorkflows(),endpoints.automationRuns(),endpoints.automationApprovals()]);setWorkflows(w.items);setRuns(r.items);setApprovals(a.items);setError("")}catch(e){setError(e instanceof Error?e.message:"Unable to load automation")}};
  useEffect(()=>{void Promise.all([endpoints.automationWorkflows(),endpoints.automationRuns(),endpoints.automationApprovals()]).then(([w,r,a])=>{setWorkflows(w.items);setRuns(r.items);setApprovals(a.items)}).catch(e=>setError(e instanceof Error?e.message:"Unable to load automation"))},[]);
  const choose=async(w:AutomationWorkflow)=>{setSelected(w);try{setVersions((await endpoints.automationVersions(w.id)).items)}catch(e){setError(e instanceof Error?e.message:"Unable to load versions")}};
  const create=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const data=new FormData(e.currentTarget);setBusy(true);try{await endpoints.createAutomationWorkflow({property_id:(localStorage.getItem("hiop.active_property_id")||null),name:String(data.get("name")),code:String(data.get("code")),workflow_category:String(data.get("category"))});e.currentTarget.reset();await load()}catch(err){setError(err instanceof Error?err.message:"Unable to create workflow")}finally{setBusy(false)}};
  return <DashboardLayout onLiveEvent={e=>{if((e.type??e.event)?.startsWith("automation_"))void load()}}>
    <header className="page-title"><div><span className="eyebrow">Approval-safe operations</span><h1>Automation</h1><p>Build versioned workflows from approved actions, simulate them, review checkpoints, and monitor runs.</p></div></header>
    {error&&<Feedback error={error}/>}
    <section className="stats-grid"><StatCard label="Workflows" value={workflows.length} detail="Property scoped" icon="settings"/><StatCard label="Runs" value={runs.length} detail="Bounded history" icon="audit"/><StatCard label="Pending approvals" value={approvals.length} detail="Human checkpoints" icon="alerts"/></section>
    <section className="hospitality-panel"><div className="panel-heading"><div><h2>Create workflow</h2><span>Definitions remain inactive until separately approved and enabled.</span></div></div><form className="topology-form" onSubmit={create}><label>Name<input name="name" required maxLength={160}/></label><label>Code<input name="code" required maxLength={60}/></label><label>Category<select name="category"><option value="custom">Custom</option><option value="incident_response">Incident response</option><option value="notification">Notification</option><option value="reporting">Reporting</option></select></label><button disabled={busy}>{busy?"Creating…":"Create workflow"}</button></form></section>
    <section className="hospitality-panel"><div className="panel-heading"><div><h2>Workflow definitions</h2><span>Select a workflow to inspect immutable versions.</span></div></div>{!workflows.length?<Feedback empty="No workflows defined."/>:<div className="hospitality-grid">{workflows.map(w=><button className="hospitality-card" key={w.id} onClick={()=>void choose(w)}><strong>{w.name}</strong><span>{w.code} · {w.workflow_category}</span><small>{w.status}{w.enabled?" · enabled":""}</small></button>)}</div>}</section>
    {selected&&<section className="hospitality-panel"><div className="panel-heading"><div><h2>{selected.name} versions</h2><span>Checksum-backed history and approval status.</span></div></div>{!versions.length?<Feedback empty="No versions created yet."/>:<div className="hospitality-grid">{versions.map(v=><article className="hospitality-card" key={v.id}><strong>Version {v.version_number}</strong><span>{v.status}</span><small>{v.checksum?.slice(0,16)??"No checksum"}</small></article>)}</div>}</section>}
    <section className="hospitality-panel"><div className="panel-heading"><div><h2>Recent runs</h2><span>Live updates refresh this bounded list.</span></div></div>{!runs.length?<Feedback empty="No workflow runs."/>:<div className="hospitality-grid">{runs.slice(0,12).map(r=><article className="hospitality-card" key={r.id}><strong>{r.status}</strong><span>{r.trigger_type}</span><small>{new Date(r.created_at).toLocaleString()}</small></article>)}</div>}</section>
  </DashboardLayout>
}
