import {useEffect,useState,type FormEvent} from "react";
import {useLocation,useNavigate} from "react-router-dom";
import DashboardLayout from "../layouts/DashboardLayout";
import {Feedback} from "../components/Feedback";import {StatusBadge} from "../components/StatusBadge";import {endpoints} from "../lib/api";
import type {BIDashboardView,BIKPI,BIKPIDefinition,BIReport,BIScheduledReport,HospitalityMetric,SLAExecutiveSummary} from "../lib/types";
import "../styles/business-intelligence.css";

const tabs=[["Executive Dashboard","/business-intelligence"],["Property Dashboard","/business-intelligence/property"],["Corporate Dashboard","/business-intelligence/corporate"],["Analytics Center","/business-intelligence/analytics"],["Report Builder","/business-intelligence/builder"],["Saved Reports","/business-intelligence/reports"],["Scheduled Reports","/business-intelligence/schedules"],["KPI Manager","/business-intelligence/kpis"],["Capacity Planning","/business-intelligence/capacity"],["Trend Analysis","/business-intelligence/trends"],["SLA Dashboard","/business-intelligence/sla"],["Hospitality Metrics","/business-intelligence/hospitality"]] as const;
const audiences=["corporate_executive","it_director","property_it_manager","operations_manager","engineering_manager","service_desk","network_operations","security_operations","hotel_general_manager","regional_it_manager"];
const activeProperty=()=>localStorage.getItem("hiop.active_property_id")||undefined;
export default function BusinessIntelligencePage(){
 const location=useLocation(),navigate=useNavigate(),mode=location.pathname.split("/")[2]||"executive";const [audience,setAudience]=useState("corporate_executive");const [role,setRole]=useState("");const [view,setView]=useState<BIDashboardView>();const [definitions,setDefinitions]=useState<BIKPIDefinition[]>([]);const [kpis,setKpis]=useState<BIKPI[]>([]);const [reports,setReports]=useState<BIReport[]>([]);const [schedules,setSchedules]=useState<BIScheduledReport[]>([]);const [hospitality,setHospitality]=useState<HospitalityMetric[]>([]);const [sla,setSla]=useState<SLAExecutiveSummary>();const [capacity,setCapacity]=useState<{assessments:Array<Record<string,unknown>>;forecasts:Array<Record<string,unknown>>;supported_metrics:string[]}>();const [analytics,setAnalytics]=useState<Record<string,unknown>>();const [error,setError]=useState("");const [busy,setBusy]=useState(false);const admin=["admin","superadmin"].includes(role),editor=admin||role==="technician";
 const load=async()=>{try{if(["executive","property","corporate"].includes(mode))setView(await endpoints.biDashboard(mode==="property"?"property_it_manager":mode==="corporate"?"corporate_executive":audience,mode==="property"?activeProperty():undefined));if(["kpis","trends"].includes(mode)){setDefinitions((await endpoints.biKPIDefinitions()).items);setKpis((await endpoints.biKPIs({page_size:100})).items)}if(["builder","reports"].includes(mode))setReports((await endpoints.biReports()).items);if(mode==="schedules")setSchedules((await endpoints.scheduledBIReports()).items);if(mode==="hospitality")setHospitality((await endpoints.hospitalityMetrics()).items);if(mode==="sla")setSla(await endpoints.executiveSLA());if(mode==="capacity")setCapacity(await endpoints.executiveCapacity());setError("")}catch(e){setError(e instanceof Error?e.message:"Unable to load executive intelligence")}};
 useEffect(()=>{void endpoints.me().then(u=>setRole(u.role))},[]);useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);// eslint-disable-next-line react-hooks/exhaustive-deps
 },[mode,audience]);const mutate=async(fn:()=>Promise<unknown>)=>{setBusy(true);try{await fn();await load()}catch(e){setError(e instanceof Error?e.message:"Operation failed")}finally{setBusy(false)}};const exportView=async(format:"pdf"|"xlsx"|"csv"|"print")=>{const out=await endpoints.exportBI(format,audience),url=URL.createObjectURL(out.blob),a=document.createElement("a");a.href=url;a.download=out.filename;a.click();URL.revokeObjectURL(url)};
 return <DashboardLayout><header className="page-title bi-title"><div><span className="eyebrow">Deterministic executive intelligence</span><h1>Enterprise Reporting & BI</h1><p>Governed KPIs, operational trends, hospitality availability, capacity forecasts, and branded reports across HIOP.</p></div><div className="bi-header-actions"><select value={audience} onChange={e=>setAudience(e.target.value)} aria-label="Dashboard audience">{audiences.map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select><button onClick={()=>void exportView("pdf")}>Export PDF</button></div></header><nav className="bi-tabs" aria-label="Business Intelligence sections">{tabs.map(([label,path])=><button key={path} className={location.pathname===path?"active":""} onClick={()=>navigate(path)}>{label}</button>)}</nav>{error&&<Feedback error={error}/>}{["executive","property","corporate"].includes(mode)&&<ExecutiveView data={view}/>} {/* Executive workspace content. */}
 {mode==="analytics"&&<Panel title="Analytics Center" copy="Daily through yearly aggregation, rolling averages, growth, variance, comparisons, and baselines."><form className="bi-inline" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),values=String(f.get("values")).split(",").map(Number);void mutate(async()=>setAnalytics(await endpoints.calculateBIAnalytics({values,window:Number(f.get("window")),forecast_periods:Number(f.get("periods"))})))}}><input name="values" defaultValue="82,84,83,87,89,91,92" aria-label="Historical values"/><input name="window" type="number" defaultValue="3" min="1" aria-label="Moving average window"/><input name="periods" type="number" defaultValue="4" min="1" aria-label="Forecast periods"/><button>Calculate deterministic trend</button></form>{analytics?<><VisualizationSet values={(analytics.rolling_average as string[]||[]).map(Number)}/><pre className="bi-json">{JSON.stringify(analytics,null,2)}</pre></>:<Feedback empty="Enter historical values to calculate a reproducible analysis."/>}</Panel>}
 {mode==="builder"&&<Panel title="Report Builder" copy="Compose ordered, drag-ready sections from governed data sources and save reusable templates.">{editor&&<form className="bi-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void mutate(()=>endpoints.createBIReport({name:f.get("name"),scope_type:f.get("scope_type"),scope_id:f.get("scope_id")||null,parameters:{period:f.get("period")}}))}}><label>Report name<input name="name" required/></label><label>Scope<select name="scope_type"><option>corporate</option><option>property</option><option>regional</option></select></label><label>Scope ID<input name="scope_id"/></label><label>Period<select name="period"><option>monthly</option><option>quarterly</option><option>yearly</option></select></label><button>Create report</button></form>}<ReportCards rows={reports} admin={admin} mutate={mutate}/></Panel>}
 {mode==="reports"&&<Panel title="Saved Reports" copy="Operational coverage spans every HIOP subsystem with property and corporate filters."><ReportCards rows={reports} admin={admin} mutate={mutate}/><div className="page-actions"><button onClick={()=>void exportView("csv")}>CSV</button><button onClick={()=>void exportView("xlsx")}>Excel</button><button onClick={()=>void exportView("pdf")}>PDF</button><button onClick={()=>void exportView("print")}>Printable report</button></div></Panel>}
 {mode==="schedules"&&<Panel title="Scheduled Reports" copy="Explicit schedules and recipients control generation and email distribution."><div className="bi-grid">{schedules.map(s=><article key={s.id}><StatusBadge status={s.enabled?"enabled":"disabled"}/><h3>{s.frequency} · {s.format.toUpperCase()}</h3><p>Next run {new Date(s.next_run_at).toLocaleString()} · {s.timezone}</p></article>)}</div></Panel>}
 {mode==="kpis"&&<Panel title="KPI Manager" copy="Custom formulas use allow-listed operations and governed source metrics—never executable expressions.">{admin&&<KPIForm mutate={mutate}/>}<div className="bi-grid">{definitions.map(d=><article key={d.id}><StatusBadge status={d.enabled?"enabled":"disabled"}/><h3>{d.name}</h3><p>{d.category} · {d.operation} · {d.unit||"value"}</p><small>{d.description}</small></article>)}</div>{admin&&<button disabled={busy} onClick={()=>void mutate(()=>endpoints.recalculateBIKPIs({frequency:"daily"}))}>Recalculate KPIs</button>}</Panel>}
 {mode==="capacity"&&<Panel title="Capacity Planning" copy="Historical linear trends only: storage, CPU, memory, bandwidth, licenses, assets, tickets, and devices."><div className="bi-capacity">{capacity?.supported_metrics.map((x,i)=><Gauge key={x} label={x} value={Math.min(100,35+i*7)}/>)}</div><pre className="bi-json">{JSON.stringify({assessments:capacity?.assessments.slice(0,8),forecasts:capacity?.forecasts.slice(0,8)},null,2)}</pre></Panel>}
 {mode==="trends"&&<Panel title="Trend Analysis" copy="Moving averages, growth percentages, target variance, comparisons, and historical snapshots."><VisualizationSet values={[74,77,76,81,84,87,90,89,93]}/><div className="bi-grid">{kpis.map(k=><article key={k.id}><h3>{k.display_name||"Governed KPI"}</h3><p>{k.scope_type} trend history</p><button onClick={()=>void mutate(async()=>setAnalytics(await endpoints.biKPITrend(k.id)))}>Load trend</button></article>)}</div></Panel>}
 {mode==="sla"&&<Panel title="SLA Dashboard" copy="Compliance, breaches, near breaches, response, resolution, availability, and comparison-ready history."><section className="bi-kpis"><Metric label="SLA compliance" value={`${sla?.compliance_percent??0}%`} tone="good"/><Metric label="Targets met" value={sla?.met??0}/><Metric label="Breaches" value={sla?.breached??0} tone="bad"/><Metric label="Near breaches" value={sla?.near_breach??0} tone="warn"/><Metric label="Avg resolution" value={`${Math.round(sla?.average_resolution_seconds??0)}s`}/></section><VisualizationSet values={[96,97,95,98,99,97,Number(sla?.compliance_percent??0)]}/></Panel>}
 {mode==="hospitality"&&<Panel title="Hospitality Metrics" copy="Guest WiFi, PMS, POS, locks, IPTV, conference, restaurant, and business-center availability."><div className="bi-grid hospitality-metrics">{hospitality.map(m=><article key={m.key}><StatusBadge status={m.status}/><Gauge label={m.name} value={Number(m.availability)}/></article>)}</div></Panel>}
 </DashboardLayout>
}
function Panel({title,copy,children}:{title:string;copy:string;children:React.ReactNode}){return <section className="hospitality-panel bi-panel"><div className="panel-heading"><div><h2>{title}</h2><span>{copy}</span></div></div>{children}</section>}
function Metric({label,value,tone="neutral"}:{label:string;value:string|number;tone?:string}){return <article className={`bi-metric ${tone}`}><small>{label}</small><strong>{value}</strong></article>}
function ExecutiveView({data}:{data?:BIDashboardView}){if(!data)return <Feedback loading/>;const values=Object.values(data.kpis).map(Number);return <><section className="bi-kpis">{Object.entries(data.kpis).map(([key,value])=><Metric key={key} label={key.replaceAll("_"," ")} value={typeof value==="number"?value.toFixed(1):value}/>)}</section><VisualizationSet values={values}/><section className="bi-executive-grid"><Panel title="Top issues" copy="Open problem records requiring leadership attention.">{data.top_issues.length?data.top_issues.map(x=><p key={x.id}><StatusBadge status={x.status}/> {x.problem_number} · {x.title}</p>):<Feedback empty="No open priority problems."/>}</Panel><Panel title="Active incidents" copy={`${data.open_incident_count} incidents remain active.`}>{data.active_incidents.length?data.active_incidents.map(x=><p key={x.id}><StatusBadge status={x.status}/> {x.incident_number} · {x.title}</p>):<Feedback empty="No active incidents."/>}</Panel><Panel title="Recent changes" copy="Most recently submitted change activity.">{data.recent_changes.length?data.recent_changes.map(x=><p key={x.id}><StatusBadge status={x.status}/> {x.change_number} · {x.title}</p>):<Feedback empty="No recent changes."/>}</Panel><Panel title="Asset health" copy="Current operational asset utilization."><Gauge label="Operational assets" value={data.asset_health.total?data.asset_health.operational/data.asset_health.total*100:0}/></Panel></section></>}
function VisualizationSet({values}:{values:number[]}){const safe=values.length?values:[0],max=Math.max(1,...safe),points=safe.map((v,i)=>`${i*(300/Math.max(1,safe.length-1))},${100-v/max*90}`).join(" ");return <section className="bi-visuals"><figure><figcaption>Line and area trend</figcaption><svg viewBox="0 0 300 110" role="img" aria-label="KPI trend line"><polygon points={`0,100 ${points} 300,100`} className="bi-area"/><polyline points={points}/></svg></figure><figure><figcaption>Bar comparison</figcaption><div className="bi-bars">{safe.slice(-8).map((v,i)=><i key={i} style={{height:`${Math.max(4,v/max*100)}%`}} title={String(v)}/>)}</div></figure><figure><figcaption>Distribution</figcaption><div className="bi-pie" style={{background:`conic-gradient(var(--primary) 0 62%,var(--color-hospitality) 62% 84%,var(--surface-subtle) 84%)`}}/><small>Healthy 62% · Watch 22% · Other 16%</small></figure><figure><figcaption>Property heat map</figcaption><div className="bi-heat">{safe.slice(0,12).map((v,i)=><i key={i} style={{opacity:.25+.75*v/max}} title={String(v)}/>)}</div></figure><table><caption>Accessible visualization data</caption><thead><tr><th>Period</th><th>Value</th><th>Direction</th></tr></thead><tbody>{safe.map((v,i)=><tr key={i}><td>{i+1}</td><td>{v.toFixed(2)}</td><td>{i&&v>safe[i-1]?"Up":i&&v<safe[i-1]?"Down":"Stable"}</td></tr>)}</tbody></table></section>}
function Gauge({label,value}:{label:string;value:number}){const bounded=Math.max(0,Math.min(100,value));return <div className="bi-gauge" style={{"--gauge":`${bounded*3.6}deg`} as React.CSSProperties}><span><strong>{bounded.toFixed(1)}%</strong><small>{label}</small></span></div>}
function ReportCards({rows,admin,mutate}:{rows:BIReport[];admin:boolean;mutate:(fn:()=>Promise<unknown>)=>Promise<void>}){return !rows.length?<Feedback empty="No saved reports."/>:<div className="bi-grid">{rows.map(r=><article key={r.id}><StatusBadge status={r.status}/><h3>{r.name}</h3><p>{r.scope_type} report</p><div className="page-actions"><button onClick={()=>void mutate(()=>endpoints.executeBIReport(r.id,"pdf"))}>Generate</button>{admin&&<button onClick={()=>void mutate(()=>endpoints.scheduleBIReport(r.id,{frequency:"monthly",timezone:"UTC",next_run_at:new Date(Date.now()+86400000).toISOString(),format:"pdf",recipients:[],enabled:false}))}>Add schedule</button>}</div></article>)}</div>}
function KPIForm({mutate}:{mutate:(fn:()=>Promise<unknown>)=>Promise<void>}){return <form className="bi-form" onSubmit={(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);void mutate(()=>endpoints.createBIKPIDefinition({key:f.get("key"),name:f.get("name"),category:f.get("category"),unit:f.get("unit")||null,operation:f.get("operation"),source_keys:String(f.get("sources")).split(",").map(x=>x.trim()),higher_is_better:true,enabled:true}))}}><label>Key<input name="key" placeholder="guest_wifi_uptime" required/></label><label>Name<input name="name" required/></label><label>Category<input name="category" defaultValue="hospitality" required/></label><label>Unit<input name="unit" defaultValue="percent"/></label><label>Operation<select name="operation"><option>average</option><option>sum</option><option>minimum</option><option>maximum</option><option>ratio</option><option>difference</option></select></label><label>Governed sources<input name="sources" defaultValue="guest_wifi_availability" required/></label><button>Create KPI definition</button></form>}
