import {useEffect,useState,type FormEvent} from "react";
import {useLocation,useNavigate} from "react-router-dom";
import DashboardLayout from "../layouts/DashboardLayout";
import {Feedback} from "../components/Feedback";
import {StatCard} from "../components/StatCard";
import {endpoints} from "../lib/api";
import type {CABMeeting,ChangeApproval,ChangeDashboard,ChangeExecution,ChangeExecutionTask,ChangeReportSummary,ChangeRequest,ChangeRiskAssessment,ChangeTask,ChangeType,EnterpriseRelease,MaintenanceWindow} from "../lib/types";
import "../styles/change-management.css";

const propertyId=()=>localStorage.getItem("hiop.active_property_id")||null;
const iso=(value:FormDataEntryValue|null)=>value?new Date(String(value)).toISOString():null;
const modes=[["Dashboard","/changes"],["RFCs","/changes/requests"],["New RFC","/changes/new"],["Approvals","/changes/approvals"],["CAB","/changes/cab"],["Risk","/changes/risk"],["Maintenance","/changes/maintenance"],["Execution","/changes/execution"],["Releases","/changes/releases"],["Timeline","/changes/timeline"],["Reports","/changes/reports"],["Audit","/changes/audit"]];

export default function ChangeManagementPage(){
  const location=useLocation(),navigate=useNavigate(),parts=location.pathname.split("/"),mode=parts[2]||"dashboard",selectedId=parts[2]==="requests"?parts[3]:undefined;
  const [dashboard,setDashboard]=useState<ChangeDashboard>();const [changes,setChanges]=useState<ChangeRequest[]>([]);const [selected,setSelected]=useState<ChangeRequest>();const [types,setTypes]=useState<ChangeType[]>([]);
  const [approvals,setApprovals]=useState<ChangeApproval[]>([]);const [tasks,setTasks]=useState<ChangeTask[]>([]);const [meetings,setMeetings]=useState<CABMeeting[]>([]);const [windows,setWindows]=useState<MaintenanceWindow[]>([]);const [releases,setReleases]=useState<EnterpriseRelease[]>([]);const [executions,setExecutions]=useState<ChangeExecution[]>([]);const [executionTasks,setExecutionTasks]=useState<ChangeExecutionTask[]>([]);const [risk,setRisk]=useState<ChangeRiskAssessment>();const [report,setReport]=useState<ChangeReportSummary>();const [audit,setAudit]=useState<Record<string,unknown>[]>([]);
  const [role,setRole]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);const admin=["admin","superadmin"].includes(role),contributor=admin||role==="technician";
  const load=async()=>{try{
    if(mode==="dashboard")setDashboard(await endpoints.changeDashboard());
    if(mode==="requests"&&!selectedId)setChanges((await endpoints.changeRequests({page_size:100})).items);
    if(mode==="requests"&&selectedId){const row=await endpoints.changeRequest(selectedId);setSelected(row);const [a,t,e]=await Promise.all([endpoints.changeApprovals(selectedId),endpoints.changeTasks(selectedId),endpoints.changeExecutions(selectedId)]);setApprovals(a.items);setTasks(t.items);setExecutions(e.items)}
    if(mode==="new")setTypes((await endpoints.changeTypes()).items);
    if(mode==="approvals")setApprovals((await endpoints.changeApprovalQueue()).items);
    if(mode==="cab")setMeetings((await endpoints.cabMeetings()).items);
    if(mode==="risk"||mode==="timeline")setChanges((await endpoints.changeRequests({page_size:100})).items);
    if(mode==="maintenance")setWindows((await endpoints.maintenanceWindows()).items);
    if(mode==="execution")setChanges((await endpoints.changeRequests({status:"scheduled",page_size:100})).items);
    if(mode==="releases")setReleases((await endpoints.enterpriseReleases()).items);
    if(mode==="reports")setReport(await endpoints.changeReportSummary());
    if(mode==="audit")setAudit((await endpoints.changeAuditHistory()).items);
    setError("");
  }catch(e){setError(e instanceof Error?e.message:"Unable to load change management")}};
  useEffect(()=>{void endpoints.me().then(u=>setRole(u.role)).catch(()=>setRole(""))},[]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer);// eslint-disable-next-line react-hooks/exhaustive-deps
  },[mode,selectedId]);
  const mutate=async(fn:()=>Promise<unknown>)=>{setBusy(true);try{await fn();await load();setError("")}catch(e){setError(e instanceof Error?e.message:"Change operation failed")}finally{setBusy(false)}};
  const createRFC=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const f=new FormData(event.currentTarget);const row=await endpoints.createChangeRequest({property_id:propertyId(),type_id:String(f.get("type_id")),title:String(f.get("title")),description:String(f.get("description")),business_justification:String(f.get("business")),technical_justification:String(f.get("technical")),impact_level:String(f.get("impact")),priority:String(f.get("priority")),backout_plan:String(f.get("backout")),validation_plan:String(f.get("validation")),test_plan:String(f.get("test")),communication_plan:String(f.get("communication")),implementation_plan:String(f.get("implementation")),scheduled_start:iso(f.get("start")),scheduled_end:iso(f.get("end"))});navigate(`/changes/requests/${row.id}`)};
  const createWindow=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const f=new FormData(event.currentTarget);await mutate(()=>endpoints.createMaintenanceWindow({property_id:propertyId(),name:String(f.get("name")),window_type:String(f.get("type")),start_at:iso(f.get("start")),end_at:iso(f.get("end")),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,blackout:f.get("blackout")==="on",emergency:f.get("emergency")==="on"}));event.currentTarget.reset()};
  const createMeeting=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const f=new FormData(event.currentTarget);await mutate(()=>endpoints.createCABMeeting({property_id:propertyId(),title:String(f.get("title")),meeting_type:String(f.get("type")),scheduled_start:iso(f.get("start")),scheduled_end:iso(f.get("end")),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,quorum_required:Number(f.get("quorum"))}));event.currentTarget.reset()};
  const createRelease=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const f=new FormData(event.currentTarget);await mutate(()=>endpoints.createEnterpriseRelease({property_id:propertyId(),name:String(f.get("name")),release_type:String(f.get("type")),description:String(f.get("description")),release_notes:String(f.get("notes")||""),rollback_plan:String(f.get("rollback")),planned_start:iso(f.get("start")),planned_end:iso(f.get("end"))}));event.currentTarget.reset()};
  const scoreRisk=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const f=new FormData(event.currentTarget),id=String(f.get("change"));const names=["guest_impact","revenue_impact","operational_impact","security_impact","compliance_impact","downtime","rollback_complexity","service_dependencies","vendor_dependency","maintenance_duration"];setRisk(await endpoints.changeRisk(id,{factors:Object.fromEntries(names.map(n=>[n,Number(f.get(n))])),rationale:String(f.get("rationale"))}))};
  const openExecution=async(run:ChangeExecution)=>{setExecutions([run]);setExecutionTasks((await endpoints.changeExecutionTasks(run.id)).items)};
  const exportReport=async(format:"csv"|"xlsx"|"pdf")=>{const out=await endpoints.exportChangeReport(format),url=URL.createObjectURL(out.blob),a=document.createElement("a");a.href=url;a.download=out.filename;a.click();URL.revokeObjectURL(url)};
  return <DashboardLayout onLiveEvent={event=>{if((event.type??event.event)?.startsWith("change_"))void load()}}>
    <header className="page-title"><div><span className="eyebrow">ITIL-aligned deterministic control</span><h1>Enterprise Change Management</h1><p>Plan, review, schedule, execute, verify, and audit hospitality infrastructure changes without autonomous production actions.</p></div></header>
    <nav className="change-tabs" aria-label="Change management sections">{modes.map(([label,path])=><button key={path} className={location.pathname===path?"active":""} onClick={()=>navigate(path)}>{label}</button>)}</nav>
    {error&&<Feedback error={error}/>}
    {mode==="dashboard"&&<><section className="stats-grid"><StatCard label="Open changes" value={dashboard?.open_changes??0} detail="Active RFC lifecycle" icon="settings"/><StatCard label="Pending approvals" value={dashboard?.pending_approvals??0} detail="Human decision required" icon="tickets"/><StatCard label="High risk" value={dashboard?.high_risk??0} detail="High or critical" icon="alerts"/><StatCard label="Success rate" value={`${dashboard?.success_rate??0}%`} detail="Closed vs failed" icon="dashboard"/></section><Panel title="Recently updated RFCs" copy="Current records from the authorized property scope."><ChangeCards rows={dashboard?.recent??[]} open={id=>navigate(`/changes/requests/${id}`)}/></Panel></>}
    {mode==="requests"&&!selectedId&&<Panel title="Change requests" copy="Searchable RFC register with explicit state, risk, priority, and ownership."><ChangeCards rows={changes} open={id=>navigate(`/changes/requests/${id}`)}/></Panel>}
    {mode==="new"&&<Panel title="RFC builder" copy="Every plan is required before review. Saving does not approve, schedule, or execute the change.">{contributor?<form className="change-form" onSubmit={createRFC}><label>Change type<select name="type_id" required>{types.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Title<input name="title" required/></label><label>Impact<select name="impact"><option>low</option><option>medium</option><option>high</option><option>critical</option></select></label><label>Priority<select name="priority"><option>normal</option><option>high</option><option>urgent</option><option>emergency</option></select></label>{[["description","Description"],["business","Business justification"],["technical","Technical justification"],["implementation","Implementation plan"],["test","Test plan"],["validation","Validation plan"],["communication","Communication plan"],["backout","Backout plan"]].map(([name,label])=><label className="change-wide" key={name}>{label}<textarea name={name} required/></label>)}<label>Proposed start<input type="datetime-local" name="start"/></label><label>Proposed end<input type="datetime-local" name="end"/></label><button disabled={busy}>Create draft RFC</button></form>:<Feedback error="Contributor permission is required to create an RFC."/>}</Panel>}
    {mode==="requests"&&selected&&<RFCDetail row={selected} approvals={approvals} tasks={tasks} executions={executions} admin={admin} contributor={contributor} action={a=>void mutate(()=>endpoints.changeAction(selected.id,a))} decide={(id,decision)=>void mutate(()=>endpoints.decideChangeApproval(selected.id,id,{decision,comments:`${decision} through reviewed change workspace`}))} start={()=>void mutate(()=>endpoints.startChangeExecution(selected.id))} openExecution={openExecution}/>}
    {mode==="approvals"&&<Panel title="Approval queue" copy="Requester separation and backend authorization are always enforced."><Cards rows={approvals} title={r=>`${r.stage} approval`} detail={r=>`${r.status} · ${new Date(r.requested_at).toLocaleString()}`}/></Panel>}
    {mode==="cab"&&<><Panel title="CAB workspace" copy="Meetings, attendance, quorum, agenda, votes, conditions, deferrals, and decisions.">{admin&&<form className="change-form" onSubmit={createMeeting}><label>Meeting title<input name="title" required/></label><label>Type<select name="type"><option>regular</option><option>emergency</option><option>virtual</option></select></label><label>Start<input type="datetime-local" name="start" required/></label><label>End<input type="datetime-local" name="end" required/></label><label>Quorum<input type="number" min="1" max="100" name="quorum" defaultValue="2"/></label><button>Schedule CAB</button></form>}<Cards rows={meetings} title={r=>r.title} detail={r=>`${r.status} · quorum ${r.quorum_required} · ${new Date(r.scheduled_start).toLocaleString()}`}/></Panel></>}
    {mode==="risk"&&<Panel title="Structured risk assessment" copy="Ten bounded factors produce an explainable low, medium, high, or critical score.">{contributor&&<form className="change-form" onSubmit={scoreRisk}><label>RFC<select name="change">{changes.map(c=><option key={c.id} value={c.id}>{c.change_id} · {c.title}</option>)}</select></label>{["guest_impact","revenue_impact","operational_impact","security_impact","compliance_impact","downtime","rollback_complexity","service_dependencies","vendor_dependency","maintenance_duration"].map(name=><label key={name}>{name.replaceAll("_"," ")}<input name={name} type="number" min="0" max="5" defaultValue="0" required/></label>)}<label className="change-wide">Rationale<textarea name="rationale" required/></label><button>Calculate and record</button></form>}{risk&&<div className="change-result"><strong>{risk.total_score} · {risk.risk_level}</strong><span>{risk.rationale}</span></div>}</Panel>}
    {mode==="maintenance"&&<Panel title="Maintenance calendar" copy="Property/corporate, emergency, recurring, blackout, timezone, approval, and overlap controls.">{admin&&<form className="change-form" onSubmit={createWindow}><label>Name<input name="name" required/></label><label>Type<select name="type"><option>standard</option><option>corporate</option><option>recurring</option><option>emergency</option><option>blackout</option></select></label><label>Start<input type="datetime-local" name="start" required/></label><label>End<input type="datetime-local" name="end" required/></label><label><input type="checkbox" name="blackout"/> Blackout</label><label><input type="checkbox" name="emergency"/> Emergency</label><button>Create window</button></form>}<Cards rows={windows} title={r=>r.name} detail={r=>`${r.window_type} · ${r.status} · ${new Date(r.start_at).toLocaleString()}`} actions={r=>admin&&r.status==="draft"?<button onClick={()=>void mutate(()=>endpoints.approveMaintenanceWindow(r.id))}>Approve</button>:undefined}/></Panel>}
    {mode==="execution"&&<><Panel title="Execution console" copy="Only approved and scheduled RFCs may enter reviewed manual execution."><ChangeCards rows={changes} open={id=>navigate(`/changes/requests/${id}`)}/></Panel>{executions[0]&&<Panel title="Execution tasks" copy={`${executions[0].progress_percent}% complete · ${executions[0].status}`}><Cards rows={executionTasks} title={r=>r.title} detail={r=>r.status} actions={r=>r.status==="ready"?<button onClick={()=>void mutate(()=>endpoints.completeChangeExecutionTask(executions[0].id,r.id,"Completed with operator verification"))}>Complete checkpoint</button>:undefined}/></Panel>}</>}
    {mode==="releases"&&<Panel title="Release manager" copy="Major, minor, patch, emergency, packages, versions, waves, verification, notes, and rollback.">{contributor&&<form className="change-form" onSubmit={createRelease}><label>Name<input name="name" required/></label><label>Type<select name="type"><option>major</option><option>minor</option><option>patch</option><option>emergency</option></select></label><label className="change-wide">Description<textarea name="description" required/></label><label className="change-wide">Release notes<textarea name="notes"/></label><label className="change-wide">Rollback plan<textarea name="rollback" required/></label><label>Start<input type="datetime-local" name="start"/></label><label>End<input type="datetime-local" name="end"/></label><button>Create release</button></form>}<Cards rows={releases} title={r=>`${r.release_id} · ${r.name}`} detail={r=>`${r.release_type} · ${r.status}`}/></Panel>}
    {mode==="timeline"&&<Panel title="Change timeline" copy="RFC revisions, approvals, execution logs, rollback, communication, and audit remain timestamped."><ChangeCards rows={changes} open={id=>navigate(`/changes/requests/${id}`)}/></Panel>}
    {mode==="reports"&&<Panel title="Change reports" copy="Success, failures, emergency trends, CAB, approvals, rollback, maintenance, property, and executive summaries."><section className="stats-grid"><StatCard label="Total RFCs" value={report?.total??0} detail="Authorized scope" icon="settings"/><StatCard label="Success" value={`${report?.success_rate??0}%`} detail="Closed vs failed" icon="dashboard"/><StatCard label="Failed" value={report?.failed??0} detail="Requires review" icon="alerts"/><StatCard label="Rollbacks" value={report?.rollbacks??0} detail="Recorded executions" icon="audit"/></section><div className="page-actions"><button onClick={()=>void exportReport("csv")}>CSV</button><button onClick={()=>void exportReport("xlsx")}>Excel</button><button onClick={()=>void exportReport("pdf")}>PDF</button></div></Panel>}
    {mode==="audit"&&<Panel title="Change audit viewer" copy="Privileged decisions and lifecycle mutations with safe metadata."><Cards rows={audit.map((r,i)=>({id:String(r.id??i),title:String(r.action??"Change event"),detail:`${String(r.actor??"")} · ${String(r.created_at??"")}`}))} title={r=>r.title} detail={r=>r.detail}/></Panel>}
  </DashboardLayout>
}

function Panel({title,copy,children}:{title:string;copy:string;children:React.ReactNode}){return <section className="hospitality-panel"><div className="panel-heading"><div><h2>{title}</h2><span>{copy}</span></div></div>{children}</section>}
function Cards<T extends {id:string}>({rows,title,detail,actions}:{rows:T[];title:(r:T)=>string;detail:(r:T)=>string;actions?:(r:T)=>React.ReactNode}){return !rows.length?<Feedback empty="No records in the current scope."/>:<div className="hospitality-grid">{rows.map(r=><article className="hospitality-card" key={r.id}><strong>{title(r)}</strong><span>{detail(r)}</span>{actions?.(r)}</article>)}</div>}
function ChangeCards({rows,open}:{rows:ChangeRequest[];open:(id:string)=>void}){return <Cards rows={rows} title={r=>`${r.change_id} · ${r.title}`} detail={r=>`${r.status} · ${r.risk_level} risk · ${r.priority}`} actions={r=><button onClick={()=>open(r.id)}>Open RFC</button>}/>}
function RFCDetail({row,approvals,tasks,executions,admin,contributor,action,decide,start,openExecution}:{row:ChangeRequest;approvals:ChangeApproval[];tasks:ChangeTask[];executions:ChangeExecution[];admin:boolean;contributor:boolean;action:(a:string)=>void;decide:(id:string,d:string)=>void;start:()=>void;openExecution:(e:ChangeExecution)=>void}){const next:{[key:string]:string}={draft:"submit",submitted:"technical-review",technical_review:"cab-review",approved:"schedule",implemented:"verify",verified:"close"};return <><Panel title={`${row.change_id} · ${row.title}`} copy={`${row.status} · ${row.risk_level} risk · ${row.approval_status}`}><div className="change-plan-grid"><Detail label="Business justification" value={row.business_justification}/><Detail label="Technical justification" value={row.technical_justification}/><Detail label="Implementation" value={row.implementation_plan}/><Detail label="Test" value={row.test_plan}/><Detail label="Validation" value={row.validation_plan}/><Detail label="Communication" value={row.communication_plan}/><Detail label="Backout" value={row.backout_plan}/></div><div className="page-actions">{contributor&&next[row.status]&&<button onClick={()=>action(next[row.status])}>{next[row.status].replaceAll("-"," ")}</button>}{contributor&&row.status==="scheduled"&&<button onClick={start}>Start controlled execution</button>}{admin&&!['closed','cancelled'].includes(row.status)&&<button className="danger-action" onClick={()=>action("cancel")}>Cancel RFC</button>}</div></Panel><div className="change-two"><Panel title="Approvals" copy="Separation of duties is backend enforced."><Cards rows={approvals} title={r=>r.stage} detail={r=>r.status} actions={r=>admin&&r.status==="pending"?<><button onClick={()=>decide(r.id,"approved")}>Approve</button><button onClick={()=>decide(r.id,"rejected")}>Reject</button></>:undefined}/></Panel><Panel title="Implementation tasks" copy="Ordered checkpoints are immutable after submission."><Cards rows={tasks} title={r=>`${r.sequence_order+1}. ${r.title}`} detail={r=>`${r.status}${r.evidence_required?" · evidence required":""}`}/></Panel></div><Panel title="Execution history" copy="Manual progress, evidence, verification, failure, and rollback."><Cards rows={executions} title={r=>r.status} detail={r=>`${r.progress_percent}% · ${r.verification_status}`} actions={r=><button onClick={()=>openExecution(r)}>Open console</button>}/></Panel></>}
function Detail({label,value}:{label:string;value:string|null}){return <div><small>{label}</small><p>{value||"Not provided"}</p></div>}
