import { useDeferredValue, useMemo, useState, type FormEvent, type ReactNode } from "react";
import { Link, useLocation, useNavigate, useParams } from "react-router-dom";
import { Feedback } from "../components/Feedback";
import { StatCard } from "../components/StatCard";
import { StatusBadge } from "../components/StatusBadge";
import { useRequest } from "../hooks/useRequest";
import DashboardLayout from "../layouts/DashboardLayout";
import { endpoints } from "../lib/api";
import { PageTitle } from "./DashboardPage";

const statuses=["draft","submitted","under_review","approved","scheduled","in_progress","completed","failed","rolled_back","cancelled","closed"];
const levels=["low","medium","high","critical"],types=["standard","normal","emergency"];
const title=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,x=>x.toUpperCase());
function MaintainLinks(){return <nav className="page-actions" aria-label="Maintain workspaces"><Link className="secondary-action" to="/incidents">Incidents</Link><Link className="secondary-action" to="/problems">Problems</Link><Link className="secondary-action" to="/problems?status=known_error">Known Errors</Link><Link className="secondary-action" to="/changes">Changes</Link><Link className="secondary-action" to="/knowledge">Knowledge</Link><Link className="secondary-action" to="/incidents/services">Services</Link></nav>}
export default function ChangesPage(){const {id}=useParams(),location=useLocation();return location.pathname==="/changes/new"?<ChangeForm/>:id?<ChangeDetail id={id}/>:<ChangeList/>}

function ChangeList(){
 const request=useRequest(()=>endpoints.governanceChanges(),[]),summary=useRequest(endpoints.governanceChangeSummary,[]),me=useRequest(endpoints.me,[]),[search,setSearch]=useState(""),[status,setStatus]=useState("all"),[risk,setRisk]=useState("all"),query=useDeferredValue(search).toLowerCase();
 const rows=useMemo(()=>(request.data??[]).filter(row=>(!query||[row.change_id,row.title,row.description,row.reason].some(x=>x?.toLowerCase().includes(query)))&&(status==="all"||row.status===status)&&(risk==="all"||row.risk===risk)),[request.data,query,status,risk]);
 return <DashboardLayout><MaintainLinks/><PageTitle eyebrow="Maintain · changes" title="Change management" copy="Plan, authorize and record operational changes. HIOP never executes infrastructure changes." action={me.data?.role==="admin"?<Link className="primary-action" to="/changes/new">Create Change</Link>:undefined}/>
 {summary.data&&<section className="stats-grid"><StatCard label="Under review" value={summary.data.under_review??0} detail={`${summary.data.high_risk??0} high risk`} icon="audit"/><StatCard label="Scheduled" value={summary.data.scheduled??0} detail={`${summary.data.upcoming??0} upcoming`} icon="check"/><StatCard label="In progress" value={summary.data.in_progress??0} detail="Execution recorded only" icon="network"/><StatCard label="Emergency" value={summary.data.emergency??0} detail="Urgent governance" icon="alerts"/></section>}
 <section className="toolbar-panel"><input aria-label="Search changes" placeholder="Change ID, title, reason or asset" value={search} onChange={e=>setSearch(e.target.value)}/><div className="filter-row"><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option>{statuses.map(x=><option key={x} value={x}>{title(x)}</option>)}</select><select value={risk} onChange={e=>setRisk(e.target.value)}><option value="all">All risk levels</option>{levels.map(x=><option key={x}>{x}</option>)}</select></div></section>
 {request.loading||request.error?<Feedback loading={request.loading} error={request.error}/>:!rows.length?<Feedback emptyTitle="No changes yet." empty="Create a change to govern planned operational work."/>:<section className="data-panel"><div className="data-table incident-table"><div className="table-row table-head"><span>Change</span><span>Schedule</span><span>Impact</span><span>Risk</span><span>Status</span></div>{rows.map(row=><Link className="table-row" to={`/changes/${row.id}`} key={row.id}><span><strong>{row.change_id}</strong><small>{row.title}</small></span><span>{row.planned_start?new Date(row.planned_start).toLocaleString():"Not scheduled"}<small>{title(row.type)}</small></span><span>{row.related_counts.asset??0} assets<small>{row.related_counts.service??0} services</small></span><span><StatusBadge status={row.risk}/></span><span><StatusBadge status={row.status}/></span></Link>)}</div></section>}</DashboardLayout>
}

function ChangeForm(){
 const nav=useNavigate(),assets=useRequest(()=>endpoints.assets(),[]),services=useRequest(()=>endpoints.technologyServices(),[]),problems=useRequest(()=>endpoints.operationalProblems(),[]),vendors=useRequest(()=>endpoints.operationalVendors(),[]);
 const [form,setForm]=useState({title:"",description:"",change_type:"normal",priority:"medium",risk:"medium",risk_explanation:"",reason:"",implementation_plan:"",validation_plan:"",rollback_plan:"",planned_start:"",planned_end:"",asset_id:"",service_id:"",problem_id:"",vendor_id:""}),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError("");try{const row=await endpoints.createGovernanceChange({...form,planned_start:form.planned_start?new Date(form.planned_start).toISOString():null,planned_end:form.planned_end?new Date(form.planned_end).toISOString():null,asset_id:form.asset_id||null,service_id:form.service_id||null,problem_id:form.problem_id||null,vendor_id:form.vendor_id||null});nav(`/changes/${row.id}`)}catch(x){setError(x instanceof Error?x.message:"Change could not be created")}finally{setBusy(false)}};
 return <DashboardLayout><MaintainLinks/><PageTitle eyebrow="Maintain · changes" title="Create change" copy="Document the plan, risk, impact and rollback before work starts."/>{error&&<Feedback error={error}/>}<form className="panel enterprise-form" onSubmit={e=>void submit(e)}><div className="form-grid"><Field label="Title"><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></Field><Field label="Type"><select value={form.change_type} onChange={e=>setForm({...form,change_type:e.target.value})}>{types.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Priority"><select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}>{levels.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Risk"><select value={form.risk} onChange={e=>setForm({...form,risk:e.target.value})}>{levels.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Planned start"><input type="datetime-local" value={form.planned_start} onChange={e=>setForm({...form,planned_start:e.target.value})}/></Field><Field label="Planned end"><input type="datetime-local" value={form.planned_end} onChange={e=>setForm({...form,planned_end:e.target.value})}/></Field><Select label="Asset" value={form.asset_id} set={x=>setForm({...form,asset_id:x})} options={assets.data?.map(x=>({id:x.id,name:`${x.asset_number} · ${x.name}`}))??[]}/><Select label="Service" value={form.service_id} set={x=>setForm({...form,service_id:x})} options={services.data?.map(x=>({id:x.id,name:x.name}))??[]}/><Select label="Problem" value={form.problem_id} set={x=>setForm({...form,problem_id:x})} options={problems.data?.map(x=>({id:x.id,name:`${x.problem_number} · ${x.title}`}))??[]}/><Select label="Vendor" value={form.vendor_id} set={x=>setForm({...form,vendor_id:x})} options={vendors.data?.map(x=>({id:x.id,name:x.name}))??[]}/></div>{[["description","Description"],["reason","Reason"],["risk_explanation","Risk explanation"],["implementation_plan","Implementation plan"],["validation_plan","Validation plan"],["rollback_plan","Rollback plan"]].map(([key,label])=><Field key={key} label={label}><textarea required={key!=="description"&&(key!=="rollback_plan"||["high","critical"].includes(form.risk))} value={form[key as keyof typeof form]} onChange={e=>setForm({...form,[key]:e.target.value})}/></Field>)}<div className="row-actions"><Link className="secondary-action" to="/changes">Cancel</Link><button className="primary-action" disabled={busy}>{busy?"Creating…":"Create Draft"}</button></div></form></DashboardLayout>
}

function ChangeDetail({id}:{id:string}){
 const request=useRequest(()=>endpoints.governanceChange(id),[id]),knowledge=useRequest(()=>endpoints.linkedPracticalKnowledge("change",id),[id]),me=useRequest(endpoints.me,[]),[note,setNote]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const run=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError("");try{await fn();await request.reload()}catch(x){setError(x instanceof Error?x.message:"Action failed")}finally{setBusy(false)}};
 if(request.loading||request.error||!request.data)return <DashboardLayout><Feedback loading={request.loading} error={request.error}/></DashboardLayout>;
 const row=request.data,admin=me.data?.role==="admin",canNote=me.data?.role!=="viewer";
 const perform=(action:string)=>{const body:Record<string,unknown>={};if(action==="schedule"){body.planned_start=row.planned_start;body.planned_end=row.planned_end}if(action==="complete")body.validation=window.prompt("Validation outcome")||"";if(action==="rollback")body.rollback_reason=window.prompt("Rollback reason")||"";if(action==="close")body.closure_notes=window.prompt("Closure notes")||"";void run(()=>endpoints.governanceChangeAction(id,action,body))};
 const next:Record<string,string[]>={draft:["submit","cancel"],submitted:["review","cancel"],under_review:["approve","cancel"],approved:["schedule","cancel"],scheduled:["start","cancel"],in_progress:["complete","fail","rollback"],completed:["close"],failed:["close"],rolled_back:["close"],cancelled:["close"]};
 return <DashboardLayout><MaintainLinks/><PageTitle eyebrow={row.change_id} title={row.title} copy={`${title(row.type)} · created ${new Date(row.created_at).toLocaleString()}`} action={<Link className="secondary-action" to="/changes">Back to Changes</Link>}/>{error&&<Feedback error={error}/>}<section className="incident-detail-grid"><article className="panel"><header className="section-head"><div><h2>Governance record</h2><p>{row.description||"No description supplied."}</p></div><StatusBadge status={row.status}/></header><dl className="detail-grid"><D l="Priority" v={title(row.priority)}/><D l="Risk" v={title(row.risk)}/><D l="Requested by" v={row.requested_by}/><D l="Owner" v={row.owner_id}/><D l="Approver" v={row.approver_id}/><D l="Outcome" v={row.outcome?title(row.outcome):null}/><D l="Planned start" v={row.planned_start?new Date(row.planned_start).toLocaleString():null}/><D l="Planned end" v={row.planned_end?new Date(row.planned_end).toLocaleString():null}/></dl>{admin&&<div className="incident-actions">{(next[row.status]??[]).map(action=><button key={action} disabled={busy} onClick={()=>perform(action)}>{title(action)}</button>)}</div>}</article><article className="panel"><h2>Schedule context</h2><p>{row.maintenance_window?`Within maintenance window: ${row.maintenance_window.name}`:"No matching approved maintenance window."}</p>{row.conflicts.length?<div className="alert-card"><strong>Potential scheduling conflict</strong>{row.conflicts.map(x=><Link key={x.id} to={`/changes/${x.id}`}>{x.change_id} · {x.title}</Link>)}</div>:<p>No overlapping scheduled changes detected.</p>}</article></section>
 <section className="panel problem-fields"><h2>Plan and validation</h2>{[["Reason",row.reason],["Risk explanation",row.risk_explanation],["Implementation plan",row.implementation_plan],["Validation plan",row.validation_plan],["Rollback plan",row.rollback_plan],["Validation outcome",row.validation_outcome],["Closure notes",row.closure_notes]].map(([label,value])=><article key={label}><div><strong>{label}</strong><p>{value||"Not documented"}</p></div></article>)}</section>
 <section className="incident-detail-grid"><article className="panel"><h2>Affected context</h2><dl className="detail-grid"><D l="Assets" v={String(row.related_counts.asset??0)}/><D l="Services" v={String(row.related_counts.service??0)}/><D l="Problems" v={String(row.related_counts.problem??0)}/><D l="Incidents" v={String(row.related_counts.incident??0)}/><D l="Vendors" v={String(row.related_counts.vendor??0)}/><D l="Locations" v={String(row.related_counts.location??0)}/></dl>{row.assets?.map(x=><Link key={x.id} to={`/assets/${x.id}`}>{x.asset_number} · {x.name}</Link>)}{row.problems?.map(x=><Link key={x.id} to={`/problems/${x.id}`}>{x.problem_number} · {x.title}</Link>)}</article><article className="panel"><h2>Potential impact</h2><p>{row.impact?`${row.impact.confirmed_affected} confirmed · ${row.impact.potentially_affected} potentially affected`:"No existing incident impact assessment available."}</p><p className="settings-note">Uses existing impact evidence and never declares potential impact as an outage.</p></article></section>
 <section className="panel"><h2>Related knowledge</h2>{knowledge.data?.length?<div className="linked-list">{knowledge.data.map(x=><Link key={x.id} to={`/knowledge/${x.id}`}><strong>{x.article_id}</strong> {x.title} <StatusBadge status={x.status}/></Link>)}</div>:<Feedback empty="No implementation guidance linked to this change."/>}</section>
 {canNote&&<section className="panel"><h2>Execution note</h2><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Record progress. Do not store secrets."/><button disabled={busy||note.trim().length<2} onClick={()=>void run(async()=>{await endpoints.addGovernanceChangeNote(id,note);setNote("")})}>Add Note</button></section>}<section className="panel"><h2>Change timeline</h2>{row.timeline?.length?<div className="incident-timeline">{row.timeline.map(x=><article key={x.id}><time>{new Date(x.timestamp).toLocaleString()}</time><strong>{title(x.type)}</strong><p>{x.summary}</p><small>{x.author}</small></article>)}</div>:<Feedback empty="No change activity recorded."/>}</section></DashboardLayout>
}
function Field({label,children}:{label:string;children:ReactNode}){return <label>{label}{children}</label>}
function Select({label,value,set,options}:{label:string;value:string;set:(x:string)=>void;options:Array<{id:string;name:string}>}){return <Field label={label}><select value={value} onChange={e=>set(e.target.value)}><option value="">None</option>{options.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field>}
function D({l,v}:{l:string;v:string|null|undefined}){return <div><dt>{l}</dt><dd>{v||"Not available"}</dd></div>}
