import {useEffect,useState,type FormEvent} from "react";
import {useLocation,useNavigate} from "react-router-dom";
import {Feedback} from "../components/Feedback";
import {StatCard} from "../components/StatCard";
import DashboardLayout from "../layouts/DashboardLayout";
import {endpoints} from "../lib/api";
import type {CIAttribute,CIClass,CIDependencyGraph,CIHealth,CIImpact,CIReconciliationCandidate,CIRelationship,CIRelationshipType,CIType,CMDBDashboard,CMDBReport,ConfigurationItem} from "../lib/types";
import "../styles/cmdb.css";

const propertyId=()=>localStorage.getItem("hiop.active_property_id")||null;
const tabs=[["Dashboard","/cmdb"],["CI Explorer","/cmdb/items"],["New CI","/cmdb/new"],["Relationships","/cmdb/relationships"],["Dependency Graph","/cmdb/graph"],["Impact","/cmdb/impact"],["Reconciliation","/cmdb/reconciliation"],["Health","/cmdb/health"],["Attributes","/cmdb/attributes"],["Search","/cmdb/search"],["Reports","/cmdb/reports"]];
const value=(row:CIAttribute)=>row.value_text??row.value_number??String(row.value_boolean??"");

export default function CMDBPage(){
  const location=useLocation(),navigate=useNavigate(),parts=location.pathname.split("/"),mode=parts[2]||"dashboard",selectedId=parts[2]==="items"?parts[3]:undefined;
  const [dashboard,setDashboard]=useState<CMDBDashboard>();const [items,setItems]=useState<ConfigurationItem[]>([]);const [selected,setSelected]=useState<ConfigurationItem>();const [classes,setClasses]=useState<CIClass[]>([]);const [types,setTypes]=useState<CIType[]>([]);const [relationships,setRelationships]=useState<CIRelationship[]>([]);const [relationshipTypes,setRelationshipTypes]=useState<CIRelationshipType[]>([]);const [graph,setGraph]=useState<CIDependencyGraph>();const [impact,setImpact]=useState<CIImpact>();const [candidates,setCandidates]=useState<CIReconciliationCandidate[]>([]);const [health,setHealth]=useState<CIHealth>();const [attributes,setAttributes]=useState<CIAttribute[]>([]);const [report,setReport]=useState<CMDBReport>();const [role,setRole]=useState("");const [search,setSearch]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);
  const admin=["admin","superadmin"].includes(role),contributor=admin||role==="technician";
  const load=async()=>{try{
    if(mode==="dashboard")setDashboard(await endpoints.cmdbDashboard());
    if(["items","relationships","impact","attributes","search"].includes(mode)&&!selectedId)setItems((await endpoints.configurationItems({page_size:100,search:search||undefined})).items);
    if(selectedId){const row=await endpoints.configurationItem(selectedId);setSelected(row);const [attrs,rels]=await Promise.all([endpoints.ciAttributes(selectedId),endpoints.ciRelationships(selectedId)]);setAttributes(attrs.items);setRelationships(rels.items)}
    if(["new","relationships","reconciliation"].includes(mode)){const [c,t,r]=await Promise.all([endpoints.ciClasses(),endpoints.ciTypes(),endpoints.ciRelationshipTypes()]);setClasses(c.items);setTypes(t.items);setRelationshipTypes(r.items)}
    if(mode==="graph")setGraph(await endpoints.cmdbDependencyGraph({property_id:propertyId()||undefined,max_nodes:1000}));
    if(mode==="reconciliation")setCandidates((await endpoints.cmdbCandidates({page_size:100})).items);
    if(mode==="health")setHealth(await endpoints.cmdbHealth(propertyId()||undefined));
    if(mode==="reports")setReport(await endpoints.cmdbReport());setError("");
  }catch(e){setError(e instanceof Error?e.message:"Unable to load CMDB")}};
  useEffect(()=>{void endpoints.me().then(u=>setRole(u.role)).catch(()=>setRole(""))},[]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer);// eslint-disable-next-line react-hooks/exhaustive-deps
  },[mode,selectedId]);
  const mutate=async(fn:()=>Promise<unknown>)=>{setBusy(true);try{await fn();await load();setError("")}catch(e){setError(e instanceof Error?e.message:"CMDB operation failed")}finally{setBusy(false)}};
  const createCI=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const f=new FormData(event.currentTarget),type=types.find(t=>t.id===String(f.get("type_id")));if(!type)return;const row=await endpoints.createConfigurationItem({property_id:propertyId(),type_id:type.id,class_id:type.class_id,name:String(f.get("name")),display_name:String(f.get("display_name")||"")||null,description:String(f.get("description")||"")||null,criticality:String(f.get("criticality")),operational_status:String(f.get("operational_status")),manufacturer:String(f.get("manufacturer")||"")||null,model:String(f.get("model")||"")||null,serial_number:String(f.get("serial_number")||"")||null,discovery_source:"manual"});navigate(`/cmdb/items/${row.id}`)};
  const createRelationship=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const f=new FormData(event.currentTarget);await mutate(()=>endpoints.createCIRelationship(String(f.get("source")),{target_ci_id:String(f.get("target")),relationship_type_id:String(f.get("type")),evidence:String(f.get("evidence")),confidence:Number(f.get("confidence"))}));event.currentTarget.reset()};
  const runImpact=async(id:string)=>setImpact(await endpoints.ciImpact(id));
  const setAttribute=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const f=new FormData(event.currentTarget),id=String(f.get("ci"));await mutate(()=>endpoints.setCIAttribute(id,{name:String(f.get("name")),data_type:"string",value_text:String(f.get("value")),source:"manual",verified:true,reason:String(f.get("reason"))}))};
  const exportReport=async(format:"csv"|"xlsx"|"pdf")=>{const out=await endpoints.exportCMDB(format),url=URL.createObjectURL(out.blob),a=document.createElement("a");a.href=url;a.download=out.filename;a.click();URL.revokeObjectURL(url)};
  return <DashboardLayout onLiveEvent={event=>{if((event.type??event.event)?.startsWith("cmdb_"))void load()}}>
    <header className="page-title"><div><span className="eyebrow">Authoritative, reviewed configuration data</span><h1>Enterprise CMDB</h1><p>Model configuration items, evidence-backed relationships, lifecycle, impact, discovery reconciliation, and data health without automatic assumptions.</p></div></header>
    <nav className="cmdb-tabs" aria-label="CMDB sections">{tabs.map(([label,path])=><button key={path} className={location.pathname===path?"active":""} onClick={()=>navigate(path)}>{label}</button>)}</nav>
    {error&&<Feedback error={error}/>}
    {mode==="dashboard"&&<><section className="stats-grid"><StatCard label="Configuration items" value={dashboard?.total_cis??0} detail="Authorized scope" icon="devices"/><StatCard label="CMDB health" value={dashboard?.health_score??"Not calculated"} detail="Deterministic score" icon="dashboard"/><StatCard label="Relationships" value={dashboard?.relationships??0} detail="Reviewed and active" icon="hierarchy"/><StatCard label="Critical CIs" value={dashboard?.critical_cis??0} detail="Highest criticality" icon="alerts"/><StatCard label="Unverified" value={dashboard?.unverified??0} detail="Review required" icon="audit"/></section><Panel title="Recently updated CIs" copy="No synthetic or dummy records."><CICards rows={dashboard?.recent??[]} open={id=>navigate(`/cmdb/items/${id}`)}/></Panel></>}
    {mode==="items"&&!selectedId&&<Panel title="CI Explorer" copy="Filterable, paginated configuration-item register."><CICards rows={items} open={id=>navigate(`/cmdb/items/${id}`)}/></Panel>}
    {mode==="items"&&selected&&<><Panel title={`${selected.ci_number} · ${selected.display_name||selected.name}`} copy={`${selected.lifecycle_stage} · ${selected.criticality} criticality · ${selected.verification_status}`}><div className="cmdb-detail"><Detail label="Class / type" value={`${selected.class_id} / ${selected.type_id}`}/><Detail label="Operational status" value={selected.operational_status}/><Detail label="Manufacturer / model" value={`${selected.manufacturer||"—"} / ${selected.model||"—"}`}/><Detail label="Serial" value={selected.serial_number||"—"}/><Detail label="Discovery source" value={selected.discovery_source}/><Detail label="Last verified" value={selected.last_verified_at?new Date(selected.last_verified_at).toLocaleString():"Never"}/></div>{contributor&&<div className="page-actions">{({planned:"ordered",ordered:"installed",installed:"operational",operational:"maintenance",maintenance:"operational",retired:"archived"} as Record<string,string>)[selected.lifecycle_stage]&&<button onClick={()=>void mutate(()=>endpoints.transitionConfigurationItem(selected.id,({planned:"ordered",ordered:"installed",installed:"operational",operational:"maintenance",maintenance:"operational",retired:"archived"} as Record<string,string>)[selected.lifecycle_stage],"Reviewed lifecycle transition"))}>Advance lifecycle</button>}<button onClick={()=>navigate("/cmdb/impact")}>Analyze impact</button></div>}</Panel><Panel title="Attributes" copy="Typed current values with server-side history."><AttributeCards rows={attributes}/></Panel><Panel title="Relationships" copy="Reviewed upstream and downstream relationship records."><RelationshipCards rows={relationships}/></Panel></>}
    {mode==="new"&&<Panel title="Create configuration item" copy="Manual creation requires an explicit class and type; no relationships are inferred.">{contributor?<form className="cmdb-form" onSubmit={createCI}><label>CI type<select name="type_id" required>{types.map(t=><option value={t.id} key={t.id}>{classes.find(c=>c.id===t.class_id)?.name} · {t.name}</option>)}</select></label><label>Name<input name="name" required/></label><label>Display name<input name="display_name"/></label><label>Criticality<select name="criticality"><option>low</option><option>medium</option><option>high</option><option>critical</option></select></label><label>Operational status<select name="operational_status"><option>unknown</option><option>online</option><option>offline</option><option>degraded</option><option>maintenance</option></select></label><label>Manufacturer<input name="manufacturer"/></label><label>Model<input name="model"/></label><label>Serial number<input name="serial_number"/></label><label className="cmdb-wide">Description<textarea name="description"/></label><button disabled={busy}>Create reviewed CI</button></form>:<Feedback error="Contributor permission is required."/>}</Panel>}
    {mode==="relationships"&&<><Panel title="Relationship manager" copy="Direction, cardinality, evidence, and confidence are explicit. No relationship is inferred.">{contributor&&<form className="cmdb-form" onSubmit={createRelationship}><label>Source CI<select name="source">{items.map(i=><option value={i.id} key={i.id}>{i.ci_number} · {i.name}</option>)}</select></label><label>Relationship<select name="type">{relationshipTypes.map(t=><option value={t.id} key={t.id}>{t.name} → {t.inverse_name}</option>)}</select></label><label>Target CI<select name="target">{items.map(i=><option value={i.id} key={i.id}>{i.ci_number} · {i.name}</option>)}</select></label><label>Confidence<input type="number" name="confidence" min="0" max="100" defaultValue="100"/></label><label className="cmdb-wide">Evidence<textarea name="evidence" required/></label><button>Create relationship</button></form>}</Panel><Panel title="CI register" copy="Open a CI to inspect its active upstream and downstream relationships."><CICards rows={items} open={id=>navigate(`/cmdb/items/${id}`)}/></Panel></>}
    {mode==="graph"&&<Panel title="Dependency graph" copy="Cycle-safe, bounded graph generated from reviewed relationships only.">{graph?<GraphView graph={graph}/>:<Feedback loading/>}</Panel>}
    {mode==="impact"&&<><Panel title="Impact analysis" copy="Potential impact language reflects deterministic dependency evidence, not guaranteed outage."><label className="cmdb-select">Root CI<select onChange={e=>void runImpact(e.target.value)} defaultValue=""><option value="" disabled>Select a CI</option>{items.map(i=><option value={i.id} key={i.id}>{i.ci_number} · {i.name}</option>)}</select></label></Panel>{impact&&<Panel title={`${impact.risk} impact · ${impact.direct_count} direct · ${impact.indirect_count} indirect`} copy={impact.warning}><div className="cmdb-impact">{impact.potentially_impacted.map(i=><span key={`${i.ci_id}-${i.depth}`}>{items.find(row=>row.id===i.ci_id)?.name||i.ci_id} · depth {i.depth} · {i.relationship}</span>)}</div></Panel>}</>}
    {mode==="reconciliation"&&<><Panel title="Discovery reconciliation" copy="Runs create review candidates only. CIs are never created automatically.">{admin&&<button onClick={()=>void mutate(()=>endpoints.runCMDBReconciliation({property_id:propertyId(),source_types:["device","network_discovery"],limit:500}))}>Refresh candidates</button>}</Panel><Panel title="Review queue" copy="Exact evidence still requires an administrator decision."><CandidateCards rows={candidates} admin={admin} decide={(id,body)=>void mutate(()=>endpoints.decideCMDBCandidate(id,body))} types={types}/></Panel></>}
    {mode==="health"&&<Panel title="CMDB health" copy="Freshness, relationship completeness, discovery coverage, duplicates, orphans, and ownership."><section className="stats-grid"><StatCard label="Health score" value={health?.health_score??"Not calculated"} detail="0–100" icon="dashboard"/><StatCard label="Verified" value={health?.verified_cis??0} detail="Current verification" icon="audit"/><StatCard label="Stale" value={health?.stale_cis??0} detail="Older than policy" icon="alerts"/><StatCard label="Orphans" value={health?.orphan_cis??0} detail="No active relationship" icon="hierarchy"/><StatCard label="Discovery coverage" value={`${health?.discovery_coverage??0}%`} detail="Non-manual sources" icon="discovery"/></section>{admin&&<button onClick={()=>void mutate(()=>endpoints.recalculateCMDBHealth(propertyId()||undefined))}>Recalculate health</button>}</Panel>}
    {mode==="attributes"&&<Panel title="Attribute manager" copy="Typed, validated attributes retain change history.">{contributor&&<form className="cmdb-form" onSubmit={setAttribute}><label>CI<select name="ci">{items.map(i=><option value={i.id} key={i.id}>{i.ci_number} · {i.name}</option>)}</select></label><label>Attribute key<input name="name" pattern="[a-z][a-z0-9_.-]+" required/></label><label>Value<input name="value" required/></label><label className="cmdb-wide">Reason<textarea name="reason" required/></label><button>Save attribute</button></form>}</Panel>}
    {mode==="search"&&<Panel title="CMDB search" copy="Search CI number, name, serial, manufacturer, and model with bounded results."><form className="cmdb-search" onSubmit={e=>{e.preventDefault();void endpoints.configurationItems({search,page_size:100}).then(r=>setItems(r.items))}}><label>Search<input value={search} onChange={e=>setSearch(e.target.value)} /></label><button>Search</button></form><CICards rows={items} open={id=>navigate(`/cmdb/items/${id}`)}/></Panel>}
    {mode==="reports"&&<Panel title="CMDB reports" copy="Coverage, duplicates, orphans, criticality, lifecycle, vendor, relationships, and health foundations."><section className="stats-grid"><StatCard label="Total" value={report?.total??0} detail="CIs" icon="devices"/><StatCard label="Critical" value={report?.critical??0} detail="Critical CIs" icon="alerts"/><StatCard label="Discovered" value={report?.discovered??0} detail="Integrated source" icon="discovery"/><StatCard label="Warranty expired" value={report?.warranty_expired??0} detail="Review required" icon="audit"/></section><div className="page-actions"><button onClick={()=>void exportReport("csv")}>CSV</button><button onClick={()=>void exportReport("xlsx")}>Excel</button><button onClick={()=>void exportReport("pdf")}>PDF</button></div></Panel>}
  </DashboardLayout>
}

function Panel({title,copy,children}:{title:string;copy:string;children:React.ReactNode}){return <section className="hospitality-panel"><div className="panel-heading"><div><h2>{title}</h2><span>{copy}</span></div></div>{children}</section>}
function CICards({rows,open}:{rows:ConfigurationItem[];open:(id:string)=>void}){return !rows.length?<Feedback empty="No configuration items in the current scope."/>:<div className="hospitality-grid">{rows.map(row=><article className="hospitality-card" key={row.id}><strong>{row.ci_number} · {row.display_name||row.name}</strong><span>{row.lifecycle_stage} · {row.criticality} · {row.operational_status}</span><small>{row.manufacturer||"Unknown vendor"} {row.model||""}</small><button onClick={()=>open(row.id)}>Open CI</button></article>)}</div>}
function AttributeCards({rows}:{rows:CIAttribute[]}){return !rows.length?<Feedback empty="No custom attributes."/>:<div className="cmdb-attributes">{rows.map(row=><div key={row.id}><strong>{row.name}</strong><span>{value(row)} {row.unit||""}</span><small>{row.source} · {row.verified?"verified":"unverified"}</small></div>)}</div>}
function RelationshipCards({rows}:{rows:CIRelationship[]}){return !rows.length?<Feedback empty="No active relationships."/>:<div className="cmdb-edge-list">{rows.map(row=><span key={row.id}>{row.source_ci_id} → {row.target_ci_id} · confidence {row.confidence}%</span>)}</div>}
function Detail({label,value}:{label:string;value:string}){return <div><small>{label}</small><strong>{value}</strong></div>}
function GraphView({graph}:{graph:CIDependencyGraph}){const byId=Object.fromEntries(graph.nodes.map(n=>[n.id,n]));return <><div className="cmdb-graph" role="img" aria-label={`${graph.nodes.length} configuration items and ${graph.relationships.length} relationships`}>{graph.nodes.map(n=><article key={n.id} className={`cmdb-node ${n.criticality}`}><strong>{n.display_name||n.name}</strong><small>{n.ci_number} · {n.lifecycle_stage}</small></article>)}</div><div className="cmdb-edge-list" aria-label="Dependency relationships">{graph.relationships.map(r=><span key={r.id}>{byId[r.source_ci_id]?.name||r.source_ci_id} <b>→ {graph.relationship_types[r.relationship_type_id]||"related"} →</b> {byId[r.target_ci_id]?.name||r.target_ci_id}</span>)}</div>{graph.cycles.length>0&&<Feedback error={`${graph.cycles.length} circular dependency path(s) require review.`}/>}</>}
function CandidateCards({rows,admin,decide,types}:{rows:CIReconciliationCandidate[];admin:boolean;decide:(id:string,body:Record<string,unknown>)=>void;types:CIType[]}){const fallback=types[0];return !rows.length?<Feedback empty="No pending reconciliation candidates."/>:<div className="hospitality-grid">{rows.map(row=><article className="hospitality-card" key={row.id}><strong>{row.candidate_name}</strong><span>{row.source_type} · {row.match_level} · score {row.score}</span><small>{row.recommended_action} · administrator review required</small>{admin&&row.status==="pending"&&<div className="page-actions">{row.proposed_ci_id?<button onClick={()=>decide(row.id,{action:"link",notes:"Reviewed exact source linkage"})}>Link reviewed CI</button>:fallback&&<button onClick={()=>decide(row.id,{action:"create",type_id:fallback.id,class_id:fallback.class_id,notes:"Reviewed new CI creation"})}>Create CI</button>}<button onClick={()=>decide(row.id,{action:"reject",notes:"Rejected during reconciliation review"})}>Reject</button></div>}</article>)}</div>}
