import {useEffect,useState,type FormEvent} from "react";
import {useLocation,useNavigate,useParams} from "react-router-dom";
import DashboardLayout from "../layouts/DashboardLayout";
import {Feedback} from "../components/Feedback";
import {StatusBadge} from "../components/StatusBadge";
import {PageTitle} from "./DashboardPage";
import {endpoints} from "../lib/api";
import type {Device,OperationalIncident} from "../lib/types";

const activeProperty=()=>localStorage.getItem("hiop.active_property_id")||"";
const closed=(status:string)=>["resolved","closed","cancelled","duplicate","merged"].includes(status);

export default function IncidentsPage(){
  const {id}=useParams(); const location=useLocation(); const navigate=useNavigate();
  const mode=location.pathname==="/incidents/new"?"new":id?"detail":"list";
  const [items,setItems]=useState<OperationalIncident[]>([]); const [selected,setSelected]=useState<OperationalIncident>();
  const [devices,setDevices]=useState<Device[]>([]); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  const load=async()=>{try{setDevices(await endpoints.devices());if(id)setSelected(await endpoints.incident(id));else if(mode==="list")setItems((await endpoints.incidents({property_id:activeProperty()||undefined,page_size:100})).items);setError("")}catch(e){setError(e instanceof Error?e.message:"Incidents could not be loaded.")}};
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);/* load follows the active route */},[id,mode]); // eslint-disable-line react-hooks/exhaustive-deps
  const create=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const property_id=activeProperty();if(!property_id){setError("Select a property before creating an incident.");return}const data=new FormData(event.currentTarget);setBusy(true);try{const device=String(data.get("device")||"");const row=await endpoints.createIncident({property_id,title:String(data.get("title")),description:String(data.get("description")||""),priority:String(data.get("priority")),severity:String(data.get("severity")),incident_type:"device_failure",source_type:device?"device":null,source_reference_type:device?"device":null,source_reference_id:device||null});navigate(`/incidents/${row.id}`)}catch(e){setError(e instanceof Error?e.message:"Incident could not be created.")}finally{setBusy(false)}};
  const action=async(name:string)=>{if(!selected)return;setBusy(true);try{const row=await endpoints.incidentTransition(selected.id,name,`${name} from the Version 1 incident workspace`);setSelected(row)}catch(e){setError(e instanceof Error?e.message:"Incident could not be updated.")}finally{setBusy(false)}};
  return <DashboardLayout><PageTitle eyebrow="Maintain" title={mode==="new"?"Create incident":selected?.incident_number||"Incidents"} copy="Create, update, resolve, and close operational incidents." action={mode==="list"?<button className="primary-action" onClick={()=>navigate("/incidents/new")}>Create incident</button>:<button className="secondary-action" onClick={()=>navigate("/incidents")}>Back to incidents</button>}/>{error&&<Feedback error={error}/>}
    {mode==="new"&&<section className="panel"><form className="topology-form" onSubmit={create}><label>Title<input name="title" required minLength={3}/></label><label>Description<textarea name="description" rows={5}/></label><label>Priority<select name="priority"><option>P3</option><option>P2</option><option>P1</option><option>P4</option></select></label><label>Severity<select name="severity"><option>medium</option><option>low</option><option>high</option><option>critical</option></select></label><label>Related device<select name="device"><option value="">None</option>{devices.map(device=><option key={device.id} value={device.id}>{device.hostname} — {device.ip_address}</option>)}</select></label><button className="primary-action" disabled={busy}>{busy?"Creating...":"Create incident"}</button></form></section>}
    {mode==="list"&&<section className="panel">{!items.length?<Feedback empty="No incidents have been created."/>:<div className="table-wrap"><table><thead><tr><th>Incident</th><th>Priority</th><th>Status</th><th>Created</th><th/></tr></thead><tbody>{items.map(item=><tr key={item.id}><td><strong>{item.title}</strong><small>{item.incident_number}</small></td><td>{item.priority}</td><td><StatusBadge status={item.status}/></td><td>{new Date(item.created_at).toLocaleString()}</td><td><button onClick={()=>navigate(`/incidents/${item.id}`)}>Open</button></td></tr>)}</tbody></table></div>}</section>}
    {mode==="detail"&&selected&&<><section className="panel"><header className="section-head"><div><h2>{selected.title}</h2><p>{selected.description||"No description supplied."}</p></div><StatusBadge status={selected.status}/></header><dl className="detail-grid"><div><dt>Priority</dt><dd>{selected.priority}</dd></div><div><dt>Severity</dt><dd>{selected.severity}</dd></div><div><dt>Created</dt><dd>{new Date(selected.created_at).toLocaleString()}</dd></div><div><dt>Assigned technician</dt><dd>{selected.incident_commander_id||"Unassigned"}</dd></div></dl><div className="page-actions">{!closed(selected.status)&&<button disabled={busy} onClick={()=>void action("resolve")}>Resolve</button>}{selected.status==="resolved"&&<button className="primary-action" disabled={busy} onClick={()=>void action("close")}>Close</button>}</div></section><section className="panel"><h2>Related troubleshooting context</h2><p>Device, monitoring, discovery, and previous incident history are shown here when the incident has a related device.</p></section></>}
  </DashboardLayout>;
}
