import { useDeferredValue, useMemo, useState, type FormEvent, type ReactNode } from "react";
import { Link, useLocation, useNavigate, useParams } from "react-router-dom";
import { Feedback } from "../components/Feedback";
import { StatCard } from "../components/StatCard";
import { StatusBadge } from "../components/StatusBadge";
import { useRequest } from "../hooks/useRequest";
import DashboardLayout from "../layouts/DashboardLayout";
import { endpoints } from "../lib/api";
import { PageTitle } from "./DashboardPage";

const statuses=["draft","in_review","published","archived"],types=["how_to","troubleshooting","sop","known_issue","recovery_procedure","reference"],categories=["network","pos","pms","wifi","printer","hardware","software","security_system","telephony","server","general_it","other"];
const title=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,x=>x.toUpperCase());
function MaintainLinks(){return <nav className="page-actions" aria-label="Maintain workspaces"><Link className="secondary-action" to="/incidents">Incidents</Link><Link className="secondary-action" to="/problems">Problems</Link><Link className="secondary-action" to="/changes">Changes</Link><Link className="secondary-action" to="/knowledge">Knowledge</Link><Link className="secondary-action" to="/incidents/services">Services</Link></nav>}
export default function KnowledgePage(){const {id}=useParams(),location=useLocation();return location.pathname==="/knowledge/new"?<ArticleForm/>:id?<ArticleDetail id={id}/>:<KnowledgeHome/>}

function KnowledgeHome(){
 const rows=useRequest(()=>endpoints.practicalKnowledgeArticles(),[]),summary=useRequest(endpoints.knowledgeBaseSummary,[]),me=useRequest(endpoints.me,[]),[search,setSearch]=useState(""),[status,setStatus]=useState("all"),[category,setCategory]=useState("all"),[kind,setKind]=useState("all"),query=useDeferredValue(search).toLowerCase();
 const visible=useMemo(()=>(rows.data??[]).filter(x=>(!query||[x.article_id,x.title,x.summary,x.content,x.category,...x.tags].some(v=>v?.toLowerCase().includes(query)))&&(status==="all"||x.status===status)&&(category==="all"||x.category===category)&&(kind==="all"||x.type===kind)),[rows.data,query,status,category,kind]);
 return <DashboardLayout><MaintainLinks/><PageTitle eyebrow="Maintain · knowledge" title="Knowledge base" copy="Search trusted organizational procedures, troubleshooting guidance and known solutions." action={me.data?.role!=="viewer"?<Link className="primary-action" to="/knowledge/new">Create Article</Link>:undefined}/>
 <section className="knowledge-search"><label>Search Knowledge<input autoFocus aria-label="Search knowledge" placeholder="POS not printing, DHCP, switch troubleshooting…" value={search} onChange={e=>setSearch(e.target.value)}/></label></section>{summary.data&&<section className="stats-grid"><StatCard label="Published" value={summary.data.published??0} detail={`${summary.data.total??0} visible articles`} icon="check"/><StatCard label="Draft" value={summary.data.draft??0} detail="Work in progress" icon="audit"/><StatCard label="In review" value={summary.data.in_review??0} detail="Awaiting publication" icon="alerts"/><StatCard label="Review due" value={summary.data.review_due??0} detail="Guidance remains available" icon="network"/></section>}
 <section className="toolbar-panel"><div className="filter-row"><select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">All categories</option>{categories.map(x=><option key={x} value={x}>{title(x)}</option>)}</select><select value={kind} onChange={e=>setKind(e.target.value)}><option value="all">All article types</option>{types.map(x=><option key={x} value={x}>{title(x)}</option>)}</select>{me.data?.role!=="viewer"&&<select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All visible statuses</option>{statuses.map(x=><option key={x} value={x}>{title(x)}</option>)}</select>}</div></section>
 {rows.loading||rows.error?<Feedback loading={rows.loading} error={rows.error}/>:!visible.length?<Feedback emptyTitle="No knowledge articles yet." empty="Authorized users can capture safe, reusable operational guidance."/>:<section className="service-grid">{visible.map(row=><Link className="panel service-card" to={`/knowledge/${row.id}`} key={row.id}><div><strong>{row.title}</strong><StatusBadge status={row.status}/></div><p>{row.summary||"No summary"}</p><small>{row.article_id} · {title(row.type)} · {title(row.category)} · v{row.version}</small><div className="tag-row">{row.tags.map(tag=><span className="tag-chip" key={tag}>{tag}</span>)}</div></Link>)}</section>}</DashboardLayout>
}

function ArticleForm(){
 const nav=useNavigate(),[form,setForm]=useState({title:"",summary:"",content:"",article_type:"troubleshooting",category:"general_it",tags:"",steps:"",warnings:"",review_date:""}),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{const row=await endpoints.createPracticalKnowledgeArticle({...form,tags:form.tags.split(",").map(x=>x.trim()).filter(Boolean),steps:form.steps.split("\n").map(x=>x.replace(/^\d+[.)]\s*/,"").trim()).filter(Boolean),review_date:form.review_date?new Date(form.review_date).toISOString():null});nav(`/knowledge/${row.id}`)}catch(x){setError(x instanceof Error?x.message:"Article could not be created")}finally{setBusy(false)}};
 return <DashboardLayout><MaintainLinks/><PageTitle eyebrow="Maintain · knowledge" title="Create knowledge article" copy="Content is stored and rendered as safe plain text; scripts and credential-like content are rejected."/>{error&&<Feedback error={error}/>}<form className="panel enterprise-form" onSubmit={e=>void submit(e)}><div className="form-grid"><Field label="Title"><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></Field><Field label="Type"><select value={form.article_type} onChange={e=>setForm({...form,article_type:e.target.value})}>{types.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Category"><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{categories.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Review date"><input type="date" value={form.review_date} onChange={e=>setForm({...form,review_date:e.target.value})}/></Field><Field label="Tags (comma separated)"><input placeholder="POS, Printer, DHCP" value={form.tags} onChange={e=>setForm({...form,tags:e.target.value})}/></Field></div><Field label="Summary"><textarea required value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})}/></Field><Field label="Main instructions"><textarea required rows={8} value={form.content} onChange={e=>setForm({...form,content:e.target.value})}/></Field><Field label="Procedure steps (one per line)"><textarea rows={8} placeholder={"Verify device power\nCheck network cable\nConfirm IP address"} value={form.steps} onChange={e=>setForm({...form,steps:e.target.value})}/></Field><Field label="Warnings / notes"><textarea value={form.warnings} onChange={e=>setForm({...form,warnings:e.target.value})}/></Field><div className="row-actions"><Link className="secondary-action" to="/knowledge">Cancel</Link><button className="primary-action" disabled={busy}>{busy?"Saving…":"Save Draft"}</button></div></form></DashboardLayout>
}

function ArticleDetail({id}:{id:string}){
 const row=useRequest(()=>endpoints.practicalKnowledgeArticle(id),[id]),me=useRequest(endpoints.me,[]),assets=useRequest(()=>endpoints.assets(),[]),services=useRequest(()=>endpoints.technologyServices(),[]),problems=useRequest(()=>endpoints.operationalProblems(),[]),changes=useRequest(()=>endpoints.governanceChanges(),[]),[targetType,setTargetType]=useState("asset"),[targetId,setTargetId]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const run=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError("");try{await fn();await row.reload()}catch(x){setError(x instanceof Error?x.message:"Action failed")}finally{setBusy(false)}};
 if(row.loading||row.error||!row.data)return <DashboardLayout><Feedback loading={row.loading} error={row.error}/></DashboardLayout>;const value=row.data,admin=me.data?.role==="admin",canEdit=admin||(me.data?.role==="technician"&&value.author_id===me.data.id);
 const options=targetType==="asset"?assets.data?.map(x=>({id:x.id,name:`${x.asset_number} · ${x.name}`})):targetType==="service"?services.data?.map(x=>({id:x.id,name:x.name})):targetType==="problem"?problems.data?.map(x=>({id:x.id,name:`${x.problem_number} · ${x.title}`})):changes.data?.map(x=>({id:x.id,name:`${x.change_id} · ${x.title}`}));
 const edit=async()=>{const content=window.prompt("Update main instructions",value.content);if(content!==null)await run(()=>endpoints.updatePracticalKnowledgeArticle(id,{content,change_summary:"Instructions updated"}))};
 return <DashboardLayout><MaintainLinks/><PageTitle eyebrow={value.article_id} title={value.title} copy={`${title(value.type)} · ${title(value.category)} · Version ${value.version}`} action={<Link className="secondary-action" to="/knowledge">Back to Knowledge</Link>}/>{error&&<Feedback error={error}/>}<section className="incident-detail-grid"><article className="panel"><header className="section-head"><div><h2>Summary</h2><p>{value.summary}</p></div><StatusBadge status={value.status}/></header><dl className="detail-grid"><D l="Author" v={value.author_id}/><D l="Owner" v={value.owner_id}/><D l="Published" v={value.published_at?new Date(value.published_at).toLocaleDateString():null}/><D l="Next review" v={value.review_date?new Date(value.review_date).toLocaleDateString():null}/><D l="Views" v={String(value.views)}/><D l="Review" v={value.review_due?"Review due":"Current"}/></dl><div className="tag-row">{value.tags.map(x=><span className="tag-chip" key={x}>{x}</span>)}</div></article><article className="panel"><h2>Workflow</h2>{canEdit&&value.status==="draft"&&<button disabled={busy} onClick={()=>void run(()=>endpoints.practicalKnowledgeAction(id,"submit"))}>Submit for Review</button>}{admin&&value.status==="in_review"&&<button disabled={busy} onClick={()=>void run(()=>endpoints.practicalKnowledgeAction(id,"publish"))}>Publish</button>}{admin&&value.status==="published"&&<button disabled={busy} onClick={()=>void run(()=>endpoints.practicalKnowledgeAction(id,"archive"))}>Archive</button>}{admin&&value.status==="archived"&&<button disabled={busy} onClick={()=>void run(()=>endpoints.practicalKnowledgeAction(id,"restore"))}>Restore to Draft</button>}{canEdit&&["draft","in_review"].includes(value.status)&&<button className="secondary-action" onClick={()=>void edit()}>Edit Article</button>}</article></section>
 <article className="panel knowledge-article"><h2>Main instructions</h2><div className="article-copy">{value.content}</div>{value.steps.length>0&&<><h2>Steps</h2><ol>{value.steps.map((step,index)=><li key={`${index}-${step}`}>{step}</li>)}</ol></>}{value.warnings&&<aside className="alert-card"><strong>Warning / note</strong><p>{value.warnings}</p></aside>}</article>
 <section className="incident-detail-grid"><article className="panel"><h2>Related HIOP records</h2><dl className="detail-grid">{Object.entries(value.related_counts).map(([key,count])=><D key={key} l={title(key)} v={String(count)}/>)}</dl>{canEdit&&<div className="inline-editor"><select value={targetType} onChange={e=>{setTargetType(e.target.value);setTargetId("")}}>{["asset","service","problem","change"].map(x=><option key={x}>{x}</option>)}</select><select value={targetId} onChange={e=>setTargetId(e.target.value)}><option value="">Select record</option>{options?.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><button disabled={!targetId} onClick={()=>void run(()=>endpoints.linkPracticalKnowledge(id,targetType,targetId))}>Link</button></div>}</article><article className="panel"><h2>Was this article helpful?</h2><div className="row-actions"><button onClick={()=>void run(()=>endpoints.practicalKnowledgeFeedback(id,true))}>Yes · {value.helpful}</button><button onClick={()=>void run(()=>endpoints.practicalKnowledgeFeedback(id,false))}>No · {value.not_helpful}</button></div></article></section>
 <section className="panel"><h2>Version history</h2>{value.versions?.map(version=><details key={version.id}><summary>Version {version.version} · {new Date(version.created_at).toLocaleString()}</summary><p>{version.change_summary||"No change summary"}</p><div className="article-copy">{version.content}</div></details>)}</section></DashboardLayout>
}
function Field({label,children}:{label:string;children:ReactNode}){return <label>{label}{children}</label>}
function D({l,v}:{l:string;v:string|null|undefined}){return <div><dt>{l}</dt><dd>{v||"Not available"}</dd></div>}
