import { useEffect,useState } from "react";
import DashboardLayout from "../layouts/DashboardLayout";
import { Feedback } from "../components/Feedback";
import { StatCard } from "../components/StatCard";
import { endpoints } from "../lib/api";
type Property = {id:string;name:string;code:string|null;city:string|null;operational_status:string};
type Summary = {overall_status:string;critical_alerts:number;services:number};
export default function OperationsPage(){const [properties,setProperties]=useState<Property[]>([]),[summary,setSummary]=useState<Summary|null>(null),[error,setError]=useState("");useEffect(()=>{void endpoints.properties().then(r=>{setProperties(r.items);if(r.items[0]) return endpoints.operationsSummary(r.items[0].id)}).then(s=>s&&setSummary(s)).catch(e=>setError(e instanceof Error?e.message:"Unable to load operations"))},[]);return <DashboardLayout><header className="page-title"><div><span className="eyebrow">Hospitality operations</span><h1>Property Operations</h1><p>Property health, critical services, and hospitality technology readiness.</p></div></header>{error&&<Feedback error={error}/>}<section className="stats-grid"><StatCard label="Properties" value={properties.length} detail="Authorized sites" icon="hierarchy"/><StatCard label="Status" value={summary?.overall_status??"Unknown"} detail="Operational health" icon="check"/><StatCard label="Critical alerts" value={summary?.critical_alerts??"—"} detail="Property scope" icon="alerts"/><StatCard label="Technology services" value={summary?.services??"—"} detail="Configured services" icon="network"/></section><section className="hospitality-panel"><div className="panel-heading"><div><h2>Hospitality command layer</h2><span>Integrations remain monitoring-only; no PMS, POS, CCTV, or access-control integrations are enabled.</span></div></div>{!properties.length?<Feedback empty="No authorized properties configured."/>:<div className="hospitality-grid">{properties.map(p=><article className="hospitality-card" key={p.id}><strong>{p.name}</strong><span>{p.code||"No code"}</span><small>{p.city||"Location not set"} · {p.operational_status}</small></article>)}</div>}</section></DashboardLayout>}

