import { useEffect, useState, type FormEvent } from "react";
import { Feedback } from "../components/Feedback";
import DashboardLayout from "../layouts/DashboardLayout";
import { endpoints } from "../lib/api";
import type { LocalAgentRegistration, ManagedAsset, OrganizationDepartment, OrganizationLocation, OrganizationProfile, TechnologyService, User } from "../lib/types";
import { PageTitle } from "./DashboardPage";

type Tab="general"|"departments"|"locations"|"assignments"|"agents";
const blankDepartment={name:"",code:"",description:""};
const blankLocation={name:"",code:"",type:"building",parent_id:"",description:""};

export default function OrganizationStructurePage(){
 const [tab,setTab]=useState<Tab>("general"),[profile,setProfile]=useState<OrganizationProfile>(),[departments,setDepartments]=useState<OrganizationDepartment[]>([]),[locations,setLocations]=useState<OrganizationLocation[]>([]),[agents,setAgents]=useState<LocalAgentRegistration[]>([]),[users,setUsers]=useState<User[]>([]),[assets,setAssets]=useState<ManagedAsset[]>([]),[services,setServices]=useState<TechnologyService[]>([]),[assignment,setAssignment]=useState({entity_type:"asset" as "asset"|"user"|"service",entity_id:"",department_id:"",location_key:""}),[department,setDepartment]=useState(blankDepartment),[location,setLocation]=useState(blankLocation),[agent,setAgent]=useState({name:"",version:""}),[error,setError]=useState(""),[notice,setNotice]=useState(""),[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);setError("");try{const [o,d,l,a,u,as,s]=await Promise.all([endpoints.organizationProfile(),endpoints.organizationDepartments(),endpoints.organizationLocations(),endpoints.organizationAgents(),endpoints.users(),endpoints.assets(),endpoints.technologyServices()]);setProfile(o);setDepartments(d);setLocations(l);setAgents(a);setUsers(u);setAssets(as);setServices(s)}catch(e){setError(e instanceof Error?e.message:"Unable to load organization structure")}finally{setLoading(false)}};
 useEffect(()=>{let active=true;Promise.all([endpoints.organizationProfile(),endpoints.organizationDepartments(),endpoints.organizationLocations(),endpoints.organizationAgents(),endpoints.users(),endpoints.assets(),endpoints.technologyServices()]).then(([o,d,l,a,u,as,s])=>{if(active){setProfile(o);setDepartments(d);setLocations(l);setAgents(a);setUsers(u);setAssets(as);setServices(s)}}).catch(e=>{if(active)setError(e instanceof Error?e.message:"Unable to load organization structure")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
 const run=async(action:()=>Promise<unknown>,message:string)=>{setError("");setNotice("");try{await action();setNotice(message);await load()}catch(e){setError(e instanceof Error?e.message:"Unable to save")}};
 const saveProfile=(event:FormEvent)=>{event.preventDefault();if(profile)void run(()=>endpoints.updateOrganizationProfile(profile),"Organization updated.")};
 const addDepartment=(event:FormEvent)=>{event.preventDefault();void run(()=>endpoints.createOrganizationDepartment(department),"Department created.");setDepartment(blankDepartment)};
 const parentOptions=location.type==="floor"?locations.filter(x=>x.type==="building"&&x.is_active):locations.filter(x=>x.type==="floor"&&x.is_active);
 const addLocation=(event:FormEvent)=>{event.preventDefault();void run(()=>endpoints.createOrganizationLocation({...location,parent_id:location.parent_id||null}),"Location created.");setLocation(blankLocation)};
 const addAgent=(event:FormEvent)=>{event.preventDefault();void run(()=>endpoints.registerOrganizationAgent(agent),"Agent identity registered.");setAgent({name:"",version:""})};
 const candidates=assignment.entity_type==="asset"?assets.map(x=>({id:x.id,name:`${x.asset_number} · ${x.name}`})):assignment.entity_type==="user"?users.map(x=>({id:x.id,name:x.username})):services.map(x=>({id:x.id,name:x.name}));
 const saveAssignment=(event:FormEvent)=>{event.preventDefault();const [location_type,location_id]=assignment.location_key.split(":");void run(()=>endpoints.assignOrganizationContext(assignment.entity_type,assignment.entity_id,{department_id:assignment.department_id||null,location_type:location_type||null,location_id:location_id||null}),"Confirmed organization assignment saved.")};
 return <DashboardLayout><PageTitle eyebrow="V4E.5 organization foundation" title="Organization" copy="Manage normal organization structure without source-code changes. All records are isolated to the active organization."/>
  <nav className="settings-nav organization-tabs" aria-label="Organization sections">{(["general","departments","locations","assignments","agents"] as Tab[]).map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x.replace("agents","local agents")}</button>)}</nav>
  {error&&<Feedback error={error}/>} {notice&&<p role="status" className="settings-note">{notice}</p>} {loading&&<Feedback loading/>}
  {!loading&&tab==="general"&&profile&&<section className="settings-panel"><header><div><span>Organization</span><h2>General information</h2><p>Changes apply only to this organization.</p></div></header><form className="settings-panel-body settings-form-grid" onSubmit={saveProfile}>{(["name","code","contact_email","contact_phone","timezone","address","description"] as const).map(key=><label key={key}><span>{key.replaceAll("_"," ")}</span><input value={profile[key]??""} onChange={e=>setProfile({...profile,[key]:e.target.value})}/></label>)}<button className="primary-action" type="submit">Save organization</button></form></section>}
  {!loading&&tab==="departments"&&<section className="organization-grid"><form className="settings-panel settings-panel-body settings-form-grid" onSubmit={addDepartment}><h2>Add department</h2><label><span>Name</span><input required value={department.name} onChange={e=>setDepartment({...department,name:e.target.value})}/></label><label><span>Code</span><input value={department.code} onChange={e=>setDepartment({...department,code:e.target.value})}/></label><label><span>Description</span><input value={department.description} onChange={e=>setDepartment({...department,description:e.target.value})}/></label><button className="primary-action">Add department</button></form><RecordTable rows={departments.map(x=>({id:x.id,name:x.name,detail:x.code||"No code",active:x.is_active,kind:"department"}))} edit={row=>{const current=departments.find(x=>x.id===row.id);const name=window.prompt("Department name",row.name);if(current&&name)void run(()=>endpoints.updateOrganizationDepartment(row.id,{name,code:current.code,description:current.description}),"Department updated.")}} toggle={(row,active)=>run(()=>endpoints.setOrganizationDepartmentStatus(row.id,active),`Department ${active?"activated":"deactivated"}.`)}/></section>}
  {!loading&&tab==="locations"&&<section className="organization-grid"><form className="settings-panel settings-panel-body settings-form-grid" onSubmit={addLocation}><h2>Add location</h2><label><span>Name</span><input required value={location.name} onChange={e=>setLocation({...location,name:e.target.value})}/></label><label><span>Type</span><select value={location.type} onChange={e=>setLocation({...location,type:e.target.value,parent_id:""})}>{["building","floor","room","area","server_room","other"].map(x=><option key={x}>{x}</option>)}</select></label>{location.type!=="building"&&<label><span>Parent</span><select required value={location.parent_id} onChange={e=>setLocation({...location,parent_id:e.target.value})}><option value="">Select parent</option>{parentOptions.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}<label><span>Code</span><input value={location.code} onChange={e=>setLocation({...location,code:e.target.value})}/></label><button className="primary-action">Add location</button></form><RecordTable rows={locations.map(x=>({id:x.id,name:x.name,detail:x.type.replaceAll("_"," "),active:x.is_active,kind:x.kind}))} edit={row=>{const current=locations.find(x=>x.id===row.id);const name=window.prompt("Location name",row.name);if(current&&name)void run(()=>endpoints.updateOrganizationLocation(row.kind,row.id,{name,code:current.code,type:current.type,parent_id:current.parent_id,description:current.description}),"Location updated.")}} toggle={(row,active)=>run(()=>endpoints.setOrganizationLocationStatus(row.kind,row.id,active),`Location ${active?"activated":"deactivated"}.`)}/></section>}
  {!loading&&tab==="assignments"&&<section className="settings-panel"><header><div><span>Confirmed context</span><h2>Assign department and location</h2><p>Manual confirmation remains authoritative over hostname or directory suggestions.</p></div></header><form className="settings-panel-body settings-form-grid" onSubmit={saveAssignment}><label><span>Record type</span><select value={assignment.entity_type} onChange={e=>setAssignment({...assignment,entity_type:e.target.value as typeof assignment.entity_type,entity_id:""})}>{["asset","user","service"].map(x=><option key={x}>{x}</option>)}</select></label><label><span>Record</span><select required value={assignment.entity_id} onChange={e=>setAssignment({...assignment,entity_id:e.target.value})}><option value="">Select record</option>{candidates.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label><span>Department</span><select value={assignment.department_id} onChange={e=>setAssignment({...assignment,department_id:e.target.value})}><option value="">Unknown / unassigned</option>{departments.filter(x=>x.is_active).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label><span>Primary location</span><select value={assignment.location_key} onChange={e=>setAssignment({...assignment,location_key:e.target.value})}><option value="">Unknown / unassigned</option>{locations.filter(x=>x.is_active).map(x=><option key={x.id} value={`${x.type}:${x.id}`}>{x.name} · {x.type}</option>)}</select></label><button className="primary-action">Save confirmed assignment</button></form></section>}
  {!loading&&tab==="agents"&&<section className="organization-grid"><form className="settings-panel settings-panel-body settings-form-grid" onSubmit={addAgent}><h2>Register agent identity</h2><p className="settings-note">Foundation only: registration and heartbeat identity. HIOP does not expose remote commands or auto-updates.</p><label><span>Name</span><input required value={agent.name} onChange={e=>setAgent({...agent,name:e.target.value})}/></label><label><span>Version</span><input value={agent.version} onChange={e=>setAgent({...agent,version:e.target.value})}/></label><button className="primary-action">Register agent</button></form><RecordTable rows={agents.map(x=>({id:x.id,name:x.name,detail:`${x.agent_id} · ${x.version||"Version unknown"}`,active:x.status==="online",kind:"agent"}))}/></section>}
 </DashboardLayout>
}

type Row={id:string;name:string;detail:string;active:boolean;kind:string};
function RecordTable({rows,toggle,edit}:{rows:Row[];toggle?:(row:Row,active:boolean)=>void;edit?:(row:Row)=>void}){return <section className="panel data-panel"><table><thead><tr><th>Name</th><th>Details</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.length?rows.map(row=><tr key={row.id}><td>{row.name}</td><td>{row.detail}</td><td><span className={`status-pill ${row.active?"success":"neutral"}`}>{row.active?"Active":"Inactive / unknown"}</span></td><td><div className="platform-row-actions">{edit&&<button className="secondary-action" onClick={()=>edit(row)}>Edit</button>}{toggle&&<button className="secondary-action" onClick={()=>toggle(row,!row.active)}>{row.active?"Deactivate":"Activate"}</button>}</div></td></tr>):<tr><td colSpan={4}>No records yet.</td></tr>}</tbody></table></section>}
