import { formatDateTime } from "../lib/dateTime";
import { useEffect, useState, type FormEvent } from "react";
import Modal from "../components/Modal";
import { useSearchParams } from "react-router-dom";
import { Feedback } from "../components/Feedback";
import DashboardLayout from "../layouts/DashboardLayout";
import { endpoints } from "../lib/api";
import type { AgentEnrollment, LocalAgentRegistration, ManagedAsset, ManagedProperty, OrganizationDepartment, OrganizationLocation, OrganizationProfile, TechnologyService, User } from "../lib/types";
import { PageTitle } from "./DashboardPage";

type Tab="general"|"departments"|"locations"|"assignments"|"agents";
const blankDepartment={name:"",code:"",description:""};
const blankLocation={name:"",code:"",type:"building",parent_id:"",description:""};

export default function OrganizationStructurePage(){
 const [params]=useSearchParams();
 const [editing,setEditing]=useState<OrganizationDepartment|OrganizationLocation>();
 const [editKind,setEditKind]=useState("department");
 const [editError,setEditError]=useState("");
 const [editBusy,setEditBusy]=useState(false);
 const [tab,setTab]=useState<Tab>(()=>["departments","locations","agents"].includes(params.get("tab")||"")?params.get("tab") as Tab:"general"),[profile,setProfile]=useState<OrganizationProfile>(),[departments,setDepartments]=useState<OrganizationDepartment[]>([]),[locations,setLocations]=useState<OrganizationLocation[]>([]),[agents,setAgents]=useState<LocalAgentRegistration[]>([]),[properties,setProperties]=useState<ManagedProperty[]>([]),[enrollment,setEnrollment]=useState<AgentEnrollment>(),[users,setUsers]=useState<User[]>([]),[assets,setAssets]=useState<ManagedAsset[]>([]),[services,setServices]=useState<TechnologyService[]>([]),[assignment,setAssignment]=useState({entity_type:"asset" as "asset"|"user"|"service",entity_id:"",department_id:"",location_key:""}),[department,setDepartment]=useState(blankDepartment),[location,setLocation]=useState(blankLocation),[agent,setAgent]=useState({name:"",property_id:""}),[error,setError]=useState(""),[notice,setNotice]=useState(""),[loading,setLoading]=useState(true);
 useEffect(()=>{if(!notice)return;const timer=window.setTimeout(()=>setNotice(""),5000);return()=>clearTimeout(timer)},[notice]);
 const load=async()=>{setLoading(true);setError("");try{const [o,d,l,a,u,as,s,p]=await Promise.all([endpoints.organizationProfile(),endpoints.organizationDepartments(),endpoints.organizationLocations(),endpoints.organizationAgents(),endpoints.users(),endpoints.assets(),endpoints.technologyServices(),endpoints.propertyContext()]);setProfile(o);setDepartments(d);setLocations(l);setAgents(a);setUsers(u);setAssets(as);setServices(s);setProperties(p.properties)}catch(e){setError(e instanceof Error?e.message:"Unable to load organization structure")}finally{setLoading(false)}};
 useEffect(()=>{let active=true;Promise.all([endpoints.organizationProfile(),endpoints.organizationDepartments(),endpoints.organizationLocations(),endpoints.organizationAgents(),endpoints.users(),endpoints.assets(),endpoints.technologyServices(),endpoints.propertyContext()]).then(([o,d,l,a,u,as,s,p])=>{if(active){setProfile(o);setDepartments(d);setLocations(l);setAgents(a);setUsers(u);setAssets(as);setServices(s);setProperties(p.properties)}}).catch(e=>{if(active)setError(e instanceof Error?e.message:"Unable to load organization structure")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
 const run=async(action:()=>Promise<unknown>,message:string)=>{setError("");setNotice("");try{await action();window.dispatchEvent(new Event("hiop:organization-updated"));setNotice(message);await load()}catch(e){setError(e instanceof Error?e.message:"Unable to save")}};
 const saveProfile=(event:FormEvent)=>{event.preventDefault();if(profile)void run(()=>endpoints.updateOrganizationProfile(profile),"Organization updated.")};
 const addDepartment=(event:FormEvent)=>{event.preventDefault();void run(()=>endpoints.createOrganizationDepartment(department),"Department created.");setDepartment(blankDepartment)};
 const parentOptions=location.type==="floor"?locations.filter(x=>x.type==="building"&&x.is_active):locations.filter(x=>x.type==="floor"&&x.is_active);
 const addLocation=(event:FormEvent)=>{event.preventDefault();void run(()=>endpoints.createOrganizationLocation({...location,parent_id:location.parent_id||null}),"Location created.");setLocation(blankLocation)};
 const addAgent=async(event:FormEvent)=>{event.preventDefault();setError("");setNotice("");try{const result=await endpoints.createAgentEnrollment({...agent,expires_minutes:15});setEnrollment(result);setNotice("Connection code created. Copy it now; it will not be shown again.");setAgent({name:"",property_id:""});await load()}catch(e){setError(e instanceof Error?e.message:"Unable to create connection code")}};
 const candidates=assignment.entity_type==="asset"?assets.map(x=>({id:x.id,name:`${x.asset_number} · ${x.name}`})):assignment.entity_type==="user"?users.map(x=>({id:x.id,name:x.username})):services.map(x=>({id:x.id,name:x.name}));
 const saveAssignment=(event:FormEvent)=>{event.preventDefault();const [location_type,location_id]=assignment.location_key.split(":");void run(()=>endpoints.assignOrganizationContext(assignment.entity_type,assignment.entity_id,{department_id:assignment.department_id||null,location_type:location_type||null,location_id:location_id||null}),"Confirmed organization assignment saved.")};
 return <DashboardLayout><PageTitle eyebrow="Administration" title="Organization" copy="Manage your organisation, departments, locations, and local agents."/>
  <nav className="settings-nav organization-tabs" aria-label="Organization sections">{(["general","departments","locations","assignments","agents"] as Tab[]).map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x.replace("agents","local agents")}</button>)}</nav>
  {error&&<Feedback error={error}/>} {notice&&<p role="status" className="settings-note">{notice}</p>} {loading&&<Feedback loading/>}
  {!loading&&tab==="general"&&profile&&<section className="settings-panel"><header><div><span>Organization</span><h2>General information</h2><p>Changes apply only to this organization.</p></div></header><form className="settings-panel-body settings-form-grid" onSubmit={saveProfile}>{(["name","code","contact_email","contact_phone","timezone","address","description"] as const).map(key=><label key={key}><span>{key.replaceAll("_"," ")}</span><input value={profile[key]??""} onChange={e=>setProfile({...profile,[key]:e.target.value})}/></label>)}<button className="primary-action" type="submit">Save organization</button></form></section>}
  {!loading&&tab==="departments"&&<section className="organization-grid"><form className="settings-panel settings-panel-body settings-form-grid" onSubmit={addDepartment}><h2>Add department</h2><label><span>Name</span><input required value={department.name} onChange={e=>setDepartment({...department,name:e.target.value})}/></label><label><span>Code</span><input value={department.code} onChange={e=>setDepartment({...department,code:e.target.value})}/></label><label><span>Description</span><input value={department.description} onChange={e=>setDepartment({...department,description:e.target.value})}/></label><button className="primary-action">Add department</button></form><RecordTable rows={departments.map(x=>({id:x.id,name:x.name,detail:x.code||"No code",active:x.is_active,kind:"department"}))} edit={row=>{const current=departments.find(x=>x.id===row.id);if(current){setEditing({...current});setEditKind("department");setEditError("")}}} toggle={(row,active)=>run(()=>endpoints.setOrganizationDepartmentStatus(row.id,active),`Department ${active?"activated":"deactivated"}.`)}/></section>}
  {!loading&&tab==="locations"&&<section className="organization-grid"><form className="settings-panel settings-panel-body settings-form-grid" onSubmit={addLocation}><h2>Add location</h2><label><span>Name</span><input required value={location.name} onChange={e=>setLocation({...location,name:e.target.value})}/></label><label><span>Type</span><select value={location.type} onChange={e=>setLocation({...location,type:e.target.value,parent_id:""})}>{["building","floor","room","area","server_room","other"].map(x=><option key={x}>{x}</option>)}</select></label>{location.type!=="building"&&<label><span>Parent</span><select required value={location.parent_id} onChange={e=>setLocation({...location,parent_id:e.target.value})}><option value="">Select parent</option>{parentOptions.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}<label><span>Code</span><input value={location.code} onChange={e=>setLocation({...location,code:e.target.value})}/></label><button className="primary-action">Add location</button></form><RecordTable rows={locations.map(x=>({id:x.id,name:x.name,detail:x.type.replaceAll("_"," "),active:x.is_active,kind:x.kind}))} edit={row=>{const current=locations.find(x=>x.id===row.id);if(current){setEditing({...current});setEditKind(row.kind);setEditError("")}}} toggle={(row,active)=>run(()=>endpoints.setOrganizationLocationStatus(row.kind,row.id,active),`Location ${active?"activated":"deactivated"}.`)}/></section>}
  {!loading&&tab==="assignments"&&<section className="settings-panel"><header><div><span>Confirmed context</span><h2>Assign department and location</h2><p>Manual confirmation remains authoritative over hostname or directory suggestions.</p></div></header><form className="settings-panel-body settings-form-grid" onSubmit={saveAssignment}><label><span>Record type</span><select value={assignment.entity_type} onChange={e=>setAssignment({...assignment,entity_type:e.target.value as typeof assignment.entity_type,entity_id:""})}>{["asset","user","service"].map(x=><option key={x}>{x}</option>)}</select></label><label><span>Record</span><select required value={assignment.entity_id} onChange={e=>setAssignment({...assignment,entity_id:e.target.value})}><option value="">Select record</option>{candidates.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label><span>Department</span><select value={assignment.department_id} onChange={e=>setAssignment({...assignment,department_id:e.target.value})}><option value="">Unknown / unassigned</option>{departments.filter(x=>x.is_active).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label><span>Primary location</span><select value={assignment.location_key} onChange={e=>setAssignment({...assignment,location_key:e.target.value})}><option value="">Unknown / unassigned</option>{locations.filter(x=>x.is_active).map(x=><option key={x.id} value={`${x.type}:${x.id}`}>{x.name} · {x.type}</option>)}</select></label><button className="primary-action">Save confirmed assignment</button></form></section>}
  {!loading&&tab==="agents"&&<section className="organization-grid"><form className="settings-panel settings-panel-body settings-form-grid" onSubmit={addAgent}><h2>Connect local agent</h2><p className="settings-note">Create a short-lived, one-time connection code for a Windows computer at this property.</p><label><span>Computer name</span><input required value={agent.name} onChange={e=>setAgent({...agent,name:e.target.value})}/></label><label><span>Property</span><select required value={agent.property_id} onChange={e=>setAgent({...agent,property_id:e.target.value})}><option value="">Select property</option>{properties.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><button className="primary-action">Create connection code</button>{enrollment&&<div role="status" className="settings-note"><strong>Connect your local agent</strong><p>Open Connect HIOP.cmd, wait for “Paste your HIOP connection code:”, paste this code, and press Enter.</p><button type="button" className="secondary-action" onClick={()=>void navigator.clipboard.writeText(enrollment.enrollment_token).then(()=>setNotice("Connection code copied.")).catch(()=>setError("Could not copy. Select the code and copy it manually."))}>Copy connection code</button><code style={{display:"block",overflowWrap:"anywhere"}}>{enrollment.enrollment_token}</code><small>Expires {formatDateTime(enrollment.expires_at)}. Use it only until installation completes.</small></div>}</form><section className="panel data-panel"><table><thead><tr><th>Agent</th><th>Property</th><th>Status</th><th>Health</th><th>Action</th></tr></thead><tbody>{agents.length?agents.map(x=><tr key={x.id}><td><strong>{x.name}</strong><small>{x.agent_id} · {x.version||"Version unknown"}</small></td><td>{properties.find(p=>p.id===x.property_id)?.name||"Property"}</td><td><span className={`status-pill ${x.status==="online"?"success":x.status==="stale"?"warning":x.status==="revoked"?"danger":"neutral"}`}>{x.status.replaceAll("_"," ")}</span></td><td><small>Heartbeat: {x.last_heartbeat?formatDateTime(x.last_heartbeat):"Never"}<br/>Queue: {x.pending_queue}/{x.queue_capacity}</small></td><td>{!["revoked","retired"].includes(x.status)&&<button className="secondary-action" onClick={()=>void run(()=>endpoints.revokeOrganizationAgent(x.id),"Agent revoked.")}>Revoke</button>}</td></tr>):<tr><td colSpan={5}>No local agents enrolled yet.</td></tr>}</tbody></table></section></section>}
 {editing&&<Modal title={`Edit ${editKind}`} onClose={()=>{if(!editBusy)setEditing(undefined)}}><form className="settings-form-grid" onSubmit={async e=>{e.preventDefault();setEditBusy(true);setEditError("");try{const body={name:editing.name,code:editing.code,description:editing.description};if(editKind==="department")await endpoints.updateOrganizationDepartment(editing.id,body);else{const place=editing as OrganizationLocation;await endpoints.updateOrganizationLocation(editKind,place.id,{...body,type:place.type,parent_id:place.parent_id})}setEditing(undefined);setNotice("Changes saved.");window.dispatchEvent(new Event("hiop:organization-updated"));await load()}catch(x){setEditError(x instanceof Error?x.message:"Changes could not be saved.")}finally{setEditBusy(false)}}}>
 <label>Name<input required minLength={2} value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></label>
 {editKind!=="floor"&&<label>Code<input value={editing.code||""} onChange={e=>setEditing({...editing,code:e.target.value})}/></label>}
 <label>Description<textarea value={editing.description||""} onChange={e=>setEditing({...editing,description:e.target.value})}/></label>
 {editKind==="room"&&<label>Type<select value={(editing as OrganizationLocation).type} onChange={e=>setEditing({...editing,type:e.target.value} as OrganizationLocation)}>{["room","area","server_room","other"].map(x=><option key={x}>{x}</option>)}</select></label>}
 {["floor","room"].includes(editKind)&&<label>{editKind==="floor"?"Building":"Floor"}<select required value={(editing as OrganizationLocation).parent_id||""} onChange={e=>setEditing({...editing,parent_id:e.target.value} as OrganizationLocation)}><option value="">Choose parent</option>{locations.filter(x=>x.kind===(editKind==="floor"?"building":"floor")).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}
 {editError&&<p role="alert">{editError}</p>}<div className="modal-actions"><button type="button" className="secondary-action" disabled={editBusy} onClick={()=>setEditing(undefined)}>Cancel</button><button className="primary-action" disabled={editBusy}>{editBusy?"Saving…":"Save changes"}</button></div></form></Modal>}
 </DashboardLayout>
}

type Row={id:string;name:string;detail:string;active:boolean;kind:string};
function RecordTable({rows,toggle,edit}:{rows:Row[];toggle?:(row:Row,active:boolean)=>void;edit?:(row:Row)=>void}){return <section className="panel data-panel"><table><thead><tr><th>Name</th><th>Details</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.length?rows.map(row=><tr key={row.id}><td>{row.name}</td><td>{row.detail}</td><td><span className={`status-pill ${row.active?"success":"neutral"}`}>{row.active?"Active":"Inactive / unknown"}</span></td><td><div className="platform-row-actions">{edit&&<button className="secondary-action" onClick={()=>edit(row)}>Edit</button>}{toggle&&<button className="secondary-action" onClick={()=>toggle(row,!row.active)}>{row.active?"Deactivate":"Activate"}</button>}</div></td></tr>):<tr><td colSpan={4}>No records yet.</td></tr>}</tbody></table></section>}
