import {useEffect,useState,type FormEvent} from "react";
import {useLocation,useNavigate} from "react-router-dom";
import DashboardLayout from "../layouts/DashboardLayout";
import {Feedback} from "../components/Feedback";
import {StatCard} from "../components/StatCard";
import {StatusBadge} from "../components/StatusBadge";
import {endpoints} from "../lib/api";
import type {FiveWhy,FishboneCause,KnownError,ProblemCorrelation,ProblemDashboard,ProblemRecord,ProblemReport,ProblemWorkaround,RootCause,RootCauseAnalysis} from "../lib/types";
import "../styles/problem-management.css";

const tabs=[["Dashboard","/problems"],["Problems","/problems/list"],["New Problem","/problems/new"],["RCA Workspace","/problems/rca"],["5 Whys","/problems/five-whys"],["Fishbone","/problems/fishbone"],["Known Errors","/problems/kedb"],["Workarounds","/problems/workarounds"],["CAPA","/problems/capa"],["Reviews","/problems/reviews"],["Correlations","/problems/correlations"],["Relationships","/problems/relationships"],["Reports","/problems/reports"]] as const;
const next:Record<string,string>={new:"under_investigation",under_investigation:"root_cause_identified",root_cause_identified:"known_error",known_error:"change_required",change_required:"resolved",resolved:"closed"};
const propertyId=()=>localStorage.getItem("hiop.active_property_id")||null;

export default function ProblemManagementPage(){
 const location=useLocation(),navigate=useNavigate(),parts=location.pathname.split("/"),mode=parts[2]||"dashboard",detailId=parts[2]==="list"?parts[3]:undefined;
 const [dashboard,setDashboard]=useState<ProblemDashboard>();const [problems,setProblems]=useState<ProblemRecord[]>([]);const [selected,setSelected]=useState<ProblemRecord>();const [knownErrors,setKnownErrors]=useState<KnownError[]>([]);const [workarounds,setWorkarounds]=useState<ProblemWorkaround[]>([]);const [correlations,setCorrelations]=useState<ProblemCorrelation[]>([]);const [report,setReport]=useState<ProblemReport>();const [rca,setRca]=useState<RootCauseAnalysis|null>(null);const [causes,setCauses]=useState<RootCause[]>([]);const [whys,setWhys]=useState<FiveWhy[]>([]);const [fishbone,setFishbone]=useState<FishboneCause[]>([]);const [role,setRole]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 const admin=["admin","superadmin"].includes(role),contributor=admin||role==="technician";
 const load=async()=>{try{const list=await endpoints.problems({page_size:100});setProblems(list.items);const active=selected||list.items[0];if(!selected&&active)setSelected(active);if(mode==="dashboard")setDashboard(await endpoints.problemDashboard());if(detailId)setSelected(await endpoints.problem(detailId));if(["kedb","workarounds"].includes(mode)){setKnownErrors((await endpoints.knownErrors()).items);setWorkarounds((await endpoints.workaroundLibrary()).items)}if(["rca","five-whys","fishbone","capa","reviews","relationships"].includes(mode)&&active){const out=await endpoints.problemRCA(active.id);setRca(out.analysis);setCauses(out.causes);setWhys(out.five_whys);setFishbone(out.fishbone)}if(mode==="correlations")setCorrelations((await endpoints.problemCorrelations()).items);if(mode==="reports")setReport(await endpoints.problemReport());setError("")}catch(e){setError(e instanceof Error?e.message:"Unable to load Problem Management")}};
 useEffect(()=>{void endpoints.me().then(u=>setRole(u.role))},[]);useEffect(()=>{const t=setTimeout(()=>void load(),0);return()=>clearTimeout(t);// eslint-disable-next-line react-hooks/exhaustive-deps
 },[mode,detailId]);
 const mutate=async(fn:()=>Promise<unknown>)=>{setBusy(true);try{await fn();await load()}catch(e){setError(e instanceof Error?e.message:"Operation failed")}finally{setBusy(false)}};
 const create=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),row=await endpoints.createProblem({property_id:propertyId(),title:f.get("title"),description:f.get("description"),summary:f.get("summary")||null,priority:f.get("priority"),severity:f.get("severity"),impact:f.get("impact"),business_impact:f.get("business_impact")||null,technical_impact:f.get("technical_impact")||null,assigned_team:f.get("assigned_team")||null,source:"manual"});navigate(`/problems/list/${row.id}`)};
 const choose=(id:string)=>{const row=problems.find(p=>p.id===id);setSelected(row);if(row&&["rca","five-whys","fishbone"].includes(mode))void endpoints.problemRCA(row.id).then(out=>{setRca(out.analysis);setCauses(out.causes);setWhys(out.five_whys);setFishbone(out.fishbone)})};
 const exportReport=async(format:"csv"|"xlsx"|"pdf")=>{const out=await endpoints.exportProblemReport(format),url=URL.createObjectURL(out.blob),a=document.createElement("a");a.href=url;a.download=out.filename;a.click();URL.revokeObjectURL(url)};
 return <DashboardLayout><header className="page-title problem-title"><div><span className="eyebrow">ITIL operational stability</span><h1>Problem Management</h1><p>Investigate recurring failures, validate root causes, publish known errors, and govern corrective action without autonomous conclusions.</p></div>{contributor&&<button className="primary-action" onClick={()=>navigate("/problems/new")}>Create problem</button>}</header>
 <nav className="problem-tabs" aria-label="Problem Management sections">{tabs.map(([label,path])=><button key={path} className={location.pathname===path?"active":""} onClick={()=>navigate(path)}>{label}</button>)}</nav>
 {error&&<Feedback error={error}/>} {mode==="dashboard"&&<><section className="problem-stats"><StatCard label="Open problems" value={dashboard?.open_problems??0} detail="Active lifecycle" icon="alerts"/><StatCard label="High priority" value={dashboard?.high_priority??0} detail="Management attention" icon="warning"/><StatCard label="Known errors" value={dashboard?.known_errors??0} detail="Published KEDB" icon="audit"/><StatCard label="RCA in progress" value={dashboard?.rca_in_progress??0} detail="Human investigation" icon="search"/><StatCard label="CAPA overdue" value={dashboard?.capa_overdue??0} detail="Verification required" icon="clock"/><StatCard label="Recurring signals" value={dashboard?.recurring_incidents??0} detail="Review suggestions" icon="network"/></section><Panel title="Recently updated problems" copy="No root cause or resolution is generated automatically."><ProblemCards rows={dashboard?.recent??[]} open={id=>navigate(`/problems/list/${id}`)}/></Panel></>}
 {mode==="list"&&!detailId&&<Panel title="Problem register" copy="Filterable enterprise problem lifecycle."><ProblemCards rows={problems} open={id=>navigate(`/problems/list/${id}`)}/></Panel>}
 {mode==="list"&&selected&&<><Panel title={`${selected.problem_number} · ${selected.title}`} copy={`${selected.priority} priority · ${selected.severity} severity · version ${selected.version}`}><div className="problem-detail"><Detail label="Status" value={selected.status}/><Detail label="Impact" value={selected.impact}/><Detail label="Owner team" value={selected.assigned_team||"Unassigned"}/><Detail label="Review date" value={selected.review_date?new Date(selected.review_date).toLocaleDateString():"Not scheduled"}/></div><p>{selected.description}</p>{contributor&&next[selected.status]&&<button className="primary-action" disabled={busy} onClick={()=>void mutate(()=>endpoints.transitionProblem(selected.id,next[selected.status],"Reviewed lifecycle transition"))}>Advance to {next[selected.status].replaceAll("_"," ")}</button>}</Panel><Panel title="Operational links" copy="Open a controlled workspace for this record."><div className="problem-actions"><button onClick={()=>{navigate("/problems/rca");setSelected(selected)}}>RCA workspace</button><button onClick={()=>navigate("/problems/capa")}>CAPA manager</button><button onClick={()=>navigate("/problems/relationships")}>Relationship graph</button></div></Panel></>}
 {mode==="new"&&<Panel title="Create problem" copy="Creation records an investigation target, never a presumed root cause.">{contributor?<form className="problem-form" onSubmit={create}><label>Title<input name="title" required/></label><label>Assigned team<input name="assigned_team"/></label><label>Priority<select name="priority"><option>normal</option><option>high</option><option>urgent</option><option>low</option></select></label><label>Severity<select name="severity"><option>medium</option><option>high</option><option>critical</option><option>low</option></select></label><label>Impact<select name="impact"><option>medium</option><option>high</option><option>critical</option><option>low</option></select></label><label className="wide">Summary<textarea name="summary"/></label><label className="wide">Description<textarea name="description" required/></label><label className="wide">Business impact<textarea name="business_impact"/></label><label className="wide">Technical impact<textarea name="technical_impact"/></label><button className="primary-action" disabled={busy}>Create problem record</button></form>:<Feedback error="Contributor permission is required."/>}</Panel>}
 {["rca","five-whys","fishbone"].includes(mode)&&<><Picker rows={problems} value={selected?.id||problems[0]?.id} onChange={choose}/>{mode==="rca"&&<RCAWorkspace selected={selected||problems[0]} rca={rca} causes={causes} contributor={contributor} mutate={mutate}/>} {mode==="five-whys"&&<FiveWhysEditor selected={selected||problems[0]} rows={whys} contributor={contributor} mutate={mutate}/>} {mode==="fishbone"&&<FishboneEditor selected={selected||problems[0]} rows={fishbone} contributor={contributor} mutate={mutate}/>}</>}
 {mode==="kedb"&&<Panel title="Known Error Database" copy="Approved, versioned symptoms, causes, workarounds, and resolutions."><KnownErrorCards rows={knownErrors} admin={admin} mutate={mutate}/></Panel>}
 {mode==="workarounds"&&<Panel title="Workaround library" copy="Reusable instructions retain risk, permissions, validation, and effectiveness evidence.">{!workarounds.length?<Feedback empty="No reviewed workarounds."/>:<div className="problem-card-grid">{workarounds.map(w=><article key={w.id}><StatusBadge status={w.workaround_type}/><h3>{w.instructions}</h3><p>{w.verification}</p><small>Risk {w.risk_level} · effectiveness {w.effectiveness_rating}/5</small></article>)}</div>}</Panel>}
 {mode==="capa"&&<Panel title="Corrective & Preventive Action Manager" copy="Assign, approve, complete, and independently verify durable actions."><Picker rows={problems} value={selected?.id||problems[0]?.id} onChange={choose}/>{contributor&&<form className="problem-inline-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),id=selected?.id||problems[0]?.id;if(id)void mutate(()=>endpoints.createProblemPlan(id,{plan_type:f.get("plan_type"),title:f.get("title"),objective:f.get("objective"),due_at:f.get("due_at")||null}))}}><select name="plan_type"><option value="corrective">Corrective</option><option value="preventive">Preventive</option></select><input name="title" placeholder="Plan title" required/><input name="objective" placeholder="Measurable objective" required/><input name="due_at" type="date"/><button>Create plan</button></form>}</Panel>}
 {mode==="reviews"&&<Panel title="Post-resolution reviews" copy="Lessons, impact, timeline, stakeholders, actions, approval, and sign-off are archived."><Picker rows={problems} value={selected?.id||problems[0]?.id} onChange={choose}/><p className="problem-guard">A problem cannot close until an administrator approves its post-resolution review.</p></Panel>}
 {mode==="correlations"&&<Panel title="Recurring incident suggestions" copy="Threshold-based deterministic grouping creates review suggestions only.">{admin&&<button className="primary-action" onClick={()=>void mutate(()=>endpoints.detectProblemCorrelations({threshold:3,lookback_days:30,property_id:propertyId()}))}>Run reviewed detection</button>}{!correlations.length?<Feedback empty="No recurring incident suggestions."/>:<div className="problem-card-grid">{correlations.map(c=><article key={c.id}><strong>{c.occurrence_count} correlated events</strong><p>{c.rationale}</p><small>Threshold {c.threshold} · {c.status}</small></article>)}</div>}</Panel>}
 {mode==="relationships"&&<Panel title="Relationship graph" copy="Incidents, changes, CIs, knowledge, vendors, services, maintenance, and automation remain explicitly linked."><Picker rows={problems} value={selected?.id||problems[0]?.id} onChange={choose}/><div className="problem-graph" role="img" aria-label="Problem relationship graph"><span>Problem</span><i>→</i><span>Reviewed linked records</span></div></Panel>}
 {mode==="reports"&&<Panel title="Problem reports" copy="Trends, recurrence, root cause, stability, resolution, KEDB usage, CAPA, and executive summaries."><section className="problem-report-grid"><Detail label="Total problems" value={String(report?.total??0)}/><Detail label="Resolution rate" value={`${report?.resolution_rate??0}%`}/><Detail label="Known errors" value={String(report?.known_errors??0)}/><Detail label="CAPA completed" value={`${report?.capa_completed??0} / ${report?.capa_total??0}`}/></section><div className="page-actions"><button onClick={()=>void exportReport("csv")}>CSV</button><button onClick={()=>void exportReport("xlsx")}>Excel</button><button onClick={()=>void exportReport("pdf")}>PDF</button></div></Panel>}
 </DashboardLayout>
}

function Panel({title,copy,children}:{title:string;copy:string;children:React.ReactNode}){return <section className="hospitality-panel problem-panel"><div className="panel-heading"><div><h2>{title}</h2><span>{copy}</span></div></div>{children}</section>}
function Detail({label,value}:{label:string;value:string}){return <div><small>{label}</small><strong>{value}</strong></div>}
function Picker({rows,value,onChange}:{rows:ProblemRecord[];value?:string;onChange:(id:string)=>void}){return <label className="problem-picker">Problem<select value={value||""} onChange={e=>onChange(e.target.value)}><option value="" disabled>Select a problem</option>{rows.map(p=><option key={p.id} value={p.id}>{p.problem_number} · {p.title}</option>)}</select></label>}
function ProblemCards({rows,open}:{rows:ProblemRecord[];open:(id:string)=>void}){return !rows.length?<Feedback empty="No problem records in scope."/>:<div className="problem-card-grid">{rows.map(p=><article key={p.id}><div><StatusBadge status={p.status}/><StatusBadge status={p.priority}/></div><h3>{p.problem_number} · {p.title}</h3><p>{p.summary||p.description}</p><small>{p.severity} severity · {p.assigned_team||"Unassigned"}</small><button onClick={()=>open(p.id)}>Open problem</button></article>)}</div>}
function RCAWorkspace({selected,rca,causes,contributor,mutate}:{selected?:ProblemRecord;rca:RootCauseAnalysis|null;causes:RootCause[];contributor:boolean;mutate:(fn:()=>Promise<unknown>)=>Promise<void>}){return <Panel title="Root Cause Analysis" copy="Timeline, technical, business, environmental, human, infrastructure, and vendor evidence remain structured and reviewed.">{!selected?<Feedback empty="Select a problem."/>:<>{contributor&&<form className="problem-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void mutate(()=>endpoints.saveProblemRCA(selected.id,{methodology:f.get("methodology"),technical_findings:f.get("technical_findings"),business_findings:f.get("business_findings"),validation:f.get("validation"),timeline:[]}))}}><label>Method<select name="methodology" defaultValue={rca?.methodology||"five_whys"}><option value="five_whys">5 Whys</option><option value="fishbone">Fishbone</option><option value="combined">Combined</option><option value="timeline">Timeline reconstruction</option></select></label><label className="wide">Technical findings<textarea name="technical_findings" defaultValue={rca?.technical_findings||""}/></label><label className="wide">Business findings<textarea name="business_findings" defaultValue={rca?.business_findings||""}/></label><label className="wide">Validation evidence<textarea name="validation" defaultValue={rca?.validation||""}/></label><button>Save RCA workspace</button></form>}<div className="problem-card-grid">{causes.map(c=><article key={c.id}><StatusBadge status={c.validated?"validated":"unvalidated"}/><h3>{c.category}</h3><p>{c.statement}</p><small>{c.evidence}</small></article>)}</div></>}</Panel>}
function FiveWhysEditor({selected,rows,contributor,mutate}:{selected?:ProblemRecord;rows:FiveWhy[];contributor:boolean;mutate:(fn:()=>Promise<unknown>)=>Promise<void>}){return <Panel title="5 Whys Editor" copy="Each answer requires an explicit investigator entry and optional evidence.">{selected&&contributor&&<form className="problem-inline-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void mutate(()=>endpoints.saveFiveWhy(selected.id,{sequence:Number(f.get("sequence")),question:f.get("question"),answer:f.get("answer"),evidence:f.get("evidence")||null}))}}><select name="sequence">{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select><input name="question" placeholder="Why did this occur?" required/><input name="answer" placeholder="Evidence-based answer" required/><input name="evidence" placeholder="Evidence reference"/><button>Save why</button></form>}<ol className="why-chain">{rows.map(w=><li key={w.id}><strong>{w.question}</strong><span>{w.answer}</span><small>{w.evidence||"No evidence reference"}</small></li>)}</ol></Panel>}
function FishboneEditor({selected,rows,contributor,mutate}:{selected?:ProblemRecord;rows:FishboneCause[];contributor:boolean;mutate:(fn:()=>Promise<unknown>)=>Promise<void>}){return <Panel title="Fishbone Diagram Editor" copy="Categorize possible causes without promoting them to validated root causes.">{selected&&contributor&&<form className="problem-inline-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void mutate(()=>endpoints.addFishboneCause(selected.id,{category:f.get("category"),cause:f.get("cause"),evidence:f.get("evidence")||null}))}}><select name="category">{["human","infrastructure","environment","process","vendor","technology"].map(x=><option key={x}>{x}</option>)}</select><input name="cause" placeholder="Possible contributing cause" required/><input name="evidence" placeholder="Evidence"/><button>Add branch</button></form>}<div className="fishbone-grid">{["human","infrastructure","environment","process","vendor","technology"].map(category=><section key={category}><h3>{category}</h3>{rows.filter(r=>r.category===category).map(r=><p key={r.id}>{r.cause}</p>)}</section>)}</div></Panel>}
function KnownErrorCards({rows,admin,mutate}:{rows:KnownError[];admin:boolean;mutate:(fn:()=>Promise<unknown>)=>Promise<void>}){return !rows.length?<Feedback empty="No known errors published or under review."/>:<div className="problem-card-grid">{rows.map(k=><article key={k.id}><StatusBadge status={k.status}/><h3>{k.error_id}</h3><p>{k.description}</p><small>{k.symptoms}</small>{admin&&<div className="problem-actions">{k.status==="draft"&&<button onClick={()=>void mutate(()=>endpoints.knownErrorAction(k.id,"approve"))}>Approve</button>}{k.status==="approved"&&<button onClick={()=>void mutate(()=>endpoints.knownErrorAction(k.id,"publish"))}>Publish</button>}{k.status==="published"&&<button onClick={()=>void mutate(()=>endpoints.knownErrorAction(k.id,"retire"))}>Retire</button>}</div>}</article>)}</div>}
