import {Link} from "react-router-dom";
import {Icon} from "../components/Icon";
import {PublicLayout} from "../components/PublicLayout";

const values=[
 ["Discover","Find devices across your hotel network.","discovery"],["Identify","Turn technical evidence into meaningful technology assets.","search"],["Understand","See topology, ports, VLANs, services, and dependencies.","hierarchy"],["Monitor","Track availability and infrastructure health.","network"],["Manage","Own the complete asset and supplier context.","devices"],["Operate","Handle incidents, problems, changes, and knowledge.","tickets"],
] as const;
export default function PublicHomePage(){return <PublicLayout>
 <section className="public-hero"><div><p className="public-eyebrow">Hospitality IT operations platform</p><h1>Hospitality IT Operations, in one place.</h1><p>Discover your hotel's technology, understand how everything is connected, monitor infrastructure health, manage assets, and keep IT operations under control.</p><div className="public-hero-actions"><Link className="public-button" to="/get-started">Get started</Link><Link className="public-button secondary" to="/get-started?intent=demo">Request a demo</Link></div><div className="public-trust-line"><span>Organization isolated</span><span>Property aware</span><span>Role based</span><span>Auditable</span></div></div><div className="product-map" aria-label="HIOP operating flow"><p>Your hotel technology</p>{["Discover","Identify","Understand","Monitor","Manage","Operate"].map((label,index)=><div key={label}><span>{String(index+1).padStart(2,"0")}</span><strong>{label}</strong>{index<5&&<i>→</i>}</div>)}</div></section>
 <section className="public-section centered" id="features"><p className="public-eyebrow">One operational picture</p><h2>From an IP address to hospitality context.</h2><p className="section-lead">HIOP connects network evidence, managed assets, services, people, and operational history without forcing your team across disconnected tools.</p><div className="value-grid">{values.map(([title,text,icon])=><article key={title}><span><Icon name={icon}/></span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
 <section className="public-section split"><div><p className="public-eyebrow">Built for hotel operations</p><h2>Technology understood in the context of the property.</h2><p>Generic tools see endpoints. HIOP helps IT teams organize POS, PMS, guest Wi-Fi, CCTV, IPTV, telephony, access control, printers, servers, and network infrastructure around the services, departments, and locations they support.</p><Link className="text-link" to="/features">Explore the platform →</Link></div><div className="hospitality-stack">{["Guest experience","Hotel operations","Technology services","Assets and devices","Network infrastructure"].map((x,i)=><div key={x}><span>{i+1}</span>{x}</div>)}</div></section>
 <section className="public-section problem"><div><p className="public-eyebrow">Bring scattered knowledge together</p><h2>Your operational truth should not live in six tools and one technician's memory.</h2></div><ul>{["Network and monitoring tools","Spreadsheets and asset lists","Directory and DHCP evidence","Vendor portals and documents","Tickets and personal knowledge"].map(x=><li key={x}><Icon name="check"/>{x}</li>)}</ul></section>
 <section className="public-section security" id="security"><div><p className="public-eyebrow">Designed for accountable operations</p><h2>Clear boundaries. Traceable actions.</h2></div><div>{["Role-based access","Organization and property isolation","Audit history","Read-only discovery principles","Secure credential handling","Enterprise-oriented web architecture"].map(x=><span key={x}><Icon name="lock"/>{x}</span>)}</div></section>
 <section className="public-cta"><p className="public-eyebrow">Start with one property. Grow with confidence.</p><h2>Bring your hotel's IT operations together.</h2><div><Link className="public-button" to="/get-started">Get started</Link><Link className="public-button secondary" to="/login">Sign in</Link></div></section>
 </PublicLayout>}
