import { useState } from "react";
import { Link } from "react-router-dom";
import { Feedback } from "../components/Feedback";
import { StatusBadge } from "../components/StatusBadge";
import { useRequest } from "../hooks/useRequest";
import DashboardLayout from "../layouts/DashboardLayout";
import { endpoints } from "../lib/api";
import { PageTitle } from "./DashboardPage";

const reports=["executive","operations","network","assets","lifecycle","incidents","problems","changes","procurement","vendors","knowledge","services","departments","locations"];
const periods=[{id:"today",label:"Today"},{id:"7d",label:"Last 7 days"},{id:"30d",label:"Last 30 days"},{id:"90d",label:"Last 90 days"},{id:"month",label:"This month"},{id:"quarter",label:"This quarter"},{id:"year",label:"This year"},{id:"custom",label:"Custom range"}];
const title=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,x=>x.toUpperCase());
export default function ReportingPage(){
 const [report,setReport]=useState("executive"),[period,setPeriod]=useState("30d"),[start,setStart]=useState(""),[end,setEnd]=useState("");
 const [departmentId,setDepartmentId]=useState(""),[locationId,setLocationId]=useState(""),[serviceId,setServiceId]=useState(""),[vendorId,setVendorId]=useState(""),[deviceType,setDeviceType]=useState(""),[status,setStatus]=useState("");
 const filters={period,start:period==="custom"&&start?new Date(start).toISOString():undefined,end:period==="custom"&&end?new Date(`${end}T23:59:59`).toISOString():undefined,department_id:departmentId||undefined,location_id:locationId||undefined,service_id:serviceId||undefined,vendor_id:vendorId||undefined,device_type:deviceType||undefined,status:status||undefined};
 const data=useRequest(()=>endpoints.organizationReport(report,filters),[report,period,start,end,departmentId,locationId,serviceId,vendorId,deviceType,status]);
 const exportCsv=async()=>{const file=await endpoints.exportOrganizationReport(report,filters);const url=URL.createObjectURL(file.blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=file.filename;anchor.click();URL.revokeObjectURL(url)};
 return <DashboardLayout><PageTitle eyebrow="Management intelligence" title="Organization reporting" copy="Prebuilt, explainable reports calculated from live HIOP organization data." action={<button className="secondary-action" onClick={()=>void exportCsv()}>Export CSV</button>}/>
 <nav className="page-actions report-tabs" aria-label="Report types">{reports.map(x=><button key={x} className={x===report?"primary-action":"secondary-action"} onClick={()=>setReport(x)}>{title(x)}</button>)}</nav>
 <section className="toolbar-panel"><div className="filter-row"><label>Reporting period<select value={period} onChange={e=>setPeriod(e.target.value)}>{periods.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label>{period==="custom"&&<><label>Start<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>End<input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label></>}<label>Device type<input value={deviceType} onChange={e=>setDeviceType(e.target.value)} placeholder="e.g. switch"/></label><label>Status<input value={status} onChange={e=>setStatus(e.target.value)} placeholder="e.g. active"/></label><label>Department ID<input value={departmentId} onChange={e=>setDepartmentId(e.target.value)} placeholder="Optional"/></label><label>Location ID<input value={locationId} onChange={e=>setLocationId(e.target.value)} placeholder="Optional"/></label><label>Service ID<input value={serviceId} onChange={e=>setServiceId(e.target.value)} placeholder="Optional"/></label><label>Vendor ID<input value={vendorId} onChange={e=>setVendorId(e.target.value)} placeholder="Optional"/></label></div></section>
 {data.loading||data.error||!data.data?<Feedback loading={data.loading} error={data.error}/>:<><section className="report-metric-grid">{data.data.metrics.map(item=>item.drilldown?<Link key={item.label} className="panel report-metric" to={item.drilldown}><small>{item.label}</small><strong>{item.value}</strong><span>Open underlying records →</span></Link>:<article key={item.label} className="panel report-metric"><small>{item.label}</small><strong>{item.value}</strong><StatusBadge status={item.quality}/></article>)}</section>
 <section className="report-grid">{Object.entries(data.data.breakdowns).map(([name,rows])=><article className="panel" key={name}><h2>{title(name)}</h2>{!rows.length?<Feedback empty="Insufficient data"/>:<div className="report-breakdown">{rows.map((row,index)=><div key={`${String(row.label)}-${index}`}><strong>{String(row.label??"Unknown")}</strong><span>{Object.entries(row).filter(([key])=>key!=="label"&&key!=="id").map(([key,value])=>`${title(key)}: ${value}`).join(" · ")}</span></div>)}</div>}</article>)}</section>
 <section className="report-grid">{Object.entries(data.data.trends).map(([name,trend])=><article className="panel" key={name}><h2>{title(name)}</h2>{trend.status!=="available"||!trend.points.length?<Feedback empty="Insufficient data"/>:<div className="trend-chart" role="img" aria-label={`${title(name)} historical trend`}>{trend.points.map(point=><div key={point.date}><span style={{height:`${Math.max(8,Math.min(100,point.value))}%`}} title={`${point.date}: ${point.value}`}/><small>{point.date.slice(5)}</small></div>)}</div>}</article>)}</section>
 <footer className="settings-note">Source: {data.data.source}. Generated {new Date(data.data.generated_at).toLocaleString()}. Missing observations remain “Insufficient data”.</footer></>}</DashboardLayout>
}
