/* eslint-disable react-hooks/set-state-in-effect */
import React, { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import DashboardLayout from "../layouts/DashboardLayout";
import { PageTitle } from "./DashboardPage";
import { Feedback } from "../components/Feedback";
import { Icon } from "../components/Icon";
import { Toast } from "../components/Toast";
import { endpoints } from "../lib/api";
import type { HierarchyCatalog, SettingsBundle, SystemHealth } from "../lib/types";
import { useTheme, type ThemePreference } from "../theme/ThemeContext";

type Section = "general"|"organization"|"departments"|"locations"|"network"|"notifications"|"appearance"|"security"|"health"|"maintenance"|"about";
const sections: Array<{key:Section;label:string;icon:"settings"|"hierarchy"|"network"|"bell"|"sun"|"lock"|"server"|"audit"}> = [
  {key:"general",label:"General",icon:"settings"},{key:"organization",label:"Organization",icon:"hierarchy"},{key:"departments",label:"Departments",icon:"hierarchy"},{key:"locations",label:"Locations",icon:"hierarchy"},{key:"network",label:"Network & scanner",icon:"network"},{key:"notifications",label:"Notifications & email",icon:"bell"},{key:"appearance",label:"Appearance",icon:"sun"},{key:"security",label:"Security",icon:"lock"},{key:"health",label:"System health",icon:"server"},{key:"maintenance",label:"Backup & maintenance",icon:"audit"},{key:"about",label:"Application information",icon:"settings"},
];

export default function SettingsPage(){
  const [section,setSection]=useState<Section>("general"); const [draft,setDraft]=useState<SettingsBundle|null>(null); const [hierarchy,setHierarchy]=useState<HierarchyCatalog|null>(null); const [health,setHealth]=useState<SystemHealth|null>(null);
  const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(""); const [notice,setNotice]=useState(""); const {preference,setPreference}=useTheme();
  const load=async()=>{setLoading(true);setError("");try{const [settings,catalog]=await Promise.all([endpoints.settings(),endpoints.hierarchy()]);setDraft(settings);setHierarchy(catalog)}catch(caught){setError(caught instanceof Error?caught.message:"Settings could not be loaded.")}finally{setLoading(false)}};
  useEffect(()=>{void load()},[]);
  const save=async()=>{if(!draft)return;setSaving(true);setNotice("");try{let result=draft;if(section==="general")result=await endpoints.updateGeneralSettings(draft.general);else if(section==="organization")result=await endpoints.updateOrganizationSettings(draft.organization);else if(section==="network")result=await endpoints.updateNetworkSettings(draft.network);else if(section==="notifications")result=await endpoints.updateNotificationSettings(draft.notifications);setDraft(result);setNotice(`${sections.find(item=>item.key===section)?.label} settings saved.`)}catch(caught){setNotice(caught instanceof Error?caught.message:"Settings could not be saved.")}finally{setSaving(false)}};
  const refreshHealth=async()=>{setHealth(null);try{setHealth(await endpoints.systemHealth())}catch(caught){setNotice(caught instanceof Error?caught.message:"Health check failed.")}};
  useEffect(()=>{if(section==="health"&&!health)void refreshHealth()},[section,health]);
  if(loading||error||!draft)return <DashboardLayout><PageTitle eyebrow="Administration" title="Settings" copy="Secure global configuration and operational health."/><Feedback loading={loading} error={error||undefined} onRetry={()=>void load()}/></DashboardLayout>;
  const g=draft.general,o=draft.organization,n=draft.network,notifications=draft.notifications;
  return <DashboardLayout><PageTitle eyebrow="Administration" title="Settings & administration" copy="Manage safe runtime configuration, organizational structure, appearance and system health."/>{notice&&<Toast message={notice} tone={notice.toLowerCase().includes("saved")?"success":"error"}/>}<div className="settings-layout"><nav className="settings-nav" aria-label="Settings sections">{sections.map(item=><button key={item.key} className={section===item.key?"active":""} onClick={()=>setSection(item.key)}><Icon name={item.icon}/><span>{item.label}</span></button>)}</nav><section className="settings-workspace">
  {section==="general"&&<SettingsPanel title="General settings" copy="Global application display and formatting defaults."><div className="settings-form-grid"><Field label="Application display name" value={g.application_name} onChange={value=>setDraft({...draft,general:{...g,application_name:value}})}/><Field label="Short name" value={g.short_name} onChange={value=>setDraft({...draft,general:{...g,short_name:value}})}/><Field label="Time zone" value={g.timezone} onChange={value=>setDraft({...draft,general:{...g,timezone:value}})}/><SelectField label="Date format" value={g.date_format} options={["DD/MM/YYYY","MM/DD/YYYY","YYYY-MM-DD"]} onChange={value=>setDraft({...draft,general:{...g,date_format:value as typeof g.date_format}})}/><SelectField label="Time format" value={g.time_format} options={["12-hour","24-hour"]} onChange={value=>setDraft({...draft,general:{...g,time_format:value as typeof g.time_format}})}/><SelectField label="Default page size" value={String(g.default_page_size)} options={["10","25","50","100"]} onChange={value=>setDraft({...draft,general:{...g,default_page_size:Number(value) as 10|25|50|100}})}/><SelectField label="Default landing page" value={g.default_landing_page} options={["/dashboard","/devices","/network","/alerts","/tickets","/reports"]} onChange={value=>setDraft({...draft,general:{...g,default_landing_page:value}})}/><Field label="Support email" type="email" value={g.support_email??""} onChange={value=>setDraft({...draft,general:{...g,support_email:value||null}})}/></div><SaveButton saving={saving} onClick={save}/></SettingsPanel>}
  {section==="organization"&&<SettingsPanel title="Organization profile" copy="Shared identity used throughout administration and operational context."><div className="settings-form-grid"><Field label="Organization name" value={o.organization_name} onChange={value=>setDraft({...draft,organization:{...o,organization_name:value}})}/><Field label="Property name" value={o.property_name} onChange={value=>setDraft({...draft,organization:{...o,property_name:value}})}/><Field label="IT department name" value={o.it_department_name} onChange={value=>setDraft({...draft,organization:{...o,it_department_name:value}})}/><Field label="Address" value={o.address} onChange={value=>setDraft({...draft,organization:{...o,address:value}})}/><Field label="City" value={o.city} onChange={value=>setDraft({...draft,organization:{...o,city:value}})}/><Field label="Country" value={o.country} onChange={value=>setDraft({...draft,organization:{...o,country:value}})}/><Field label="Support email" type="email" value={o.support_email??""} onChange={value=>setDraft({...draft,organization:{...o,support_email:value||null}})}/><Field label="Support phone" value={o.support_phone} onChange={value=>setDraft({...draft,organization:{...o,support_phone:value}})}/></div><p className="settings-note"><Icon name="warning"/>Logo upload is unavailable because secure file storage is not configured.</p><SaveButton saving={saving} onClick={save}/></SettingsPanel>}
  {section==="departments"&&<HierarchySummary title="Departments" copy="Normalized, database-backed departments. No additional names are invented." items={hierarchy?.departments??[]} link="/hierarchy"/>}
  {section==="locations"&&<HierarchySummary title="Locations" copy="Rooms and locations are managed through the normalized property hierarchy." items={hierarchy?.rooms??[]} link="/hierarchy"/>}
  {section==="network"&&<SettingsPanel title="Network & scanner" copy="Runtime-safe scanner controls. The approved CIDR remains limited to a private network."><div className="settings-form-grid"><Field label="Approved private network" value={n.approved_network} onChange={value=>setDraft({...draft,network:{...n,approved_network:value}})}/><NumberField label="Scan interval (minutes)" value={n.scan_interval_minutes} min={5} max={1440} onChange={value=>setDraft({...draft,network:{...n,scan_interval_minutes:value}})}/><NumberField label="Ping timeout (seconds)" value={n.ping_timeout_seconds} min={1} max={30} onChange={value=>setDraft({...draft,network:{...n,ping_timeout_seconds:value}})}/><NumberField label="Maximum workers" value={n.max_concurrent_workers} min={1} max={32} onChange={value=>setDraft({...draft,network:{...n,max_concurrent_workers:value}})}/><NumberField label="Offline threshold" value={n.offline_threshold} min={1} max={20} onChange={value=>setDraft({...draft,network:{...n,offline_threshold:value}})}/></div><div className="settings-toggles"><Toggle label="Automatic scanning" checked={n.automatic_scanning} onChange={value=>setDraft({...draft,network:{...n,automatic_scanning:value}})}/><Toggle label="Exclude retired devices" checked={n.exclude_retired_devices} onChange={value=>setDraft({...draft,network:{...n,exclude_retired_devices:value}})}/><Toggle label="Automatic alerts" checked={n.automatic_alerts} onChange={value=>setDraft({...draft,network:{...n,automatic_alerts:value}})}/><Toggle label="Automatic offline tickets" checked={n.automatic_offline_tickets} onChange={value=>setDraft({...draft,network:{...n,automatic_offline_tickets:value}})}/></div><SaveButton saving={saving} onClick={save}/></SettingsPanel>}
  {section==="notifications"&&<SettingsPanel title="Notifications & email" copy="Notification policy is persisted; SMTP credentials remain deployment-only and are never returned."><div className="settings-toggles"><Toggle label="Email notifications" checked={notifications.email_notifications} onChange={value=>setDraft({...draft,notifications:{...notifications,email_notifications:value}})}/><Toggle label="Device offline" checked={notifications.device_offline} onChange={value=>setDraft({...draft,notifications:{...notifications,device_offline:value}})}/><Toggle label="Device restored" checked={notifications.device_restored} onChange={value=>setDraft({...draft,notifications:{...notifications,device_restored:value}})}/><Toggle label="Ticket assignment" checked={notifications.ticket_assignment} onChange={value=>setDraft({...draft,notifications:{...notifications,ticket_assignment:value}})}/><Toggle label="Critical alerts" checked={notifications.critical_alerts} onChange={value=>setDraft({...draft,notifications:{...notifications,critical_alerts:value}})}/></div><div className="settings-form-grid"><Field label="Sender display name" value={notifications.sender_display_name} onChange={value=>setDraft({...draft,notifications:{...notifications,sender_display_name:value}})}/><Field label="Recipient email" type="email" value={notifications.recipient_email??""} onChange={value=>setDraft({...draft,notifications:{...notifications,recipient_email:value||null}})}/></div><ReadOnlyGrid data={draft.email}/><p className="settings-note"><Icon name="lock"/>SMTP credentials are environment-only. Test email is unavailable until a secure runtime mail provider is configured.</p><SaveButton saving={saving} onClick={save}/></SettingsPanel>}
  {section==="appearance"&&<SettingsPanel title="Appearance" copy="This preference is personal to this browser and applies immediately across HIOP."><div className="theme-choice">{(["light","dark","system"] as ThemePreference[]).map(value=><button key={value} className={preference===value?"active":""} onClick={()=>setPreference(value)}><Icon name={value==="dark"?"moon":"sun"}/><strong>{value}</strong><span>{value==="system"?"Follow operating system":`${value} interface`}</span></button>)}</div><p className="settings-note"><Icon name="check"/>The brand accent remains #C29F04 to preserve accessible HIOP identity.</p></SettingsPanel>}
  {section==="security"&&<SettingsPanel title="Security posture" copy="Read-only facts from the current authentication implementation."><ReadOnlyGrid data={draft.security}/><p className="settings-note"><Icon name="lock"/>Secret keys, password hashes, tokens and database credentials are never exposed here.</p></SettingsPanel>}
  {section==="health"&&<SettingsPanel title="System health" copy="A live, secret-safe view of core HIOP services."><button className="secondary-action" onClick={()=>void refreshHealth()}><Icon name="server"/>Refresh health</button>{health?<ReadOnlyGrid data={health as unknown as Record<string,unknown>}/>:<Feedback loading/>}</SettingsPanel>}
  {section==="maintenance"&&<SettingsPanel title="Backup & maintenance" copy="No application-managed backup engine exists, so destructive or fake controls are intentionally omitted."><div className="maintenance-guide"><h3>PostgreSQL operational backup</h3><ol><li>Use the deployment host’s secured PostgreSQL service account.</li><li>Run an encrypted `pg_dump` outside the source tree.</li><li>Store backups in access-controlled off-host storage.</li><li>Test restores in an isolated environment before relying on them.</li></ol><p>HIOP does not execute restores, arbitrary SQL, shell commands, log deletion or database resets from this interface.</p></div></SettingsPanel>}
  {section==="about"&&<SettingsPanel title="Application information" copy="Non-sensitive metadata reported by the running deployment."><ReadOnlyGrid data={draft.application}/><div className="module-list"><strong>Supported modules</strong><span>Dashboard</span><span>Devices</span><span>Network</span><span>Alerts</span><span>Tickets</span><span>Users</span><span>Audit</span><span>Reports</span><span>Settings</span></div></SettingsPanel>}
  </section></div></DashboardLayout>
}

function SettingsPanel({title,copy,children}:{title:string;copy:string;children:React.ReactNode}){return <article className="settings-panel"><header><div><span>Configuration</span><h2>{title}</h2><p>{copy}</p></div><Icon name="settings"/></header><div className="settings-panel-body">{children}</div></article>}
function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange:(value:string)=>void;type?:string}){return <label><span>{label}</span><input required type={type} value={value} onChange={event=>onChange(event.target.value)}/></label>}
function NumberField({label,value,min,max,onChange}:{label:string;value:number;min:number;max:number;onChange:(value:number)=>void}){return <label><span>{label}</span><input type="number" value={value} min={min} max={max} onChange={event=>onChange(Number(event.target.value))}/></label>}
function SelectField({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(value:string)=>void}){return <label><span>{label}</span><select value={value} onChange={event=>onChange(event.target.value)}>{options.map(option=><option key={option}>{option}</option>)}</select></label>}
function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(value:boolean)=>void}){return <label className="settings-toggle"><span><strong>{label}</strong><small>{checked?"Enabled":"Disabled"}</small></span><input type="checkbox" checked={checked} onChange={event=>onChange(event.target.checked)}/><i/></label>}
function SaveButton({saving,onClick}:{saving:boolean;onClick:()=>Promise<void>}){return <button className="primary-action settings-save" disabled={saving} onClick={()=>void onClick()}>{saving?"Saving…":"Save changes"}</button>}
function ReadOnlyGrid({data}:{data:Record<string,unknown>}){return <dl className="settings-readonly">{Object.entries(data).map(([key,value])=><div key={key}><dt>{key.replaceAll("_"," ")}</dt><dd>{typeof value==="boolean"?(value?"Yes":"No"):Array.isArray(value)?value.join(", "):value==null?"Unavailable":String(value)}</dd></div>)}</dl>}
function HierarchySummary({title,copy,items,link}:{title:string;copy:string;items:Array<{id:string;name:string;is_active:boolean}>;link:string}){return <SettingsPanel title={title} copy={copy}><div className="settings-record-list">{items.length?items.map(item=><div key={item.id}><span><i className={item.is_active?"active":""}/><strong>{item.name}</strong></span><small>{item.is_active?"Active":"Inactive"}</small></div>):<p>No real records are stored.</p>}</div><Link className="primary-action settings-manage" to={link}>Manage in Locations & structure</Link></SettingsPanel>}
