import { clearAuthToken, getAuthToken } from "./auth";

// Same-origin by default; Vite and nginx proxy this path to FastAPI.
const API_URL = import.meta.env.VITE_API_URL ?? "/api/v1";

export class ApiError extends Error { status: number; constructor(message: string, status: number) { super(message); this.status = status; } }

const inFlightGets = new Map<string, Promise<unknown>>();

function errorDetailMessage(detail: unknown): string | undefined {
  if (typeof detail === "string") return detail;
  if (Array.isArray(detail)) {
    return detail
      .map((item) => typeof item === "object" && item !== null && "msg" in item && typeof item.msg === "string" ? item.msg : "Invalid value")
      .join(" ");
  }
  if (typeof detail === "object" && detail !== null && "message" in detail && typeof detail.message === "string") {
    return detail.message;
  }
  return undefined;
}

export async function api<T>(path: string, init: RequestInit = {}): Promise<T> {
  const method = (init.method ?? "GET").toUpperCase();
  const token = getAuthToken();
  const requestKey = method === "GET" && !init.signal ? `${token ?? "anonymous"}:${path}` : "";
  const existing = requestKey ? inFlightGets.get(requestKey) : undefined;
  if (existing) return existing as Promise<T>;

  const request = performRequest<T>(path, init, token);
  if (!requestKey) return request;
  inFlightGets.set(requestKey, request);
  try { return await request; }
  finally { inFlightGets.delete(requestKey); }
}

async function performRequest<T>(path: string, init: RequestInit, token: string | null): Promise<T> {
  const headers = new Headers(init.headers);
  const activeProperty = window.localStorage.getItem("hiop.active_property_id");
  if (activeProperty && !headers.has("X-HIOP-Property-ID")) headers.set("X-HIOP-Property-ID", activeProperty);
  if (init.body && !(init.body instanceof FormData) && !headers.has("Content-Type")) headers.set("Content-Type", "application/json");
  if (token) headers.set("Authorization", `Bearer ${token}`);
  let response: Response;
  try { response = await fetch(`${API_URL}${path}`, { ...init, headers }); }
  catch { throw new ApiError("Cannot reach the HIOP backend. Confirm FastAPI is running.", 0); }
  if (response.status === 401) { clearAuthToken(); window.dispatchEvent(new Event("hiop:unauthorized")); }
  if (!response.ok) {
    let message = `Request failed (${response.status})`;
    try {
      const body: unknown = await response.json();
      if (typeof body === "object" && body !== null && "detail" in body) {
        message = errorDetailMessage(body.detail) ?? message;
      }
    } catch { /* non-JSON response */ }
    throw new ApiError(message, response.status);
  }
  if (response.status === 204) return undefined as T;
  return response.json() as Promise<T>;
}

function queryString(values: Record<string, string | number | boolean | undefined>) {
  const params = new URLSearchParams();
  Object.entries(values).forEach(([key, value]) => { if (value !== undefined && value !== "") params.set(key, String(value)); });
  const query = params.toString();
  return query ? `?${query}` : "";
}

async function download(path: string) {
  const token = getAuthToken();
  let response: Response;
  try { response = await fetch(`${API_URL}${path}`, { headers: token ? { Authorization: `Bearer ${token}` } : {} }); }
  catch { throw new ApiError("Cannot reach the HIOP backend. Confirm FastAPI is running.", 0); }
  if (response.status === 401) { clearAuthToken(); window.dispatchEvent(new Event("hiop:unauthorized")); }
  if (!response.ok) throw new ApiError(`Export failed (${response.status})`, response.status);
  const disposition = response.headers.get("Content-Disposition") ?? "";
  return { blob: await response.blob(), filename: disposition.match(/filename="?([^";]+)"?/)?.[1] ?? "hiop-audit.csv" };
}

export const endpoints = {
  login: (email: string, password: string) => api<{access_token:string}>("/auth/login", { method: "POST", body: JSON.stringify({ email, password }) }),
  me: () => api<import("./types").User>("/auth/me"),
  context: () => api<unknown>("/context"),
  selectProperty: (property_id:string) => api<unknown>("/context/property", {method:"POST",body:JSON.stringify({property_id})}),
  operationsSummary: (id:string) => api<{overall_status:string;critical_alerts:number;services:number}>(`/properties/${id}/operations-summary`),
  configurationVersions: () => api<{items:{id:string;version_number:number;checksum:string;format:string}[];total:number}>("/configuration-management/versions"),
  buildings: (query = "") => api<{items:import("./types").Building[];total:number}>(`/buildings${query}`),
  floors: (query = "") => api<{items:import("./types").Floor[];total:number}>(`/floors${query}`),
  zones: (query = "") => api<{items:import("./types").Zone[];total:number}>(`/zones${query}`),
  organizations: (query = "") => api<{items:import("./types").Organization[];total:number;page:number;page_size:number}>(`/organizations${query}`),
  properties: (query = "") => api<{items:import("./types").Property[];total:number;page:number;page_size:number}>(`/properties${query}`),
  createOrganization: (body: unknown) => api<import("./types").Organization>("/organizations", {method:"POST", body:JSON.stringify(body)}),
  createProperty: (body: unknown) => api<import("./types").Property>("/properties", {method:"POST", body:JSON.stringify(body)}),
  updateProperty: (id:string, body: unknown) => api<import("./types").Property>(`/properties/${id}`, {method:"PATCH", body:JSON.stringify(body)}),
  archiveProperty: (id:string) => api<void>(`/properties/${id}`, {method:"DELETE"}),
  dashboard: () => api<import("./types").DashboardData>("/dashboard/"),
  devices: () => api<import("./types").Device[]>("/devices/"),
  device: (id: string) => api<import("./types").Device>(`/devices/${id}`),
  createDevice: (body: import("./types").DeviceInput) => api<import("./types").Device>("/devices/", { method: "POST", body: JSON.stringify(body) }),
  updateDevice: (id: string, body: Partial<import("./types").DeviceInput>) => api<import("./types").Device>(`/devices/${id}`, { method: "PUT", body: JSON.stringify(body) }),
  retireDevice: (id: string) => api<{message:string}>(`/devices/${id}`, { method: "DELETE" }),
  deviceScans: (id: string) => api<import("./types").Scan[]>(`/devices/${id}/scans`),
  deviceAlerts: (id: string) => api<import("./types").Alert[]>(`/devices/${id}/alerts`),
  deviceTickets: (id: string) => api<import("./types").Ticket[]>(`/devices/${id}/tickets`),
  deviceAuditLogs: (id: string) => api<import("./types").AuditLog[]>(`/devices/${id}/audit-logs`),
  scanDevice: (device_id: string) => api<import("./types").Scan>("/network/scan", { method: "POST", body: JSON.stringify({ device_id }) }),
  scanAll: () => api<{total_devices:number;online:number;offline:number;results:import("./types").Scan[]}>("/network/scan-all", { method: "POST" }),
  scanRange: (network: string) => api<Array<{ip_address:string;status:string;response_time:number|null}>>("/network/scan-range", { method: "POST", body: JSON.stringify({ network }) }),
  scanHistory: (limit = 100) => api<import("./types").Scan[]>(`/network/history?limit=${limit}`),
  tickets: () => api<import("./types").Ticket[]>("/tickets/"),
  ticket: (id: string) => api<import("./types").Ticket>(`/tickets/${id}`),
  createTicket: (body: import("./types").TicketInput) => api<import("./types").Ticket>("/tickets/", { method: "POST", body: JSON.stringify(body) }),
  updateTicket: (id: string, body: Partial<import("./types").Ticket>) => api<import("./types").Ticket>(`/tickets/${id}`, { method: "PUT", body: JSON.stringify(body) }),
  assignTicket: (id: string, assignedTo: string) => api<import("./types").Ticket>(`/tickets/${id}/assign?assigned_to=${encodeURIComponent(assignedTo)}`, { method: "PATCH" }),
  closeTicket: (id: string) => api<import("./types").Ticket>(`/tickets/${id}/close`, { method: "PATCH" }),
  deleteTicket: (id: string) => api<{message:string}>(`/tickets/${id}`, { method: "DELETE" }),
  alerts: () => api<import("./types").Alert[]>("/alerts"),
  acknowledgeAlert: (id: string) => api<{id:string;acknowledged:boolean}>(`/alerts/${id}/acknowledge`, { method: "PATCH" }),
  auditLogs: (filters: import("./types").AuditFilters = {}, signal?: AbortSignal) => api<import("./types").AuditLogPage>(`/audit-logs${queryString(filters)}`, { signal }),
  auditLog: (id: string) => api<import("./types").AuditLog>(`/audit-logs/${id}`),
  exportAuditLogs: (filters: import("./types").AuditFilters = {}) => download(`/audit-logs/export${queryString(filters)}`),
  reportsSummary: (filters: Pick<import("./types").ReportFilters, "start_date" | "end_date"> = {}) => api<import("./types").ReportsSummary>(`/reports/summary${queryString(filters)}`),
  report: (name: import("./types").ReportKey, filters: import("./types").ReportFilters = {}) => api<import("./types").ReportPage>(`/reports/${name}${queryString(filters)}`),
  exportReport: (name: import("./types").ReportKey, filters: import("./types").ReportFilters = {}) => download(`/reports/${name}/export${queryString(filters)}`),
  users: () => api<import("./types").User[]>("/users"),
  user: (id: string) => api<import("./types").User>(`/users/${id}`),
  userAudit: (id: string) => api<import("./types").AuditLog[]>(`/users/${id}/audit`),
  userRoles: () => api<string[]>("/users/roles"),
  eligibleAssignees: () => api<import("./types").User[]>("/users/eligible-assignees"),
  createUser: (body: import("./types").UserInput) => api<import("./types").User>("/users", { method: "POST", body: JSON.stringify(body) }),
  updateUser: (id: string, body: Pick<import("./types").UserInput, "username" | "email">) => api<import("./types").User>(`/users/${id}`, { method: "PATCH", body: JSON.stringify(body) }),
  changeUserRole: (id: string, role: string) => api<import("./types").User>(`/users/${id}/role`, { method: "PATCH", body: JSON.stringify({ role }) }),
  changeUserStatus: (id: string, is_active: boolean) => api<import("./types").User>(`/users/${id}/status`, { method: "PATCH", body: JSON.stringify({ is_active }) }),
  resetUserPassword: (id: string, password: string) => api<{message:string}>(`/users/${id}/reset-password`, { method: "POST", body: JSON.stringify({ password }) }),
  deactivateUser: (id: string) => api<void>(`/users/${id}`, { method: "DELETE" }),
  settings: () => api<import("./types").SettingsBundle>("/settings"),
  publicSettings: () => api<import("./types").PublicSettings>("/settings/public"),
  updateGeneralSettings: (body: import("./types").GeneralSettings) => api<import("./types").SettingsBundle>("/settings/general", { method: "PUT", body: JSON.stringify(body) }),
  updateOrganizationSettings: (body: import("./types").OrganizationSettings) => api<import("./types").SettingsBundle>("/settings/organization", { method: "PUT", body: JSON.stringify(body) }),
  updateNetworkSettings: (body: import("./types").NetworkSettings) => api<import("./types").SettingsBundle>("/settings/network", { method: "PUT", body: JSON.stringify(body) }),
  updateNotificationSettings: (body: import("./types").NotificationSettings) => api<import("./types").SettingsBundle>("/settings/notifications", { method: "PUT", body: JSON.stringify(body) }),
  updateDiscoverySettings: (body: import("./types").DiscoverySettings) => api<import("./types").SettingsBundle>("/settings/discovery", { method: "PUT", body: JSON.stringify(body) }),
  updateIncidentSettings: (body: import("./types").IncidentSettings) => api<import("./types").SettingsBundle>("/settings/incidents", { method: "PUT", body: JSON.stringify(body) }),
  systemHealth: () => api<import("./types").SystemHealth>("/settings/system-health"),
  hierarchy: () => api<import("./types").HierarchyCatalog>("/hierarchy"),
  createHierarchy: (kind: import("./types").HierarchyKind, body: Partial<import("./types").HierarchyItem>) => api<import("./types").HierarchyItem>(`/hierarchy/${kind}`, { method: "POST", body: JSON.stringify(body) }),
  updateHierarchy: (kind: import("./types").HierarchyKind, id: string, body: Partial<import("./types").HierarchyItem>) => api<import("./types").HierarchyItem>(`/hierarchy/${kind}/${id}`, { method: "PUT", body: JSON.stringify(body) }),
  deactivateHierarchy: (kind: import("./types").HierarchyKind, id: string) => api<void>(`/hierarchy/${kind}/${id}`, { method: "DELETE" }),
  discovery: (filters: import("./types").DiscoveryFilters = {}) => api<import("./types").DiscoveryPage>(`/discovery${queryString(filters)}`),
  discoveryDetail: (id: string) => api<import("./types").DiscoveredDevice>(`/discovery/${id}`),
  discoveryStats: () => api<import("./types").DiscoveryStats>("/discovery/stats"),
  runDiscovery: (range_scanned: string) => api<import("./types").DiscoveryRun>("/discovery/run", { method: "POST", body: JSON.stringify({ range_scanned }) }),
  approveDiscovery: (id: string, inventory: import("./types").InventoryApproval) => api<import("./types").ApprovalResponse>(`/discovery/${id}/approve`, { method: "POST", body: JSON.stringify(inventory) }),
  ignoreDiscovery: (id: string) => api<import("./types").DiscoveredDevice>(`/discovery/${id}/ignore`, { method: "POST" }),
  rejectDiscovery: (id: string, reason?: string) => api<import("./types").DiscoveredDevice>(`/discovery/${id}/reject`, { method: "POST", body: JSON.stringify({ reason: reason || null }) }),
  bulkApproveDiscovery: (items: import("./types").BulkApprovalItem[]) => api<import("./types").BulkActionResponse>("/discovery/bulk-approve", { method: "POST", body: JSON.stringify({ items }) }),
  bulkIgnoreDiscovery: (discovery_ids: string[]) => api<import("./types").BulkActionResponse>("/discovery/bulk-ignore", { method: "POST", body: JSON.stringify({ discovery_ids }) }),
  bulkRejectDiscovery: (discovery_ids: string[], reason?: string) => api<import("./types").BulkActionResponse>("/discovery/bulk-reject", { method: "POST", body: JSON.stringify({ discovery_ids, reason: reason || null }) }),
  exportDiscovery: () => download("/discovery/export"),
  importSessions: (filters: import("./types").ImportSessionFilters = {}) => api<import("./types").ImportSessionPage>(`/imports${queryString(filters)}`),
  importSession: (id: string) => api<import("./types").ImportSession>(`/imports/${id}`),
  uploadImport: (file: File, signal?: AbortSignal) => { const body = new FormData(); body.append("file", file); return api<import("./types").ImportUploadResponse>("/imports/device-inventory/upload", { method: "POST", body, signal }); },
  importColumns: (id: string, worksheet?: string) => api<import("./types").ImportColumnDetection>(`/imports/${id}/columns${queryString({ worksheet })}`),
  saveImportMapping: (id: string, mapping: Record<string, string | null>, worksheet?: string | null) => api<import("./types").ImportColumnDetection>(`/imports/${id}/mapping`, { method: "POST", body: JSON.stringify({ mapping, worksheet: worksheet || null }) }),
  validateImport: (id: string) => api<import("./types").ImportSession>(`/imports/${id}/validate`, { method: "POST" }),
  importRows: (id: string, filters: import("./types").ImportRowFilters = {}) => api<import("./types").ImportedDevicePage>(`/imports/${id}/rows${queryString(filters)}`),
  importRow: (sessionId: string, rowId: string) => api<import("./types").ImportedDevice>(`/imports/${sessionId}/rows/${rowId}`),
  importErrors: (id: string) => api<import("./types").ImportErrorReport>(`/imports/${id}/errors`),
  exportImportErrors: (id: string) => download(`/imports/${id}/errors/export`),
  cancelImport: (id: string) => api<import("./types").ImportSession>(`/imports/${id}/cancel`, { method: "POST" }),
  runImportMatching: (id: string) => api<import("./types").ImportSummary>(`/imports/${id}/match`, { method: "POST" }),
  recomputeImportMatches: (id: string) => api<import("./types").ImportSummary>(`/imports/${id}/matches/recompute`, { method: "POST" }),
  importMatches: (id: string, filters: import("./types").ImportMatchFilters = {}) => api<import("./types").ImportMatchPage>(`/imports/${id}/matches${queryString(filters)}`),
  importRowMatches: (sessionId: string, rowId: string) => api<import("./types").ImportMatchCandidate[]>(`/imports/${sessionId}/rows/${rowId}/matches`),
  importMergePlan: (sessionId: string, rowId: string, candidateId?: string) => api<import("./types").MergePlan>(`/imports/${sessionId}/rows/${rowId}/merge-plan${queryString({ candidate_id: candidateId })}`),
  acceptImportMatch: (sessionId: string, rowId: string, candidateId: string) => api<import("./types").ImportMatchCandidate>(`/imports/${sessionId}/rows/${rowId}/accept-match`, { method: "POST", body: JSON.stringify({ candidate_id: candidateId }) }),
  rejectImportMatch: (sessionId: string, rowId: string, candidateId: string) => api<import("./types").ImportMatchCandidate>(`/imports/${sessionId}/rows/${rowId}/reject-match`, { method: "POST", body: JSON.stringify({ candidate_id: candidateId }) }),
  markImportCreateNew: (sessionId: string, rowId: string) => api<import("./types").ImportedDevice>(`/imports/${sessionId}/rows/${rowId}/mark-create-new`, { method: "POST" }),
  markImportSkip: (sessionId: string, rowId: string) => api<import("./types").ImportedDevice>(`/imports/${sessionId}/rows/${rowId}/mark-skip`, { method: "POST" }),
  importLocationSuggestion: (sessionId: string, rowId: string) => api<import("./types").ImportLocationSuggestion>(`/imports/${sessionId}/rows/${rowId}/location-suggestion`),
  importLocationSuggestions: (sessionId: string) => api<import("./types").ImportLocationSuggestion[]>(`/imports/${sessionId}/locations`),
  reviewImportLocation: (sessionId: string, rowId: string, body: import("./types").LocationReviewInput) => api<import("./types").ImportLocationSuggestion>(`/imports/${sessionId}/rows/${rowId}/location-suggestion`, { method: "POST", body: JSON.stringify(body) }),
  setImportDisposition: (sessionId: string, rowId: string, body: {disposition:import("./types").FinalDisposition;approved_fields?:string[];approved_overwrites?:string[]}) => api<import("./types").ImportedDevice>(`/imports/${sessionId}/rows/${rowId}/disposition`, { method: "POST", body: JSON.stringify(body) }),
  importReadiness: (id: string) => api<import("./types").ImportReadiness>(`/imports/${id}/readiness`),
  importExecutionPlan: (id: string, persist = false) => api<import("./types").ImportReadiness>(`/imports/${id}/execution-plan${queryString({persist:persist ? "true" : undefined})}`),
  finalizeImport: (id: string, planVersion: number, idempotencyKey: string) => api<import("./types").ImportResults>(`/imports/${id}/finalize`, { method: "POST", body: JSON.stringify({plan_version:planVersion,idempotency_key:idempotencyKey,confirm_inventory_mutation:true,confirm_rollback_limits:true}) }),
  importResults: (id: string, page = 1) => api<import("./types").ImportResults>(`/imports/${id}/results${queryString({page,page_size:50})}`),
  importRollbackPreview: (id: string) => api<import("./types").RollbackPreview>(`/imports/${id}/rollback-preview`),
  rollbackImport: (id: string) => api<import("./types").ImportResults>(`/imports/${id}/rollback`, { method: "POST", body: JSON.stringify({confirmation:"ROLLBACK"}) }),
  retryFailedImport: (id: string) => api<import("./types").ImportResults>(`/imports/${id}/retry-failed`, { method: "POST" }),
  adOverview: () => api<import("./types").ADOverview>("/active-directory/overview"),
  adSettings: () => api<Record<string,unknown>>("/active-directory/settings"),
  adConnections: (filters: Record<string,string|number|undefined> = {}) => api<import("./types").ADPage<import("./types").ADConnection>>(`/active-directory/connections${queryString(filters)}`),
  adConnection: (id:string) => api<import("./types").ADConnection>(`/active-directory/connections/${id}`),
  createADConnection: (body:import("./types").ADConnectionInput) => api<import("./types").ADConnection>("/active-directory/connections", {method:"POST",body:JSON.stringify(body)}),
  updateADConnection: (id:string, body:Partial<import("./types").ADConnectionInput>) => api<import("./types").ADConnection>(`/active-directory/connections/${id}`, {method:"PATCH",body:JSON.stringify(body)}),
  disableADConnection: (id:string) => api<import("./types").ADConnection>(`/active-directory/connections/${id}/disable`, {method:"POST"}),
  updateADSecret: (id:string, secret:string) => api<import("./types").ADConnection>(`/active-directory/connections/${id}/secret`, {method:"POST",body:JSON.stringify({bind_secret:secret})}),
  testADConnection: (id:string) => api<import("./types").ADTestResult>(`/active-directory/connections/${id}/test`, {method:"POST"}),
  adRootDse: (id:string) => api<import("./types").ADRootDse>(`/active-directory/connections/${id}/root-dse`),
  adSyncConfig: (id:string) => api<import("./types").ADSyncConfig>(`/active-directory/connections/${id}/sync-config`),
  updateADSyncConfig: (id:string, body:Partial<import("./types").ADSyncConfig>) => api<import("./types").ADSyncConfig>(`/active-directory/connections/${id}/sync-config`, {method:"PUT",body:JSON.stringify(body)}),
  startADSync: (id:string, body:{sync_mode:"full"|"incremental";dry_run:boolean;object_types:string[]}) => api<{sync_run_id:string;status:string;warnings:string[]}>(`/active-directory/connections/${id}/sync`, {method:"POST",body:JSON.stringify(body)}),
  adSyncRuns: (filters:Record<string,string|number|undefined>={}) => api<import("./types").ADPage<import("./types").ADSyncRun>>(`/active-directory/sync-runs${queryString(filters)}`),
  adSyncRun: (id:string) => api<import("./types").ADSyncRun>(`/active-directory/sync-runs/${id}`),
  cancelADSync: (id:string) => api<import("./types").ADSyncRun>(`/active-directory/sync-runs/${id}/cancel`, {method:"POST"}),
  adSyncSummary: (id:string) => api<Record<string,unknown>>(`/active-directory/sync-runs/${id}/summary`),
  adObjects: (filters:Record<string,string|number|undefined>={}) => api<import("./types").ADPage<import("./types").ADObject>>(`/active-directory/objects${queryString(filters)}`),
  adObject: (id:string) => api<import("./types").ADObject>(`/active-directory/objects/${id}`),
  adObjectChanges: (id:string, page=1) => api<import("./types").ADPage<import("./types").ADChange>>(`/active-directory/objects/${id}/changes${queryString({page,page_size:50})}`),
  adMatches: (filters:Record<string,string|number|undefined>={}) => api<import("./types").ADPage<import("./types").ADMatch>>(`/active-directory/matches${queryString(filters)}`),
  runADMatching: (id:string, body={object_types:["user","computer"],recompute:false,dry_run:false}) => api<Record<string,unknown>>(`/active-directory/connections/${id}/match`, {method:"POST",body:JSON.stringify(body)}),
  adReconciliationPlan: (id:string) => api<Record<string,unknown>>(`/active-directory/objects/${id}/reconciliation-plan`),
  resolveADObject: (id:string, body:Record<string,unknown>) => api<Record<string,unknown>>(`/active-directory/objects/${id}/resolve`, {method:"POST",body:JSON.stringify(body)}),
  ignoreADObject: (id:string) => api<Record<string,unknown>>(`/active-directory/objects/${id}/ignore`, {method:"POST"}),
  adMappings: (connectionId:string, kind:string) => api<import("./types").ADMapping[]>(`/active-directory/connections/${connectionId}/mappings/${kind}`),
  createADMapping: (connectionId:string, kind:"departments"|"ous"|"roles", body:Record<string,unknown>) => api<import("./types").ADMapping>(`/active-directory/connections/${connectionId}/mappings/${kind}`, {method:"POST",body:JSON.stringify(body)}),
  deleteADMapping: (connectionId:string, kind:string, id:string) => api<void>(`/active-directory/connections/${connectionId}/mappings/${kind}/${id}`, {method:"DELETE"}),
  previewADMapping: (connectionId:string, kind:string, id:string) => api<{items:Array<Record<string,unknown>>;total:number;truncated:boolean}>(`/active-directory/connections/${connectionId}/mappings/${kind}/${id}/preview`),
  adReviewQueue: (filters:Record<string,string|number|undefined>={}) => api<import("./types").ADPage<Record<string,unknown>>>(`/active-directory/review-queue${queryString(filters)}`),
  snmpCredentials: (filters:Record<string,string|number|undefined>={}) => api<import("./types").SNMPPage<import("./types").SNMPCredential>>(`/snmp/credentials${queryString(filters)}`),
  automationWorkflows: () => api<{items:import("./types").AutomationWorkflow[]}>("/automation/workflows"),
  createAutomationWorkflow: (body:{property_id:string|null;name:string;code:string;workflow_category:string}) => api<import("./types").AutomationWorkflow>("/automation/workflows",{method:"POST",body:JSON.stringify(body)}),
  automationVersions: (id:string) => api<{items:import("./types").AutomationVersion[]}>(`/automation/workflows/${id}/versions`),
  createAutomationVersion: (id:string,body:{trigger_definition:Record<string,unknown>;workflow_graph:Record<string,unknown>}) => api<import("./types").AutomationVersion>(`/automation/workflows/${id}/versions`,{method:"POST",body:JSON.stringify(body)}),
  automationSteps: (versionId:string) => api<{items:import("./types").AutomationStep[]}>(`/automation/workflow-versions/${versionId}/steps`),
  createAutomationStep: (versionId:string,body:Record<string,unknown>) => api<import("./types").AutomationStep>(`/automation/workflow-versions/${versionId}/steps`,{method:"POST",body:JSON.stringify(body)}),
  automationPlan: (versionId:string) => api<{steps:import("./types").AutomationStep[];step_count:number;approval_checkpoints:number}>(`/automation/workflow-versions/${versionId}/plan`),
  approveAutomationVersion: (versionId:string) => api<import("./types").AutomationVersion>(`/automation/workflow-versions/${versionId}/approve`,{method:"POST"}),
  enableAutomationWorkflow: (id:string) => api<{enabled:boolean;status:string}>(`/automation/workflows/${id}/enable`,{method:"POST"}),
  runAutomationWorkflow: (id:string,dry_run=true) => api<{run_id:string;status:string;dry_run:boolean}>(`/automation/workflows/${id}/run`,{method:"POST",body:JSON.stringify({dry_run,idempotency_key:crypto.randomUUID()})}),
  automationRuns: () => api<{items:import("./types").AutomationRun[]}>("/automation/runs"),
  automationApprovals: () => api<{items:import("./types").AutomationApproval[]}>("/automation/approvals"),
  decideAutomationApproval: (id:string,decision:"approved"|"rejected",reason="") => api<{status:string;run_status:string}>(`/automation/approvals/${id}/decision`,{method:"POST",body:JSON.stringify({decision,reason:reason||null})}),
  automationTriggers: () => api<{items:import("./types").AutomationTrigger[]}>("/automation/triggers"),
  createAutomationTrigger: (body:Record<string,unknown>) => api<import("./types").AutomationTrigger>("/automation/triggers",{method:"POST",body:JSON.stringify(body)}),
  setAutomationTrigger: (id:string,enabled:boolean) => api<{enabled:boolean}>(`/automation/triggers/${id}/${enabled?"enable":"disable"}`,{method:"POST"}),
  validateAutomationTrigger: (body:Record<string,unknown>) => api<{valid:boolean;errors:string[];warnings:string[];risk:string}>("/automation/trigger-validation",{method:"POST",body:JSON.stringify(body)}),
  testAutomationTrigger: (id:string,body:Record<string,unknown>) => api<Record<string,unknown>>(`/automation/triggers/${id}/test`,{method:"POST",body:JSON.stringify(body)}),
  automationSchedules: () => api<{items:import("./types").AutomationSchedule[]}>("/automation/schedules"),
  createAutomationSchedule: (body:Record<string,unknown>) => api<import("./types").AutomationSchedule>("/automation/schedules",{method:"POST",body:JSON.stringify(body)}),
  setAutomationSchedule: (id:string,enabled:boolean) => api<{enabled:boolean}>(`/automation/schedules/${id}/${enabled?"enable":"disable"}`,{method:"POST"}),
  runAutomationSchedule: (id:string) => api<{accepted:boolean;schedule_id:string}>(`/automation/schedules/${id}/run-now`,{method:"POST"}),
  automationEvents: () => api<{items:import("./types").AutomationEvent[]}>("/automation/events"),
  automationEventCatalogue: () => api<{items:import("./types").AutomationEventDefinition[]}>("/automation/event-catalogue"),
  reprocessAutomationEvent: (id:string,reason:string,trigger_ids:string[]=[]) => api<Record<string,unknown>>(`/automation/events/${id}/reprocess`,{method:"POST",body:JSON.stringify({reason,trigger_ids})}),
  automationTriggerHistory: () => api<{items:Array<{id:string;status:string;suppression_reason:string|null;created_at:string}>}>("/automation/trigger-executions"),
  automationSchedulerStatus: () => api<{scheduler_running:boolean;jobs:Array<{id:string;next_run_time:string|null}>;enabled_schedules:number}>("/automation/scheduler-status"),
  automationCorrelationGroups: () => api<{items:import("./types").AutomationCorrelationGroup[]}>("/automation/correlation-groups"),
  automationDeadLetters: () => api<{items:import("./types").AutomationDeadLetter[]}>("/automation/dead-letter-events"),
  retryAutomationDeadLetter: (id:string) => api<{status:string}>(`/automation/dead-letter-events/${id}/retry`,{method:"POST"}),
  ignoreAutomationDeadLetter: (id:string) => api<{status:string}>(`/automation/dead-letter-events/${id}/ignore`,{method:"POST"}),
  automationRetentionPreview: (days=30) => api<{cutoff:string;eligible_events:number;eligible_outbox:number;protected_dead_letters:number}>(`/automation/retention/preview?retention_days=${days}`),
  automationReportSummary: () => api<import("./types").AutomationReportSummary>("/automation/reports/summary"),
  incidents: (params:Record<string,string|number|boolean|undefined>={}) => api<{items:import("./types").OperationalIncident[];total:number;page:number;page_size:number}>(`/incidents${queryString(params)}`),
  incident: (id:string) => api<import("./types").OperationalIncident>(`/incidents/${id}`),
  createIncident: (body:Record<string,unknown>) => api<import("./types").OperationalIncident>("/incidents",{method:"POST",body:JSON.stringify(body)}),
  similarIncidents: (body:Record<string,unknown>) => api<{items:import("./types").OperationalIncident[]}>("/incidents/similar",{method:"POST",body:JSON.stringify(body)}),
  updateIncident: (id:string,body:Record<string,unknown>) => api<import("./types").OperationalIncident>(`/incidents/${id}`,{method:"PATCH",body:JSON.stringify(body)}),
  incidentTransition: (id:string,action:string,reason="") => api<import("./types").OperationalIncident>(`/incidents/${id}/${action}`,{method:"POST",body:JSON.stringify({reason:reason||null})}),
  incidentTasks: (id:string) => api<{items:import("./types").IncidentTask[]}>(`/incidents/${id}/tasks`),
  createIncidentTask: (id:string,body:Record<string,unknown>) => api<import("./types").IncidentTask>(`/incidents/${id}/tasks`,{method:"POST",body:JSON.stringify(body)}),
  incidentTaskAction: (incidentId:string,taskId:string,action:string,body:Record<string,unknown>={}) => api<import("./types").IncidentTask>(`/incidents/${incidentId}/tasks/${taskId}/${action}`,{method:"POST",body:JSON.stringify(body)}),
  incidentParticipants: (id:string) => api<{items:import("./types").IncidentParticipant[]}>(`/incidents/${id}/participants`),
  addIncidentParticipant: (id:string,body:Record<string,unknown>) => api<import("./types").IncidentParticipant>(`/incidents/${id}/participants`,{method:"POST",body:JSON.stringify(body)}),
  incidentTimeline: (id:string) => api<{items:import("./types").IncidentTimelineEntry[];total:number}>(`/incidents/${id}/timeline`),
  incidentEvidence: (id:string) => api<{items:import("./types").IncidentEvidence[];total:number}>(`/incidents/${id}/evidence`),
  addIncidentEvidence: (id:string,body:Record<string,unknown>) => api<import("./types").IncidentEvidence>(`/incidents/${id}/evidence`,{method:"POST",body:JSON.stringify(body)}),
  incidentCommunications: (id:string) => api<{items:import("./types").IncidentCommunication[]}>(`/incidents/${id}/communications`),
  previewIncidentCommunication: (id:string,body:Record<string,unknown>) => api<{subject:string;message:string;external_delivery_configured:boolean}>(`/incidents/${id}/communications/preview`,{method:"POST",body:JSON.stringify(body)}),
  sendIncidentCommunication: (id:string,body:Record<string,unknown>) => api<import("./types").IncidentCommunication>(`/incidents/${id}/communications/send`,{method:"POST",body:JSON.stringify(body)}),
  incidentChecklists: (id:string) => api<{items:import("./types").IncidentChecklistItem[]}>(`/incidents/${id}/checklists`),
  incidentChecklistAction: (incidentId:string,itemId:string,action:string,body:Record<string,unknown>) => api<import("./types").IncidentChecklistItem>(`/incidents/${incidentId}/checklists/${itemId}/${action}`,{method:"POST",body:JSON.stringify(body)}),
  incidentDecisions: (id:string) => api<{items:import("./types").IncidentDecision[]}>(`/incidents/${id}/decisions`),
  decideIncident: (incidentId:string,decisionId:string,decision:string,rationale:string) => api<import("./types").IncidentDecision>(`/incidents/${incidentId}/decisions/${decisionId}/decide`,{method:"POST",body:JSON.stringify({decision,rationale})}),
  incidentRecommendations: (id:string) => api<{items:import("./types").IncidentRecommendation[]}>(`/incidents/${id}/recommendations`),
  incidentRecommendationAction: (incidentId:string,recommendationId:string,action:string,reason="") => api<import("./types").IncidentRecommendation>(`/incidents/${incidentId}/recommendations/${recommendationId}/${action}`,{method:"POST",body:JSON.stringify({reason:reason||null})}),
  incidentRecoveryReadiness: (id:string) => api<{ready:boolean;open_tasks:number;pending_required_checklist:number;evidence_count:number;manual_confirmation_required:boolean}>(`/incidents/${id}/recovery-readiness`),
  verifyIncidentRecovery: (id:string,reason:string) => api<import("./types").OperationalIncident>(`/incidents/${id}/verify-recovery`,{method:"POST",body:JSON.stringify({reason})}),
  incidentPlaybooks: (propertyId?:string) => api<{items:import("./types").OperationalPlaybook[]}>(`/incidents/playbooks${queryString({property_id:propertyId})}`),
  createIncidentPlaybook: (body:Record<string,unknown>) => api<import("./types").OperationalPlaybook>("/incidents/playbooks",{method:"POST",body:JSON.stringify(body)}),
  incidentPlaybookVersions: (id:string) => api<{items:import("./types").OperationalPlaybookVersion[]}>(`/incidents/playbooks/${id}/versions`),
  createIncidentPlaybookVersion: (id:string,body:Record<string,unknown>) => api<import("./types").OperationalPlaybookVersion>(`/incidents/playbooks/${id}/versions`,{method:"POST",body:JSON.stringify(body)}),
  incidentPlaybookSteps: (versionId:string) => api<{items:import("./types").OperationalPlaybookStep[]}>(`/incidents/playbook-versions/${versionId}/steps`),
  createIncidentPlaybookStep: (versionId:string,body:Record<string,unknown>) => api<import("./types").OperationalPlaybookStep>(`/incidents/playbook-versions/${versionId}/steps`,{method:"POST",body:JSON.stringify(body)}),
  incidentPlaybookVersionAction: (versionId:string,action:string,reason="") => api<Record<string,unknown>>(`/incidents/playbook-versions/${versionId}/${action}`,{method:"POST",body:JSON.stringify({reason:reason||null})}),
  startIncidentPlaybook: (incidentId:string,playbookId:string) => api<import("./types").IncidentPlaybookRun>(`/incidents/${incidentId}/playbooks/${playbookId}/start`,{method:"POST"}),
  incidentPlaybookRuns: (incidentId:string) => api<{items:import("./types").IncidentPlaybookRun[]}>(`/incidents/${incidentId}/playbook-runs`),
  incidentPlaybookRun: (runId:string) => api<import("./types").IncidentPlaybookRun>(`/incidents/playbook-runs/${runId}`),
  incidentPlaybookRunSteps: (runId:string) => api<{items:import("./types").IncidentPlaybookStepRun[]}>(`/incidents/playbook-runs/${runId}/steps`),
  controlIncidentPlaybookRun: (runId:string,action:"pause"|"resume"|"cancel") => api<import("./types").IncidentPlaybookRun>(`/incidents/playbook-runs/${runId}/control/${action}`,{method:"POST"}),
  retryIncidentPlaybookStep: (runId:string,stepRunId:string) => api<import("./types").IncidentPlaybookStepRun>(`/incidents/playbook-runs/${runId}/retry-step${queryString({step_run_id:stepRunId})}`,{method:"POST"}),
  compensateIncidentPlaybookStep: (runId:string,stepRunId:string) => api<import("./types").IncidentPlaybookStepRun>(`/incidents/playbook-runs/${runId}/compensate-step${queryString({step_run_id:stepRunId})}`,{method:"POST"}),
  completeIncidentPlaybookStep: (runId:string,stepRunId:string,body:Record<string,unknown>) => api<import("./types").IncidentPlaybookStepRun>(`/incidents/playbook-runs/${runId}/steps/${stepRunId}/complete`,{method:"POST",body:JSON.stringify(body)}),
  incidentReportSummary: (propertyId?:string) => api<import("./types").IncidentReportSummary>(`/incidents/reports/summary${queryString({property_id:propertyId})}`),
  knowledgeDashboard: () => api<import("./types").KnowledgeDashboard>("/knowledge/dashboard"),
  knowledgeArticles: (filters:Record<string,string|number|undefined>={}) => api<{items:import("./types").KnowledgeArticle[];total:number;page:number;page_size:number}>(`/knowledge/articles${queryString(filters)}`),
  knowledgeArticle: (id:string) => api<import("./types").KnowledgeArticle>(`/knowledge/articles/${id}`),
  createKnowledgeArticle: (body:Record<string,unknown>) => api<import("./types").KnowledgeArticle>("/knowledge/articles",{method:"POST",body:JSON.stringify(body)}),
  updateKnowledgeArticle: (id:string,body:Record<string,unknown>) => api<import("./types").KnowledgeArticle>(`/knowledge/articles/${id}`,{method:"PATCH",body:JSON.stringify(body)}),
  knowledgeArticleAction: (id:string,action:string,comments?:string) => api<import("./types").KnowledgeArticle>(`/knowledge/articles/${id}/${action}`,{method:"POST",body:JSON.stringify({comments:comments||null})}),
  knowledgeRevisions: (id:string) => api<{items:import("./types").KnowledgeRevision[]}>(`/knowledge/articles/${id}/revisions`),
  rollbackKnowledgeRevision: (articleId:string,revisionId:string) => api<import("./types").KnowledgeArticle>(`/knowledge/articles/${articleId}/revisions/${revisionId}/rollback`,{method:"POST"}),
  rateKnowledgeArticle: (id:string,rating:number,feedback?:string) => api<Record<string,unknown>>(`/knowledge/articles/${id}/rating`,{method:"POST",body:JSON.stringify({rating,feedback:feedback||null})}),
  favoriteKnowledgeArticle: (id:string) => api<{favorite:boolean}>(`/knowledge/articles/${id}/favorite`,{method:"POST"}),
  knowledgeFavorites: () => api<{items:import("./types").KnowledgeArticle[]}>("/knowledge/favorites"),
  knowledgeRecent: () => api<{items:import("./types").KnowledgeArticle[]}>("/knowledge/recent"),
  knowledgeCategories: () => api<{items:import("./types").KnowledgeCategory[]}>("/knowledge/categories"),
  createKnowledgeCategory: (body:Record<string,unknown>) => api<import("./types").KnowledgeCategory>("/knowledge/categories",{method:"POST",body:JSON.stringify(body)}),
  knowledgeTags: () => api<{items:import("./types").KnowledgeTag[]}>("/knowledge/tags"),
  createKnowledgeTag: (body:Record<string,unknown>) => api<import("./types").KnowledgeTag>("/knowledge/tags",{method:"POST",body:JSON.stringify(body)}),
  knowledgeApprovals: (status?:string) => api<{items:import("./types").KnowledgeApproval[]}>(`/knowledge/approvals${queryString({status})}`),
  runbooks: () => api<{items:import("./types").Runbook[]}>("/knowledge/runbooks"),
  runbook: (id:string) => api<import("./types").Runbook>(`/knowledge/runbooks/${id}`),
  createRunbook: (body:Record<string,unknown>) => api<import("./types").Runbook>("/knowledge/runbooks",{method:"POST",body:JSON.stringify(body)}),
  runbookVersions: (id:string) => api<{items:import("./types").RunbookVersion[]}>(`/knowledge/runbooks/${id}/versions`),
  createRunbookVersion: (id:string,body:Record<string,unknown>) => api<import("./types").RunbookVersion>(`/knowledge/runbooks/${id}/versions`,{method:"POST",body:JSON.stringify(body)}),
  runbookSteps: (versionId:string) => api<{items:import("./types").RunbookStep[]}>(`/knowledge/runbook-versions/${versionId}/steps`),
  createRunbookStep: (versionId:string,body:Record<string,unknown>) => api<import("./types").RunbookStep>(`/knowledge/runbook-versions/${versionId}/steps`,{method:"POST",body:JSON.stringify(body)}),
  runbookVersionAction: (versionId:string,action:"submit-review"|"approve") => api<import("./types").RunbookVersion>(`/knowledge/runbook-versions/${versionId}/${action}`,{method:"POST",body:JSON.stringify({comments:null})}),
  executeRunbook: (id:string,body:Record<string,unknown>) => api<import("./types").RunbookExecution>(`/knowledge/runbooks/${id}/execute`,{method:"POST",body:JSON.stringify(body)}),
  runbookExecutions: (status?:string) => api<{items:import("./types").RunbookExecution[]}>(`/knowledge/runbook-executions${queryString({status})}`),
  runbookExecutionSteps: (id:string) => api<{items:import("./types").RunbookExecutionStep[]}>(`/knowledge/runbook-executions/${id}/steps`),
  completeRunbookExecutionStep: (executionId:string,stepId:string,body:Record<string,unknown>) => api<import("./types").RunbookExecutionStep>(`/knowledge/runbook-executions/${executionId}/steps/${stepId}/complete`,{method:"POST",body:JSON.stringify(body)}),
  standardProcedures: () => api<{items:import("./types").StandardProcedure[]}>("/knowledge/sops"),
  createStandardProcedure: (body:Record<string,unknown>) => api<import("./types").StandardProcedure>("/knowledge/sops",{method:"POST",body:JSON.stringify(body)}),
  standardProcedureAction: (id:string,action:string) => api<import("./types").StandardProcedure>(`/knowledge/sops/${id}/${action}`,{method:"POST",body:JSON.stringify({comments:null})}),
  acknowledgeStandardProcedure: (id:string) => api<Record<string,unknown>>(`/knowledge/sops/${id}/acknowledge`,{method:"POST"}),
  serviceCatalogs: () => api<{items:import("./types").ServiceCatalog[]}>("/knowledge/service-catalogs"),
  createServiceCatalog: (body:Record<string,unknown>) => api<import("./types").ServiceCatalog>("/knowledge/service-catalogs",{method:"POST",body:JSON.stringify(body)}),
  catalogItems: (id:string) => api<{items:import("./types").CatalogItem[]}>(`/knowledge/service-catalogs/${id}/items`),
  createCatalogItem: (id:string,body:Record<string,unknown>) => api<import("./types").CatalogItem>(`/knowledge/service-catalogs/${id}/items`,{method:"POST",body:JSON.stringify(body)}),
  knowledgeDocuments: () => api<{items:import("./types").KnowledgeDocument[]}>("/knowledge/documents"),
  createKnowledgeDocument: (body:Record<string,unknown>) => api<import("./types").KnowledgeDocument>("/knowledge/documents",{method:"POST",body:JSON.stringify(body)}),
  troubleshootingGuides: () => api<{items:import("./types").TroubleshootingGuide[]}>("/knowledge/troubleshooting"),
  createTroubleshootingGuide: (body:Record<string,unknown>) => api<import("./types").TroubleshootingGuide>("/knowledge/troubleshooting",{method:"POST",body:JSON.stringify(body)}),
  operationalChecklists: () => api<{items:import("./types").OperationalChecklistTemplate[]}>("/knowledge/checklists"),
  createOperationalChecklist: (body:Record<string,unknown>) => api<import("./types").OperationalChecklistTemplate>("/knowledge/checklists",{method:"POST",body:JSON.stringify(body)}),
  executeOperationalChecklist: (id:string) => api<Record<string,unknown>>(`/knowledge/checklists/${id}/execute`,{method:"POST"}),
  searchKnowledge: (filters:Record<string,string|number|undefined>) => api<{items:import("./types").KnowledgeSearchResult[];total:number;page:number;page_size:number;query:string;sort:string}>(`/knowledge/search${queryString(filters)}`),
  knowledgeRelationships: (filters:Record<string,string|undefined>={}) => api<{items:Array<Record<string,unknown>>}>(`/knowledge/relationships${queryString(filters)}`),
  createKnowledgeRelationship: (body:Record<string,unknown>) => api<Record<string,unknown>>("/knowledge/relationships",{method:"POST",body:JSON.stringify(body)}),
  updateKnowledgeResource: (resource:"categories"|"tags"|"runbooks"|"sops"|"service-catalogs"|"catalog-items"|"documents"|"troubleshooting"|"checklists",id:string,body:Record<string,unknown>) => api<Record<string,unknown>>(`/knowledge/${resource}/${id}`,{method:"PATCH",body:JSON.stringify(body)}),
  retireKnowledgeResource: (resource:"categories"|"tags"|"runbooks"|"sops"|"service-catalogs"|"catalog-items"|"documents"|"troubleshooting"|"checklists",id:string) => api<void>(`/knowledge/${resource}/${id}`,{method:"DELETE"}),
  knowledgeReportSummary: () => api<import("./types").KnowledgeReportSummary>("/knowledge/reports/summary"),
  knowledgeAuditHistory: (params:Record<string,string|number|undefined>={}) => api<{items:Record<string,unknown>[];total:number;page:number;page_size:number}>(`/knowledge/audit-history?${new URLSearchParams(Object.entries(params).filter(([,v])=>v!==undefined).map(([k,v])=>[k,String(v)])).toString()}`),
  exportKnowledgeReport: (format:"csv"|"xlsx"|"pdf") => download(`/knowledge/reports/export${queryString({format})}`),
  changeDashboard: () => api<import("./types").ChangeDashboard>("/changes/dashboard"),
  changeTypes: () => api<{items:import("./types").ChangeType[]}>("/changes/types"),
  changeRequests: (filters:Record<string,string|number|undefined>={}) => api<import("./types").ChangePage<import("./types").ChangeRequest>>(`/changes${queryString(filters)}`),
  changeRequest: (id:string) => api<import("./types").ChangeRequest>(`/changes/requests/${id}`),
  createChangeRequest: (body:Record<string,unknown>) => api<import("./types").ChangeRequest>("/changes",{method:"POST",body:JSON.stringify(body)}),
  updateChangeRequest: (id:string,body:Record<string,unknown>) => api<import("./types").ChangeRequest>(`/changes/requests/${id}`,{method:"PATCH",body:JSON.stringify(body)}),
  changeAction: (id:string,action:string,comments?:string) => api<import("./types").ChangeRequest>(`/changes/requests/${id}/actions/${action}`,{method:"POST",body:JSON.stringify({comments:comments||null})}),
  changeApprovals: (id:string) => api<{items:import("./types").ChangeApproval[]}>(`/changes/requests/${id}/approvals`),
  decideChangeApproval: (changeId:string,approvalId:string,body:Record<string,unknown>) => api<import("./types").ChangeApproval>(`/changes/requests/${changeId}/approvals/${approvalId}`,{method:"POST",body:JSON.stringify(body)}),
  changeApprovalQueue: () => api<import("./types").ChangePage<import("./types").ChangeApproval>>("/changes/approvals/queue"),
  changeTasks: (id:string) => api<{items:import("./types").ChangeTask[]}>(`/changes/requests/${id}/tasks`),
  addChangeTask: (id:string,body:Record<string,unknown>) => api<import("./types").ChangeTask>(`/changes/requests/${id}/tasks`,{method:"POST",body:JSON.stringify(body)}),
  changeRisk: (id:string,body:Record<string,unknown>) => api<import("./types").ChangeRiskAssessment>(`/changes/requests/${id}/risk-assessments`,{method:"POST",body:JSON.stringify(body)}),
  cabMeetings: () => api<{items:import("./types").CABMeeting[]}>("/changes/cab/meetings"),
  createCABMeeting: (body:Record<string,unknown>) => api<import("./types").CABMeeting>("/changes/cab/meetings",{method:"POST",body:JSON.stringify(body)}),
  cabVote: (meetingId:string,changeId:string,body:Record<string,unknown>) => api<Record<string,unknown>>(`/changes/cab/meetings/${meetingId}/changes/${changeId}/vote`,{method:"POST",body:JSON.stringify(body)}),
  cabDecision: (meetingId:string,changeId:string,body:Record<string,unknown>) => api<Record<string,unknown>>(`/changes/cab/meetings/${meetingId}/changes/${changeId}/decision`,{method:"POST",body:JSON.stringify(body)}),
  maintenanceWindows: () => api<{items:import("./types").MaintenanceWindow[]}>("/changes/maintenance/windows"),
  createMaintenanceWindow: (body:Record<string,unknown>) => api<import("./types").MaintenanceWindow>("/changes/maintenance/windows",{method:"POST",body:JSON.stringify(body)}),
  approveMaintenanceWindow: (id:string) => api<import("./types").MaintenanceWindow>(`/changes/maintenance/windows/${id}/approve`,{method:"POST",body:JSON.stringify({comments:null})}),
  maintenanceConflicts: (id:string) => api<{items:import("./types").MaintenanceConflict[]}>(`/changes/maintenance/windows/${id}/conflicts`),
  changeExecutions: (id:string) => api<{items:import("./types").ChangeExecution[]}>(`/changes/requests/${id}/executions`),
  startChangeExecution: (id:string) => api<import("./types").ChangeExecution>(`/changes/requests/${id}/executions`,{method:"POST"}),
  changeExecutionTasks: (id:string) => api<{items:import("./types").ChangeExecutionTask[]}>(`/changes/executions/${id}/tasks`),
  completeChangeExecutionTask: (executionId:string,taskId:string,notes:string) => api<import("./types").ChangeExecutionTask>(`/changes/executions/${executionId}/tasks/${taskId}/complete${queryString({notes})}`,{method:"POST"}),
  requestChangeRollback: (executionId:string,reason:string) => api<import("./types").ChangeRollback>(`/changes/executions/${executionId}/rollback${queryString({reason})}`,{method:"POST"}),
  enterpriseReleases: () => api<{items:import("./types").EnterpriseRelease[]}>("/changes/releases"),
  createEnterpriseRelease: (body:Record<string,unknown>) => api<import("./types").EnterpriseRelease>("/changes/releases",{method:"POST",body:JSON.stringify(body)}),
  changeCommunications: () => api<{items:import("./types").ChangeCommunication[]}>("/changes/communications"),
  createChangeCommunication: (body:Record<string,unknown>) => api<import("./types").ChangeCommunication>("/changes/communications",{method:"POST",body:JSON.stringify(body)}),
  changeReportSummary: () => api<import("./types").ChangeReportSummary>("/changes/reports/summary"),
  exportChangeReport: (format:"csv"|"xlsx"|"pdf") => download(`/changes/reports/export${queryString({format})}`),
  changeAuditHistory: (entityId?:string) => api<{items:Record<string,unknown>[];total:number}>(`/changes/audit-history${queryString({entity_id:entityId})}`),
  snmpCredential: (id:string) => api<import("./types").SNMPCredential>(`/snmp/credentials/${id}`),
  createSNMPCredential: (body:import("./types").SNMPCredentialInput) => api<import("./types").SNMPCredential>("/snmp/credentials",{method:"POST",body:JSON.stringify(body)}),
  updateSNMPCredential: (id:string,body:Partial<import("./types").SNMPCredentialInput>) => api<import("./types").SNMPCredential>(`/snmp/credentials/${id}`,{method:"PATCH",body:JSON.stringify(body)}),
  rotateSNMPSecret: (id:string,body:{community?:string;authentication_secret?:string;privacy_secret?:string}) => api<import("./types").SNMPCredential>(`/snmp/credentials/${id}/secret`,{method:"POST",body:JSON.stringify(body)}),
  disableSNMPCredential: (id:string) => api<import("./types").SNMPCredential>(`/snmp/credentials/${id}/disable`,{method:"POST"}),
  snmpTargets: (filters:Record<string,string|number|undefined>={}) => api<import("./types").SNMPPage<import("./types").SNMPTarget>>(`/snmp/targets${queryString(filters)}`),
  snmpTarget: (id:string) => api<import("./types").SNMPTarget>(`/snmp/targets/${id}`),
  createSNMPTarget: (body:import("./types").SNMPTargetInput) => api<import("./types").SNMPTarget>("/snmp/targets",{method:"POST",body:JSON.stringify(body)}),
  updateSNMPTarget: (id:string,body:Partial<import("./types").SNMPTargetInput>) => api<import("./types").SNMPTarget>(`/snmp/targets/${id}`,{method:"PATCH",body:JSON.stringify(body)}),
  disableSNMPTarget: (id:string) => api<import("./types").SNMPTarget>(`/snmp/targets/${id}/disable`,{method:"POST"}),
  testSNMPTarget: (id:string) => api<import("./types").SNMPTargetTestResult>(`/snmp/targets/${id}/test`,{method:"POST",body:JSON.stringify({include_optional_identity:true})}),
  collectSNMPTarget: (id:string,groups:string[]) => api<{poll_run_id:string;accepted_groups:string[];status:string;warnings:string[]}>(`/snmp/targets/${id}/collect`,{method:"POST",body:JSON.stringify({groups})}),
  snmpPollingConfig: (id:string) => api<import("./types").SNMPPollingConfiguration>(`/snmp/targets/${id}/polling-config`),
  updateSNMPPollingConfig: (id:string,body:Partial<import("./types").SNMPPollingConfiguration>) => api<import("./types").SNMPPollingConfiguration>(`/snmp/targets/${id}/polling-config`,{method:"PUT",body:JSON.stringify(body)}),
  snmpPollRuns: (filters:Record<string,string|number|undefined>={}) => api<import("./types").SNMPPage<import("./types").SNMPPollRun>>(`/snmp/poll-runs${queryString(filters)}`),
  snmpPollRun: (id:string) => api<import("./types").SNMPPollRun>(`/snmp/poll-runs/${id}`),
  snmpPollResults: (id:string,page=1) => api<import("./types").SNMPPage<import("./types").SNMPMetric>>(`/snmp/poll-runs/${id}/results${queryString({page,page_size:100})}`),
  cancelSNMPPoll: (id:string) => api<import("./types").SNMPPollRun>(`/snmp/poll-runs/${id}/cancel`,{method:"POST"}),
  snmpProfiles: (filters:Record<string,string|number|undefined>={}) => api<import("./types").SNMPPage<import("./types").SNMPDeviceProfile>>(`/snmp/profiles${queryString(filters)}`),
  createSNMPProfile: (body:Record<string,unknown>) => api<import("./types").SNMPDeviceProfile>("/snmp/profiles",{method:"POST",body:JSON.stringify(body)}),
  updateSNMPProfile: (id:string,body:Record<string,unknown>) => api<import("./types").SNMPDeviceProfile>(`/snmp/profiles/${id}`,{method:"PATCH",body:JSON.stringify(body)}),
  snmpOids: (filters:Record<string,string|number|undefined>={}) => api<import("./types").SNMPPage<import("./types").SNMPOIDDefinition>>(`/snmp/oids${queryString(filters)}`),
  createSNMPOid: (body:Record<string,unknown>) => api<import("./types").SNMPOIDDefinition>("/snmp/oids",{method:"POST",body:JSON.stringify(body)}),
  updateSNMPOid: (id:string,body:Record<string,unknown>) => api<import("./types").SNMPOIDDefinition>(`/snmp/oids/${id}`,{method:"PATCH",body:JSON.stringify(body)}),
  snmpCandidates: (filters:Record<string,string|number|undefined>={}) => api<import("./types").SNMPPage<import("./types").SNMPDiscoveryCandidate>>(`/snmp/candidates${queryString(filters)}`),
  snmpCandidate: (id:string) => api<import("./types").SNMPDiscoveryCandidate>(`/snmp/candidates/${id}`),
  matchSNMPCandidate: (id:string) => api<import("./types").SNMPPage<import("./types").SNMPMatchCandidate>>(`/snmp/candidates/${id}/match`,{method:"POST"}),
  snmpCandidateMatches: (id:string) => api<import("./types").SNMPPage<import("./types").SNMPMatchCandidate>>(`/snmp/candidates/${id}/matches`),
  snmpOnboardingPlan: (id:string) => api<import("./types").SNMPOnboardingPlan>(`/snmp/candidates/${id}/onboarding-plan`),
  approveSNMPCandidate: (id:string,device:Record<string,unknown>,expected_updated_at?:string) => api<Record<string,unknown>>(`/snmp/candidates/${id}/approve`,{method:"POST",body:JSON.stringify({device,expected_updated_at})}),
  linkSNMPCandidate: (id:string,device_id:string,expected_updated_at?:string) => api<Record<string,unknown>>(`/snmp/candidates/${id}/link`,{method:"POST",body:JSON.stringify({device_id,expected_updated_at})}),
  enrichSNMPCandidate: (id:string,device_id:string,fields:string[],overwrite=false,expected_updated_at?:string) => api<Record<string,unknown>>(`/snmp/candidates/${id}/enrich`,{method:"POST",body:JSON.stringify({device_id,fields,overwrite,expected_updated_at})}),
  reviewSNMPCandidate: (id:string,action:"ignore"|"reject"|"restore",expected_updated_at?:string) => api<import("./types").SNMPDiscoveryCandidate>(`/snmp/candidates/${id}/${action}`,{method:"POST",body:JSON.stringify({expected_updated_at})}),
  snmpInterfaces: (filters:Record<string,string|number|undefined>={}) => api<import("./types").SNMPPage<import("./types").SNMPInterface>>(`/snmp/interfaces${queryString(filters)}`),
  snmpTargetInterfaces: (id:string,filters:Record<string,string|number|undefined>={}) => api<import("./types").SNMPPage<import("./types").SNMPInterface>>(`/snmp/targets/${id}/interfaces${queryString(filters)}`),
  snmpInterface: (id:string) => api<import("./types").SNMPInterface>(`/snmp/interfaces/${id}`),
  snmpInterfaceChanges: (id:string,page=1) => api<import("./types").SNMPPage<import("./types").SNMPInterfaceChange>>(`/snmp/interfaces/${id}/changes${queryString({page,page_size:50})}`),
  snmpInterfaceMetrics: (id:string,filters:Record<string,string|number|undefined>={}) => api<import("./types").SNMPPage<import("./types").SNMPMetric>>(`/snmp/interfaces/${id}/metrics${queryString(filters)}`),
  snmpMetrics: (filters:Record<string,string|number|undefined>={}) => api<import("./types").SNMPPage<import("./types").SNMPMetric>>(`/snmp/metrics${queryString(filters)}`),
  snmpTargetMetrics: (id:string,filters:Record<string,string|number|undefined>={}) => api<import("./types").SNMPPage<import("./types").SNMPMetric>>(`/snmp/targets/${id}/metrics${queryString(filters)}`),
  snmpMetricSummary: (id:string,metric_key:string) => api<import("./types").SNMPMetricSummary>(`/snmp/targets/${id}/metric-summary${queryString({metric_key})}`),
  snmpStateChanges: (filters:Record<string,string|number|undefined>={}) => api<import("./types").SNMPPage<import("./types").SNMPStateChange>>(`/snmp/state-changes${queryString(filters)}`),
  snmpRetentionPreview: () => api<import("./types").SNMPRetentionPreview>("/snmp/retention/preview"),
  runSNMPRetentionCleanup: () => api<import("./types").SNMPRetentionPreview>("/snmp/retention/cleanup",{method:"POST"}),
  snmpAlertRules: (filters:Record<string,string|number|boolean|undefined>={}) => api<import("./types").SNMPPage<import("./types").SNMPAlertRule>>(`/snmp/alert-rules${queryString(filters)}`),
  createSNMPAlertRule: (body:Record<string,unknown>) => api<import("./types").SNMPAlertRule>("/snmp/alert-rules",{method:"POST",body:JSON.stringify(body)}),
  updateSNMPAlertRule: (id:string,body:Record<string,unknown>) => api<import("./types").SNMPAlertRule>(`/snmp/alert-rules/${id}`,{method:"PATCH",body:JSON.stringify(body)}),
  previewSNMPAlertRule: (body:Record<string,unknown>) => api<{items:Array<{target_id:string;would_trigger:boolean;sample_count:number}>;estimated_alert_count:number}>("/snmp/alert-rules/preview",{method:"POST",body:JSON.stringify(body)}),
  snmpAlerts: (filters:Record<string,string|number|boolean|undefined>={}) => api<import("./types").SNMPPage<import("./types").SNMPAlertEvent>>(`/snmp/alerts${queryString(filters)}`),
  evaluateSNMPAlerts: (id:string) => api<Record<string,number>>(`/snmp/targets/${id}/evaluate-alerts`,{method:"POST"}),
  snmpSchedulerHealth: () => api<import("./types").SNMPSchedulerHealth>("/snmp/scheduler/health"),
  reconcileSNMPScheduler: () => api<Record<string,number>>("/snmp/scheduler/reconcile",{method:"POST"}),
  pauseSNMPPolling: (id:string) => api<Record<string,number>>(`/snmp/targets/${id}/polling/pause`,{method:"POST"}),
  resumeSNMPPolling: (id:string) => api<Record<string,number>>(`/snmp/targets/${id}/polling/resume`,{method:"POST"}),
  setSNMPMaintenance: (id:string,enabled:boolean,reason="") => api<import("./types").SNMPPollingConfiguration>(`/snmp/targets/${id}/maintenance${queryString({enabled,reason})}`,{method:"POST"}),
  topologies: (filters:Record<string,string|number|boolean|undefined>={}) => api<import("./types").TopologyPage<import("./types").Topology>>(`/topology${queryString(filters)}`),
  topology: (id:string) => api<import("./types").Topology>(`/topology/${id}`),
  createTopology: (body:Record<string,unknown>) => api<import("./types").Topology>("/topology",{method:"POST",body:JSON.stringify(body)}),
  updateTopology: (id:string,body:Record<string,unknown>) => api<import("./types").Topology>(`/topology/${id}`,{method:"PATCH",body:JSON.stringify(body)}),
  setDefaultTopology: (id:string) => api<import("./types").Topology>(`/topology/${id}/set-default`,{method:"POST"}),
  enableTopology: (id:string,enabled:boolean) => api<import("./types").Topology>(`/topology/${id}/${enabled?"enable":"disable"}`,{method:"POST"}),
  bootstrapTopology: (id:string,body:Record<string,unknown>) => api<Record<string,unknown>>(`/topology/bootstrap${queryString({topology_id:id})}`,{method:"POST",body:JSON.stringify(body)}),
  topologyGraph: (id:string,filters:Record<string,string|number|boolean|undefined>={}) => api<import("./types").TopologyGraph>(`/topology/${id}/graph${queryString(filters)}`),
  topologyStats: (id:string) => api<import("./types").TopologyStats>(`/topology/${id}/stats`),
  topologyNodes: (id:string,filters:Record<string,string|number|boolean|undefined>={}) => api<import("./types").TopologyPage<import("./types").TopologyNode>>(`/topology/${id}/nodes${queryString(filters)}`),
  topologyNode: (id:string,nodeId:string) => api<import("./types").TopologyNode>(`/topology/${id}/nodes/${nodeId}`),
  createTopologyNode: (id:string,body:Record<string,unknown>) => api<import("./types").TopologyNode>(`/topology/${id}/nodes`,{method:"POST",body:JSON.stringify(body)}),
  updateTopologyNode: (id:string,nodeId:string,body:Record<string,unknown>) => api<import("./types").TopologyNode>(`/topology/${id}/nodes/${nodeId}`,{method:"PATCH",body:JSON.stringify(body)}),
  hideTopologyNode: (id:string,nodeId:string,hide=true) => api<import("./types").TopologyNode>(`/topology/${id}/nodes/${nodeId}/${hide?"hide":"restore"}`,{method:"POST"}),
  topologyLinks: (id:string,filters:Record<string,string|number|boolean|undefined>={}) => api<import("./types").TopologyPage<import("./types").TopologyLink>>(`/topology/${id}/links${queryString(filters)}`),
  topologyLink: (id:string,linkId:string) => api<import("./types").TopologyLink>(`/topology/${id}/links/${linkId}`),
  createTopologyLink: (id:string,body:Record<string,unknown>) => api<import("./types").TopologyLink>(`/topology/${id}/links`,{method:"POST",body:JSON.stringify(body)}),
  updateTopologyLink: (id:string,linkId:string,body:Record<string,unknown>) => api<import("./types").TopologyLink>(`/topology/${id}/links/${linkId}`,{method:"PATCH",body:JSON.stringify(body)}),
  topologyLinkAction: (id:string,linkId:string,action:"confirm"|"suppress"|"restore") => api<import("./types").TopologyLink>(`/topology/${id}/links/${linkId}/${action}`,{method:"POST"}),
  topologySegments: (id:string) => api<import("./types").TopologyPage<import("./types").NetworkSegment>>(`/topology/${id}/segments?page_size=100`),
  topologyDependencies: (id:string) => api<import("./types").TopologyPage<import("./types").DeviceDependency>>(`/topology/${id}/dependencies?page_size=100`),
  topologyLayout: (id:string) => api<{items:import("./types").NodePosition[];total:number}>(`/topology/${id}/layout`),
  saveTopologyLayout: (id:string,body:import("./types").NodePosition[]) => api<{updated:number}>(`/topology/${id}/layout`,{method:"PUT",body:JSON.stringify(body)}),
  topologyNeighbors: (id:string,nodeId:string) => api<{node_id:string;nodes:import("./types").TopologyNode[];links:import("./types").TopologyLink[]}>(`/topology/${id}/neighbors/${nodeId}`),
  topologyPath: (id:string,source:string,target:string,pathType:string) => api<import("./types").TopologyPathResult>(`/topology/${id}/path-analysis${queryString({source_node_id:source,target_node_id:target,path_type:pathType,max_paths:5})}`),
  topologyImpact: (id:string,nodeId:string) => api<import("./types").TopologyImpact>(`/topology/${id}/impact-analysis${queryString({node_id:nodeId})}`),
  topologyOrphans: (id:string) => api<{items:import("./types").TopologyNode[];total:number}>(`/topology/${id}/orphans`),
  topologyInference: (id:string) => api<import("./types").TopologyInferenceState>(`/topology/${id}/inference`),
  runTopologyInference: (id:string,dryRun=false) => api<import("./types").TopologyInferenceRun>(`/topology/${id}/run-inference`,{method:"POST",body:JSON.stringify({dry_run:dryRun,include_dependencies:true,include_layer_suggestions:true})}),
  topologyConflicts: (id:string,filters:Record<string,string|number|undefined>={}) => api<import("./types").TopologyPage<import("./types").TopologyConflict>>(`/topology/${id}/conflicts${queryString(filters)}`),
  topologyReviewItems: (id:string,filters:Record<string,string|number|undefined>={}) => api<import("./types").TopologyPage<import("./types").TopologyReviewItem>>(`/topology/${id}/review-items${queryString(filters)}`),
  resolveTopologyReview: (id:string,itemId:string,action:"approve"|"reject"|"ignore",note="") => api<import("./types").TopologyReviewItem>(`/topology/${id}/review-items/${itemId}/${action}`,{method:"POST",body:JSON.stringify({note:note||null})}),
  topologyCandidateLinks: (id:string,filters:Record<string,string|number|undefined>={}) => api<import("./types").TopologyPage<import("./types").TopologyLink>>(`/topology/${id}/candidate-links${queryString(filters)}`),
  topologyCandidateLinkAction: (id:string,linkId:string,action:"confirm"|"reject"|"suppress") => api<import("./types").TopologyLink>(`/topology/${id}/candidate-links/${linkId}/${action}`,{method:"POST"}),
  topologySnapshots: (id:string,filters:Record<string,string|number|undefined>={}) => api<import("./types").TopologyPage<import("./types").TopologySnapshot>>(`/topology/${id}/snapshots${queryString(filters)}`),
  createTopologySnapshot: (id:string,body:Record<string,unknown>) => api<import("./types").TopologySnapshot>(`/topology/${id}/snapshots`,{method:"POST",body:JSON.stringify(body)}),
  topologySnapshotGraph: (id:string,snapshotId:string) => api<import("./types").TopologySnapshotGraph>(`/topology/${id}/snapshots/${snapshotId}/graph`),
  compareTopologySnapshot: (id:string,snapshotId:string) => api<import("./types").SnapshotComparison>(`/topology/${id}/comparison${queryString({snapshot_id:snapshotId})}`),
  topologyChanges: (id:string,filters:Record<string,string|number|undefined>={}) => api<import("./types").TopologyPage<import("./types").TopologyChange>>(`/topology/${id}/changes${queryString(filters)}`),
  topologySchedule: (id:string) => api<import("./types").TopologySchedule>(`/topology/${id}/schedule`),
  updateTopologySchedule: (id:string,body:Omit<import("./types").TopologySchedule,"id"|"topology_id"|"maintenance_mode"|"maintenance_reason"|"maintenance_started_at"|"maintenance_ends_at"|"last_scheduler_reconciliation_at"|"created_at"|"updated_at">) => api<import("./types").TopologySchedule>(`/topology/${id}/schedule`,{method:"PUT",body:JSON.stringify(body)}),
  pauseTopologySchedule: (id:string) => api<{paused_jobs:number}>(`/topology/${id}/schedule/pause`,{method:"POST"}),
  resumeTopologySchedule: (id:string) => api<{resumed_jobs:number}>(`/topology/${id}/schedule/resume`,{method:"POST"}),
  topologySchedulerStatus: (id:string) => api<import("./types").TopologySchedulerStatus>(`/topology/${id}/scheduler-status`),
  topologyHealth: (id:string) => api<import("./types").TopologyHealth>(`/topology/${id}/health`),
  topologyAnalytics: (id:string) => api<import("./types").TopologyAnalytics>(`/topology/${id}/analytics`),
  topologyOperationalRuns: (id:string,filters:Record<string,string|number|undefined>={}) => api<import("./types").TopologyPage<import("./types").TopologyOperationalRun>>(`/topology/${id}/operational-runs${queryString(filters)}`),
  topologyAlertRules: (filters:Record<string,string|number|boolean|undefined>={}) => api<import("./types").TopologyPage<import("./types").TopologyAlertRule>>(`/topology/alert-rules${queryString(filters)}`),
  createTopologyAlertRule: (body:Record<string,unknown>) => api<import("./types").TopologyAlertRule>("/topology/alert-rules",{method:"POST",body:JSON.stringify(body)}),
  updateTopologyAlertRule: (id:string,body:Record<string,unknown>) => api<import("./types").TopologyAlertRule>(`/topology/alert-rules/${id}`,{method:"PATCH",body:JSON.stringify(body)}),
  previewTopologyAlertRule: (id:string,topologyId:string) => api<{rule_id:string;would_trigger:boolean;evidence?:Record<string,unknown>}>(`/topology/alert-rules/${id}/preview${queryString({topology_id:topologyId})}`,{method:"POST"}),
  topologyAlerts: (filters:Record<string,string|number|boolean|undefined>={}) => api<import("./types").TopologyPage<import("./types").TopologyAlertEvent>>(`/topology/alerts${queryString(filters)}`),
  startTopologyMaintenance: (id:string,reason:string,ends_at?:string) => api<import("./types").TopologySchedule>(`/topology/${id}/maintenance/start`,{method:"POST",body:JSON.stringify({reason,ends_at:ends_at||null})}),
  endTopologyMaintenance: (id:string) => api<import("./types").TopologySchedule>(`/topology/${id}/maintenance/end`,{method:"POST"}),
  topologyReportSummary: (id:string) => api<{health:import("./types").TopologyHealth;analytics:import("./types").TopologyAnalytics;open_alerts:number;failed_runs:number}>(`/topology/${id}/reports/summary`),
  exportTopologyCsv: (id:string,kind:"nodes"|"links") => download(`/topology/${id}/exports/${kind}.csv`),
  topologyRetentionPreview: () => api<import("./types").TopologyRetentionPreview>("/topology/retention/preview"),
  runTopologyRetentionCleanup: () => api<import("./types").TopologyRetentionPreview>("/topology/retention/cleanup",{method:"POST"}),
  setTopologyBaseline: (id:string,snapshotId:string) => api<{snapshot_id:string;is_operational_baseline:boolean;is_protected:boolean}>(`/topology/${id}/snapshots/${snapshotId}/baseline`,{method:"POST"}),
  cmdbDashboard:()=>api<import("./types").CMDBDashboard>("/cmdb/dashboard"),
  ciClasses:()=>api<{items:import("./types").CIClass[]}>("/cmdb/classes"),
  ciTypes:(class_id?:string)=>api<{items:import("./types").CIType[]}>(`/cmdb/types${queryString({class_id})}`),
  configurationItems:(filters:Record<string,string|number|boolean|undefined>={})=>api<import("./types").CMDBPage<import("./types").ConfigurationItem>>(`/cmdb/items${queryString(filters)}`),
  configurationItem:(id:string)=>api<import("./types").ConfigurationItem>(`/cmdb/items/${id}`),
  createConfigurationItem:(body:Record<string,unknown>)=>api<import("./types").ConfigurationItem>("/cmdb/items",{method:"POST",body:JSON.stringify(body)}),
  updateConfigurationItem:(id:string,body:Record<string,unknown>)=>api<import("./types").ConfigurationItem>(`/cmdb/items/${id}`,{method:"PATCH",body:JSON.stringify(body)}),
  transitionConfigurationItem:(id:string,target_stage:string,reason:string)=>api<import("./types").ConfigurationItem>(`/cmdb/items/${id}/lifecycle`,{method:"POST",body:JSON.stringify({target_stage,reason})}),
  ciLifecycleHistory:(id:string)=>api<{items:Array<Record<string,unknown>>}>(`/cmdb/items/${id}/lifecycle`),
  ciAttributes:(id:string)=>api<{items:import("./types").CIAttribute[]}>(`/cmdb/items/${id}/attributes`),
  setCIAttribute:(id:string,body:Record<string,unknown>)=>api<import("./types").CIAttribute>(`/cmdb/items/${id}/attributes`,{method:"PUT",body:JSON.stringify(body)}),
  ciIdentifiers:(id:string)=>api<{items:import("./types").CIIdentifier[]}>(`/cmdb/items/${id}/identifiers`),
  addCIIdentifier:(id:string,body:Record<string,unknown>)=>api<import("./types").CIIdentifier>(`/cmdb/items/${id}/identifiers`,{method:"POST",body:JSON.stringify(body)}),
  ciRelationshipTypes:()=>api<{items:import("./types").CIRelationshipType[]}>("/cmdb/relationship-types"),
  ciRelationships:(id:string,direction="both")=>api<{items:import("./types").CIRelationship[]}>(`/cmdb/items/${id}/relationships${queryString({direction})}`),
  createCIRelationship:(id:string,body:Record<string,unknown>)=>api<import("./types").CIRelationship>(`/cmdb/items/${id}/relationships`,{method:"POST",body:JSON.stringify(body)}),
  cmdbDependencyGraph:(filters:Record<string,string|number|undefined>={})=>api<import("./types").CIDependencyGraph>(`/cmdb/dependency-graph${queryString(filters)}`),
  ciImpact:(id:string)=>api<import("./types").CIImpact>(`/cmdb/items/${id}/impact`),
  runCMDBReconciliation:(body:Record<string,unknown>)=>api<Record<string,number>>("/cmdb/reconciliation/run",{method:"POST",body:JSON.stringify(body)}),
  cmdbCandidates:(filters:Record<string,string|number|undefined>={})=>api<import("./types").CMDBPage<import("./types").CIReconciliationCandidate>>(`/cmdb/reconciliation/candidates${queryString(filters)}`),
  decideCMDBCandidate:(id:string,body:Record<string,unknown>)=>api<Record<string,unknown>>(`/cmdb/reconciliation/candidates/${id}/decision`,{method:"POST",body:JSON.stringify(body)}),
  cmdbHealth:(property_id?:string)=>api<import("./types").CIHealth>(`/cmdb/health${queryString({property_id})}`),
  recalculateCMDBHealth:(property_id?:string)=>api<import("./types").CIHealth>(`/cmdb/health/recalculate${queryString({property_id})}`,{method:"POST"}),
  cmdbReport:()=>api<import("./types").CMDBReport>("/cmdb/reports/summary"),
  exportCMDB:(format:"csv"|"xlsx"|"pdf")=>download(`/cmdb/reports/export${queryString({format})}`),
  problemDashboard:()=>api<import("./types").ProblemDashboard>("/problems/dashboard"),
  problems:(filters:Record<string,string|number|undefined>={})=>api<{items:import("./types").ProblemRecord[];total:number;page:number;page_size:number}>(`/problems${queryString(filters)}`),
  problem:(id:string)=>api<import("./types").ProblemRecord>(`/problems/${id}`),
  createProblem:(body:Record<string,unknown>)=>api<import("./types").ProblemRecord>("/problems",{method:"POST",body:JSON.stringify(body)}),
  updateProblem:(id:string,body:Record<string,unknown>)=>api<import("./types").ProblemRecord>(`/problems/${id}`,{method:"PATCH",body:JSON.stringify(body)}),
  transitionProblem:(id:string,target_status:string,reason:string)=>api<import("./types").ProblemRecord>(`/problems/${id}/transition`,{method:"POST",body:JSON.stringify({target_status,reason})}),
  bulkTransitionProblems:(body:Record<string,unknown>)=>api<Record<string,unknown>>("/problems/bulk-transitions",{method:"POST",body:JSON.stringify(body)}),
  problemRCA:(id:string)=>api<{analysis:import("./types").RootCauseAnalysis|null;causes:import("./types").RootCause[];five_whys:import("./types").FiveWhy[];fishbone:import("./types").FishboneCause[];factors:Array<Record<string,unknown>>}>(`/problems/${id}/rca`),
  saveProblemRCA:(id:string,body:Record<string,unknown>)=>api<import("./types").RootCauseAnalysis>(`/problems/${id}/rca`,{method:"PUT",body:JSON.stringify(body)}),
  addProblemCause:(id:string,body:Record<string,unknown>)=>api<import("./types").RootCause>(`/problems/${id}/rca/causes`,{method:"POST",body:JSON.stringify(body)}),
  saveFiveWhy:(id:string,body:Record<string,unknown>)=>api<import("./types").FiveWhy>(`/problems/${id}/rca/five-whys`,{method:"POST",body:JSON.stringify(body)}),
  addFishboneCause:(id:string,body:Record<string,unknown>)=>api<import("./types").FishboneCause>(`/problems/${id}/rca/fishbone`,{method:"POST",body:JSON.stringify(body)}),
  knownErrors:(filters:Record<string,string|undefined>={})=>api<{items:import("./types").KnownError[];total:number}>(`/problems/known-errors/library${queryString(filters)}`),
  createKnownError:(body:Record<string,unknown>)=>api<import("./types").KnownError>("/problems/known-errors",{method:"POST",body:JSON.stringify(body)}),
  knownErrorAction:(id:string,action:"approve"|"publish"|"retire")=>api<import("./types").KnownError>(`/problems/known-errors/${id}/${action}`,{method:"POST"}),
  addWorkaround:(id:string,body:Record<string,unknown>)=>api<import("./types").ProblemWorkaround>(`/problems/known-errors/${id}/workarounds`,{method:"POST",body:JSON.stringify(body)}),
  workaroundLibrary:()=>api<{items:import("./types").ProblemWorkaround[]}>("/problems/workarounds/library"),
  problemCAPA:(id:string)=>api<Record<string,unknown>>(`/problems/${id}/capa`),
  createProblemPlan:(id:string,body:Record<string,unknown>)=>api<Record<string,unknown>>(`/problems/${id}/capa/plans`,{method:"POST",body:JSON.stringify(body)}),
  createProblemReview:(id:string,body:Record<string,unknown>)=>api<Record<string,unknown>>(`/problems/${id}/reviews`,{method:"POST",body:JSON.stringify(body)}),
  addProblemRelationship:(id:string,body:Record<string,unknown>)=>api<Record<string,unknown>>(`/problems/${id}/relationships`,{method:"POST",body:JSON.stringify(body)}),
  problemCorrelations:()=>api<{items:import("./types").ProblemCorrelation[]}>("/problems/correlations/suggestions"),
  detectProblemCorrelations:(body:Record<string,unknown>)=>api<Record<string,number>>("/problems/correlations/detect",{method:"POST",body:JSON.stringify(body)}),
  problemRelationshipGraph:(id:string)=>api<{nodes:Array<Record<string,string>>;edges:Array<Record<string,string>>}>(`/problems/${id}/relationships/graph`),
  problemReport:()=>api<import("./types").ProblemReport>("/problems/reports/summary"),
  exportProblemReport:(format:"csv"|"xlsx"|"pdf")=>download(`/problems/reports/export${queryString({format})}`),
  assetDashboard:()=>api<import("./types").AssetDashboard>("/asset-management/dashboard"),
  enterpriseAssets:(filters:Record<string,string|number|undefined>={})=>api<{items:import("./types").EnterpriseAsset[];total:number}>(`/asset-management/assets${queryString(filters)}`),
  enterpriseAsset:(id:string)=>api<import("./types").EnterpriseAsset>(`/asset-management/assets/${id}`),
  createEnterpriseAsset:(body:Record<string,unknown>)=>api<import("./types").EnterpriseAsset>("/asset-management/assets",{method:"POST",body:JSON.stringify(body)}),
  transitionEnterpriseAsset:(id:string,target_stage:string,reason:string)=>api<import("./types").EnterpriseAsset>(`/asset-management/assets/${id}/transition`,{method:"POST",body:JSON.stringify({target_stage,reason})}),
  assetTimeline:(id:string)=>api<Record<string,unknown>>(`/asset-management/assets/${id}/timeline`),
  assetFinancials:(id:string)=>api<Record<string,unknown>>(`/asset-management/assets/${id}/financials`),
  recalculateDepreciation:()=>api<{updated:number}>("/asset-management/assets/recalculate-depreciation",{method:"POST"}),
  vendors:(filters:Record<string,string|number|undefined>={})=>api<{items:import("./types").VendorRecord[];total:number}>(`/asset-management/vendors${queryString(filters)}`),
  vendor:(id:string)=>api<Record<string,unknown>>(`/asset-management/vendors/${id}`),
  createVendor:(body:Record<string,unknown>)=>api<import("./types").VendorRecord>("/asset-management/vendors",{method:"POST",body:JSON.stringify(body)}),
  approveVendor:(id:string)=>api<import("./types").VendorRecord>(`/asset-management/vendors/${id}/approve`,{method:"POST"}),
  purchaseRequests:()=>api<{items:import("./types").PurchaseRequestRecord[]}>("/asset-management/procurement/requests"),
  createPurchaseRequest:(body:Record<string,unknown>)=>api<import("./types").PurchaseRequestRecord>("/asset-management/procurement/requests",{method:"POST",body:JSON.stringify(body)}),
  submitPurchaseRequest:(id:string)=>api<import("./types").PurchaseRequestRecord>(`/asset-management/procurement/requests/${id}/submit`,{method:"POST"}),
  decidePurchaseRequest:(id:string,body:Record<string,unknown>)=>api<import("./types").PurchaseRequestRecord>(`/asset-management/procurement/requests/${id}/decision`,{method:"POST",body:JSON.stringify(body)}),
  purchaseOrders:()=>api<{items:import("./types").PurchaseOrderRecord[]}>("/asset-management/procurement/orders"),
  receivePurchaseOrder:(body:Record<string,unknown>)=>api<Record<string,unknown>>("/asset-management/procurement/receive",{method:"POST",body:JSON.stringify(body)}),
  contracts:()=>api<{items:import("./types").ContractRecord[]}>("/asset-management/contracts"),
  createContract:(body:Record<string,unknown>)=>api<import("./types").ContractRecord>("/asset-management/contracts",{method:"POST",body:JSON.stringify(body)}),
  warranties:()=>api<{items:import("./types").WarrantyRecord[];claims:Array<Record<string,unknown>>}>("/asset-management/warranties"),
  softwareLicenses:()=>api<{items:import("./types").SoftwareLicenseRecord[];products:Array<Record<string,unknown>>}>("/asset-management/licenses"),
  checkLicenseCompliance:()=>api<{checked:number}>("/asset-management/licenses/compliance/check",{method:"POST"}),
  inventory:()=>api<Record<string,unknown>>("/asset-management/inventory"),
  assetReport:()=>api<import("./types").AssetReport>("/asset-management/reports/summary"),
  exportAssetReport:(format:"csv"|"xlsx"|"pdf")=>download(`/asset-management/reports/export${queryString({format})}`),
};
